from ex import QS, M, F, TF, S

a = 'Unit exercise (matric style)'
U = [
 ('Who is known as the father of modern taxonomy?', ['Aristotle', 'Whittaker', 'Carl Linnaeus', 'Robert Hooke'], 'C', 54, ['Linnaeus built the hierarchy of ranks and binomial nomenclature.', 'Whittaker proposed the five kingdoms; Hooke named cells.'], 'Linnaeus = Latin names.', ('Who proposed the five-kingdom system?', 'R. H. Whittaker (1969).')),
 ('The correct sequence of taxa from highest to lowest is', ['Kingdom, Class, Phylum, Order, Family, Genus, Species', 'Kingdom, Phylum, Class, Order, Family, Genus, Species', 'Kingdom, Phylum, Order, Class, Genus, Family, Species', 'Species, Genus, Family, Order, Class, Phylum, Kingdom'], 'B', 54, ['Use King Philip Came Over For Good Soup.', 'D is the reverse order (lowest to highest).'], 'Read the question: highest → lowest.', ('Which rank is directly below kingdom?', 'Phylum.')),
 ('The scientific name of any organism consists of', ['class and genus', 'class and order', 'phylum and class', 'genus and species'], 'D', 56, ['Binomial = two names: genus + species.'], 'Bi-nomial = two names.', ('Which part of *Felis leo* is the genus?', '*Felis*.')),
 ('Which of the following organisms are most closely related?', ['Two members of the same family', 'Two members of the same order', 'Two members of the same genus', 'Two members of the same class'], 'C', 55, ['The lower the shared rank, the closer the relationship.', 'Genus is the lowest rank among the options.'], 'Lower shared rank = closer relatives.', ('Are human and lion in the same order?', 'No — Primates vs Carnivora; same class Mammalia.')),
 ('A dichotomous key works by', ['comparing an organism with photographs', 'a series of paired, mutually exclusive statements', 'measuring DNA', 'listing common names'], 'B', 58, ['Each couplet has two choices; one leads on.'], 'Di = two.', ('What is one pair of statements called?', 'A couplet.')),
 ('Diatoms and *Euglena* belong to kingdom', ['Protista', 'Fungi', 'Animalia', 'Plantae'], 'A', 71, ['Both are simple unicellular algae — plant-like protists.'], 'Unicellular eukaryote in water → think Protista.', ('Is *Amoeba* in the same kingdom?', 'Yes — Protista (Sarcodina).')),
 ('Nitrifying bacteria are examples of', ['photoautotrophs', 'chemoautotrophs', 'chemoheterotrophs', 'photoheterotrophs'], 'B', 64, ['They make food using chemical energy from oxidising ammonia.'], 'Chemo = chemicals, auto = self-feeding.', ('What do photoautotrophs use?', 'Light energy.')),
 ('Cell division in bacteria takes place mainly by', ['fragmentation', 'binary fission', 'conjugation', 'sporulation'], 'B', 64, ['Bacteria split into two daughter cells every 20–30 minutes.', 'Conjugation is genetic transfer, not division.'], 'Binary = two.', ('How many bacteria from one after 2 hours if it divides every 30 min?', '2⁴ = 16.')),
 ('Bacteria are responsible for', ['introducing oxygen into the atmosphere', 'recycling minerals in the ecosystem', 'causing deadly diseases', 'all of the above'], 'D', 66, ['Cyanobacteria produced the first oxygen; decomposers recycle minerals; parasites cause disease.'], 'When every option is true, choose “all of the above”.', ('Which bacteria fix nitrogen and photosynthesise?', 'Cyanobacteria.')),
 ('An organism with pseudopodia belongs to phylum', ['Ciliophora', 'Mastigophora', 'Sarcodina', 'Sporozoa'], 'C', 67, ['Pseudopodia (false feet) are the locomotory structure of Sarcodina, e.g. *Amoeba*.'], 'Sarco walks on false feet.', ('Which phylum moves by flagella?', 'Mastigophora.')),
 ('The vector of *Trypanosoma* is the', ['female *Anopheles* mosquito', 'tsetse fly', 'house fly', 'tick'], 'B', 69, ['*Trypanosoma* → sleeping sickness → tsetse fly.', 'Anopheles carries Plasmodium.'], 'Match parasite → disease → vector in a chain.', ('What is the vector of malaria?', 'The female Anopheles mosquito.')),
 ('Which of the following is a colonial green alga?', ['*Chlamydomonas*', '*Spirogyra*', '*Volvox*', '*Ulva*'], 'C', 74, ['*Chlamydomonas* unicellular, *Spirogyra* filamentous, *Ulva* multicellular, *Volvox* colonial.'], 'Volvox = a “village” of cells.', ('Which green alga is two cells thick with a holdfast?', '*Ulva* (sea lettuce).')),
 ('Fungi are very important in the environment as', ['producers', 'decomposers', 'predators', 'pollinators'], 'B', 76, ['They secrete enzymes and break down dead matter, recycling nutrients.'], 'Saprophyte → decomposer.', ('What is a mass of hyphae called?', 'Mycelium.')),
 ('The fungus and alga in a lichen live in a relationship called', ['parasitism', 'commensalism', 'mutualism', 'predation'], 'C', 80, ['Both partners benefit → mutualism.'], 'Mutual = both.', ('What does the alga give the fungus?', 'Food made by photosynthesis.')),
 ('Mushrooms produce spores on club-shaped structures called', ['asci', 'basidia', 'sporangia', 'conidia'], 'B', 79, ['Basidiomycota = club fungi; basidium bears four basidiospores.'], 'Sac 8 (ascus), club 4 (basidium).', ('In which phylum is yeast?', 'Ascomycota.')),
 ('Which disease is caused by a fungus?', ['Malaria', 'Sleeping sickness', 'Athlete’s foot', 'Amoebic dysentery'], 'C', 81, ['Malaria, sleeping sickness and amoebic dysentery are caused by protozoa.', 'Athlete’s foot is caused by dermatophyte fungi.'], 'Protozoa: malaria, sleeping sickness, dysentery; fungi: thrush, ringworm, athlete’s foot.', ('Which fungus causes thrush?', '*Candida albicans*.')),
 ('In mosses, spores are produced inside the', ['thallus', 'capsule', 'sori', 'gemmae'], 'B', 83, ['The moss sporophyte ends in a capsule that releases spores.'], 'Moss → capsule.', ('Which generation is dominant in mosses?', 'The gametophyte.')),
 ('Which feature is used to classify vascular plants?', ['presence or absence of seeds', 'type of vascular bundle', 'type of leaves', 'type of sporangia'], 'A', 82, ['Plants are classified by presence or absence of vessels and seeds.'], 'Vessels and seeds.', ('Which vascular plants have no seeds?', 'Pteridophytes (ferns).')),
 ('A plant with naked seeds borne on cones is a', ['bryophyte', 'pteridophyte', 'gymnosperm', 'angiosperm'], 'C', 84, ['Gymno = naked; seeds on cone scales.'], 'Gymno-sperm = naked seed.', ('Give an example of a gymnosperm.', 'Pine (a conifer).')),
 ('Which pair are both monocots?', ['Beans and maize', 'Teff and sorghum', 'Chickpea and wheat', 'Groundnut and beans'], 'B', 85, ['Teff and sorghum each have one cotyledon; beans, chickpeas and groundnuts are dicots.'], 'Grasses (cereals) are monocots.', ('Which type has net-veined leaves?', 'Dicots.')),
 ('Which of the following has radial symmetry?', ['flatworm', 'annelid', 'chordate', 'cnidarian'], 'D', 87, ['Cnidarians (*Hydra*, jellyfish) are radial; the others are bilateral.'], 'Radial = sessile/floating animals with tentacles in a circle.', ('Which phylum is asymmetrical?', 'Porifera (sponges).')),
 ('The clitellum of an earthworm', ['contains the heart', 'is associated with reproduction', 'acts as a respiratory system', 'is necessary for movement'], 'B', 94, ['It secretes the sticky cocoon in which eggs are laid.'], 'Clitellum → cocoon.', ('What helps earthworms anchor during movement?', 'Setae.')),
 ('Members of class Osteichthyes', ['have skeletons made of bone', 'include rays and skates', 'do not have jaws', 'all of the above'], 'A', 104, ['Osteo = bone.', 'Rays and skates are cartilaginous; bony fishes have jaws.'], 'Osteo = bone, chondro = cartilage.', ('What gives bony fishes buoyancy?', 'The swim bladder.')),
 ('The phenomenon in which most sponges act as one sex for a time and then change to the other is', ['parthenogenesis', 'sequential hermaphroditism', 'regeneration', 'budding'], 'B', 90, ['Changing sex in sequence = sequential hermaphroditism; prevents self-fertilisation.'], 'Sequence = one after another.', ('How do sponges reproduce asexually?', 'By fragmentation.')),
 ('Which arthropod group has three body parts and three pairs of legs?', ['Arachnids', 'Crustaceans', 'Insects', 'Myriapods'], 'C', 99, ['Insects: head, thorax, abdomen; 3 pairs of legs on the thorax.'], 'Insect = 3 + 3.', ('How many legs does a spider have?', 'Eight.')),
 ('Which animals have a two-chambered heart?', ['Amphibians', 'Fishes', 'Reptiles', 'Birds'], 'B', 103, ['Heart chambers: fish 2, amphibians 3, reptiles 3 (crocodile 4), birds 4, mammals 4.'], '2-3-3-4-4.', ('Which reptile has a four-chambered heart?', 'The crocodile.')),
 ('An egg-laying mammal is called a', ['marsupial', 'monotreme', 'placental mammal', 'reptile'], 'B', 112, ['Monotremes lay eggs (platypus, spiny anteater).'], 'Mono-treme: the egg layer.', ('What is special about marsupials?', 'Young develop in a pouch after a short placenta.')),
 ('Animals with constant body temperature are', ['poikilothermic', 'homoeothermic', 'hermaphrodites', 'heterotrophic'], 'B', 108, ['Birds and mammals are homoeothermic (warm-blooded).'], 'Homoeo = same (temperature).', ('Name two homoeothermic classes.', 'Birds and mammals.')),
 ('Which statement about viruses is correct?', ['They belong to kingdom Monera', 'They are cells without a nucleus', 'They reproduce only inside living host cells', 'They make their own food'], 'C', 61, ['Viruses are not cells and have no metabolism; they are not in any kingdom.'], 'Virus = DNA/RNA + protein coat, host needed.', ('What is a virus made of?', 'DNA or RNA inside a protein coat.')),
 ('If Monera is to bacteria, ____ is to sponges.', ['Plantae', 'Animalia', 'Fungi', 'Protista'], 'B', 89, ['Sponges (Porifera) are the simplest animals → Animalia.'], 'Sponges are animals, not plants.', ('A pine tree belongs to which kingdom?', 'Plantae.')),
 ('An organism has cellulose cell walls, chlorophyll, vascular tissue, seeds enclosed in fruits and leaves with parallel veins. It is a', ['gymnosperm', 'dicot', 'monocot', 'fern'], 'C', 85, ['Cellulose + chlorophyll → Plantae.', 'Seeds in fruits → angiosperm.', 'Parallel veins → monocot.'], 'Narrow down rank by rank: kingdom → group → class.', ('What would net veins and two cotyledons indicate?', 'A dicot.')),
 ('Which pair of organisms are both heterotrophs that absorb their food?', ['Yeast and mushroom', 'Moss and fern', 'Amoeba and Paramecium', 'Euglena and Volvox'], 'A', 76, ['Yeast and mushroom are fungi — absorb food.', 'Amoeba and Paramecium ingest food; mosses, ferns, Euglena, Volvox photosynthesise.'], 'Absorb → fungi.', ('Which pair ingest food?', '*Amoeba* and *Paramecium*.')),
]
for n, (q, o, ans, pg, why, tip, sim) in enumerate(U, 1):
    M(f'u{n:02d}', a, pg, q, o, ans, [f'Answer {ans}: {o["ABCDE".index(ans)]}.'] + why, tip, [sim])

F('u33', a, 116, 'During alternation of generations the ____ generation alternates with the gametophyte generation.', 'sporophyte', ['sporophyte', 'zygote', 'prothallus'],
  ['Answer: sporophyte.', 'The two generations are sporophyte (makes spores) and gametophyte (makes gametes).'], 'Spores ↔ gametes.', [('What does the gametophyte produce?', 'Gametes.')])
F('u34', a, 116, 'The two body forms of cnidarians are the polyp and the ____.', 'medusa', ['medusa', 'planula', 'proglottid'],
  ['Answer: medusa.', 'Polyp = attached, mouth up; medusa = free-floating, mouth down. The planula is the larva.'], 'Medusa floats like a jellyfish umbrella.', [('What is the swimming larva of cnidarians called?', 'Planula.')])
F('u35', a, 116, 'Some animals reproduce asexually by regeneration, budding and ____.', 'parthenogenesis', ['parthenogenesis', 'conjugation', 'pollination'],
  ['Answer: parthenogenesis.', 'An unfertilised egg develops into a new individual.'], 'Partheno = virgin (no fertilisation).', [('Which animal reproduces by budding?', '*Hydra*.')])
S('u36', a, 117, 'Describe at least three ways in which bacteria obtain food.', 'Photoautotrophic (make food using light), chemoautotrophic (make food using energy from inorganic chemicals such as ammonia), saprophytic (feed on dead organic matter), parasitic (feed on a living host).',
  ['Step 1: split into autotrophs and heterotrophs.', 'Step 2: autotrophs — photo- and chemo-.', 'Step 3: heterotrophs — saprophytic and parasitic.'], 'Two autotrophic + two heterotrophic ways = four full points.', [('Match: cyanobacteria — ?', 'Give off O₂ by photosynthesis.')])
