from common import *

L21 = L('2-1', '2.1', 'The Importance of Classification', [53, 57], [
    T('c01', '2.1 Why do we classify at all?', 53,
      'Imagine walking into a market where tomatoes, nails, soap, teff and medicine are all thrown into one big pile. You would waste hours finding anything. Shops solve this by **grouping** things that are alike. Biology has the same problem, only much bigger.',
      'From early times people grouped plants and animals by **use** (edible, poisonous, medicinal plants), by **habit or size** (herbs, shrubs, trees) and by obvious type (insects, birds, fishes). Grouping makes living things easier to understand, remember and talk about.',
      '**Taxonomy** is the branch of biology that deals with the **naming and classification** of organisms. A biologist who specialises in this work is a **taxonomist**.',
      '**Step 1 — the problem:** millions of organisms are already known, new ones are discovered all the time, and there are also fossils. Nobody can learn each one separately.',
      '**Step 2 — the solution:** taxonomists examine the **structure** of organisms carefully. Organisms that are **alike** are put in the same group; organisms that are **different** go into other groups.',
      '**Step 3 — the result:** a system of **naming and arranging** organisms into groups, so that one name tells you a lot about the organism and its relatives.'),
    TB('t01', 'Why classification is needed — the five big reasons', 53, ['Reason', 'What it means', 'Everyday example'], [
        ['**Order out of huge numbers**', 'Millions of living and fossil organisms are arranged into a manageable set of groups', 'Like books on shelves by subject in a library'],
        ['**Easy identification**', 'Once you know the group, you can name an unknown specimen quickly', 'A student finds a plant in the school compound and keys it out'],
        ['**Shows relationships**', 'Organisms in the same group share many features (they are related)', 'Lion, leopard and domestic cat are all cats (family Felidae)'],
        ['**One name for the whole world**', 'Each species gets one scientific name that every scientist understands', '*Zea mays* is maize in Asmara, Nairobi and Paris'],
        ['**Useful predictions**', 'If one member of a group is useful or harmful, its relatives may be too', 'Relatives of a medicinal plant may contain similar medicines'],
    ]),
    T('c02', 'A short history: from Aristotle to Whittaker', 54,
      '**Aristotle** (Greek thinker, 4th century BC) made one of the first written classifications. He grouped animals by simple features such as where they live and move (land, water, air) and whether or not they have red blood. His student **Theophrastus** grouped plants as **herbs, shrubs and trees** — the same everyday grouping the textbook mentions.',
      '**Carl Linnaeus** (1707–1778), a **Swedish botanist**, built the system we still use, more than 200 years ago. He did two great things: (1) he arranged every organism then known into a series of **increasingly general groups** (a hierarchy), based on how similar their structures are; (2) he gave every species a **two-word scientific name** (binomial nomenclature). For this he is called the **“father” of modern taxonomy**.',
      'Later, as microscopes and chemistry improved, the number of kingdoms grew: two kingdoms (plants, animals) → three (fungi separated) → four (prokaryotes separated as Monera) → **five kingdoms**, proposed by **R. H. Whittaker in 1969**. This five-kingdom system is the one your textbook and exams use.',
      'Your exam will most often ask: **“Who is the father of taxonomy?”** → Linnaeus. **“Who proposed the five kingdoms, and when?”** → Whittaker, 1969.'),
    TB('t02', 'Timeline of classification', 54, ['Who / when', 'Idea', 'Remember it as'], [
        ['Aristotle (4th century BC)', 'Animals grouped by habitat and blood; plants (by Theophrastus) as herbs, shrubs, trees', 'The first “sorting”'],
        ['Carl Linnaeus (1700s)', 'Hierarchy of ranks + binomial nomenclature in Latin', 'Father of modern taxonomy'],
        ['Two → three → four kingdoms', 'Fungi separated (chitin wall, no chlorophyll); then prokaryotes separated as Monera', 'Better microscopes, more kingdoms'],
        ['R. H. Whittaker (1969)', 'Five kingdoms: Monera, Protista, Fungi, Plantae, Animalia', 'The system in this unit'],
        ['Carl Woese (late 20th century)', 'Three domains above kingdoms: Bacteria, Archaea, Eukarya (from molecular studies)', 'Extra, for wider reading'],
    ]),
    T('c03', 'The seven ranks (taxa) — a ladder of groups', 54,
      'In biological classification a group of any size is called a **taxon** (plural: **taxa**). Since Linnaeus, the groups are arranged as a **hierarchy**: big groups contain smaller groups, which contain even smaller groups. There are **seven main ranks**:',
      '**Kingdom → Phylum → Class → Order → Family → Genus → Species**',
      'Read the ladder **downwards**: the groups get **smaller**, and the members become **more similar** to each other. Read it **upwards**: the groups get **bigger** and the members are **less similar**.',
      '**Kingdom** — the highest (largest) rank. In this book there are five kingdoms: Monera, Protista, Fungi, Plantae and Animalia.',
      '**Phylum** (plural: phyla) — each kingdom is divided into phyla by its main features. Example: an animal with a backbone goes into phylum **Chordata**.',
      '**Class** — a smaller division of a phylum. Chordata contains the classes fishes, amphibians, reptiles, birds and mammals.',
      '**Order** — each class is divided into orders. Insects are split into orders mainly by their **wings**; all two-winged insects, e.g. house flies, are in order **Diptera**.',
      '**Family** — each order contains several families. Frogs and toads are in the **same order** but **different families**.',
      '**Genus** (plural: genera) — members are very similar. Some can interbreed but the offspring may be **infertile**, e.g. the **mule** (horse × donkey).',
      '**Species** — the lowest (smallest) rank. Members are very similar (small differences such as flower colour) and **can interbreed to produce fertile offspring**. One genus usually has several species; the textbook gives genus *Felis* with 10 or more species — lion, tiger, leopard, cheetah, domestic cat and others.'),
    DG('d01', 'Hierarchy pyramid: the higher the rank, the bigger and less alike the group', 54, 'pyramid', 'plain'),
    MN('m01', 'King Philip Came Over For Good Soup', 55,
       ['The first letter of each word gives the ranks in order from biggest to smallest. Say it three times, then write the ranks from memory.',
        '**Tigrinya-friendly tip:** think of an address that gets smaller step by step: **ሃገር** (country) → **ዞባ** (region) → **ንኡስ ዞባ** (sub-zone) → **ዓዲ** (village) → **ስድራ** (family) → **ሰብ** (one person). The country is like the kingdom and one person is like one species: the further down you go, the smaller the group and the more alike its members. (Taxonomy has seven ranks; the address idea is the same.)'],
       [('K', 'King', 'Kingdom — largest group'), ('P', 'Philip', 'Phylum'), ('C', 'Came', 'Class'), ('O', 'Over', 'Order'), ('F', 'For', 'Family'), ('G', 'Good', 'Genus'), ('S', 'Soup', 'Species — smallest group')]),
    TB('t03', 'Worked hierarchy: human, maize, mushroom and lion', 56, ['Rank', 'Human', 'Maize', 'Mushroom', 'Lion'], [
        ['**Kingdom**', 'Animalia', 'Plantae', 'Fungi', 'Animalia'],
        ['**Phylum**', 'Chordata', 'Angiospermae', 'Basidiomycota', 'Chordata'],
        ['**Class**', 'Mammalia', 'Monocotyledon', 'Hymenomycetes', 'Mammalia'],
        ['**Order**', 'Primates', 'Commelinales', 'Agaricales', 'Carnivora'],
        ['**Family**', 'Hominidae', 'Poaceae', 'Agaricaceae', 'Felidae'],
        ['**Genus**', '*Homo*', '*Zea*', '*Agaricus*', '*Felis* (modern books: *Panthera*)'],
        ['**Species**', '*sapiens*', '*mays*', '*bisporus*', '*leo*'],
        ['**Scientific name**', '*Homo sapiens*', '*Zea mays*', '*Agaricus bisporus*', '*Felis leo* (*Panthera leo*)'],
    ], 'Read across one row to compare: human and lion share **kingdom, phylum and class** (both are mammals with backbones), then split at **order** (Primates vs Carnivora). Maize and the mushroom split from them already at **kingdom**.',
       'The human, maize and mushroom columns follow the textbook’s table. Your textbook writes the lion as *Felis leo*; newer books use *Panthera leo*. In an exam built on this textbook, *Felis leo* is accepted.'),
    WK('w01', 'Worked example: how related are two organisms?', 56,
       'Use the table above. Which pair is more closely related: (a) human and lion, or (b) lion and maize? Explain using ranks.',
       ['**Step 1 — rule:** the **lower** the rank two organisms share, the **more closely related** they are.',
        '**Step 2 — human and lion:** same kingdom (Animalia), phylum (Chordata) and class (Mammalia). They first differ at **order**.',
        '**Step 3 — lion and maize:** they differ already at **kingdom** (Animalia vs Plantae), so they share no rank at all in the table.',
        '**Step 4 — conclude:** human and lion share three ranks; lion and maize share none.'],
       '(a) Human and lion are more closely related: they share kingdom, phylum and class, while lion and maize differ at kingdom level.'),
    T('c04', 'Binomial nomenclature: one organism, one two-part name', 56,
      '**Binomial** means **two names**. Linnaeus gave every species a two-word **scientific name**, for example *Homo sapiens* (human), *Felis domestica* (domestic cat) and *Zea mays* (maize).',
      '**Part 1 = genus name** (like a surname, shared by close relatives). **Part 2 = species name** (the particular kind inside that genus).',
      '**Why Latin?** Common names are not universal: different people use different languages and different local names. A lion is **ኣንበሳ** in Tigrinya, *anbessa* in Amharic, *simba* in Swahili — but *Felis leo* everywhere. Latin is an old language that no longer changes, so the name stays fixed. A name from another language is **Latinised**: *Aloe massawana* is the aloe first identified near **Massawa**.',
      '**Shortening:** after the full name has been written once, the genus may be shortened to its capital letter, e.g. *Acacia tortilis* → *A. tortilis*.'),
    TB('t04', 'The four rules for writing a scientific name', 57, ['Rule', 'Correct', 'Wrong'], [
        ['1. Every organism has only **one** scientific name', '*Zea mays* for maize', 'Giving maize two different scientific names'],
        ['2. The name has **two parts**: genus then species', '*Homo sapiens*', '*Homo* alone, or *sapiens Homo*'],
        ['3. Genus starts with a **capital**, species with a **small** letter', '*Homo sapiens*', 'Homo Sapiens, homo sapiens'],
        ['4. **Italics** when printed; **each word underlined separately** when handwritten', '*Felis leo* in print; by hand, a line under Felis and a separate line under leo', 'Felis leo in plain print; one line under both words'],
    ], 'Exam trap: options often differ only in a capital letter or in italics. Check the capital G, the small s, and the italics — one at a time.'),
    WK('w02', 'Worked example: spot the correctly written name', 57,
       'Which is correct? A. Homo Sapiens  B. homo sapiens  C. *Homo sapiens*  D. *Homo Sapiens*',
       ['**Step 1 — check the genus:** it must start with a capital. B fails (small h).',
        '**Step 2 — check the species:** it must start with a small letter. A and D fail (capital S).',
        '**Step 3 — check printing:** a printed name must be in italics. C is in italics and passes every rule.'],
       'C. *Homo sapiens*'),
    WK('w03', 'Worked example: classify by your own criteria (Activity 2.1)', 57,
       'Group these six organisms into two groups in two different ways: lion, maize, house fly, teff, honey bee, acacia.',
       ['**Step 1 — choose a criterion you can observe.** Way 1: “Can it make its own food (green, photosynthesises)?”',
        '**Step 2 — sort:** Plants: maize (*Zea mays*), teff, acacia (*Acacia tortilis*). Animals: lion (*Felis leo*), house fly (*Musca domestica*), honey bee (*Apis mellifera*).',
        '**Step 3 — a second criterion:** “Does it have a backbone?” — Vertebrate: lion. Invertebrates: house fly, honey bee. (Plants are not grouped this way; this criterion only works inside animals.)',
        '**Step 4 — lesson learned:** a good criterion is a feature you can **see or test**, and each organism must fall clearly into **one** group.'],
       'Way 1: plants (maize, teff, acacia) vs animals (lion, house fly, honey bee). Way 2 (animals only): vertebrate (lion) vs invertebrates (house fly, honey bee).'),
    CK('k01', 55, 'The smallest unit (rank) of classification is the', ['phylum', 'class', 'species', 'kingdom'], 'C',
       '**Species** is the lowest rank. Kingdom is the highest. Use KPCOFGS: S comes last.'),
    CK('k02', 55, 'The category “class” is directly subdivided into', ['species', 'phyla', 'families', 'orders'], 'D',
       'Class → **Order** → Family. In KPCOFGS, O (Over) comes right after C (Came).'),
    CK('k03', 56, 'Taxonomists use Latin for scientific names mainly because Latin', ['is spoken by most scientists today', 'no longer changes and gives one name understood worldwide', 'is easier than English', 'has short words'], 'B',
       'Latin is no longer a changing everyday language, so a Latin name stays fixed and is the same in every country.'),
    CK('k04', 55, 'A mule is produced by crossing a horse and a donkey but cannot reproduce. This shows that horse and donkey are', ['the same species', 'in the same genus but different species', 'in different kingdoms', 'in different phyla'], 'B',
       'Members of one **species** produce **fertile** offspring. Organisms of the same **genus** may interbreed but the offspring (mule) are infertile.'),
])
