from common import *

L22 = L('2-2', '2.2', 'Specimen Identification and Keys', [58, 60], [
    T('c05', '2.2 What is a key?', 58,
      'You find an unknown animal or plant. How do you find its name? Books that help you name organisms use a **key**: a series of questions which, when answered one after another, **lead you to the name of the specimen**.',
      'Taxonomists use several types of keys. The most familiar one in botany and zoology is the **dichotomous key** (*dicho* = in two, *tomous* = cut: “cut in two”).',
      'A dichotomous key is a series of **couplets**. A couplet is a **pair of statements that are mutually exclusive** — only one of the two can be true for your specimen (e.g. “wings present” / “wings absent”).',
      'At each couplet you **decide** which statement fits. That statement either gives you the **name** (a taxon) or tells you **which couplet to go to next**.',
      'With every step the number of possible names gets **smaller**, until only **one** possibility is left.'),
    T('c06', 'How to build a dichotomous key — four steps', 58,
      '**Step a — list the features.** Write the main observable features of each organism, looking for features that make each one **different** from the others (wings? gills? hooves? diet? height?).',
      '**Step b — pair the features.** Arrange them as **pairs of opposite statements** (aquatic with gills / terrestrial with lungs).',
      '**Step c — read each pair.** Beside each statement write either the **name** of the organism or the **number of the next couplet**.',
      '**Step d — continue** until **every** organism has been named.',
      '**Golden rules:** use features you can **see or measure** (not “it looks like a cat”); never use features that change (size of a young animal, colour that fades); each couplet must split the group into **two**; with *n* organisms you need *n* − 1 couplets.'),
    TB('t05', 'The textbook key: goat, donkey, cow, bat, fish and hyena', 59, ['Couplet', 'Statement', 'Leads to'], [
        ['1a', 'Aquatic, breathes with gills', '**Fish (F)**'],
        ['1b', 'Terrestrial, breathes with lungs', 'go to 2'],
        ['2a', 'Wings present', '**Bat (B)**'],
        ['2b', 'Wings absent', 'go to 3'],
        ['3a', 'Flesh eating (carnivore)', '**Hyena (D)**'],
        ['3b', 'Plant eating (herbivore)', 'go to 4'],
        ['4a', 'Hoof undivided', '**Donkey (A)**'],
        ['4b', 'Hoof divided', 'go to 5'],
        ['5a', 'Height more than 1.5 m', '**Cow (C)**'],
        ['5b', 'Height less than 0.5 m', '**Goat (E)**'],
    ], 'Six animals → **five couplets** (6 − 1 = 5). Each couplet removes one animal from the list.'),
    ST('s01', 'Walk the key couplet by couplet', 59, 'key', [
        ('**Couplet 1:** gills or lungs? The fish breathes with gills and lives in water — it is named here. The other five go to 2.', 'k1'),
        ('**Couplet 2:** wings? Only the bat has wings. Four animals remain: hyena, donkey, cow, goat.', 'k2'),
        ('**Couplet 3:** diet? The hyena eats flesh. Donkey, cow and goat eat plants.', 'k3'),
        ('**Couplet 4:** hoof? The donkey has an undivided hoof; cow and goat have divided (split) hooves.', 'k4'),
        ('**Couplet 5:** height? The cow is taller than 1.5 m, the goat is shorter. Every animal now has a name.', 'k5'),
    ]),
    T('c07', 'The same key as yes/no questions', 60,
      'Every couplet can be turned into a **yes/no question**:',
      '1. Is the animal aquatic and does it breathe with gills? **Yes** → fish. **No** (terrestrial, lungs) → go to 2.',
      '2. Are wings present? **Yes** → bat. **No** → go to 3.',
      '3. Is the animal flesh eating? **Yes** → hyena. **No** (plant eating) → go to 4.',
      '4. Is the hoof undivided? **Yes** → donkey. **No** (divided) → go to 5.',
      '5. Is it more than 1.5 m tall? **Yes** → cow. **No** → goat.',
      'Whether written as statements or as questions, the key works the same way: **two choices at every step**.'),
    WK('w04', 'Worked example: use the key on an unknown animal', 59,
       'An animal lives on land, has no wings, eats grass, has split hooves and is about 0.4 m tall at the shoulder. Name it using the key.',
       ['**Couplet 1:** lives on land → not fish → go to 2.',
        '**Couplet 2:** no wings → not bat → go to 3.',
        '**Couplet 3:** eats grass (herbivore) → not hyena → go to 4.',
        '**Couplet 4:** split (divided) hooves → not donkey → go to 5.',
        '**Couplet 5:** less than 0.5 m → goat.'],
       'Goat (E).'),
    WK('w05', 'Worked example: build your own key (Activity 2.2)', 60,
       'Build a dichotomous key for snail, earthworm, spider, butterfly and ant using the features shell, wings and number of legs.',
       ['**Step a — features:** snail: shell, no legs. Earthworm: no shell, no legs. Spider: no shell, 8 legs, no wings. Butterfly: 6 legs, wings. Ant (worker): 6 legs, no wings.',
        '**Step b — first couplet must split the group in two:** “legs absent” (snail, earthworm) / “legs present” (spider, butterfly, ant).',
        '**Step c — write it out:** 1a Legs absent → go to 2; 1b Legs present → go to 3. 2a Shell present → **snail**; 2b Shell absent → **earthworm**. 3a Eight legs → **spider**; 3b Six legs → go to 4. 4a Wings present → **butterfly**; 4b Wings absent → **ant**.',
        '**Step d — check:** 5 organisms, 4 couplets (5 − 1). Every statement uses a visible feature. Every organism is named once.'],
       '1 legs absent→2 / legs present→3; 2 shell→snail / no shell→earthworm; 3 eight legs→spider / six legs→4; 4 wings→butterfly / no wings→ant.'),
    RM('r01', 'Common mistakes with keys', 60,
       '✗ Using a feature that is not visible on the specimen (“it is dangerous”). ✓ Use structures: legs, wings, hooves, gills.',
       '✗ Couplets that overlap (“big” / “brown”). ✓ The two statements must be **opposites** of the same feature.',
       '✗ Skipping a couplet because you “know” the answer. ✓ Always start at couplet 1 and follow the numbers.'),
    MN('m02', 'Key memory: “Two doors at every step”', 58,
       ['Picture a corridor with **two doors** at every step: you open **one** door only, and behind it is either a **name** or **another pair of doors**. *Di-* = two, so dichotomous = two choices.',
        '**Tigrinya-friendly tip:** a couplet is like the question **“እወ ወይስ ኣይፋል?”** (yes or no?) — one answer only, then move on.']),
    CK('k05', 58, 'A dichotomous key is made of', ['single statements about colour', 'pairs of mutually exclusive statements', 'pictures only', 'lists of scientific names'], 'B',
       'Each couplet is a **pair** of statements of which only **one** can be true for the specimen.'),
    CK('k06', 59, 'How many couplets are needed in a dichotomous key for 8 organisms?', ['4', '6', '7', '8'], 'C',
       'Each couplet separates off one more organism, so *n* organisms need *n* − 1 couplets: 8 − 1 = **7**.'),
    CK('k07', 59, 'In the textbook key, which couplet separates the donkey from the cow and goat?', ['gills or lungs', 'wings', 'diet', 'hoof divided or undivided'], 'D',
       'Couplet 4: the donkey’s hoof is **undivided**; cow and goat have **divided** hooves.'),
])

L23 = L('2-3', '2.3', 'The Five-Kingdom Classification', [60, 63], [
    T('c08', '2.3 From two kingdoms to five', 61,
      'Taxonomy changes as technology lets biologists see **more detail inside cells and molecules**. Follow the story step by step:',
      '**Step 1 — two kingdoms:** every organism was a **plant** or an **animal**.',
      '**Step 2 — three kingdoms:** **fungi** were separated from plants. Fungi had been treated as plants because they have a cell wall, but the wall is chemically different: plant wall = **cellulose**, fungal wall = **chitin**. Fungi also **lack chlorophyll** and feed on dead or decaying matter.',
      '**Step 3 — four kingdoms:** the big difference between **prokaryotes** (no true nucleus) and **eukaryotes** (true nucleus) was recognised. Prokaryotes such as bacteria became kingdom **Monera**.',
      '**Step 4 — five kingdoms:** many simple organisms once placed with plants or animals were moved into kingdom **Protista**. The five-kingdom system was first suggested by **R. H. Whittaker in 1969** and is widely used today. It is not the only system, but it is the most accepted one at this level.'),
    DG('d02', 'The five kingdoms at a glance', 62, 'kingdoms', 'plain'),
    TB('t06', 'The five kingdoms side by side (Activity 2.3 completed)', 63, ['Kingdom', 'Cell type', 'Cellular organisation', 'Cell wall', 'Mode of nutrition', 'Examples'], [
        ['**Monera**', 'Prokaryotic', 'Unicellular (simple)', 'Present (not cellulose)', 'Autotrophic (photo- or chemosynthetic) or heterotrophic (saprophytic, parasitic)', 'Bacteria, cyanobacteria'],
        ['**Protista**', 'Eukaryotic', 'Mostly unicellular; some colonial or multicellular', 'Present in some (algae), absent in others (protozoa)', 'Autotrophic (algae) or heterotrophic (protozoa, slime moulds)', '*Amoeba*, *Paramecium*, *Euglena*, *Spirogyra*, slime moulds'],
        ['**Fungi**', 'Eukaryotic', 'Mostly multicellular (hyphae); yeast unicellular', 'Present — **chitin**', 'Heterotrophic: **absorb** food (saprophytes or parasites)', 'Yeast, *Rhizopus* (bread mould), mushroom'],
        ['**Plantae**', 'Eukaryotic', 'Complex multicellular with tissues and organs', 'Present — **cellulose**', 'Autotrophic: **photosynthesis** with chlorophyll', 'Mosses, ferns, pine, maize, teff'],
        ['**Animalia**', 'Eukaryotic', 'Complex multicellular with tissues, organs, systems', '**Absent**', 'Heterotrophic: **ingest** food', 'Sponges, worms, insects, fish, humans'],
    ], 'Learn the table **column by column**: first all the cell types (only Monera is prokaryotic), then the walls (chitin vs cellulose vs none), then nutrition (make food, absorb food, ingest food).'),
    T('c09', 'Two words you must own: autotroph and heterotroph', 61,
      'An **autotroph** (*auto* = self, *troph* = feeding) produces complex organic compounds (food) from **simple inorganic molecules** such as carbon dioxide and water. Energy comes from **light** (photosynthesis) or from **chemicals** (chemosynthesis). Examples: plants, algae, cyanobacteria.',
      'A **heterotroph** (*hetero* = other) **cannot make its own food** and depends on complex organic substances made by other organisms. Animals **ingest** (swallow) food; fungi **absorb** digested food; many bacteria and protozoa are heterotrophs too.',
      'Tip for exam stems: “**makes** its own food” → autotroph; “**takes** food from others” → heterotroph; “**absorbs**” → fungi or saprophytic bacteria; “**ingests**” → animals or protozoa.'),
    MN('m03', 'Many People Find Plants Amazing', 61,
       ['The five kingdoms in order from simplest to most complex: **M**onera, **P**rotista, **F**ungi, **P**lantae, **A**nimalia.',
        'Remember the two “P”s: the first P (Protista) is **tiny and simple**, the second P (Plantae) is **big and green**.'],
       [('M', 'Many', 'Monera — prokaryotes (bacteria)'), ('P', 'People', 'Protista — simple eukaryotes'), ('F', 'Find', 'Fungi — chitin wall, absorb food'), ('P', 'Plants', 'Plantae — cellulose, photosynthesis'), ('A', 'Amazing', 'Animalia — no wall, ingest food')]),
    TB('t07', 'Key questions that place any organism in a kingdom', 63, ['Ask in this order', 'If YES', 'If NO'], [
        ['1. Is the cell prokaryotic (no true nucleus)?', '**Monera**', 'go to 2'],
        ['2. Is it mostly a single cell (or simple colony) that lives in water or damp places?', '**Protista**', 'go to 3'],
        ['3. Does it have a chitin wall, no chlorophyll, and absorb its food?', '**Fungi**', 'go to 4'],
        ['4. Does it have cellulose walls and chlorophyll (photosynthesis)?', '**Plantae**', '**Animalia** (no wall, ingests food)'],
    ], 'This is itself a little dichotomous key — 2.2 and 2.3 work together. (Yeast is single-celled but has a chitin wall and absorbs food, so it goes to Fungi.)'),
    T('c10', 'Beyond five kingdoms: the three domains', 61,
      'Molecular studies (by **Carl Woese**) later showed that prokaryotes are of two very different kinds. Many biologists now add a rank **above** kingdom, the **domain**:',
      '**Domain Bacteria** — ordinary bacteria and cyanobacteria (prokaryotes).',
      '**Domain Archaea** — prokaryotes that often live in extreme places such as hot springs and very salty water.',
      '**Domain Eukarya** — all eukaryotes: protists, fungi, plants and animals.',
      'So in the three-domain view, the old kingdom Monera is split into two domains. For your Grade 9 exams the **five-kingdom** system of Whittaker is the main one; domains are useful background.'),
    TB('t08', 'Five kingdoms vs three domains', 61, ['Five-kingdom system', 'Three-domain system'], [
        ['Monera (all prokaryotes)', 'Bacteria + Archaea (two separate domains)'],
        ['Protista, Fungi, Plantae, Animalia', 'All inside domain Eukarya'],
        ['Proposed by Whittaker, 1969', 'Proposed by Woese, from molecular (RNA) studies'],
        ['Based on cell type, organisation and nutrition', 'Based mainly on molecular differences'],
    ]),
    T('c11', 'Where do viruses fit? (Nowhere — and here is why)', 61,
      'Viruses are **not placed in any of the five kingdoms**. Remember from Unit 1:',
      '**1.** A virus is **not a cell**: it is only genetic material (**DNA or RNA**) inside a **protein coat**. Kingdoms group **cellular** organisms.',
      '**2.** A virus can **reproduce only inside a living host cell**; outside a host it shows no life activities and can even be crystallised.',
      '**3.** It has no metabolism of its own (no respiration, no nutrition).',
      'Because viruses show some features of living things (they reproduce and have genes) and some features of non-living things, their nature is called **ambiguous** — they lie on the border between living and non-living.'),
    WK('w06', 'Worked example: place an organism in its kingdom', 62,
       'An organism is multicellular, made of thread-like filaments, has no chlorophyll, has cell walls of chitin and grows on old bread. Which kingdom? Give two reasons.',
       ['**Step 1 — cell type:** multicellular threads with walls suggest a eukaryote, so not Monera.',
        '**Step 2 — nutrition:** no chlorophyll, grows on (absorbs food from) bread → heterotroph that absorbs food, so not Plantae.',
        '**Step 3 — wall chemistry:** chitin, not cellulose → Fungi, not Plantae; animals have no wall at all.',
        '**Step 4 — conclude:** kingdom Fungi (it is bread mould, *Rhizopus*).'],
       'Fungi — it has chitin cell walls and absorbs food without chlorophyll (saprophyte).'),
    CK('k08', 61, 'The five-kingdom classification was proposed by', ['Linnaeus in 1735', 'Whittaker in 1969', 'Aristotle', 'Woese in 1990'], 'B',
       'R. H. **Whittaker, 1969**. Linnaeus gave the ranks and binomial names; Woese proposed domains.'),
    CK('k09', 61, 'Fungi were separated from plants mainly because fungi', ['are multicellular', 'have chitin walls and no chlorophyll', 'have a nucleus', 'live on land'], 'B',
       'Plant walls are **cellulose**; fungal walls are **chitin**. Fungi also lack chlorophyll and feed on dead matter.'),
    CK('k10', 61, 'Which kingdom contains organisms without a cell wall that ingest their food?', ['Monera', 'Fungi', 'Plantae', 'Animalia'], 'D',
       'Animals have **no cell wall** and **ingest** food.'),
    CK('k11', 61, 'Viruses are not placed in any kingdom because they', ['are too small to see', 'are not cells and reproduce only inside living host cells', 'cause disease', 'live only in water'], 'B',
       'Kingdoms group **cellular** organisms; a virus is DNA or RNA in a protein coat and reproduces only in a host cell.'),
])
