from common import *

L24 = L('2-4', '2.3.1', 'Kingdom Monera', [63, 66], [
    T('c12', '2.3.1 Monera: the simplest cells', 63,
      'All members of kingdom Monera are **prokaryotic** and **unicellular**: no true nucleus (the DNA lies free in a nucleoid region) and no membrane-bound organelles such as mitochondria or chloroplasts. The kingdom contains two groups: **bacteria** and **cyanobacteria** (once called blue-green algae).',
      '**Where are bacteria?** Everywhere life is possible: hot springs, deep ocean beds, air, water, soil, on the surfaces of objects, and inside the bodies of animals and plants. They are the **simplest and most abundant** micro-organisms.',
      '**Shapes (useful extra):** rod-shaped = **bacilli**, spherical = **cocci**, spiral = **spirilla**.'),
    T('c13', 'A. Bacteria — how they feed', 63,
      '**Nutrition** is the way an organism obtains and assimilates its food. Bacteria show **two modes**:',
      '**1. Heterotrophic (most bacteria)** — cannot make food. **Saprophytic** bacteria feed on waste and dead organic matter (they are decomposers that recycle minerals). **Parasitic** bacteria take food from a living **host** and may cause disease.',
      '**2. Autotrophic** — make their own food. **Photoautotrophic** bacteria use **light energy** (photosynthesis). **Chemoautotrophic** bacteria use **chemical energy** from inorganic substances such as **ammonia, hydrogen sulphide or hydrogen gas**. Nitrifying bacteria (ammonia → nitrite → nitrate) are chemoautotrophs.'),
    TB('t09', 'Nutrition types in Monera', 64, ['Type', 'Energy source', 'Carbon source', 'Example'], [
        ['Photoautotroph', 'Light', 'CO₂', 'Cyanobacteria, some purple and green bacteria'],
        ['Chemoautotroph', 'Inorganic chemicals (NH₃, H₂S, H₂)', 'CO₂', 'Nitrifying bacteria'],
        ['Saprophytic heterotroph', 'Organic matter', 'Dead organic matter', 'Decay bacteria (decomposers)'],
        ['Parasitic heterotroph', 'Organic matter', 'Living host', 'Disease-causing bacteria'],
    ], '“**Auto** = self-made, **photo** = light, **chemo** = chemicals.” Read the name and the energy source tells itself.'),
    ST('s02', 'Binary fission step by step', 64, 'fission', [
        ('**Step 1 — grow:** the cell elongates (gets longer).', 'f1'),
        ('**Step 2 — copy:** the single chromosome (DNA) **duplicates**; the two copies move apart.', 'f2'),
        ('**Step 3 — split:** the cytoplasm divides into two; a new wall forms across the middle.', 'f3'),
        ('**Step 4 — two daughter cells** grow and divide again, every **20–30 minutes**. 1 → 2 → 4 → 8 …', 'f4'),
    ], 'Bacteria reproduce **asexually** by binary fission. They do not reproduce sexually, but some, like *Escherichia coli*, transfer genetic material from one cell to another by a primitive sexual process called **conjugation**.'),
    WK('w07', 'Worked example: how fast do bacteria multiply?', 64,
       'One bacterium divides every 30 minutes. How many bacteria are present after 3 hours, if none die?',
       ['**Step 1 — count the divisions:** 3 hours = 180 minutes; 180 ÷ 30 = **6 divisions**.',
        '**Step 2 — each division doubles the number:** 1 → 2 → 4 → 8 → 16 → 32 → 64.',
        '**Step 3 — as a formula:** number = 2^(divisions) = 2⁶ = 64.'],
       '64 bacteria. This is why food goes bad quickly when it is kept warm.'),
    T('c14', 'B. Cyanobacteria', 65,
      '**Where:** almost every life-supporting environment — fresh water, the sea and damp soil (where they give the “earthy” smell).',
      '**Colour:** named after their **bluish** pigment, but they may be red, pink, yellow, brown or black. The **Red Sea** turns red at times when a red-pigmented species is abundant.',
      '**Form:** single rod-shaped or spherical cells, in **colonies** or long **filaments**. Cells are larger than other bacteria and **lack flagella**.',
      '**Nutrition:** autotrophic with **chlorophyll**; like plants they **release oxygen** in photosynthesis. Cyanobacteria are believed to be responsible for the **first appearance of significant amounts of oxygen on Earth**. Many can also **fix atmospheric nitrogen** into nitrates or ammonia in the soil.',
      '**Reproduction:** only asexual — **simple cell division** or **fragmentation** (a filament breaks into pieces, each grows into a new filament). No sexual reproduction.'),
    TB('t10', 'Bacteria vs cyanobacteria', 65, ['Feature', 'Bacteria', 'Cyanobacteria'], [
        ['Cell type', 'Prokaryotic, unicellular', 'Prokaryotic, unicellular (in colonies or filaments)'],
        ['Nutrition', 'Mostly heterotrophic; some auto-', 'Autotrophic — photosynthesis with chlorophyll, release O₂'],
        ['Flagella', 'Some have flagella', 'No flagella'],
        ['Reproduction', 'Binary fission; conjugation in some (e.g. *E. coli*)', 'Cell division or fragmentation; no sexual'],
        ['Special role', 'Decomposers, nitrifying bacteria, some cause disease', 'First oxygen on Earth; nitrogen fixation'],
    ]),
    RM('r02', 'Are all bacteria harmful? No!', 66,
       '**Useful:** decomposers recycle minerals; nitrogen-fixing and nitrifying bacteria make soil fertile; bacteria help make yoghurt and cheese.',
       '**Harmful:** parasitic bacteria cause diseases in humans, animals and plants.',
       'So in the exam “Bacteria are responsible for: oxygen in the atmosphere, recycling minerals, causing diseases” → **all of the above**.'),
    MN('m04', 'Monera memory', 63,
       ['**“Mono-nucleus? No nucleus!”** — Monera are the only kingdom with **no true nucleus**.',
        '**Photo = ፎቶ (light picture), chemo = chemicals.** A photoautotroph uses light like a camera; a chemoautotroph uses chemicals like ammonia.']),
    CK('k12', 64, 'Bacteria mainly reproduce by', ['fragmentation', 'binary fission', 'spores only', 'budding'], 'B',
       '**Binary fission**: elongate, duplicate DNA, divide into two. Fragmentation is typical of cyanobacteria filaments.'),
    CK('k13', 64, 'Nitrifying bacteria that get energy by oxidising ammonia are', ['photoautotrophs', 'chemoautotrophs', 'saprophytes', 'parasites'], 'B',
       'They make food using **chemical energy** from inorganic ammonia → **chemo**autotrophs.'),
    CK('k14', 66, 'Which organisms are believed to have produced the first significant oxygen on Earth?', ['Fungi', 'Cyanobacteria', 'Protozoa', 'Mosses'], 'B',
       'Cyanobacteria photosynthesise with chlorophyll and release O₂.'),
])

L25 = L('2-5', '2.3.2', 'Kingdom Protista', [66, 76], [
    T('c15', '2.3.2 Protista: simple eukaryotes', 67,
      'Kingdom Protista contains many **simple eukaryotes** (true nucleus). Some are **unicellular**, some **colonial**, a few **multicellular**.',
      'Shared features: they all need a **water-based environment** (fresh water, sea or damp soil); all are **aerobic** with **mitochondria**; some have **chloroplasts** and photosynthesise; most reproduce by **binary fission** and **conjugation**; many form **cysts** (protective outer coverings) in bad conditions.',
      'Protists are divided into **three groups by mode of nutrition**: **A. animal-like protists (protozoa)**, **B. plant-like protists (algae)** and **C. fungus-like protists (slime moulds)**.'),
    DG('d03', 'Protista: three groups, sorted by how they feed', 67, 'protista', 'plain'),
    T('c16', 'A. Protozoa — animal-like protists', 67,
      'Protozoa are **heterotrophs** that **ingest** solid food (**holozoic** nutrition). Some have mouth-like parts to catch prey; others use pseudopodia to move and to engulf prey such as bacteria and other small one-celled organisms.',
      'Protozoa are divided into **four phyla by their locomotory structure**:',
      '**i. Sarcodina** — move by **pseudopodia** (“false feet”): cytoplasm flows into an outgrowth that grows longer. Example: *Amoeba proteus* (free-living, fresh water). *Entamoeba histolytica* is a parasite that causes **amoebic dysentery**; it spreads through **contaminated water and uncooked vegetables**.',
      '**ii. Ciliophora** — move by **cilia**. Example: *Paramecium* (fresh water), perhaps the most complex of all single cells: covered by rows of cilia; **oral groove** leading to the mouth pore and gullet; **two nuclei** (small **micronucleus**, large **macronucleus**); **two contractile vacuoles** (front and back) that remove excess water. Reproduces asexually by binary fission and sexually by **conjugation** (exchange of micronucleus material).',
      '**iii. Mastigophora** — move by **flagella** (whip-like). Example: *Trypanosoma*, a parasite that causes **African sleeping sickness (trypanosomiasis)**, spread by the bite of the **tsetse fly**. It harms cattle and humans: irregular fever, swelling, skin eruptions, then headache, convulsions, coma and death. Parasites are first in the **blood**, later only in the **nervous system**.',
      '**iv. Sporozoa** — **no locomotory structure**; spore-forming and almost all **parasites**, often with two alternate hosts. Example: *Plasmodium*, the cause of **malaria**, carried by the **female *Anopheles* mosquito**.'),
    TB('t11', 'The four protozoan phyla side by side', 68, ['Phylum', 'Moves by', 'Example', 'Disease / note'], [
        ['**Sarcodina**', 'Pseudopodia (false feet)', '*Amoeba proteus*; *Entamoeba histolytica*', 'Amoebic dysentery (contaminated water, raw vegetables)'],
        ['**Ciliophora**', 'Cilia', '*Paramecium*', 'Two nuclei, two contractile vacuoles, conjugation'],
        ['**Mastigophora**', 'Flagella', '*Trypanosoma*', 'Sleeping sickness, spread by tsetse fly'],
        ['**Sporozoa**', 'No locomotory structure', '*Plasmodium*', 'Malaria, spread by female *Anopheles* mosquito'],
    ]),
    MN('m05', 'Protozoa by movement: “Sarco walks, Cilio rows, Mastigo whips, Sporo sits”', 68,
       ['**Sarco**dina walks on false feet; **Cilio**phora rows with many tiny oars (cilia); **Mastigo**phora whips (Greek *mastix* = whip, flagellum); **Sporo**zoa sits still and makes spores.',
        '**Tigrinya-friendly tip:** malaria is carried by **ትንኒ** (mosquito) — only the **female** *Anopheles* bites to feed on blood. Sleep under a net, drain standing water.']),
    TB('t12', 'Malaria: the four Plasmodium species', 70, ['Species', 'Type of malaria', 'Fever repeats', 'Note'], [
        ['*P. vivax*', 'Benign (mild)', 'Every 48 hours', 'Common in Eritrea'],
        ['*P. falciparum*', 'Malignant (harmful)', 'Every 36–48 hours', 'Common in Eritrea; the dangerous one'],
        ['*P. ovale*', '—', '—', 'One of the four human species'],
        ['*P. malariae*', '—', '—', 'One of the four human species'],
    ], 'Main symptoms: **chills and fever at regular intervals**, with heavy **sweating**.'),
    T('c17', 'B. Algae — plant-like protists', 70,
      'Algae are **autotrophic**: they contain photosynthetic pigments and store carbohydrates. They may be unicellular or multicellular and are classified (into more than six phyla) by cell structure, number of flagella, reproduction and life cycle. They are grouped as **simple algae** and **complex algae**.',
      '**i. Simple algae** — all unicellular. Phyla: **Chrysophyta** (diatoms), **Euglenophyta** (euglenoids) and **Pyrrophyta** (dinoflagellates). Floating micro-organisms in water are **plankton**: the photosynthetic part (unicellular algae) is **phytoplankton** — the **primary food source for aquatic animals**; the tiny animals are **zooplankton**.',
      '***Euglena*** lives in muddy water of slow streams, stagnant pools and ditches polluted with animal urine and faeces. It is smaller than *Amoeba* and has a definite shape. Parts: one **flagellum** at the front, attached at the base of a flask-shaped **reservoir**; a **contractile vacuole** near the reservoir; a funnel-like mouth leading to a short **gullet**; many **chloroplasts**; **no cell wall** — shape kept by a thin flexible **pellicle**; a light-sensitive **eyespot (stigma)**. It swims **towards** light of favourable intensity but moves **away** from direct sunlight. It reproduces by **binary fission**; in bad conditions it forms a **cyst**, divides inside, and releases two daughter cells when conditions improve.',
      '**Why is *Euglena* special?** It has chloroplasts (plant-like) but no cell wall and it moves with a flagellum (animal-like) — a good reason why a separate kingdom, Protista, was needed.'),
    T('c18', 'Complex algae (seaweeds)', 72,
      'Three phyla that are wholly or partly multicellular: **Rhodophyta (red algae)**, **Phaeophyta (brown algae)** and **Chlorophyta (green algae)**. They form masses along coasts and sometimes float in the open sea.',
      '**Green algae are the most diverse**: unicellular, filamentous, colonial and multicellular forms, in the sea, fresh water and damp soil. Examples: *Chlamydomonas*, *Spirogyra*, *Volvox*, *Ulva*.',
      '***Chlamydomonas*** — unicellular, **two flagella** (biflagellate); one large chloroplast containing a red **eyespot (stigma)**; **two contractile vacuoles** at the front. Asexual: the nucleus divides to make **up to 16 daughter cells** inside the parent wall. Sexual: two gametes of different mating types **fuse** → zygote → thick wall and dormancy → nucleus divides to give **four** cells that grow flagella and walls.',
      '***Spirogyra*** — **filamentous**, in slow water, ponds and ditches (dark-green hair-like masses). Each cell is independent and has a **spiral chloroplast** with **pyrenoids** (where sugar is stored as **starch**). Reproduction: (1) **fission** (cell division); (2) in bad conditions **conjugation** — the contents of one cell pass through a canal into the opposite cell, the nuclei fuse (**fertilisation**) to form a **zygote**, which gets a thick coat and becomes a **zygospore**; later it grows into a new filament.',
      '***Volvox*** — **colonial**; each cell has **two flagella**, so the colony moves; an intercellular matrix holds the cells; darker green **daughter colonies** are often inside.',
      '***Ulva*** (sea lettuce) — truly **multicellular** with **division of labour**; body **two cells thick**; a **holdfast** anchors it to the sea floor.'),
    TB('t13', 'Green algae compared', 72, ['Alga', 'Body form', 'Movement', 'Key structures', 'Reproduction'], [
        ['*Chlamydomonas*', 'Unicellular', 'Two flagella', 'One large chloroplast, eyespot, two contractile vacuoles', 'Asexual (up to 16 daughter cells); sexual (gamete fusion)'],
        ['*Spirogyra*', 'Filamentous', 'None', 'Spiral chloroplast with pyrenoids (starch)', 'Fission; conjugation → zygospore'],
        ['*Volvox*', 'Colonial', 'Flagella (two per cell)', 'Intercellular matrix, daughter colonies', 'Daughter colonies'],
        ['*Ulva*', 'Multicellular (two cells thick)', 'None (fixed)', 'Holdfast, division of labour', '—'],
        ['*Euglena* (euglenoid)', 'Unicellular', 'One flagellum', 'Pellicle, eyespot, many chloroplasts, no wall', 'Binary fission; cyst in bad conditions'],
    ]),
    T('c19', 'C. Slime moulds — fungus-like protists', 75,
      'Slime moulds feed like fungi: they **absorb** nutrients. Their structure is unusual:',
      '**Acellular slime mould:** no separate cells — one giant **multinucleate mass** of cytoplasm.',
      '**Cellular slime mould — life cycle step by step:** (1) single free-living cells called **amoebae** feed on bacteria; (2) when food runs short they **gather** and move together as a **“slug”** (pseudoplasmodium); (3) the slug turns into a **fruiting body**; (4) the fruiting body releases many **spores**; (5) each spore produces a new amoeba — the cycle is complete.'),
    TB('t14', 'The three protist groups', 76, ['Group', 'Nutrition', 'Like a…', 'Examples'], [
        ['Protozoa', 'Heterotrophic, **ingest** food (holozoic)', 'Animal', '*Amoeba*, *Paramecium*, *Trypanosoma*, *Plasmodium*'],
        ['Algae', 'Autotrophic, **photosynthesis**', 'Plant', '*Euglena*, diatoms, *Chlamydomonas*, *Spirogyra*, *Volvox*, *Ulva*'],
        ['Slime moulds', 'Heterotrophic, **absorb** food', 'Fungus', 'Cellular and acellular slime moulds'],
    ]),
    WK('w08', 'Worked example: name the protist from clues', 68,
       'A single-celled organism from pond water is covered in rows of tiny hairs, has an oral groove, a large and a small nucleus and two contractile vacuoles. Name it and its phylum, and explain the role of the contractile vacuoles.',
       ['**Step 1 — movement clue:** rows of tiny hairs = **cilia** → phylum **Ciliophora**.',
        '**Step 2 — structure clues:** oral groove + macronucleus and micronucleus → *Paramecium*.',
        '**Step 3 — contractile vacuoles:** in fresh water, water keeps entering the cell; the contractile vacuoles collect and **pump out excess water** so the cell does not burst.'],
       '*Paramecium*, phylum Ciliophora (animal-like protist). Its contractile vacuoles remove excess water from the cytoplasm.'),
    WK('w09', 'Worked example: why classify Euglena as a protist?', 71,
       'Give two plant-like and two animal-like features of *Euglena*, and explain why it is placed in Protista.',
       ['**Step 1 — plant-like:** it has **chloroplasts** and makes food by photosynthesis; it stores carbohydrate.',
        '**Step 2 — animal-like:** it has **no cell wall** (only a flexible pellicle) and it **moves** with a flagellum; it has an eyespot that senses light.',
        '**Step 3 — decide:** it is a simple, unicellular eukaryote living in water that fits neither Plantae nor Animalia → **Protista** (plant-like protist, phylum Euglenophyta).'],
       'Plant-like: chloroplasts, photosynthesis. Animal-like: no cell wall, moves by a flagellum. It is a simple unicellular eukaryote in water, so it is a protist.'),
    CK('k15', 69, 'African sleeping sickness is caused by', ['*Plasmodium*', '*Trypanosoma*', '*Entamoeba*', '*Paramecium*'], 'B',
       '*Trypanosoma* (Mastigophora), spread by the **tsetse fly**.'),
    CK('k16', 70, 'Malaria is transmitted to humans by', ['the tsetse fly', 'the male *Anopheles* mosquito', 'the female *Anopheles* mosquito', 'contaminated water'], 'C',
       'Only the **female *Anopheles*** mosquito carries *Plasmodium*.'),
    CK('k17', 73, 'In *Spirogyra*, sugar is stored as starch in the', ['eyespot', 'pyrenoids', 'contractile vacuole', 'holdfast'], 'B',
       'The spiral chloroplast carries **pyrenoids**, where starch is stored.'),
    CK('k18', 71, 'Diatoms and *Euglena* belong to kingdom', ['Protista', 'Fungi', 'Animalia', 'Plantae'], 'A',
       'Both are **simple algae** (Chrysophyta and Euglenophyta) — plant-like protists.'),
])

L26 = L('2-6', '2.3.3', 'Kingdom Fungi', [76, 82], [
    T('c20', '2.3.3 Fungi: the absorbers and decomposers', 76,
      'Fungi are mostly **filamentous eukaryotes** with **saprophytic** nutrition. A few are **unicellular** (yeast). The filaments are **hyphae** (singular: hypha); a mass of hyphae is a **mycelium** (plural: mycelia). A mushroom is many hyphae packed tightly together.',
      'In some fungi the hyphae are divided into separate cells by cross walls; in others the hyphae are long **multinucleate tubes** with no cross walls.',
      '**How fungi feed:** they **secrete enzymes** onto their food, **digest it outside** the body and then **absorb** the products. They are **saprophytes** (feed on dead matter), **parasites** (feed on living hosts) or partners in a mutual association (lichens). As **decomposers** they are very important in the environment.',
      '**Reproduction:** both asexual and sexual, by **spores**. Spores are **non-motile** and are spread by **wind or water**. Usually fungi use **asexual** spores; in bad conditions (lack of food and water) many reproduce **sexually**. Fungi are **classified by their type of sexual reproduction** into four phyla.'),
    T('c21', 'The four phyla of fungi', 77,
      '**A. Zygomycota** — filamentous, cottony growth; hyphae **without cross walls**. Sexual reproduction by **conjugation** → a **zygosporangium** with zygospores, which can stay dormant until conditions are good. Example: ***Rhizopus*** (black bread mould): tubular multinucleate hyphae with creeping branches (stolons), absorbing **rhizoids** and upright **sporangiophores**; the black spore walls give the colour. On a suitable surface, mature spore-bearing mycelia form within **72 hours**.',
      '**B. Ascomycota (sac fungi)** — asexual spores in chains called **conidia**; sexual spores in a small sac, the **ascus**, usually **eight ascospores** per ascus; many asci sit in a cup-like **ascocarp**. **Yeasts** are the simplest ascomycetes: one-celled, used for **bread, beer and wine**. In good conditions yeast multiplies by **budding** (unequal division). In bad conditions a cell divides its nucleus twice → **four ascospores** inside an ascus; these dormant spores resist drying and are sold as “active yeast”.',
      '**C. Basidiomycota (club fungi)** — mushrooms, bracket fungi, puffballs. Spores form on a **club-shaped basidium**, each bearing **four basidiospores**. The mycelium spreads out in a circle from where the spore landed; at the edge, packed hyphae form fruiting bodies called **basidiocarps** (mushrooms). The **gills** under the cap are lined with basidia.',
      '**D. Deuteromycota (imperfect fungi)** — fungi whose **sexual reproduction is unknown**. When a sexual stage is discovered, the fungus is moved to Ascomycota or Basidiomycota.'),
    TB('t15', 'Fungi phyla side by side', 78, ['Phylum', 'Common name', 'Sexual spores in…', 'Asexual reproduction', 'Example'], [
        ['**Zygomycota**', 'Conjugation fungi', 'Zygosporangium (zygospores)', 'Sporangiospores from sporangia', '*Rhizopus* (black bread mould)'],
        ['**Ascomycota**', 'Sac fungi', 'Ascus — 8 ascospores (yeast: 4)', 'Conidia; budding in yeast', 'Yeast, *Penicillium*'],
        ['**Basidiomycota**', 'Club fungi', 'Basidium — 4 basidiospores', '—', 'Mushroom (*Agaricus*), bracket fungi, puffballs, rust fungi'],
        ['**Deuteromycota**', 'Imperfect fungi', 'Unknown (no sexual stage known)', 'Asexual spores', 'Moved when sexual stage is found'],
    ]),
    MN('m06', '“Zebras Always Bite Donkeys” — Z, A, B, D', 77,
       ['**Z**ygo = **z**ygospore by conjugation; **A**sco = **a** sac (ascus) of 8; **B**asidio = **b**aseball **b**at (a club-shaped basidium) with 4; **D**eutero = **d**on’t know the sex stage.',
        'Numbers trick: **sac 8, club 4** — “a sack holds more than a club.”'],
       [('Z', 'Zebras', 'Zygomycota — zygosporangium, Rhizopus'), ('A', 'Always', 'Ascomycota — ascus with 8 ascospores, yeast'), ('B', 'Bite', 'Basidiomycota — basidium with 4 spores, mushroom'), ('D', 'Donkeys', 'Deuteromycota — imperfect, sexual stage unknown')]),
    DG('d04', 'Yeast reproduction and a mushroom basidium', 79, 'fungi', 'plain'),
    T('c22', 'Lichens: a fungus and an alga working together', 80,
      'A **lichen** is an association of a **fungus** and a **green alga** living in **mutualism** — a symbiosis in which **both benefit**.',
      '**The fungus gives:** it holds **water** to keep the alga moist, “digests” the rock surface to release **minerals** for both, and **protects** the alga.',
      '**The alga gives:** it has **chlorophyll** and makes **organic food** for both by photosynthesis.',
      'This is why lichens can grow on bare rocks and tree bark where neither partner could live alone.'),
    TB('t16', 'Economic importance of fungi', 81, ['Useful', 'Harmful to humans', 'Harmful to crops'], [
        ['Yeast for **bread, beer and wine**', '*Candida albicans* → **thrush** (mouth and throat)', '**Blight** (Zygomycota) → potatoes, tomatoes'],
        ['**Edible mushrooms**', '**Dermatophytes** → **ringworm**, **athlete’s foot**', '**Rust** (Basidiomycota; 250+ kinds) → wheat, barley, oats; wheat rust'],
        ['**Penicillin** from *Penicillium notatum*', '—', '**Downy mildew**'],
        ['**Decomposers** recycling nutrients', '—', '—'],
    ]),
    TB('t17', 'Fungi vs plants — the exam favourite', 82, ['Feature', 'Fungi', 'Plants'], [
        ['Cell wall', '**Chitin**', '**Cellulose**'],
        ['Chlorophyll', 'Absent', 'Present'],
        ['Nutrition', 'Heterotrophic — absorb food (saprophyte / parasite)', 'Autotrophic — photosynthesis'],
        ['Body', 'Hyphae and mycelium', 'Roots, stems, leaves (tissues and organs)'],
        ['Stored food', 'Glycogen and oil (not starch)', 'Starch'],
    ]),
    WK('w10', 'Worked example: the bread experiment (Activity 2.6)', 77,
       'Moist bread kept in a dark cupboard for 3 days grows white cottony threads with tiny black dots. Identify the organism, its phylum, and explain what the threads and dots are.',
       ['**Step 1 — observation:** cottony threads = **hyphae** forming a **mycelium**; black dots = **sporangia** full of black spores.',
        '**Step 2 — identify:** black bread mould = ***Rhizopus***.',
        '**Step 3 — phylum:** hyphae without cross walls, sexual reproduction by conjugation → **Zygomycota**.',
        '**Step 4 — why it grew:** moisture + food (bread) + warmth; darkness does not matter because fungi do not photosynthesise. Spores from the air landed and germinated (within about 72 hours).'],
       '*Rhizopus* (Zygomycota). Threads = hyphae (mycelium); black dots = sporangia containing spores.'),
    CK('k19', 76, 'A mass of fungal hyphae is called a', ['spore', 'mycelium', 'basidium', 'rhizoid'], 'B',
       'Many hyphae together = **mycelium**.'),
    CK('k20', 78, 'Yeast multiplies quickly in good conditions by', ['binary fission', 'budding', 'conjugation', 'fragmentation'], 'B',
       'Yeast forms a bud (unequal partitioning) — **budding**.'),
    CK('k21', 80, 'In a lichen, the alga provides', ['water', 'minerals from rock', 'food by photosynthesis', 'protection'], 'C',
       'The alga has chlorophyll and makes **food**; the fungus provides water, minerals and protection.'),
    CK('k22', 81, 'Penicillin is obtained from', ['*Rhizopus*', '*Candida albicans*', '*Penicillium notatum*', 'yeast'], 'C',
       'The antibiotic **penicillin** comes from the fungus *Penicillium notatum*.'),
])
