from common import *

L27 = L('2-7', '2.3.4', 'Kingdom Plantae', [82, 87], [
    T('c23', '2.3.4 Plants: green, multicellular, on land', 82,
      'Members of kingdom Plantae are **multicellular eukaryotes** with **cellulose** cell walls. Their cells are **specialised into tissues and organs**. They are **photosynthetic** organisms **adapted to life on land**, with pigments **chlorophyll and carotenoids**, and they **store food as starch**.',
      '**How do plants differ from complex algae?** Algae (seaweeds) live in water and have no true tissues or organs (*Ulva* is only two cells thick); plants have tissues and organs and most are adapted to land.'),
    T('c24', 'Alternation of generations — slowly, step by step', 82,
      'The plant life cycle alternates between **two generations** (two kinds of plant body):',
      '**Step 1:** the **sporophyte** (spore-bearing plant) matures and produces **spores**.',
      '**Step 2:** each spore grows into a **gametophyte** (gamete-producing plant).',
      '**Step 3:** the mature gametophyte produces **gametes** (sex cells: sperm and egg).',
      '**Step 4:** two gametes **fuse** (fertilisation) → a **zygote**.',
      '**Step 5:** the zygote grows into a new **sporophyte** — and the cycle repeats.',
      '**Memory hook:** *Sporophyte → spores; Gametophyte → gametes.* The name tells you what it makes.'),
    DG('d05', 'Alternation of generations cycle', 82, 'altgen', 'plain'),
    T('c25', 'The four plant groups', 82,
      'Plants are classified by the **presence or absence of vessels (vascular tissue) and seeds** into four main groups: **bryophytes, pteridophytes, gymnosperms and angiosperms**.',
      '**A. Bryophyta (mosses and liverworts)** — the **first land plants**, but they live in **very damp, shady places**. **No vascular tissue**, so water and food move cell to cell and the plants **stay small**. They have root-like **rhizoids** and leaf-like structures — **not** true roots or leaves. The **gametophyte is dominant**; the sporophyte depends on it for food. Spores form in a **capsule**. **Water is needed** for sperm to swim to the egg.',
      '**B. Pteridophyta (ferns, club mosses, horsetails)** — **seedless vascular** plants with **true roots, stems and leaves**. Underground stem = **rhizome**; fern leaves = **fronds**, growing from buds on the rhizome. The **sporophyte is dominant** (much larger). The gametophyte is a tiny, independent, **heart-shaped prothallus** that does **not** depend on the sporophyte for food. Spores form in clusters (sori) on the **underside of the frond**.',
      '**C. Gymnosperms (“naked-seed” plants)** — differ from ferns in having **seeds** and **no independent gametophyte** (it is tiny and stays inside the sporophyte). Seeds sit **on the surface of cone scales** (naked). Includes **conifers** (largest group, e.g. pine), ginkgos, cycads and gnetophytes. A pine has **staminate (male) cones**, small (less than 3 cm), and larger **ovulate (female) cones** made of scales, each scale carrying **two seeds**.',
      '**D. Angiosperms (flowering plants)** — the gametophyte is reduced to a **few cells inside the flower**. Seeds develop in the **ovary** at the base of the flower; the ovary protects ovules better than a cone scale, and the ovary wall becomes the **fruit** that **encloses the seeds**. The **most diverse** plant group (**more than 250 000 species**). Two classes: **monocotyledons** and **dicotyledons**.'),
    DG('d06', 'Plant groups: a ladder of new features', 83, 'plants', 'plain'),
    TB('t18', 'The four plant groups side by side', 84, ['Feature', 'Bryophytes', 'Pteridophytes', 'Gymnosperms', 'Angiosperms'], [
        ['Examples', 'Mosses, liverworts', 'Ferns, club mosses, horsetails', 'Pine (conifers), cycads, ginkgo', 'Maize, teff, beans, acacia'],
        ['Vascular tissue', '**No**', 'Yes', 'Yes', 'Yes'],
        ['True roots, stems, leaves', 'No (rhizoids)', 'Yes (rhizome, fronds)', 'Yes', 'Yes'],
        ['Seeds', 'No (spores)', 'No (spores)', '**Naked** on cone scales', '**Enclosed** in fruit'],
        ['Flowers', 'No', 'No', 'No (cones)', '**Yes**'],
        ['Dominant generation', '**Gametophyte**', 'Sporophyte', 'Sporophyte', 'Sporophyte'],
        ['Gametophyte', 'Main plant', 'Independent prothallus', 'Tiny, inside sporophyte', 'A few cells inside flower'],
        ['Water for fertilisation', 'Yes', 'Yes', 'No', 'No'],
    ], 'Read left → right: each group adds one “invention”: **vessels** (ferns) → **seeds** (gymnosperms) → **flowers and fruits** (angiosperms). And the gametophyte gets smaller at every step.'),
    MN('m07', '“Brave Pupils Get A’s” — the plant ladder', 82,
       ['**B**ryophytes → **P**teridophytes → **G**ymnosperms → **A**ngiosperms: from simplest to most advanced.',
        '**Tigrinya-friendly tip:** **ጣፍ** (teff), **ዕፉን** (maize) and sorghum are all **monocots** — grasses with long, parallel-veined leaves. Beans and chickpeas (**ሽምብራ**) are **dicots** — open the seed and it splits into **two** halves.'],
       [('B', 'Brave', 'Bryophytes — no vessels, no seeds'), ('P', 'Pupils', 'Pteridophytes — vessels, no seeds'), ('G', 'Get', 'Gymnosperms — naked seeds in cones'), ('A', 'A’s', 'Angiosperms — flowers, seeds in fruits')]),
    TB('t19', 'Monocots vs dicots', 85, ['Feature', 'Monocotyledons', 'Dicotyledons'], [
        ['Seed leaves (cotyledons)', '**One**', '**Two**'],
        ['Leaf veins', 'Parallel', 'Net-like (branched)'],
        ['Flower parts', 'In threes (or multiples of 3)', 'In fours or fives (or multiples)'],
        ['Roots', 'Fibrous', 'Tap root'],
        ['Vascular bundles in stem', 'Scattered', 'In a ring'],
        ['Examples', 'Teff, sorghum, wheat, maize, barley', 'Beans, groundnuts, chickpeas, peas'],
    ], 'Activity 2.9 check: soak seeds of beans, peas, maize and barley for three days, remove the seed coat — beans and peas split into **two** cotyledons (dicots); maize and barley have **one** (monocots).'),
    WK('w11', 'Worked example: identify a plant group from clues', 84,
       'A plant has true roots, stems and leaves and vascular tissue. On the underside of its leaves are brown dots containing spores. It has no seeds or flowers. Name its group and describe its gametophyte.',
       ['**Step 1 — vessels?** Yes → not a bryophyte.',
        '**Step 2 — seeds?** No, it reproduces by spores → not a gymnosperm or angiosperm.',
        '**Step 3 — conclude:** seedless vascular plant = **Pteridophyta** (a fern; the leaves are fronds).',
        '**Step 4 — gametophyte:** a tiny, heart-shaped, independent **prothallus**; the large leafy plant you see is the sporophyte.'],
       'Pteridophyta (fern). Its gametophyte is a small, independent, heart-shaped prothallus.'),
    WK('w12', 'Worked example: why are mosses small?', 83,
       'Explain why mosses grow only a few centimetres tall and only in damp places.',
       ['**Step 1:** mosses have **no vascular tissue** (no xylem or phloem).',
        '**Step 2:** water and food must move slowly **from cell to cell** — this only works over short distances, so the plant must stay **small**.',
        '**Step 3:** their **sperm must swim** through water to reach the egg, and the plant body dries out easily — so they need **damp, shady** places.'],
       'No vascular tissue (only cell-to-cell transport) keeps them small; swimming sperm and lack of protection against drying keep them in damp places.'),
    CK('k23', 83, 'In mosses the dominant generation is the', ['sporophyte', 'gametophyte', 'prothallus', 'rhizome'], 'B',
       'In bryophytes the **gametophyte** is the main plant; the sporophyte depends on it.'),
    CK('k24', 84, 'Gymnosperms are called “naked-seed” plants because their seeds', ['have no seed coat', 'are produced on the surface of cone scales', 'are inside a fruit', 'have no food store'], 'B',
       'The seeds lie **on the cone scales**, not enclosed in a fruit.'),
    CK('k25', 85, 'Which of these is a dicot?', ['Teff', 'Maize', 'Chickpea', 'Sorghum'], 'C',
       'Chickpea has **two cotyledons**. Teff, maize and sorghum are monocots.'),
    CK('k26', 115, 'Which feature is used to classify vascular plants into groups?', ['the presence or absence of seeds', 'leaf colour', 'height', 'the soil they grow in'], 'A',
       'Plants are classified by the presence or absence of **vessels and seeds**.'),
])
