from common import *

L28 = L('2-8', '2.3.5 A', 'Kingdom Animalia: Body Plans and Invertebrates', [87, 103], [
    T('c26', '2.3.5 Animals: what they all share', 87,
      'All animals are **multicellular** and made of **eukaryotic cells without cell walls**. Their tissues form **organs and organ systems**. They respire **aerobically**.',
      '**Nutrition:** animals are **heterotrophs** — no chlorophyll, so they feed on plants, other animals or both. Because they must **find food**, **locomotion** is important in nearly all animals (most are motile during at least part of their life).',
      '**Sexual reproduction (most animals):** specialised sex cells fuse at **fertilisation** to form a **zygote**, which develops into a new individual.',
      '**Asexual reproduction (some animals):** **regeneration** — regrowth of a lost tissue or body part in an adult (e.g. a starfish arm); **parthenogenesis** — an **unfertilised** egg is activated and develops into a new organism; **budding** — an outgrowth that detaches and becomes a new individual (e.g. *Hydra*).',
      'Animals are broadly split into **invertebrates** (no backbone) and **vertebrates** (backbone).'),
    T('c27', 'Body symmetry', 87,
      '**Symmetry** describes how body parts are arranged around an axis, so that the body can be divided into similar halves.',
      '**Asymmetrical** — no pattern; cannot be split into similar halves. The most primitive animals, e.g. **sponges**.',
      '**Radial symmetry** — parts arranged around a **central axis**, like spokes of a wheel; can be cut through the centre in **more than one plane** to give identical halves. Usually **sessile** (fixed); reaching out in all directions helps them catch food. Examples: **cnidarians** (*Hydra*, jellyfish) and adult **echinoderms** (starfish).',
      '**Bilateral symmetry** — only **one** plane gives two mirror-image halves (left and right). Usually active animals with a head end (**cephalisation**). Examples: flatworms, roundworms, annelids, molluscs, arthropods, vertebrates.'),
    DG('d07', 'Asymmetry, radial and bilateral symmetry', 87, 'symmetry', 'plain'),
    T('c28', 'A. Invertebrates — eight phyla, one by one', 89,
      '**i. Porifera (sponges)** — mostly marine, a few in fresh water. The **simplest animals**: **asymmetrical**; cells are differentiated but there are **no true tissues** and no three germ layers. Two cell layers with a jelly-like layer between, where **amoeboid cells** crawl and secrete **spicules** (mineral needles) or **spongin** (protein). **Sessile, porous filter feeders**: **collar cells (choanocytes)** beat their flagella to draw water in through the **pores** and out through the **osculum**; food is trapped by collar cells and digested **inside cells** (intracellular). Asexual by **fragmentation**; most show **sequential hermaphroditism** (one sex, then the other), which prevents self-fertilisation.',
      '**ii. Cnidaria (coelenterates)** — jellyfish, *Hydra*, sea anemones, corals; mostly marine (*Hydra* lives in fresh water). **Radial symmetry**, **two tissue layers** with jelly between; **tentacles** with stinging **nematocysts**; a sac-like gut with **one opening** (mouth = anus). Two body forms: **polyp** (attached, mouth and tentacles **up**) and **medusa** (free-floating, mouth and tentacles **down**, an upside-down polyp). Asexual by **budding**; sexual reproduction gives a swimming larva, the **planula**, which settles and becomes a polyp.',
      '**iii. Platyhelminthes (flatworms)** — planaria, flukes, tapeworms. **Flat**, **bilateral**, with **cephalisation** (a definite head) and organs; gut (if any) has **one opening**. **Free-living** (e.g. planaria): carnivores and scavengers in water and moist land. **Parasitic**: **flukes** (in gut, liver, lungs, bladder or blood vessels) and **tapeworms** (in the intestine; **no gut** of their own — they absorb digested food; a **scolex** for attachment and a chain of **proglottids**, each with male and female organs). Body coverings resist the host’s enzymes and immune defences. Most are **hermaphrodites** but cross-fertilise; can reproduce asexually by **transverse fission + regeneration**.',
      '**iv. Nematoda (roundworms)** — *Ascaris*, hookworms, *Trichinella*. **Cylindrical**, **bilateral**, **unsegmented**, tapered body with a tough **cuticle** that is **moulted** during growth. **No cilia or flagella**. **Complete gut** (mouth **and** anus). Free-living in soil or parasites of animals and plants. **Separate sexes**, sexual reproduction.',
      '**v. Mollusca** — snails, slugs, clams. **Bilateral**, soft body, distinct head, usually a **shell of calcium carbonate**. Three body parts: muscular **foot** (movement), **visceral mass** (internal organs), **mantle** (fold of tissue over the visceral mass; secretes the shell). Many have a toothed **radula** for scraping. **Open circulatory system** with a **three-chambered heart**. Mostly separate sexes.',
      '**vi. Annelida (segmented worms)** — earthworms, leeches, polychaetes. **Bilateral**, body of ring-like **segments** separated inside by **septa**; each segment has its own circulatory, excretory, nervous, muscular and respiratory parts. **Closed circulatory system**; complete gut; most have bristles (**setae**) that anchor them during movement; most are hermaphrodites. **Earthworms** burrow in moist soil and eat decaying plant matter — they **fertilise and aerate** the soil. **Leeches** (no setae) are predators or blood-sucking parasites. The **clitellum** of earthworms and some leeches secretes a sticky substance that forms the **cocoon (egg sac)** — it is **associated with reproduction**. **Polychaetes** (e.g. *Nereis*) are marine, with tentacles and many setae.'),
    TB('t20', 'Invertebrate phyla side by side', 89, ['Phylum', 'Examples', 'Symmetry', 'Body / layers', 'Gut', 'Key feature'], [
        ['**Porifera**', 'Sponges', 'Asymmetrical', 'Cells, no true tissues', 'None (intracellular digestion)', 'Pores, osculum, collar cells, spicules'],
        ['**Cnidaria**', '*Hydra*, jellyfish, corals', 'Radial', 'Two tissue layers', 'One opening', 'Tentacles with nematocysts; polyp and medusa'],
        ['**Platyhelminthes**', 'Planaria, flukes, tapeworm', 'Bilateral', 'Flat, head (cephalisation)', 'One opening or none', 'Mostly hermaphrodite; many parasites'],
        ['**Nematoda**', '*Ascaris*, hookworm', 'Bilateral', 'Round, unsegmented, cuticle', 'Complete', 'Separate sexes; moult cuticle'],
        ['**Mollusca**', 'Snail, slug, clam', 'Bilateral', 'Soft; foot, visceral mass, mantle', 'Complete', 'CaCO₃ shell, radula, open circulation'],
        ['**Annelida**', 'Earthworm, leech, *Nereis*', 'Bilateral', 'Segmented (septa)', 'Complete', 'Setae, clitellum, closed circulation'],
        ['**Arthropoda**', 'Insects, spiders, crabs, millipedes', 'Bilateral', 'Segmented, exoskeleton of chitin', 'Complete', 'Jointed legs; largest phylum'],
        ['**Echinodermata**', 'Starfish, sea urchin, sea cucumber', 'Radial (adults)', 'Spiny skin', 'Complete', 'Water vascular system; all marine; no head'],
    ]),
    T('c29', 'vii. Arthropods — the biggest phylum', 96,
      '*Arthron* = joint, *pod* = foot (leg): **jointed appendages** + a body covered by an **exoskeleton** of **chitin and protein**. These two features make arthropods the most successful animals in many environments. **Largest phylum** of the animal kingdom.',
      'Jointed appendages work as **legs** (walking), **antennae** (sensing) and **mouthparts** (feeding). Arthropods walk, crawl, climb, hop, fly, glide or swim.',
      'The exoskeleton protects organs, supports the body and helps movement — but it **cannot expand**, so it is **shed (moulted)** periodically for growth.',
      'Inside: **ganglia** as a brain, a heart-like organ, complete gut and excretory system, good sense organs (antennae, eyes). Breathing by body surface, **gills**, **tracheae** or **book lungs**. **Open circulatory system**: blood pumped into the body space around the organs, then back to the heart.',
      'Arthropods are grouped by **number of legs** (and body parts) into four groups: **arachnids, crustaceans, myriapods and insects**.'),
    TB('t21', 'The four arthropod groups', 96, ['Group', 'Examples', 'Body parts', 'Legs', 'Antennae', 'Other'], [
        ['**Arachnids**', 'Spiders, ticks, mites, scorpions', 'Cephalothorax + abdomen', '**4 pairs (8)**', '**None**', 'No mandibles; ticks and mites are ectoparasites'],
        ['**Crustaceans**', 'Lobster, shrimp, crab, crayfish', 'Cephalothorax + abdomen', 'Many', '**2 pairs**', 'Mostly aquatic; shield-like cover; mandibles'],
        ['**Myriapods**', 'Centipedes, millipedes', 'Head + many similar segments', 'Centipede **1 pair** per segment; millipede **2 pairs**', '1 pair', 'Centipedes carnivores with poison fangs; millipedes eat decaying plants'],
        ['**Insects**', 'Bees, ants, flies, grasshoppers, butterflies', '**Head, thorax, abdomen**', '**3 pairs (6)** on thorax', '**1 pair**', 'Usually 1–2 pairs of wings; spiracles and tracheae'],
    ], 'Count to decide: **6 legs = insect**, **8 legs = arachnid**, **2 pairs of antennae = crustacean**, **many segments with legs = myriapod**. **Tigrinya check:** **ንህቢ** (bee) and **ጻጸ** (ant) have 6 legs → insects; **ሳሬት** (spider) has 8 → arachnid.'),
    T('c30', 'Insects in detail', 98,
      'Insects are the **most successful invertebrates on land** thanks to: a **tracheal system** for breathing, a **cuticle** that reduces water loss, and **wings and flight** (to spread, find food, catch prey and escape).',
      '**Body:** **head** (1 pair of antennae, eyes, mouth), **thorax** (3 segments, each with **1 pair of legs**, and usually **1 or 2 pairs of wings**; holds the main muscles), **abdomen** (stomach and reproductive organs; a sting in some). Some insects are **wingless**: ants, fleas, lice. Air enters through **spiracles** — insects have **no lungs**.',
      '**Mouthparts:** chewing in less specialised insects (grasshopper); in others modified for **sucking, piercing and slicing** (e.g. mosquito).',
      '**Metamorphosis** — a marked change of form during growth. **Incomplete** (grasshopper): **egg → nymph → adult** (three stages). **Complete** (butterfly, house fly): **egg → larva → pupa → adult** (four stages).'),
    DG('d08', 'Insect body and the two kinds of metamorphosis', 101, 'insect', 'plain'),
    T('c31', 'viii. Echinoderms — spiny skin', 101,
      '*Echinos* = spiny, *derma* = skin. Starfish, sea urchins, sea cucumbers. **Exclusively marine** and **radially symmetrical** (parts radiate from the centre). Body forms vary — soft, cylindrical, spiny, many-armed, feathery — but all have a unique **water vascular system** used for **feeding, locomotion, respiration and sensing**. They have **no head, eyes or brain**.',
      '**Reproduction:** asexual — a single starfish arm with a small piece of the central disc can **regenerate** the whole animal. Sexual — seasonal breeding, eggs released into the sea, **external fertilisation**, free-swimming **larvae** that develop into adults.'),
    MN('m08', 'Invertebrate phyla in textbook order', 89,
       ['**“Poor Cats Pull Nets, Monkeys And Apes Eat”** → **P**orifera, **C**nidaria, **P**latyhelminthes, **N**ematoda, **M**ollusca, **A**nnelida, **A**rthropoda, **E**chinodermata.',
        '**Gut openings:** sponges none → cnidarians and flatworms **one** → roundworms and above **two** (mouth and anus).'],
       [('P', 'Poor', 'Porifera — sponges, asymmetrical'), ('C', 'Cats', 'Cnidaria — radial, stinging cells'), ('P', 'Pull', 'Platyhelminthes — flatworms'), ('N', 'Nets', 'Nematoda — roundworms'), ('M', 'Monkeys', 'Mollusca — foot, mantle, shell'), ('A', 'And', 'Annelida — segmented worms'), ('A', 'Apes', 'Arthropoda — jointed legs'), ('E', 'Eat', 'Echinodermata — spiny skin')]),
    WK('w13', 'Worked example: phylum from a description', 94,
       'A worm-like animal from moist soil has a body of many ring-like segments, bristles on each segment and a thick band near the front that makes a cocoon. Name it, its phylum, and the band.',
       ['**Step 1 — worm shape options:** flat (Platyhelminthes), round unsegmented (Nematoda) or **segmented** (Annelida).',
        '**Step 2 — segments + setae** → **Annelida**.',
        '**Step 3 — lives in soil, makes a cocoon** → **earthworm**.',
        '**Step 4 — the band** that secretes the sticky cocoon is the **clitellum** (used in reproduction).'],
       'Earthworm, phylum Annelida; the band is the clitellum, which forms the egg cocoon.'),
    WK('w14', 'Worked example: insect or arachnid?', 96,
       'A small animal has two body parts, eight legs and no antennae. Another has three body parts, six legs, one pair of antennae and two pairs of wings. Classify each.',
       ['**Animal 1:** 2 body parts (cephalothorax + abdomen), **8 legs**, **no antennae** → **arachnid** (e.g. spider).',
        '**Animal 2:** head, thorax, abdomen; **6 legs**; 1 pair of antennae; wings → **insect** (e.g. bee).',
        '**Both** have jointed legs and an exoskeleton → phylum **Arthropoda**.'],
       'Animal 1 is an arachnid; animal 2 is an insect. Both are arthropods.'),
    CK('k27', 114, 'Which of these has radial symmetry?', ['flatworm', 'annelid', 'chordate', 'cnidarian'], 'D',
       'Cnidarians (e.g. *Hydra*, jellyfish) are **radially** symmetrical; the others are bilateral.'),
    CK('k28', 115, 'The clitellum of an earthworm', ['contains the heart', 'is associated with reproduction', 'acts as a respiratory organ', 'is needed for movement'], 'B',
       'It secretes the sticky material of the **cocoon** in which eggs are laid.'),
    CK('k29', 99, 'Which life cycle shows complete metamorphosis?', ['egg → nymph → adult', 'egg → larva → pupa → adult', 'egg → adult', 'egg → tadpole → adult'], 'B',
       'Complete metamorphosis has **four** stages including the **pupa** (butterfly, house fly).'),
    CK('k30', 98, 'A millipede differs from a centipede because it has', ['no legs', 'two pairs of legs per segment', 'poison fangs', 'eight legs'], 'B',
       '**Milli**pede: **2 pairs** per segment, eats decaying plants. Centipede: 1 pair, carnivore with poison fangs.'),
    CK('k31', 90, 'Sponges are best described as', ['radially symmetrical with tentacles', 'asymmetrical filter feeders with pores', 'segmented worms', 'animals with a water vascular system'], 'B',
       'Sponges are **asymmetrical**, **porous**, sessile **filter feeders**.'),
])

L29 = L('2-9', '2.3.5 B', 'Kingdom Animalia: Vertebrates', [103, 114], [
    T('c32', 'B. Vertebrates — animals with a backbone', 103,
      'Vertebrates have a true, usually **bony endoskeleton**, with a **backbone** around the spinal cord and a **skull** around the brain. They belong to phylum **Chordata**. Five classes: **fishes, amphibians, reptiles, birds and mammals**.',
      '**Two key words:** **poikilothermic** (“cold-blooded”) — body temperature **changes with the surroundings** (fishes, amphibians, reptiles). **Homoeothermic** (“warm-blooded”) — body temperature is kept **constant** (birds and mammals).'),
    T('c33', 'i. Fishes', 103,
      '**Aquatic**, the **most diverse** vertebrate group: common fishes, sharks, skates, rays. They swim with **fins**; a **streamlined, lubricated** body makes swimming cheap in energy. Many have **scales** and all breathe by **gills**. Complete gut, **closed circulation** with a **two-chambered heart**, **poikilothermic**.',
      '**Reproduction:** most release many eggs into water and males release sperm over them → **external fertilisation**. **Sharks** use **internal** fertilisation.',
      '**a. Chondrichthyes (cartilaginous fishes)** — sharks and rays: skeleton of **cartilage**, true jaws, two pairs of fins, skin with **tooth-like scales**, **five pairs of gill slits** on each side of the head.',
      '**b. Osteichthyes (bony fishes)** — skeleton of **bone**; sturgeons, eels, sea horses and most freshwater and marine fishes; overlapping scales, two-chambered heart, jaws, **covered gills (operculum)**, usually a **swim bladder** — a gas-filled bag that gives **buoyancy**.'),
    TB('t22', 'Cartilaginous vs bony fishes', 104, ['Feature', 'Chondrichthyes', 'Osteichthyes'], [
        ['Skeleton', 'Cartilage', 'Bone'],
        ['Examples', 'Sharks, rays, skates', 'Tilapia, eels, sea horses, sturgeons'],
        ['Gills', 'Five pairs of open slits', 'Covered by a flap (operculum)'],
        ['Scales', 'Tooth-like', 'Overlapping'],
        ['Swim bladder', 'Absent', 'Usually present (buoyancy)'],
        ['Fertilisation', 'Internal (sharks)', 'Mostly external'],
    ], 'Exam check: “Members of class Osteichthyes have skeletons made of **bone**” — rays and skates are cartilaginous, and all fishes here have jaws.'),
    T('c34', 'ii. Amphibians', 105,
      'Frogs, toads, salamanders — **two pairs of legs**; the **first vertebrates to walk on land**. They move between water and land or spend one life stage in each (*amphi* = both, *bios* = life).',
      'Adults mostly **carnivorous**, larvae herbivorous. A **true tongue** first appears in amphibians. They breathe through a **moist, non-scaly skin** and **lungs** (tadpoles by gills). **Three-chambered heart**; **poikilothermic**.',
      '**Reproduction:** most frogs and toads return to **water**, lay eggs there, **external fertilisation**; eggs hatch into swimming **tadpoles** that change gradually (**metamorphosis**) into adults.'),
    T('c35', 'iii. Reptiles', 106,
      'Snakes, lizards, turtles, tortoises, crocodiles, alligators. All except snakes have **two pairs of limbs** with **claws**; legs do not fully lift the body. **Dry, waterproof, scaly skin** for dry places; the outer skin layer is **shed** regularly.',
      'Breathe by **lungs**; **poikilothermic**; heart **not completely four-chambered** — except **crocodiles** (four chambers). **Internal fertilisation** and **shelled eggs** — so reproduction does not need open water.',
      '**Why were reptiles among the first vertebrates fully adapted to land?** Waterproof scaly skin (no drying out), lungs only, internal fertilisation, and eggs with a shell that keeps the embryo moist.'),
    T('c36', 'iv. Birds', 107,
      'From the tiny humming bird to the ostrich. Four limbs, the **forelimbs modified as wings**. **Feathers are unique to birds** and do many jobs: **insulation** (birds are warm-blooded, body temperature about **40 °C**), protection from **UV rays**, incubation and **waterproofing**, **flight**, appearance and **colours** for camouflage and breeding display. Worn feathers are replaced by **moulting**.',
      'Other features: **scales on the legs**, a **four-chambered heart**, **hollow bones** (light, for flight), **no teeth**; **homoeothermic**; they breathe faster than mammals and are warmer.',
      '**Adaptations:** beaks match food (finch — seeds, crack; hawk — flesh, tear; swallow — insects, catch; duck — small water animals, strain). Feet match life (woodpecker — climbing; duck — swimming, webbed; pigeon — perching).'),
    TB('t23', 'Bird beaks and feet', 109, ['Bird', 'Food', 'Beak use', 'Feet adapted for'], [
        ['Finch', 'Seeds', 'Crack seeds (short, strong beak)', 'Perching'],
        ['Hawk', 'Animal flesh', 'Cut and tear flesh (hooked beak)', 'Gripping prey (talons)'],
        ['Swallow', 'Insects', 'Catch insects in flight (wide gape)', 'Perching'],
        ['Duck', 'Small animals in water', 'Strain food out of water (flat beak)', 'Swimming (webbed feet)'],
        ['Woodpecker', 'Insects in bark', 'Chisel into wood', 'Climbing'],
        ['Pigeon', 'Seeds and grains', 'Pick up seeds', 'Perching'],
    ]),
    T('c37', 'v. Mammals', 111,
      'Mammals have **body hair**, **external ears**, and females feed young with **milk from mammary glands**. **Specialised teeth** match the diet: you can usually tell a mammal’s diet from its teeth.',
      '**By diet:** **carnivores** (meat: lion, wolf, tiger, dog, cat), **herbivores** (plants: cow, elephant, giraffe, horse), **omnivores** (both: humans, pigs), **insectivores** (insects: anteaters).',
      '**Homoeothermic** — so they can be active day or night and live in harsh places. Also: a **diaphragm** for efficient breathing, a **four-chambered heart**, **sweat glands**.',
      '**Groups by birth and feeding of young:** **aplacental** mammals — **monotremes** (lay eggs; young then drink milk: **platypus**, **spiny anteater**) and **marsupials** (short-lived placenta for about 8–12 days, then the embryo grows in a **pouch**: **kangaroo**) — and **placental** mammals (a true placenta feeds the embryo through its whole development: shrews, dogs, whales, dolphins, humans).'),
    TB('t24', 'The five vertebrate classes side by side', 103, ['Feature', 'Fishes', 'Amphibians', 'Reptiles', 'Birds', 'Mammals'], [
        ['Skin', 'Scales', 'Moist, no scales', 'Dry scales', 'Feathers (scales on legs)', 'Hair'],
        ['Breathing', 'Gills', 'Skin and lungs (tadpole gills)', 'Lungs', 'Lungs', 'Lungs + diaphragm'],
        ['Heart chambers', '2', '3', '3 (not fully 4); crocodile 4', '4', '4'],
        ['Body temperature', 'Poikilothermic', 'Poikilothermic', 'Poikilothermic', 'Homoeothermic', 'Homoeothermic'],
        ['Fertilisation', 'Mostly external (sharks internal)', 'External', 'Internal', 'Internal', 'Internal'],
        ['Young', 'Eggs in water', 'Eggs in water → tadpoles', 'Shelled eggs', 'Shelled eggs', 'Mostly born alive, fed milk'],
        ['Examples', 'Tilapia, shark', 'Frog, toad', 'Snake ተመን, lizard, crocodile', 'Ostrich, pigeon', 'Human, goat, camel'],
    ]),
    MN('m09', '“Fish Always Respect Big Mammals” — and the heart count 2-3-3-4-4', 103,
       ['**F**ishes, **A**mphibians, **R**eptiles, **B**irds, **M**ammals. Heart chambers go up: **2, 3, 3 (crocodile 4), 4, 4**.',
        '**Warm vs cold:** only the two with **covers that trap heat** — **feathers** (birds) and **hair** (mammals) — are warm-blooded.',
        '**Tigrinya-friendly tip:** **ዓሳ** (fish) — gills; **ዑፍ** (bird) — feathers; **ሰብ** (human) — hair and milk. Say the body covering and you know the class.'],
       [('F', 'Fish', 'Fishes — gills, 2-chambered heart'), ('A', 'Always', 'Amphibians — moist skin, 3 chambers'), ('R', 'Respect', 'Reptiles — dry scales, shelled eggs'), ('B', 'Big', 'Birds — feathers, 4 chambers'), ('M', 'Mammals', 'Mammals — hair, milk, 4 chambers')]),
    WK('w15', 'Worked example: classify a vertebrate from clues', 106,
       'A vertebrate has dry scaly skin, breathes only with lungs, lays eggs with shells on land and its body temperature changes with the weather. Which class? Name one example from Eritrea.',
       ['**Step 1 — skin:** dry and scaly → reptile (fishes have wet scales and gills; birds have feathers).',
        '**Step 2 — breathing:** lungs only → not a fish or amphibian larva.',
        '**Step 3 — eggs with shells on land, poikilothermic** → reptile, not bird (birds are homoeothermic).',
        '**Step 4 — example:** a lizard, snake (**ተመን**) or tortoise.'],
       'Class Reptilia (reptiles), e.g. a lizard or a snake.'),
    WK('w16', 'Worked example: why is a bat a mammal and not a bird?', 111,
       'A bat flies with wings. Give three reasons it is classified as a mammal.',
       ['**Step 1 — covering:** a bat has **hair/fur**, not feathers.',
        '**Step 2 — young:** the female gives birth and feeds the young with **milk** from **mammary glands**.',
        '**Step 3 — other mammal features:** **external ears** and **teeth** (birds have no teeth).',
        '**Step 4 — lesson:** classify by **structure**, not by what the animal does (flying).'],
       'It has hair, feeds its young on milk from mammary glands, and has external ears and teeth.'),
    CK('k32', 104, 'The swim bladder of a bony fish', ['digests food', 'gives buoyancy', 'pumps blood', 'stores eggs'], 'B',
       'It is a **gas-filled bag** that gives **buoyancy**.'),
    CK('k33', 105, 'Which vertebrates have a three-chambered heart and breathe through moist skin?', ['Fishes', 'Amphibians', 'Birds', 'Mammals'], 'B',
       '**Amphibians**: moist non-scaly skin + lungs; heart with three chambers.'),
    CK('k34', 112, 'The platypus is a mammal that', ['has a pouch', 'lays eggs', 'has feathers', 'breathes with gills'], 'B',
       'It is a **monotreme** — an **egg-laying** mammal whose young drink milk.'),
    CK('k35', 104, 'Fishes, amphibians and reptiles are all', ['homoeothermic', 'poikilothermic', 'placental', 'four-chambered'], 'B',
       'Their body temperature varies with the surroundings — **poikilothermic**.'),
])
