r"""Grade 11: 2.2.4 (relative concentration, nature of the electrode), 2.2.5 applications of electrolysis, 2.2.6 Faraday's laws
with every electrode equation written out, 3.2 carbon cycle, 3.3 nitrogen cycle, 3.4.1 extraction of sulphur (Frasch) and
its allotropes, 3.4.3 Contact process, sulphuric acid and sulphates."""
from co import Unit, eq, ie

# ====================================================================================== Unit 2 · electrolysis
U2 = Unit('chem11-u2')
L224 = '2.2.4 Electrolysis of aqueous solutions'
L225 = '2.2.5 Applications of electrolysis'
L226 = "2.2.6 Faraday's laws"

AQ = [
    U2.T('c01', '2.2.4 (2) Relative concentration of the ions, step by step', 52,
         'In a solution there are always **two possible cations** (the metal ion and H⁺ from water) and **two possible anions** (the acid ion and OH⁻ from water). Only one of each is discharged. The first rule (position in the electrochemical series) is not the only rule: **concentration** can change the winner.',
         '**Step 1 — List all the ions,** from the salt and from water. For NaCl(aq): Na⁺, Cl⁻ from the salt; H⁺, OH⁻ from water.',
         '**Step 2 — Cathode (−):** compare the cations. Na⁺ is very high in the series and very hard to discharge, so **H⁺ is discharged** even when Na⁺ is far more concentrated — here the position wins.',
         eq('2H^+(aq) + 2e^- -> H2(g)'),
         '**Step 3 — Anode (+):** compare the anions. OH⁻ is easier to discharge than Cl⁻. **But** if Cl⁻ is present at a **much higher concentration** (brine, concentrated HCl) Cl⁻ is discharged instead — here the concentration wins.',
         eq('2Cl^-(aq) -> Cl2(g) + 2e^-'),
         '**Step 4 — Decide what is left in solution.** In brine the H⁺ and Cl⁻ leave; Na⁺ and OH⁻ stay → the solution becomes **sodium hydroxide**.',
         eq('2NaCl(aq) + 2H2O(l) -> H2(g) + Cl2(g) + 2NaOH(aq)'),
         '**Dilute NaCl(aq) is different:** with little Cl⁻, OH⁻ is discharged and **oxygen** is formed: ' + ie('4OH^-(aq) -> 2H2O(l) + O2(g) + 4e^-') + '. Overall only water is decomposed: ' + ie('2H2O(l) -> 2H2(g) + O2(g)') + ', and the salt solution slowly gets more concentrated.',
         '**Concentrated hydrochloric acid** behaves like brine at the anode: H₂ at the cathode, Cl₂ at the anode: ' + ie('2HCl(aq) -> H2(g) + Cl2(g)') + '.'),
    U2.SS('s01', 'Model: dilute vs concentrated sodium chloride', 52, 'co_brine',
          [('dilute', 'Dilute NaCl', 'Cathode: H₂. Anode: OH⁻ is discharged → O₂. Water is used up; NaCl is left more concentrated.'),
           ('conc', 'Brine', 'Cathode: H₂. Anode: the huge excess of Cl⁻ wins → Cl₂. Na⁺ and OH⁻ stay behind → NaOH(aq).')]),
    U2.T('c02', '2.2.4 (3) Nature of the electrode, step by step', 54,
         'The electrode material is the **least important** factor, but in two cases it decides the product.',
         '**Case 1 — Mercury cathode with brine.** On mercury, H⁺ is very slow to discharge, while sodium dissolves in the mercury as an **amalgam**. So **Na⁺** is discharged instead of H⁺:',
         eq('Na^+(aq) + e^- -> Na(s)'), eq('Na(s) + Hg(l) -> NaHg(l)'),
         'The anode (graphite) still gives Cl₂. The amalgam is later treated with water to give very pure NaOH and H₂: ' + ie('2NaHg(l) + 2H2O(l) -> 2NaOH(aq) + H2(g) + 2Hg(l)') + '.',
         '**Case 2 — Copper(II) sulphate with an inert vs a copper anode.** The cathode is the same in both cells (Cu²⁺ is lower than H⁺ in the series, so copper is deposited):',
         eq('Cu^2+(aq) + 2e^- -> Cu(s)'),
         '**Graphite or platinum anode (inert):** SO₄²⁻ is not discharged, OH⁻ is → oxygen: ' + ie('4OH^-(aq) -> 2H2O(l) + O2(g) + 4e^-') + '. The blue colour fades and the solution becomes acidic (H₂SO₄ is left).',
         '**Copper anode (active):** neither anion is discharged. The copper atoms of the anode lose electrons more easily, so **the anode dissolves**: ' + ie('Cu(s) -> Cu^2+(aq) + 2e^-') + '. No gas forms; the blue colour stays the same, because every Cu²⁺ removed at the cathode is replaced at the anode.',
         '**Correction:** the textbook says the mercury-cathode example uses “molten sodium chloride”. It is **aqueous** sodium chloride (brine) — in a melt there is no H⁺ to compete with.'),
    U2.SS('s02', 'Model: CuSO₄(aq) with an inert and with a copper anode', 54, 'co_cuso4',
          [('inert', 'Graphite anode', 'Anode: oxygen bubbles. Cu²⁺ is used up, so the blue fades and H₂SO₄ is left.'),
           ('copper', 'Copper anode', 'Anode: copper dissolves, no gas. Cu²⁺ in = Cu²⁺ out, so the blue stays.')]),
    U2.TB('t01', 'The three factors and which one wins', 52,
          ['Factor', 'Rule', 'Example'],
          [['Position in the series', 'the ion lower in the series (cation) or easier to oxidise (anion) is discharged', 'H⁺ before Na⁺; Cu²⁺ before H⁺; OH⁻ before SO₄²⁻'],
           ['Concentration', 'a much more concentrated ion can be discharged instead', 'Cl⁻ before OH⁻ in brine and concentrated HCl'],
           ['Nature of the electrode', 'some electrodes change the product', 'Hg cathode: Na⁺ discharged; Cu anode: dissolves']],
          'Concentration can beat a small difference in the series (Cl⁻ vs OH⁻), but not a large one: Na⁺ is never discharged before H⁺ on an inert cathode.'),
    U2.TB('t02', 'Exercise 2.7 completed (inert electrodes)', 52,
          ['Electrolyte', 'Ions in solution', 'Cathode', 'Anode'],
          [['Dilute NaCl', 'Na⁺, H⁺, Cl⁻, OH⁻', 'H₂(g)', 'O₂(g)'], ['CuSO₄ solution', 'Cu²⁺, H⁺, SO₄²⁻, OH⁻', 'Cu(s)', 'O₂(g)'],
           ['Concentrated HBr', 'H⁺, Br⁻, OH⁻', 'H₂(g)', 'Br₂'], ['Molten PbBr₂', 'Pb²⁺, Br⁻', 'Pb(l)', 'Br₂(g)']]),
    U2.WK('w01', 'Worked example: predicting products step by step', 53,
          'Predict the products at each inert electrode for (a) concentrated KCl(aq), (b) dilute H₂SO₄, (c) AgNO₃(aq). Write the half-equations.',
          ['(a) Ions K⁺, H⁺, Cl⁻, OH⁻. Cathode: K⁺ is very high in the series → H⁺: ' + ie('2H^+(aq) + 2e^- -> H2(g)') + '. Anode: concentrated Cl⁻ → ' + ie('2Cl^-(aq) -> Cl2(g) + 2e^-') + '; KOH is left.',
           '(b) Ions H⁺, SO₄²⁻, OH⁻. Cathode: H₂. Anode: OH⁻ before SO₄²⁻ → ' + ie('4OH^-(aq) -> 2H2O(l) + O2(g) + 4e^-') + '. Volume ratio H₂ : O₂ = 2 : 1.',
           '(c) Ions Ag⁺, H⁺, NO₃⁻, OH⁻. Cathode: Ag⁺ is below H⁺ → ' + ie('Ag^+(aq) + e^- -> Ag(s)') + '. Anode: OH⁻ before NO₃⁻ → O₂; HNO₃ is left.'],
          '(a) H₂ / Cl₂; (b) H₂ / O₂; (c) Ag / O₂'),
    U2.WK('w02', 'Worked example: why H₂ : O₂ is 2 : 1 (Hoffmann apparatus)', 51,
          'In the electrolysis of dilute sulphuric acid, 20 cm³ of gas is collected at the cathode. What volume of oxygen is collected at the anode?',
          ['Cathode: ' + ie('4H^+(aq) + 4e^- -> 2H2(g)') + ' (both half-equations written for 4 e⁻).', 'Anode: ' + ie('4OH^-(aq) -> 2H2O(l) + O2(g) + 4e^-'),
           'The same 4 e⁻ give 2 mol H₂ and 1 mol O₂ → ratio 2 : 1.', 'O₂ = 20 ÷ 2 = **10 cm³**.'],
          '10 cm³ of oxygen'),
    U2.CK('k01', 52, 'Brine is electrolysed with graphite electrodes. The gas at the anode is …', ['O₂', 'H₂', 'Cl₂', 'Na vapour'], 'C',
          'In brine Cl⁻ is far more concentrated than OH⁻, so Cl⁻ is discharged → Cl₂. (Dilute NaCl would give O₂.)'),
    U2.CK('k02', 54, 'CuSO₄(aq) is electrolysed with copper electrodes. What happens to the blue colour?', ['it fades', 'it deepens', 'it stays the same', 'it turns green'], 'C',
          'The copper anode dissolves at the same rate as copper is deposited, so [Cu²⁺] does not change.'),
]
U2.M('q01', L224, 52, 'In the electrolysis of dilute NaCl(aq) with inert electrodes, the products are …',
     ['H₂ and Cl₂', 'Na and Cl₂', 'H₂ and O₂', 'Na and O₂'], 'C',
     ['Step 1: cathode — H⁺ is discharged before Na⁺ → H₂.', 'Step 2: anode — in dilute solution OH⁻ is discharged before Cl⁻ → O₂.', 'Step 3: so H₂ and O₂ (water is decomposed).'],
     'Dilute → O₂; concentrated chloride → Cl₂.', [('Products for brine?', 'H₂ and Cl₂ (NaOH left).'), ('Products for dilute H₂SO₄?', 'H₂ and O₂.')])
U2.S('q02', L224, 54, 'Explain why sodium (not hydrogen) is discharged at a mercury cathode in the electrolysis of brine. Write the equations.',
     'On mercury H⁺ is discharged only very slowly, while sodium dissolves in mercury to form an amalgam; so Na⁺ + e⁻ → Na, then Na + Hg → NaHg.',
     ['Step 1: normally H⁺ wins over Na⁺ (position in the series).', 'Step 2: the nature of the electrode changes this: discharge of H⁺ on Hg is very difficult.',
      'Step 3: Na formed dissolves in Hg as amalgam NaHg(l), which removes it from the solution.', 'Step 4: Na⁺(aq) + e⁻ → Na(s); Na(s) + Hg(l) → NaHg(l).'],
     'This is the only common case where Na⁺ is discharged from water.', [('What is an amalgam?', 'An alloy of a metal with mercury.'), ('Product at the graphite anode?', 'Cl₂.')])
U2.M('q03', L224, 54, 'CuSO₄(aq) is electrolysed with graphite electrodes. The solution at the end is …', ['neutral CuSO₄', 'acidic (H₂SO₄)', 'alkaline (NaOH)', 'pure water'], 'B',
     ['Step 1: cathode removes Cu²⁺ (copper is deposited).', 'Step 2: anode removes OH⁻ (oxygen given off).', 'Step 3: H⁺ and SO₄²⁻ remain → sulphuric acid.'],
     'Look at which ions are left behind.', [('Solution left after electrolysis of brine?', 'NaOH (alkaline).'), ('After dilute NaCl?', 'More concentrated NaCl.')])
U2.S('q04', L224, 54, 'Write the half-equation at each electrode when CuSO₄(aq) is electrolysed with copper electrodes.',
     'Cathode: Cu²⁺(aq) + 2e⁻ → Cu(s); anode: Cu(s) → Cu²⁺(aq) + 2e⁻.',
     ['Step 1: cathode — Cu²⁺ is lower than H⁺ in the series → copper deposited.', 'Step 2: anode — the copper metal loses electrons more easily than SO₄²⁻ or OH⁻.',
      'Step 3: so the anode dissolves; electrons balance (2 e⁻ each side).'],
     'An active anode dissolves instead of giving a gas.', [('Mass change of the anode?', 'It decreases.'), ('Of the cathode?', 'It increases by the same mass.')])
U2.TF('q05', L224, 52, 'In concentrated hydrochloric acid, chloride ions are discharged at the anode in preference to hydroxide ions.', True,
      ['Step 1: OH⁻ is normally easier to discharge.', 'Step 2: in concentrated HCl, [Cl⁻] is enormously greater than [OH⁻].', 'Step 3: concentration wins → Cl₂.'],
      'High concentration can win over a small difference in the series.', [('In very dilute HCl?', 'Mainly O₂ (with some Cl₂).'), ('Cathode product with HCl?', 'H₂.')])

APP = [
    U2.T('c03', '2.2.5 Applications of electrolysis, step by step', 56,
         'Electrolysis is used to coat objects, to make gases and alkalis, to extract reactive metals and to purify metals. In every application ask the same questions: **what is the cathode, the anode and the electrolyte?** and **which ions are discharged?**',
         '**1 · Electroplating** — coating an object with a thin layer of another metal, to prevent rusting or to make it look better (silver or gold on spoons and jewellery, chromium on taps, tin on cans).',
         '• **Cathode (−):** the object to be plated. • **Anode (+):** the plating metal. • **Electrolyte:** a solution of a salt of the plating metal.',
         'For silver plating (AgNO₃ electrolyte): cathode ' + ie('Ag^+(aq) + e^- -> Ag(s)') + ', anode ' + ie('Ag(s) -> Ag^+(aq) + e^-') + '. The anode dissolves as fast as silver is deposited, so the electrolyte stays the same.',
         '**2 · Preparation of gases and extraction of metals** — Cl₂ and H₂ from brine; O₂ and H₂ from acidified water. Very reactive metals (Na, K, Ca, Mg, Al) cannot be reduced by carbon, so they are extracted by electrolysis of their **molten** compounds.',
         'Sodium from molten NaCl: cathode ' + ie('Na^+(l) + e^- -> Na(l)') + ', anode ' + ie('2Cl^-(l) -> Cl2(g) + 2e^-') + '.',
         'Aluminium: Al₂O₃ is dissolved in molten **cryolite** (Na₃AlF₆) to lower the working temperature (from about 2050 °C to about 950 °C). Cathode ' + ie('Al^3+(l) + 3e^- -> Al(l)') + ', anode ' + ie('2O^2-(l) -> O2(g) + 4e^-') + '. The hot carbon anodes burn away, ' + ie('C(s) + O2(g) -> CO2(g)') + ', and must be replaced.',
         '**3 · Purification (refining) of copper** — impure copper is the **anode**, a thin sheet of pure copper is the **cathode**, the electrolyte is CuSO₄(aq) with a little H₂SO₄. Copper dissolves from the anode and is deposited on the cathode (99.99 % pure). Less reactive impurities (Ag, Au, Pt) fall as **anode mud**; more reactive ones (Zn, Fe) stay in solution.',
         '**4 · Manufacture of sodium hydroxide** — electrolysis of brine gives three useful products at once: ' + ie('2NaCl(aq) + 2H2O(l) -> H2(g) + Cl2(g) + 2NaOH(aq)') + '. NaOH is used for soap, paper and textiles; Cl₂ for water treatment and PVC; H₂ for margarine and ammonia.'),
    U2.ST('s03', 'Model: electroplating a spoon with silver (Fig. 2.6)', 56, 'co_plating',
          [('**Anode (+): pure silver** — silver atoms lose electrons and go into solution.', 'anode'),
           ('**Cathode (−): the spoon** — Ag⁺ ions gain electrons; a thin, even silver layer forms.', 'cathode'),
           ('**Electrolyte:** Ag⁺ ions carry the current through the solution; their concentration stays constant.', 'ions')]),
    U2.ST('s04', 'Model: refining copper (Fig. 2.7)', 57, 'co_refine',
          [('**Anode (+): impure copper** gets thinner: Cu → Cu²⁺ + 2e⁻.', 'anode'), ('**Cathode (−): pure copper** grows: Cu²⁺ + 2e⁻ → Cu.', 'cathode'),
           ('**Anode mud:** silver, gold and platinum do not dissolve and collect under the anode — they are valuable by-products.', 'mud')]),
    U2.TB('t03', 'Electroplating and refining compared', 57,
          ['', 'Electroplating (silver)', 'Refining copper'],
          [['Anode (+)', 'pure plating metal (Ag)', 'impure copper'], ['Cathode (−)', 'object to be coated', 'thin sheet of pure copper'],
           ['Electrolyte', 'salt of the plating metal (AgNO₃)', 'CuSO₄(aq) + a little H₂SO₄'], ['Aim', 'thin even coat, for protection/appearance', 'very pure copper for wires'],
           ['Electrolyte concentration', 'stays the same', 'stays almost the same'], ['By-product', 'none', 'anode mud (Ag, Au, Pt)']],
          'In both, the anode is a metal that dissolves (an active anode). The difference is the purpose and what the cathode is.'),
    U2.TB('t04', 'Activity 2.7 and Exercise 2.8 answered (CuCl₂ with carbon rods)', 55,
          ['Question', 'Answer'],
          [['What do you observe in the solution?', 'bubbles at the anode (pale green-yellow chlorine, bleach smell); the blue colour slowly fades'],
           ['What happened to the rods?', 'the cathode rod is coated with pink-brown copper'], ['Rusty nail as the cathode?', 'it becomes copper-coated (clean it first so the coat sticks)'],
           ['CuCl₂ dissolving in water', 'CuCl₂(s) → Cu²⁺(aq) + 2Cl⁻(aq)'], ['Anode half-reaction', '2Cl⁻ → Cl₂ + 2e⁻'], ['Cathode half-reaction', 'Cu²⁺ + 2e⁻ → Cu'],
           ['Electrolyte', 'copper(II) chloride solution, CuCl₂(aq)']]),
    U2.WK('w03', 'Worked example: design a nickel-plating cell', 56,
          'You want to nickel-plate an iron key. Name the anode, cathode and electrolyte and write the electrode equations.',
          ['The object to be coated is always the **cathode** → the iron key (cleaned).', 'The plating metal is the **anode** → a nickel bar.',
           'The electrolyte must contain the plating ions → nickel(II) sulphate solution.', 'Cathode: ' + ie('Ni^2+(aq) + 2e^- -> Ni(s)') + '; anode: ' + ie('Ni(s) -> Ni^2+(aq) + 2e^-') + '.'],
          'Anode Ni, cathode key, electrolyte NiSO₄(aq)'),
    U2.WK('w04', 'Worked example: why aluminium needs electrolysis and cryolite', 57,
          'Explain why aluminium is extracted by electrolysis, why cryolite is used, and why the anodes must be replaced.',
          ['Al is above carbon in the reactivity series, so carbon cannot reduce Al₂O₃.', 'Pure Al₂O₃ melts at about 2050 °C — too costly; dissolved in molten cryolite it conducts at about 950 °C.',
           'Oxygen formed at the hot carbon anodes reacts with them: ' + ie('C(s) + O2(g) -> CO2(g)') + ', so they burn away.'],
          'Too reactive for carbon; cryolite lowers the temperature; anodes burn.'),
    U2.CK('k03', 56, 'In electroplating, the object to be plated is made the …', ['anode', 'cathode', 'electrolyte', 'salt bridge'], 'B',
          'Metal ions are positive and are reduced at the negative electrode, the cathode — so the object must be the cathode.'),
    U2.CK('k04', 57, 'In copper refining the anode mud contains …', ['Zn and Fe', 'pure copper', 'Ag and Au', 'CuSO₄ crystals'], 'C',
          'Metals less reactive than copper (Ag, Au, Pt) do not dissolve at the anode and fall to the bottom.'),
]
U2.M('q10', L225, 56, 'Which electrolyte would you use to plate a spoon with silver?', ['CuSO₄(aq)', 'AgNO₃(aq)', 'NaCl(aq)', 'H₂SO₄(aq)'], 'B',
     ['Step 1: the electrolyte must contain the plating metal ions.', 'Step 2: silver → Ag⁺.', 'Step 3: silver nitrate is soluble → AgNO₃(aq).'],
     'Plating ion = plating metal.', [('Electrolyte for copper plating?', 'CuSO₄(aq).'), ('For nickel plating?', 'NiSO₄(aq).')])
U2.S('q11', L225, 57, 'Write the electrode equations for the purification of copper and say what happens to the mass of each electrode.',
     'Anode: Cu(s) → Cu²⁺(aq) + 2e⁻ (loses mass). Cathode: Cu²⁺(aq) + 2e⁻ → Cu(s) (gains mass).',
     ['Step 1: impure copper anode dissolves.', 'Step 2: Cu²⁺ ions move to the pure cathode and are deposited.', 'Step 3: anode loses mass; cathode gains (slightly less, because impurities fall as mud).'],
     'Active anode → dissolves.', [('Where does Ag end up?', 'Anode mud.'), ('Where does Zn end up?', 'In solution as Zn²⁺.')])
U2.M('q12', L225, 58, 'The three products of the electrolysis of brine are …', ['Na, Cl₂, H₂O', 'H₂, Cl₂, NaOH', 'O₂, H₂, NaCl', 'H₂, O₂, NaOH'], 'B',
     ['Step 1: cathode H₂.', 'Step 2: anode Cl₂ (concentrated chloride).', 'Step 3: Na⁺ and OH⁻ remain → NaOH.'],
     'Brine → H₂ + Cl₂ + NaOH.', [('Use of chlorine?', 'Water treatment, PVC, bleach.'), ('Use of NaOH?', 'Soap, paper.')])
U2.S('q13', L225, 57, 'Write the half-equations at the electrodes in the extraction of aluminium.', 'Cathode: Al³⁺ + 3e⁻ → Al(l); anode: 2O²⁻ → O₂(g) + 4e⁻.',
     ['Step 1: molten electrolyte contains Al³⁺ and O²⁻.', 'Step 2: Al³⁺ gains 3 electrons at the cathode.', 'Step 3: O²⁻ loses 2 electrons; two of them give O₂.',
      'Step 4: overall 2Al₂O₃(l) → 4Al(l) + 3O₂(g) (12 e⁻ transferred).'],
     'Balance electrons: 4Al³⁺ + 12e⁻ and 6O²⁻ − 12e⁻.', [('Half-equation for sodium from molten NaCl?', 'Na⁺ + e⁻ → Na.'), ('Why must the electrolyte be molten?', 'So that the ions can move.')])
U2.TF('q14', L225, 56, 'In electroplating with a silver anode the concentration of Ag⁺ in the electrolyte falls steadily.', False,
      ['Step 1: at the cathode Ag⁺ is removed.', 'Step 2: at the anode the same number of Ag⁺ ions is produced.', 'Step 3: the concentration stays constant.'],
      'Active anode replaces the ions used.', [('With an inert anode?', 'Then Ag⁺ would fall.'), ('Which electrode loses mass?', 'The silver anode.')])

FAR = [
    U2.T('c04', "2.2.6 Faraday's laws, step by step", 59,
         "Faraday's laws connect the **amount of electricity** passed with the **amount of product** at an electrode. Every calculation starts from the **half-equation**, because it tells you how many electrons each ion needs.",
         '**Step 1 — Charge passed:** $$Q = I \\times t$$ with I in amperes and t in **seconds** (1 C = 1 A s).',
         '**Step 2 — Moles of electrons:** one mole of electrons carries **1 faraday, F = 96 500 C**. $$n(e^-) = \\frac{Q}{F}$$',
         '**Step 3 — Use the half-equation:** z = the charge on the ion = electrons per atom.',
         eq('Ag^+(aq) + e^- -> Ag(s)', r'\text{1 mol e}^- \to \text{1 mol Ag}'),
         eq('Cu^2+(aq) + 2e^- -> Cu(s)', r'\text{2 mol e}^- \to \text{1 mol Cu}'),
         eq('Al^3+(l) + 3e^- -> Al(l)', r'\text{3 mol e}^- \to \text{1 mol Al}'),
         '**Step 4 — Mass:** moles of metal × molar mass. All steps together give the textbook formula:',
         '$$m = \\frac{A}{z}\\cdot\\frac{I\\,t}{F} = \\frac{\\text{Eq. mass} \\times I \\times t}{96\\,500}$$',
         "**First law:** m ∝ Q (double the current or the time → double the mass). The constant k = A/(zF) is the **electrochemical equivalent** (mass deposited by 1 C).",
         "**Second law:** for the **same charge** (cells in series), the masses are in the ratio of the **equivalent masses** A/z: $$\\frac{m_1}{m_2} = \\frac{A_1/z_1}{A_2/z_2}$$",
         '**Gases:** same method; at room conditions 1 mol of gas occupies about 24 dm³. ' + ie('2Cl^-(aq) -> Cl2(g) + 2e^-') + ' → 2 mol e⁻ per mol Cl₂; ' + ie('4OH^-(aq) -> 2H2O(l) + O2(g) + 4e^-') + ' → 4 mol e⁻ per mol O₂.'),
    U2.ST('s05', 'Model: two cells in series (second law)', 61, 'co_series',
          [('**Silver cell:** ' + ie('Ag^+(aq) + e^- -> Ag(s)') + ' — every mole of electrons deposits 108 g of silver.', 'ag'),
           ('**Nickel cell:** ' + ie('Ni^2+(aq) + 2e^- -> Ni(s)') + ' — every mole of electrons deposits only ½ mol = 29.5 g of nickel.', 'ni'),
           ('**Same wire, same current, same time → same Q.** So mass(Ag) : mass(Ni) = 108 : 29.5.', 'q')]),
    U2.TB('t05', 'Equivalent masses of common electrode products', 59,
          ['Product', 'Half-equation', 'A (g/mol)', 'z', 'Eq. mass A/z (g)'],
          [['Silver', 'Ag⁺ + e⁻ → Ag', '108', '1', '108'], ['Copper', 'Cu²⁺ + 2e⁻ → Cu', '63.5 (≈ 64)', '2', '31.75 (≈ 32)'],
           ['Nickel', 'Ni²⁺ + 2e⁻ → Ni', '59', '2', '29.5'], ['Aluminium', 'Al³⁺ + 3e⁻ → Al', '27', '3', '9'], ['Chromium', 'Cr³⁺ + 3e⁻ → Cr', '52', '3', '17.3'],
           ['Gold', 'Au³⁺ + 3e⁻ → Au', '197', '3', '65.7'], ['Hydrogen', '2H⁺ + 2e⁻ → H₂', '2 (H₂)', '2 per H₂', '1'], ['Oxygen', '4OH⁻ → 2H₂O + O₂ + 4e⁻', '32 (O₂)', '4 per O₂', '8']]),
    U2.WK('w05', 'Worked example 1: copper deposited (textbook)', 59,
          'What mass of copper is deposited from copper(II) sulphate solution by a current of 5.0 A for 100 s? (Cu = 64)',
          ['Cathode: ' + ie('Cu^2+(aq) + 2e^- -> Cu(s)') + ' → z = 2, Eq. mass = 64/2 = 32 g.', r'\(Q = I t = 5.0 \times 100 = 500\ \text{C}\)',
           r'\(n(e^-) = 500 / 96\,500 = 5.18 \times 10^{-3}\ \text{mol}\); \(n(\text{Cu}) = \tfrac{1}{2} n(e^-) = 2.59 \times 10^{-3}\ \text{mol}\)',
           r'\(m = 2.59 \times 10^{-3} \times 64 = 0.166\ \text{g}\) — the same as \(\dfrac{32 \times 5.0 \times 100}{96\,500}\).'],
          '≈ 0.17 g of copper'),
    U2.WK('w06', 'Worked example 2: time to deposit silver (textbook, corrected)', 60,
          'Calculate the time needed to deposit 0.56 g of silver from silver nitrate solution with a current of 4.5 A. (Ag = 108)',
          ['Cathode: ' + ie('Ag^+(aq) + e^- -> Ag(s)') + ' → z = 1, Eq. mass = 108 g. (The textbook line “atomic mass of Ag is 64” is a misprint; Ag = 108, as used in its working.)',
           r'Rearrange \(m = \dfrac{\text{Eq. mass} \times I t}{F}\) → \(t = \dfrac{m F}{\text{Eq. mass} \times I}\).', r'\(t = \dfrac{0.56 \times 96\,500}{108 \times 4.5} = \dfrac{54\,040}{486} = 111\ \text{s}\)'],
          '≈ 111 s (1.9 min)'),
    U2.WK('w07', 'Worked example 3: silver and nickel in series (second law)', 61,
          'Two cells, AgNO₃(aq) and Ni(NO₃)₂(aq), are in series. 2.16 g of silver is deposited in the first cell. What mass of nickel is deposited in the second? (Ag = 108, Ni = 59)',
          ['Half-equations: ' + ie('Ag^+(aq) + e^- -> Ag(s)') + ' and ' + ie('Ni^2+(aq) + 2e^- -> Ni(s)') + ' → Eq. masses 108 and 59/2 = 29.5.',
           r'Second law: \(\dfrac{m_{\text{Ag}}}{m_{\text{Ni}}} = \dfrac{108}{29.5}\) → \(m_{\text{Ni}} = 2.16 \times \dfrac{29.5}{108} = 0.59\ \text{g}\).',
           r'Charge needed: \(Q = \dfrac{2.16}{108} \times 96\,500 = 1930\ \text{C}\).',
           'Note: the textbook also says 1.5 A for 10 min (900 C). That charge would deposit only 1.01 g Ag and 0.275 g Ni, so its data do not agree; 2.16 g needs 1930 C (1.5 A for about 21.4 min). In the textbook, “Z_Ag = 108, Z_Ni = 59” are the **atomic masses**, not charges.'],
          '0.59 g of nickel (Q = 1930 C)'),
    U2.WK('w08', 'Worked example 4: Exercise 2.9 Q2 — the charge on chromium', 62,
          'Electrolysis of a molten chromium salt for 1.50 h with a current of 10.0 A deposits 9.71 g of Cr. Find the oxidation number of chromium. (Cr = 52)',
          [r'\(Q = 10.0 \times 1.50 \times 3600 = 54\,000\ \text{C}\); \(n(e^-) = 54\,000/96\,500 = 0.560\ \text{mol}\)', r'\(n(\text{Cr}) = 9.71/52 = 0.187\ \text{mol}\)',
           r'Electrons per Cr atom: \(0.560 / 0.187 = 3.0\) → ' + ie('Cr^3+(l) + 3e^- -> Cr(l)') + '.',
           'Correction: the textbook gives Cr = 62 and 8.4 A. The molar mass of chromium is **52 g/mol**; with 52 and 8.4 A the ratio is 2.5 (not a whole number), so the current must be 10.0 A, as in the original version of this problem.'],
          '+3'),
    U2.WK('w09', 'Worked example 5: Exercise 2.9 Q3 — equivalent mass of gold', 62,
          'The same charge deposits 2.158 g of silver and 1.314 g of gold. Eq. mass of Ag = 107.8. Find the equivalent mass of gold and the charge on the gold ion.',
          [r'\(\dfrac{m_{\text{Au}}}{m_{\text{Ag}}} = \dfrac{E_{\text{Au}}}{E_{\text{Ag}}}\) → \(E_{\text{Au}} = 107.8 \times \dfrac{1.314}{2.158} = 65.6\ \text{g}\)',
           'z = A/Eq. mass = 197/65.6 = 3 → ' + ie('Au^3+(aq) + 3e^- -> Au(s)') + '.'],
          'Eq. mass of Au ≈ 65.6 g; Au³⁺'),
    U2.WK('w10', 'Worked example 6: volume of chlorine from brine', 59,
          'Brine is electrolysed with 2.00 A for 965 s. What volume of chlorine (at room conditions, 24 dm³/mol) is formed at the anode?',
          [r'\(Q = 2.00 \times 965 = 1930\ \text{C}\); \(n(e^-) = 1930/96\,500 = 0.0200\ \text{mol}\)', 'Anode: ' + ie('2Cl^-(aq) -> Cl2(g) + 2e^-') + ' → n(Cl₂) = 0.0200/2 = 0.0100 mol.',
           r'\(V = 0.0100 \times 24 = 0.24\ \text{dm}^3 = 240\ \text{cm}^3\)'],
          '240 cm³ of Cl₂'),
    U2.CK('k05', 59, 'The same charge that deposits 1 mol of Ag deposits how much Cu?', ['2 mol', '1 mol', '½ mol', '¼ mol'], 'C',
          'Ag⁺ needs 1 e⁻, Cu²⁺ needs 2 e⁻. 1 mol e⁻ → 1 mol Ag but only ½ mol Cu.'),
    U2.RM('r01', 'Tips and common mistakes', 59,
          'Always convert time to seconds (min × 60, h × 3600).',
          'Write the half-equation first — z is the number of electrons in it, not the group number.',
          'The second law only works when the cells are in series (same charge).'),
]
U2.S('q20', L226, 59, 'What mass of silver is deposited by 0.50 A flowing for 30 minutes through AgNO₃(aq)? (Ag = 108)', '1.01 g',
     ['Step 1: Ag⁺(aq) + e⁻ → Ag(s); z = 1.', 'Step 2: Q = 0.50 × 30 × 60 = 900 C.', 'Step 3: n(e⁻) = 900/96 500 = 9.33 × 10⁻³ mol = n(Ag).', 'Step 4: m = 9.33 × 10⁻³ × 108 = 1.01 g.'],
     'Q = It with t in seconds.', [('Same current, 60 min?', '2.01 g.'), ('Copper instead (Cu = 64), 30 min?', '0.30 g.')], accept=['1.0 g', '1.01', '1.0'])
U2.S('q21', L226, 62, 'Exercise 2.9 Q1: find the mass of copper deposited from CuSO₄(aq) by a current of 2.0 A for 1 hour. (Cu = 63.5)', '2.37 g',
     ['Step 1: Cu²⁺(aq) + 2e⁻ → Cu(s); Eq. mass = 63.5/2 = 31.75 g.', 'Step 2: Q = 2.0 × 3600 = 7200 C.', 'Step 3: m = 31.75 × 7200 / 96 500 = 2.37 g.'],
     'Use the Eq. mass for a quick answer.', [('With 1.0 A for 1 h?', '1.18 g.'), ('Time to deposit 4.74 g with 2.0 A?', '2 h.')], accept=['2.4 g', '2.37', '2.4'])
U2.M('q22', L226, 61, 'Cells of AgNO₃ and CuSO₄ are in series. 1.08 g of silver is deposited. The mass of copper deposited (Cu = 64) is …', ['0.64 g', '0.32 g', '1.08 g', '0.16 g'], 'B',
     ['Step 1: Eq. masses: Ag 108/1 = 108; Cu 64/2 = 32.', 'Step 2: m(Cu) = 1.08 × 32/108.', 'Step 3: = 0.32 g.'],
     'Ratio of equivalent masses.', [('Mass of Ni (Eq. 29.5) for the same charge?', '0.295 g.'), ('Moles of electrons passed?', '0.010 mol.')])
U2.S('q23', L226, 59, 'How long must 3.00 A flow to deposit 2.70 g of aluminium from molten Al₂O₃? (Al = 27)', '9650 s (about 2 h 41 min)',
     ['Step 1: Al³⁺ + 3e⁻ → Al; n(Al) = 2.70/27 = 0.100 mol.', 'Step 2: n(e⁻) = 3 × 0.100 = 0.300 mol.', 'Step 3: Q = 0.300 × 96 500 = 28 950 C.', 'Step 4: t = 28 950 / 3.00 = 9650 s.'],
     'moles of metal → moles of e⁻ → Q → t.', [('Time for 0.270 g at 3.00 A?', '965 s.'), ('Mass of Al from 96 500 C?', '9 g.')], accept=['9650', '9650 s'])
U2.S('q24', L226, 59, 'In the electrolysis of dilute H₂SO₄, 0.0400 mol of electrons are passed. Find the moles of H₂ and of O₂ formed.', 'H₂ 0.0200 mol; O₂ 0.0100 mol',
     ['Step 1: cathode 2H⁺ + 2e⁻ → H₂: 2 e⁻ per H₂ → 0.0400/2 = 0.0200 mol.', 'Step 2: anode 4OH⁻ → 2H₂O + O₂ + 4e⁻: 4 e⁻ per O₂ → 0.0400/4 = 0.0100 mol.', 'Step 3: ratio 2 : 1.'],
     'Read the electrons off each half-equation.', [('Volume of H₂ at 24 dm³/mol?', '0.48 dm³.'), ('Charge passed?', '3860 C.')])
U2.TF('q25', L226, 59, 'Doubling the current and halving the time leaves the mass deposited unchanged.', True,
      ['Step 1: m ∝ Q = I × t.', 'Step 2: (2I) × (t/2) = I × t.', 'Step 3: Q is the same, so m is the same.'],
      'First law: mass depends only on the charge.', [('Double current and double time?', '4 × the mass.'), ('Half the current, same time?', 'Half the mass.')])

# ====================================================================================== Unit 3 · cycles, sulphur, sulphuric acid
U3 = Unit('chem11-u3')
LC = '3.2 The carbon cycle'
LN = '3.3 The nitrogen cycle'
LS = '3.4.1 Extraction and allotropes of sulphur'
LH = '3.4.3 Sulphuric acid and sulphates'

CARB = [
    U3.T('c01', 'The carbon cycle, step by step', 82,
         'Carbon is in every living thing. It moves between the **air**, **living things**, the **oceans** and **rocks and fuels**, and carbon dioxide is the “transfer agent” that carries it. The **carbon cycle** is the set of processes that keeps the CO₂ in the air (about 0.04 % by volume) roughly constant.',
         '**Step 1 — Photosynthesis removes CO₂.** Green plants use sunlight and chlorophyll to turn CO₂ and water into glucose and oxygen:',
         eq('6CO2(g) + 6H2O(l) ->{sunlight, chlorophyll} C6H12O6(aq) + 6O2(g)'),
         '**Step 2 — Feeding passes carbon on.** Animals eat plants (and other animals); the carbon becomes part of their bodies.',
         '**Step 3 — Respiration returns CO₂.** Plants and animals oxidise glucose to release energy:',
         eq('C6H12O6(aq) + 6O2(g) -> 6CO2(g) + 6H2O(l)', r'\text{energy released}'),
         '**Step 4 — Decay returns CO₂.** When plants and animals die, bacteria and fungi (decomposers) break them down and respire, releasing CO₂.',
         '**Step 5 — Fossil fuels store carbon.** Remains buried for millions of years without air become coal, oil and natural gas.',
         '**Step 6 — Combustion returns CO₂ fast.** Burning fuels, wood and charcoal: ' + ie('CH4(g) + 2O2(g) -> CO2(g) + 2H2O(l)') + ', ' + ie('C(s) + O2(g) -> CO2(g)') + '.',
         '**Step 7 — Oceans and rocks.** CO₂ dissolves in rain water and in the oceans: ' + ie('CO2(g) + H2O(l) <=> H2CO3(aq)') + '. Sea animals use dissolved carbonate to build shells of CaCO₃, which become limestone. Heating limestone and volcanoes release CO₂ again.',
         '**Correction:** the textbook says CO₂ is removed “as acid rain”. CO₂ makes rain water only **very slightly acidic** (pH ≈ 5.6); “acid rain” means rain made much more acidic by SO₂ and nitrogen oxides. The correct statement is that CO₂ **dissolves in rain, seas and oceans**.'),
    U3.ST('s01', 'Model: the carbon cycle (Fig. 3.5)', 83, 'co_ccycle',
          [('**Photosynthesis** takes CO₂ out of the air into plants.', 'photo'), ('**Respiration and decay** put CO₂ back into the air.', 'resp'),
           ('**Combustion** of fossil fuels and wood puts back CO₂ that was stored for millions of years.', 'burn'),
           ('**Oceans** dissolve CO₂ (H₂CO₃, carbonates, limestone) and release it again.', 'sea')]),
    U3.TB('t01', 'Processes that remove and add carbon dioxide', 83,
          ['Process', 'Removes or adds CO₂?', 'Who/what does it', 'Equation (simplified)'],
          [['Photosynthesis', 'removes', 'green plants, algae', '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂'], ['Dissolving', 'removes', 'rain, seas, oceans', 'CO₂ + H₂O ⇌ H₂CO₃'],
           ['Shell / limestone formation', 'removes (stores)', 'sea animals', 'Ca²⁺ + CO₃²⁻ → CaCO₃'], ['Respiration', 'adds', 'all living things', 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O'],
           ['Decay', 'adds', 'bacteria, fungi', '(respiration of decomposers)'], ['Combustion', 'adds', 'people: fuels, wood, charcoal', 'C + O₂ → CO₂'],
           ['Heating limestone, volcanoes', 'adds', 'industry, Earth', 'CaCO₃ → CaO + CO₂']]),
    U3.T('c02', 'Upsetting the balance: the greenhouse effect', 83,
         "**Step 1:** sunlight warms the Earth's surface. **Step 2:** the warm surface gives out **infrared** radiation. **Step 3:** CO₂ (and methane, water vapour) absorbs infrared and acts like a **thermal blanket**.",
         '**Step 4:** human activities add CO₂ faster than plants and oceans can remove it — **burning fossil fuels** and **cutting down forests** (fewer trees for photosynthesis, and the wood is often burnt).',
         '**Result:** more CO₂ → stronger greenhouse effect → **global warming** → changed rainfall, droughts, melting ice and rising sea levels.',
         '**What helps:** planting trees, using less fuel, renewable energy (solar, wind, hydro), efficient stoves.',
         '**Do not confuse:** the greenhouse effect is about CO₂ trapping heat; the **ozone hole** is caused by CFCs; **acid rain** is caused by SO₂ and NOₓ.'),
    U3.WK('w01', 'Worked example: CO₂ from burning charcoal', 83,
          'Calculate the mass of CO₂ produced when 1.2 kg of charcoal (pure carbon) burns completely. (C = 12, O = 16)',
          [eq('C(s) + O2(g) -> CO2(g)'), '1 mol C (12 g) gives 1 mol CO₂ (44 g).', r'\(n(\text{C}) = 1200/12 = 100\ \text{mol}\) → \(n(\text{CO}_2) = 100\ \text{mol}\).',
           r'\(m = 100 \times 44 = 4400\ \text{g} = 4.4\ \text{kg}\)', 'The mass is larger than the charcoal because oxygen from the air is added.'],
          '4.4 kg of CO₂'),
    U3.WK('w02', 'Worked example: CO₂ used in photosynthesis', 82,
          'What mass of CO₂ must a plant take in to make 90 g of glucose? (C₆H₁₂O₆ = 180 g/mol)',
          [eq('6CO2(g) + 6H2O(l) -> C6H12O6(aq) + 6O2(g)'), r'\(n(\text{glucose}) = 90/180 = 0.50\ \text{mol}\)',
           r'Ratio 6 : 1 → \(n(\text{CO}_2) = 3.0\ \text{mol}\); \(m = 3.0 \times 44 = 132\ \text{g}\).'],
          '132 g'),
    U3.CK('k01', 82, 'Which process removes CO₂ from the atmosphere?', ['respiration', 'combustion', 'photosynthesis', 'decay'], 'C',
          'Photosynthesis uses CO₂; the other three all release it.'),
    U3.CK('k02', 83, 'Cutting down forests increases atmospheric CO₂ because …', ['trees give out CO₂ in the day', 'less photosynthesis takes place and the wood is often burnt', 'soil absorbs oxygen', 'it causes acid rain'], 'B',
          'Fewer trees remove less CO₂, and burning or decaying wood adds CO₂.'),
]
U3.M('q01', LC, 82, 'In the carbon cycle, carbon passes from plants to animals by …', ['respiration', 'feeding', 'combustion', 'photosynthesis'], 'B',
     ['Step 1: plants make carbon compounds (glucose, starch).', 'Step 2: animals eat plants.', 'Step 3: so carbon moves by feeding (eating).'],
     'Follow the arrow from “plants” to “animals” in the cycle.', [('How does carbon pass from animals to air?', 'Respiration (and decay after death).'), ('From fossil fuels to air?', 'Combustion.')])
U3.S('q02', LC, 83, 'List two ways in which CO₂ is removed from the atmosphere and two ways it is added. (Exercise 3.2 Q3)',
     'Removed: photosynthesis; dissolving in rain, seas and oceans. Added: respiration (and decay); combustion of fuels.',
     ['Step 1: removal = into plants (photosynthesis) or into water (dissolving).', 'Step 2: addition = respiration, decay, combustion, heating limestone, volcanoes.', 'Step 3: give two of each.'],
     'Think “into living things / water” vs “out of living things / fuels”.', [('Write the photosynthesis equation.', '6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂.'), ('Write the respiration equation.', 'C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O.')])
U3.S('q03', LC, 83, 'Explain how burning fossil fuels leads to global warming.',
     'Burning releases CO₂ that was stored underground; CO₂ absorbs infrared radiation from the warm Earth and traps heat (greenhouse effect), so the average temperature rises.',
     ['Step 1: fossil fuel + oxygen → CO₂ + water.', 'Step 2: this CO₂ adds to the air faster than plants and oceans remove it.', 'Step 3: more CO₂ absorbs more infrared → global warming.'],
     'Link fuel → CO₂ → infrared → warming.', [('Name another greenhouse gas.', 'Methane (CH₄) or water vapour.'), ('One way to reduce CO₂ emissions?', 'Use solar/wind energy; plant trees.')])
U3.M('q04', LC, 82, 'Which pair of processes are the reverse of each other?', ['photosynthesis and respiration', 'combustion and decay', 'respiration and decay', 'dissolving and combustion'], 'A',
     ['Step 1: photosynthesis: CO₂ + H₂O → glucose + O₂.', 'Step 2: respiration: glucose + O₂ → CO₂ + H₂O.', 'Step 3: they are reverse reactions.'],
     'Compare reactants and products.', [('Which needs sunlight?', 'Photosynthesis.'), ('Which releases energy?', 'Respiration.')])
U3.S('q05', LC, 82, 'What mass of CO₂ is produced when 32 g of methane burns completely? (C = 12, H = 1, O = 16)', '88 g',
     ['Step 1: CH₄ + 2O₂ → CO₂ + 2H₂O.', 'Step 2: n(CH₄) = 32/16 = 2.0 mol → n(CO₂) = 2.0 mol.', 'Step 3: m = 2.0 × 44 = 88 g.'],
     'Moles of C in = moles of CO₂ out.', [('Mass of CO₂ from 24 g of carbon?', '88 g.'), ('Mass of water from 32 g CH₄?', '72 g.')], accept=['88', '88 g'])

NIT = [
    U3.T('c03', 'The nitrogen cycle, step by step', 97,
         'Plants and animals need nitrogen to make **proteins**. Air is 78 % nitrogen, but N₂ has a very strong triple bond (N≡N), so most living things **cannot use N₂ directly**. Nitrogen must first be **fixed** — changed into ammonium or nitrate compounds.',
         '**Step 1 — Nitrogen fixation (N₂ → compounds).** (a) **Nitrogen-fixing bacteria**, some free in the soil and some in the **root nodules of legumes** (beans, peas, clover, chickpeas), turn N₂ into ammonium compounds. (b) **Lightning** makes N₂ and O₂ combine; the oxides dissolve in rain to form nitric acid, which reaches the soil as nitrates:',
         eq('N2(g) + O2(g) ->{lightning} 2NO(g)'), eq('2NO(g) + O2(g) -> 2NO2(g)'), eq('4NO2(g) + O2(g) + 2H2O(l) -> 4HNO3(aq)'),
         '(c) **Industry (Haber process)** makes ammonia for fertilisers: ' + ie('N2(g) + 3H2(g) <=>{Fe, 450 °C} 2NH3(g)') + '.',
         '**Step 2 — Nitrification.** **Nitrifying bacteria** in the soil oxidise ammonium to nitrite and then to nitrate: NH₄⁺ → NO₂⁻ → NO₃⁻.',
         '**Step 3 — Assimilation.** Plant roots absorb nitrates (and ammonium) and make **plant proteins**. Animals get nitrogen by **eating** plants.',
         '**Step 4 — Ammonification (decay).** Dead plants and animals, urine and droppings are broken down by **decomposers** (bacteria and fungi); the nitrogen in proteins becomes **ammonia / ammonium** again.',
         '**Step 5 — Denitrification.** **Denitrifying bacteria**, mainly in waterlogged soils with little air, turn nitrates back into **N₂ gas**, which returns to the air. The cycle is complete.',
         '**Correction:** the textbook says that when plants and animals die, “denitrifying bacteria convert the nitrogen in the proteins” into atmospheric nitrogen, and that “some plants” convert N₂. Proteins are first turned into ammonium by **decomposers**; denitrifying bacteria act on **nitrates**; and N₂ is fixed by **bacteria** living in the roots of legumes, not by the plants themselves.'),
    U3.ST('s02', 'Model: the nitrogen cycle (Fig. 3.11)', 98, 'co_ncycle',
          [('**Fixation:** bacteria (legume nodules), lightning and the Haber process turn N₂ into NH₄⁺ or NO₃⁻.', 'fix'),
           ('**Nitrification:** nitrifying bacteria oxidise NH₄⁺ → NO₂⁻ → NO₃⁻.', 'nitrify'),
           ('**Plants and animals:** roots absorb NO₃⁻ to make proteins; animals eat plants; death and waste return NH₄⁺ via decomposers.', 'plants'),
           ('**Denitrification:** denitrifying bacteria turn NO₃⁻ back into N₂.', 'denit')]),
    U3.TB('t02', 'The bacteria of the nitrogen cycle — how they differ', 97,
          ['Bacteria', 'Change they make', 'Where', 'Effect on soil fertility'],
          [['Nitrogen-fixing', 'N₂ → NH₄⁺ (ammonium compounds)', 'legume root nodules; soil', 'increases'], ['Decomposers (putrefying)', 'proteins, urea → NH₃ / NH₄⁺', 'dead matter, waste', 'returns N to soil'],
           ['Nitrifying', 'NH₄⁺ → NO₂⁻ → NO₃⁻', 'well-aired soil', 'increases (nitrate is the form most plants take up)'], ['Denitrifying', 'NO₃⁻ → N₂', 'waterlogged, airless soil', 'decreases']],
          'Fixing and nitrifying bacteria **add** usable nitrogen to the soil; denitrifying bacteria **remove** it. Farmers plough and drain soil to keep it aerated.'),
    U3.WK('w03', 'Worked example: why farmers rotate crops with beans', 97,
          'A farmer grows chickpeas one year and wheat the next. Explain the chemistry.',
          ['Chickpeas are legumes; their root nodules hold nitrogen-fixing bacteria.', 'The bacteria turn N₂ from the air into ammonium compounds that the plant uses.',
           'When the roots and leftover plants decay, decomposers and nitrifying bacteria release ammonium and nitrates into the soil.', 'The wheat then uses these nitrates — less fertiliser is needed.'],
          'Legumes fix nitrogen and enrich the soil.'),
    U3.WK('w04', 'Worked example: nitrogen content of fertilisers', 98,
          'Which supplies more nitrogen per kilogram: ammonium nitrate, NH₄NO₃, or urea, CO(NH₂)₂? (N = 14, H = 1, O = 16, C = 12)',
          [r'NH₄NO₃: \(M = 80\); N = 2 × 14 = 28 → \(\%\text{N} = \dfrac{28}{80} \times 100 = 35\%\).', r'Urea: \(M = 60\); N = 28 → \(\%\text{N} = \dfrac{28}{60} \times 100 = 46.7\%\).',
           'Urea supplies more nitrogen per kilogram.'],
          'Urea (46.7 % N vs 35 %)'),
    U3.CK('k03', 97, 'Which organisms return nitrogen to the air?', ['nitrifying bacteria', 'nitrogen-fixing bacteria', 'denitrifying bacteria', 'legumes'], 'C',
          'Denitrifying bacteria turn nitrates into N₂ gas.'),
    U3.CK('k04', 97, 'Why can plants not use atmospheric nitrogen directly?', ['N₂ is too rare', 'the N≡N triple bond is very strong and unreactive', 'N₂ is poisonous', 'N₂ is a liquid'], 'B',
          'N₂ is very unreactive because of its strong triple bond; it must be fixed first.'),
]
U3.M('q10', LN, 97, 'The conversion of ammonium ions to nitrates in the soil is called …', ['fixation', 'nitrification', 'denitrification', 'ammonification'], 'B',
     ['Step 1: NH₄⁺ → NO₂⁻ → NO₃⁻ is an oxidation.', 'Step 2: it is done by nitrifying bacteria.', 'Step 3: so it is nitrification.'],
     'Nitri-fication makes nitrates; de-nitrification destroys them.', [('Name for N₂ → NH₄⁺?', 'Nitrogen fixation.'), ('Name for proteins → NH₃?', 'Ammonification (decay).')])
U3.S('q11', LN, 98, 'Outline the main processes of the nitrogen cycle. (Review Q12)',
     'Fixation (bacteria, lightning, Haber) → nitrification (NH₄⁺ → NO₂⁻ → NO₃⁻) → assimilation by plants, feeding by animals → decay to ammonium by decomposers → denitrification of nitrates back to N₂.',
     ['Step 1: N₂ is fixed into ammonium/nitrates.', 'Step 2: nitrifying bacteria make nitrates.', 'Step 3: plants absorb nitrates and make proteins; animals eat plants.',
      'Step 4: death and waste → decomposers → ammonium.', 'Step 5: denitrifying bacteria → N₂ back to air.'],
     'Five words: fix, nitrify, absorb, decay, denitrify.', [('Which step involves lightning?', 'Fixation.'), ('Which step is helped by waterlogging?', 'Denitrification.')])
U3.S('q12', LN, 97, 'Write the three equations that show how lightning adds nitrates to the soil.', 'N₂ + O₂ → 2NO; 2NO + O₂ → 2NO₂; 4NO₂ + O₂ + 2H₂O → 4HNO₃',
     ['Step 1: lightning provides the energy to break N≡N: N₂ + O₂ → 2NO.', 'Step 2: NO reacts with more oxygen: 2NO + O₂ → 2NO₂.', 'Step 3: NO₂ dissolves in rain with oxygen: 4NO₂ + O₂ + 2H₂O → 4HNO₃.',
      'Step 4: HNO₃ reacts with minerals in soil to form nitrates.'],
     'Each equation must balance — count O atoms.', [('Colour of NO₂?', 'Reddish-brown.'), ('Which process makes ammonia in industry?', 'Haber process.')])
U3.TF('q13', LN, 97, 'Waterlogged soil loses nitrogen because denitrifying bacteria work best where there is little air.', True,
      ['Step 1: water fills the air spaces in soil.', 'Step 2: denitrifying bacteria thrive without oxygen.', 'Step 3: they convert nitrates to N₂, which escapes.'],
      'Drain and plough → keep nitrates.', [('Which bacteria need air?', 'Nitrifying bacteria.'), ('Effect of ploughing?', 'Aerates soil; helps nitrification.')])
U3.M('q14', LN, 98, 'Percentage of nitrogen in ammonium sulphate, (NH₄)₂SO₄ (M = 132), is …', ['10.6 %', '21.2 %', '35 %', '46.7 %'], 'B',
     ['Step 1: N atoms = 2 → 28 g.', 'Step 2: % N = 28/132 × 100.', 'Step 3: = 21.2 %.'],
     '% = (mass of N in formula ÷ M) × 100.', [('% N in NH₃?', '82.4 %.'), ('% N in KNO₃ (M = 101)?', '13.9 %.')])

SULF = [
    U3.T('c04', 'Extraction of sulphur: the Frasch process, step by step', 101,
         'Sulphur occurs **free** in underground deposits (Italy, Mexico, Japan, Poland, USA; in Eritrea at Marsa Fatuma and Erta Ale) and **combined** in ores such as pyrite FeS₂, zinc blende ZnS, galena PbS and chalcopyrite CuFeS₂ (Debarwa, Adi Nefas). Deep deposits are hard to mine by digging (loose sand, poisonous H₂S), so the sulphur is **melted underground and pushed up**.',
         '**Step 1 — Drill** a hole down to the deposit.',
         '**Step 2 — Insert three pipes, one inside another** (concentric).',
         '**Step 3 — Pump superheated water** (about 170 °C, kept liquid by high pressure) down the **outer, largest pipe**. Sulphur melts at about 115 °C, so it melts around the pipe.',
         '**Step 4 — Blow hot compressed air** down the **inner, smallest pipe**. It mixes with the molten sulphur and makes a light **froth**.',
         '**Step 5 — The froth of molten sulphur, water and air rises up the middle pipe** to the surface.',
         '**Step 6 — Collect and cool** in large tanks: the sulphur solidifies, about **99.5 % pure**, so it needs no further purification.',
         '**Why it works:** sulphur has a **low melting point** (below the temperature of superheated water), it is **insoluble in water** (so it is not washed away), and as a froth with air it is **light enough to be pushed up**.',
         '**Sulphur from ores:** roasting sulphide ores gives SO₂ directly, which is used to make sulphuric acid: ' + ie('4FeS2(s) + 11O2(g) -> 2Fe2O3(s) + 8SO2(g)') + '.'),
    U3.ST('s03', 'Model: the Frasch process (Fig. 3.12)', 101, 'co_frasch',
          [('**Outer pipe:** superheated water (≈ 170 °C, under pressure) melts the sulphur.', 'water'),
           ('**Inner pipe:** hot compressed air makes the molten sulphur froth.', 'air'),
           ('**Middle pipe:** molten sulphur + water + air rise to the surface, cool and solidify (≈ 99.5 % pure).', 'up')]),
    U3.TB('t03', 'The three pipes', 101,
          ['Pipe', 'What goes through it', 'Direction', 'Job'],
          [['Outer (largest)', 'superheated water ≈ 170 °C', 'down', 'melts the sulphur'], ['Inner (smallest)', 'hot compressed air', 'down', 'forces the molten sulphur up as a froth'],
           ['Middle', 'molten sulphur + water + air', 'up', 'carries the sulphur to the surface']]),
    U3.TB('t04', 'Allotropes of sulphur (Table 3.2)', 102,
          ['', 'Rhombic (α) sulphur', 'Monoclinic (β) sulphur', 'Plastic sulphur'],
          [['Stable', 'below 96 °C (room temperature)', 'above 96 °C', 'not stable — slowly becomes rhombic'], ['Colour', 'bright yellow', 'pale yellow', 'brown-amber, rubbery'],
           ['Crystal shape', 'octahedral (rhombic)', 'long needles', 'amorphous (no crystals)'], ['Melting point', '113 °C', '119 °C', '—'],
           ['Density', '2.07 g/cm³', '1.98 g/cm³', '—'], ['Particles', 'S₈ rings', 'S₈ rings, packed differently', 'long chains of S atoms'],
           ['How made', 'crystallise from CS₂ solution', 'cool molten sulphur slowly above 96 °C', 'pour boiling sulphur into cold water']],
          'Rhombic and monoclinic differ only in how the S₈ rings are packed; 96 °C is the **transition temperature** between them. (The textbook also gives 115 °C as “the” melting point — that is an average; the two crystalline forms melt at 113 °C and 119 °C.)'),
    U3.WK('w05', 'Worked example: Activity 3.11 — making monoclinic sulphur', 102,
          'Powdered sulphur is heated slowly until it melts, then cooled; when a crust forms it is pierced and the liquid is poured off. What do you see and why?',
          ['Heating: the yellow powder melts to a runny amber liquid (at about 115–119 °C).', 'Cooling: a crust forms; under it are long, thin, pale-yellow **needle** crystals — monoclinic sulphur (they form above 96 °C).',
           'At room temperature, over a day or so, the needles turn opaque and break up into tiny rhombic crystals — rhombic is the stable form below 96 °C.'],
          'Needles of monoclinic sulphur, which slowly change to rhombic.'),
    U3.CK('k05', 101, 'In the Frasch process the hot compressed air is used to …', ['melt the sulphur', 'oxidise the sulphur', 'force molten sulphur up as a froth', 'cool the sulphur'], 'C',
          'Superheated water melts it; compressed air makes a light froth that rises up the middle pipe.'),
    U3.CK('k06', 102, 'Rhombic and monoclinic sulphur differ in …', ['the number of atoms per molecule', 'the packing of S₈ molecules in the crystal', 'the element they contain', 'their chemical reactions'], 'B',
          'Both are made of S₈ rings; only the crystal packing differs, which changes shape, density and melting point.'),
]
U3.M('q20', LS, 101, 'Superheated water is used in the Frasch process to … (Review Q5)', ['dissolve sulphur', 'melt sulphur', 'oxidise sulphur', 'cool sulphur'], 'B',
     ['Step 1: sulphur is insoluble in water, so it cannot dissolve.', "Step 2: superheated water (≈ 170 °C) is hotter than sulphur's melting point (≈ 115 °C).", 'Step 3: so it melts the sulphur.'],
     'Water: melts. Air: lifts.', [('Why must the water be under pressure?', 'To stay liquid above 100 °C.'), ('Purity of Frasch sulphur?', 'About 99.5 %.')])
U3.S('q21', LS, 102, 'Explain the difference between rhombic sulphur and monoclinic sulphur. (Exercise Q1)',
     'Both are S₈ molecules, packed differently. Rhombic: stable below 96 °C, bright yellow octahedral crystals, m.p. 113 °C, density 2.07 g/cm³. Monoclinic: stable above 96 °C, pale yellow needles, m.p. 119 °C, density 1.98 g/cm³.',
     ['Step 1: same element and same molecule (S₈).', 'Step 2: different crystal packing.', 'Step 3: compare stability, shape, colour, m.p., density.'],
     'Allotropes = same element, different structure.', [('Transition temperature?', '96 °C.'), ('Name the amorphous allotrope.', 'Plastic sulphur.')])
U3.S('q22', LS, 103, 'What is plastic sulphur and how is it made? (Exercise Q3)', 'An amorphous, rubbery form of sulphur made of long chains of S atoms, made by pouring boiling sulphur into cold water; it slowly turns into rhombic sulphur.',
     ['Step 1: boil sulphur; the S₈ rings break and form long chains.', 'Step 2: pour it into cold water — the chains are frozen before they can form rings.', 'Step 3: rubbery solid; over time it hardens to rhombic.'],
     'Sudden cooling traps the chains.', [('Is plastic sulphur crystalline?', 'No, amorphous.'), ('What does it change into?', 'Rhombic sulphur.')])
U3.TF('q23', LS, 101, 'Sulphur can be extracted by the Frasch process because it has a low melting point and does not dissolve in water.', True,
      ['Step 1: m.p. ≈ 115 °C < 170 °C water.', 'Step 2: insoluble — it is not carried away in solution.', 'Step 3: both are needed.'],
      'Physical properties make the method possible.', [('Could the method extract NaCl?', 'No — NaCl would dissolve in the water.'), ('Name a sulphide ore.', 'Pyrite, FeS₂.')])
U3.S('q24', LS, 100, 'Write the balanced equation, with state symbols, for roasting pyrite (FeS₂) in air.', '4FeS₂(s) + 11O₂(g) → 2Fe₂O₃(s) + 8SO₂(g)',
     ['Step 1: products: iron(III) oxide and sulphur dioxide.', 'Step 2: balance Fe and S: 4FeS₂ → 2Fe₂O₃ + 8SO₂.', 'Step 3: O on the right = 6 + 16 = 22 → 11O₂.'],
     'Balance Fe, then S, then O last.', [('Roasting ZnS?', '2ZnS + 3O₂ → 2ZnO + 2SO₂.'), ('Burning sulphur?', 'S + O₂ → SO₂.')])

ACID = [
    U3.T('c05', 'The Contact process for sulphuric acid, step by step', 107,
         'Sulphuric acid is made in larger amounts than any other chemical. The **Contact process** gives concentrated, very pure acid in high yield. Its name comes from Stage 2, where the gases react **in contact with** the surface of a solid catalyst.',
         '**Stage 1 — Make SO₂.** Burn sulphur in dry air (or roast sulphide ores):',
         eq('S(s) + O2(g) -> SO2(g)'),
         'The gas is **purified** (dust removed, dried) because impurities, especially dust and arsenic compounds, would **poison the catalyst**.',
         '**Stage 2 — Convert SO₂ to SO₃** (the key step). The reaction is **reversible** and **exothermic**:',
         eq('2SO2(g) + O2(g) <=>{V2O5, 450 °C} 2SO3(g)', r'\Delta H = -197\ \text{kJ}'),
         '**Conditions:** catalyst **vanadium(V) oxide, V₂O₅**; temperature **about 450 °C**; pressure **1–2 atm**; excess air. About 99 % conversion is reached over several catalyst beds.',
         '**Stage 3 — Absorb SO₃** in **98 % sulphuric acid** to form **oleum** (fuming sulphuric acid):',
         eq('SO3(g) + H2SO4(l) -> H2S2O7(l)'),
         '**Stage 4 — Dilute the oleum** carefully with water to give 98 % acid:',
         eq('H2S2O7(l) + H2O(l) -> 2H2SO4(l)'),
         '**Why not SO₃ straight into water?** ' + ie('SO3(g) + H2O(l) -> H2SO4(l)') + ' is so exothermic that the water boils and a **fine mist** of acid droplets forms, which is hard to condense and escapes.',
         '**Correction:** the textbook prints Stage 2 as “2SO₂ + O₂ → SO₃”; it must be **2SO₃** on the right (S: 2 = 2, O: 6 = 6) with a reversible arrow ⇌.'),
    U3.ST('s04', 'Model: the Contact process (Fig. 3.15)', 108, 'co_contact',
          [('**Burner:** S + O₂ → SO₂; then the gas is cleaned and dried so the catalyst is not poisoned.', 'burn'),
           ('**Converter:** 2SO₂ + O₂ ⇌ 2SO₃ over V₂O₅ at about 450 °C, 1–2 atm.', 'conv'),
           ('**Absorber:** SO₃ dissolves in 98 % H₂SO₄ → oleum H₂S₂O₇.', 'abs'),
           ('**Diluter:** H₂S₂O₇ + H₂O → 2H₂SO₄; part of the acid goes back to the absorber.', 'dil')]),
    U3.TB('t05', 'Why these conditions? (2SO₂ + O₂ ⇌ 2SO₃, ΔH negative)', 108,
          ['Condition', 'Effect on yield', 'Effect on rate', 'Choice'],
          [['Temperature', 'low T favours SO₃ (exothermic)', 'low T is too slow', '≈ 450 °C — a compromise'],
           ['Pressure', 'high P favours SO₃ (3 mol gas → 2 mol)', 'faster', '1–2 atm: yield is already ≈ 99 %, high pressure is costly'],
           ['Catalyst V₂O₅', 'none (does not shift equilibrium)', 'much faster', 'used; cheaper and less easily poisoned than platinum'],
           ['Excess O₂ (air)', 'pushes equilibrium to the right', '—', 'used']]),
    U3.T('c06', 'Properties of sulphuric acid, with equations', 108,
         '**Physical:** colourless, oily, dense (1.84 g/cm³ for 98 %), high boiling point (≈ 338 °C); it mixes with water giving out **a lot of heat** — **always add acid to water, slowly, never water to acid**.',
         '**1 · Dilute acid is a strong, dibasic acid.** It turns blue litmus red and reacts with metals above hydrogen, with bases and with carbonates:',
         eq('Zn(s) + H2SO4(aq) -> ZnSO4(aq) + H2(g)'), eq('Mg(s) + H2SO4(aq) -> MgSO4(aq) + H2(g)'),
         'Two H⁺ per molecule → two kinds of salt: the **normal** salt (sulphate) and the **acid** salt (hydrogensulphate):',
         eq('2NaOH(aq) + H2SO4(aq) -> Na2SO4(aq) + 2H2O(l)'), eq('NaOH(aq) + H2SO4(aq) -> NaHSO4(aq) + H2O(l)'),
         '**2 · Concentrated acid is a dehydrating agent** — it removes water, even the H and O atoms of compounds. Sugar turns into a black column of carbon with steam:',
         eq('C12H22O11(s) ->{conc. acid} 12C(s) + 11H2O(g)'),
         'Blue copper(II) sulphate crystals turn white: ' + ie('CuSO4.5H2O(s) ->{conc. acid} CuSO4(s) + 5H2O(l)') + '.',
         '**3 · Hot concentrated acid is an oxidising agent** (it is reduced to SO₂):',
         eq('Cu(s) + 2H2SO4(l) -> CuSO4(aq) + SO2(g) + 2H2O(l)'), eq('C(s) + 2H2SO4(l) -> CO2(g) + 2SO2(g) + 2H2O(g)'), eq('S(s) + 2H2SO4(l) -> 3SO2(g) + 2H2O(g)'),
         '**4 · It is non-volatile,** so it drives the more volatile acids out of their salts:',
         eq('NaCl(s) + H2SO4(l) -> NaHSO4(s) + HCl(g)'), eq('NaNO3(s) + H2SO4(l) -> NaHSO4(s) + HNO3(g)'),
         '**Corrections:** sugar (sucrose) is **C₁₂H₂₂O₁₁** (the textbook prints C₁₂O₂₂H₁₁); copper and carbon each need **two** H₂SO₄ in their equations, as written above.'),
    U3.TB('t06', 'Dilute and concentrated sulphuric acid — how they differ', 109,
          ['', 'Dilute H₂SO₄', 'Concentrated H₂SO₄ (98 %)'],
          [['Main particles', 'H⁺(aq), SO₄²⁻(aq), water', 'mostly H₂SO₄ molecules'], ['Acts as', 'a strong acid', 'dehydrating and oxidising agent'],
           ['With zinc', 'H₂ given off', 'SO₂ given off (when hot)'], ['With copper', 'no reaction', 'CuSO₄ + SO₂ (hot)'], ['With sugar', 'no charring', 'chars it to carbon']]),
    U3.T('c07', 'Sulphates: preparation, test and uses', 110,
         '**Sulphates** are salts of sulphuric acid in which the hydrogen is replaced by a metal (or NH₄⁺). Choose the method by solubility.',
         '**Method 1 — Acid + metal.** (a) Dilute acid with a metal above hydrogen: ' + ie('Zn(s) + H2SO4(aq) -> ZnSO4(aq) + H2(g)') + '. (b) Hot concentrated acid with copper: ' + ie('Cu(s) + 2H2SO4(l) -> CuSO4(aq) + SO2(g) + 2H2O(l)') + '.',
         '**Method 2 — Dilute acid + oxide, hydroxide or carbonate:** ' + ie('CuO(s) + H2SO4(aq) -> CuSO4(aq) + H2O(l)') + '; ' + ie('MgCO3(s) + H2SO4(aq) -> MgSO4(aq) + H2O(l) + CO2(g)') + '.',
         '**Method 3 — Double decomposition (precipitation)** for the insoluble sulphates BaSO₄ and PbSO₄ (CaSO₄ is only slightly soluble):',
         eq('BaCl2(aq) + H2SO4(aq) -> BaSO4(s) + 2HCl(aq)'), eq('Ba^2+(aq) + SO4^2-(aq) -> BaSO4(s)'),
         '**Test for a sulphate (Activity 3.13):** add dilute HCl, then barium chloride solution. A **white precipitate** of BaSO₄ shows sulphate ions. (The HCl removes carbonate and sulphite, which would also give white precipitates.)',
         '**Uses of sulphuric acid:** more than half goes into **fertilisers** — ammonium sulphate (NH₄)₂SO₄ and superphosphate Ca(H₂PO₄)₂ — and also into detergents, paints and pigments, fibres and plastics, as a dehydrating agent, and as the electrolyte in car (lead–acid) batteries.',
         '**Correction:** the formula of calcium dihydrogenphosphate in superphosphate is **Ca(H₂PO₄)₂** (Ca²⁺ with two H₂PO₄⁻), not Ca(H₂PO₄)₃.'),
    U3.TB('t07', 'Common sulphates', 110,
          ['Sulphate', 'Formula', 'Soluble?', 'Use'],
          [['Ammonium sulphate', '(NH₄)₂SO₄', 'yes', 'nitrogen fertiliser'], ['Copper(II) sulphate', 'CuSO₄·5H₂O (blue)', 'yes', 'fungicide; anhydrous (white) tests for water'],
           ['Magnesium sulphate', 'MgSO₄·7H₂O (Epsom salt)', 'yes', 'medicine'], ['Calcium sulphate', 'CaSO₄·2H₂O (gypsum)', 'slightly', 'plaster, cement'],
           ['Barium sulphate', 'BaSO₄', 'no', 'X-ray “barium meal”'], ['Iron(II) sulphate', 'FeSO₄·7H₂O (green)', 'yes', 'treating anaemia, ink']]),
    U3.WK('w06', 'Worked example: mass of acid from sulphur', 107,
          'What mass of H₂SO₄ can be made from 64 tonnes of sulphur by the Contact process (100 % yield)? (S = 32, H₂SO₄ = 98)',
          ['Follow the sulphur atom: S → SO₂ → SO₃ → H₂S₂O₇ → H₂SO₄; overall **1 mol S gives 1 mol H₂SO₄**.', r'\(n(\text{S}) = 64 \times 10^{6}\ \text{g} / 32 = 2.0 \times 10^{6}\ \text{mol}\)',
           r'\(m(\text{H}_2\text{SO}_4) = 2.0 \times 10^{6} \times 98\ \text{g} = 196\ \text{tonnes}\)'],
          '196 tonnes'),
    U3.WK('w07', 'Worked example: oxidising or reducing agent? (Exercise Q4)', 111,
          'State the role of sulphur dioxide in (a) 2HNO₃ + SO₂ → H₂SO₄ + 2NO₂, (b) 2H₂S + SO₂ → 3S + 2H₂O.',
          ['(a) S goes from +4 in SO₂ to +6 in H₂SO₄ — it is oxidised, so SO₂ is the **reducing agent** (HNO₃ is reduced to NO₂).',
           '(b) S in SO₂ goes from +4 to 0 — it is reduced, so SO₂ is the **oxidising agent** (S in H₂S goes from −2 to 0).',
           eq('2H2S(g) + SO2(g) -> 3S(s) + 2H2O(l)')],
          '(a) reducing agent; (b) oxidising agent'),
    U3.CK('k07', 108, 'The catalyst in the Contact process is …', ['iron', 'platinum only', 'vanadium(V) oxide', 'nickel'], 'C',
          'V₂O₅ is used. (Iron is the Haber process catalyst; platinum works but is expensive and easily poisoned.)'),
    U3.CK('k08', 109, 'When concentrated H₂SO₄ is added to sugar, the acid acts as …', ['an acid', 'a dehydrating agent', 'a reducing agent', 'a catalyst'], 'B',
          'It removes H and O as water, leaving black carbon: C₁₂H₂₂O₁₁ → 12C + 11H₂O.'),
    U3.RM('r01', 'Tips and common mistakes', 107,
          'Remember the order: Burn, Clean, Convert, Absorb, Dilute.',
          'SO₃ is absorbed in concentrated acid, not in water.',
          'Diluting: always add ACID to WATER, slowly, with stirring.'),
]
U3.M('q30', LH, 108, 'In the Contact process SO₃ is absorbed in …', ['water', 'dilute H₂SO₄', '98 % H₂SO₄', 'NaOH solution'], 'C',
     ['Step 1: SO₃ + water makes an acid mist.', 'Step 2: so it is absorbed in 98 % acid → oleum.', 'Step 3: oleum is then diluted.'],
     'Absorb in acid, then dilute.', [('Formula of oleum?', 'H₂S₂O₇.'), ('Equation for diluting oleum?', 'H₂S₂O₇ + H₂O → 2H₂SO₄.')])
U3.S('q31', LH, 108, 'Explain why a temperature of about 450 °C is used in the converter even though a lower temperature gives a higher yield.',
     'The forward reaction is exothermic, so lower temperatures favour SO₃, but then the rate is too slow even with the catalyst; 450 °C gives a good yield at a fast rate (a compromise).',
     ['Step 1: ΔH is negative → low T shifts equilibrium right (more SO₃).', 'Step 2: low T → slow reaction; the catalyst needs about 400–450 °C to work well.', 'Step 3: 450 °C is a compromise between yield and rate.'],
     'Yield vs rate — say both.', [('Why only 1–2 atm?', 'Yield is already ~99 %; higher pressure costs more.'), ('Effect of the catalyst on yield?', 'None — it only speeds up the reaction.')])
U3.S('q32', LH, 109, 'Write balanced equations with state symbols for the reaction of hot concentrated sulphuric acid with (a) copper, (b) carbon.',
     '(a) Cu(s) + 2H₂SO₄(l) → CuSO₄(aq) + SO₂(g) + 2H₂O(l); (b) C(s) + 2H₂SO₄(l) → CO₂(g) + 2SO₂(g) + 2H₂O(g)',
     ['Step 1: the acid is reduced to SO₂ (S: +6 → +4).', 'Step 2: (a) Cu → Cu²⁺ (gives 2 e⁻) — one H₂SO₄ is reduced, another forms CuSO₄ → 2H₂SO₄.',
      'Step 3: (b) C → CO₂ (gives 4 e⁻) — two S atoms must be reduced → 2H₂SO₄, 2SO₂.', 'Step 4: balance H and O with water.'],
     'Electrons lost by the element = electrons gained by S (+6 → +4: 2 each).', [('Hot conc. acid with sulphur?', 'S + 2H₂SO₄ → 3SO₂ + 2H₂O.'), ('Gas produced in all three?', 'SO₂.')])
U3.M('q33', LH, 110, 'Which method is used to prepare barium sulphate?', ['Ba + dilute H₂SO₄', 'BaCO₃ + H₂SO₄', 'precipitation from BaCl₂(aq) and a sulphate solution', 'heating barium with sulphur'], 'C',
     ['Step 1: BaSO₄ is insoluble.', 'Step 2: insoluble salts are made by double decomposition.', 'Step 3: BaCl₂(aq) + H₂SO₄(aq) → BaSO₄(s) + 2HCl(aq); filter, wash, dry.'],
     'Insoluble salt → precipitation.', [('Other insoluble sulphate?', 'PbSO₄.'), ('Colour of BaSO₄?', 'White.')])
U3.S('q34', LH, 110, 'Describe a test for sulphate ions and write the ionic equation.', 'Add dilute HCl then BaCl₂(aq): a white precipitate of BaSO₄ forms. Ba²⁺(aq) + SO₄²⁻(aq) → BaSO₄(s).',
     ['Step 1: acidify with dilute HCl (removes carbonate/sulphite).', 'Step 2: add barium chloride solution.', 'Step 3: white precipitate → sulphate present.'],
     'Acidify first, or carbonates give a false result.', [('Test for chloride ions?', 'Dilute HNO₃ then AgNO₃ — white AgCl.'), ('Test for CO₂?', 'Limewater turns milky.')])
U3.S('q35', LH, 107, 'What mass of sulphuric acid can be made from 8.0 kg of sulphur? (S = 32, H₂SO₄ = 98)', '24.5 kg',
     ['Step 1: overall S → H₂SO₄ (1 : 1).', 'Step 2: n(S) = 8000/32 = 250 mol.', 'Step 3: m = 250 × 98 = 24 500 g = 24.5 kg.'],
     'Follow one S atom through all four stages.', [('From 1 tonne of S?', '3.06 tonnes.'), ('Mass of SO₂ from 8.0 kg S?', '16 kg.')], accept=['24.5', '24.5 kg', '24500 g'])
U3.TF('q36', LH, 109, 'Dilute sulphuric acid reacts with copper to give hydrogen.', False,
      ['Step 1: copper is below hydrogen in the activity series.', 'Step 2: dilute acid cannot oxidise it — no reaction.', 'Step 3: only hot concentrated acid reacts, giving SO₂, not H₂.'],
      'Dilute = acid behaviour; hot concentrated = oxidising behaviour.', [('Does zinc react with dilute H₂SO₄?', 'Yes, H₂ given off.'), ('Products of Cu with hot conc. H₂SO₄?', 'CuSO₄, SO₂, H₂O.')])

U = {'chem11-u2': (U2, {'co_brine': 'brine', 'co_cuso4': 'cuso4', 'co_plating': 'plating', 'co_refine': 'refine', 'co_series': 'series'}),
     'chem11-u3': (U3, {'co_ccycle': 'ccycle', 'co_ncycle': 'ncycle', 'co_frasch': 'frasch', 'co_contact': 'contact'})}
BLOCKS = [('chem11-u2-l2-2', 'chem11-u2-c13', AQ), ('chem11-u2-l2-2', 'chem11-u2-c14', APP), ('chem11-u2-l2-2', 'chem11-u2-c15', FAR),
          ('chem11-u3-l3-2', 'chem11-u3-cm-r01', CARB), ('chem11-u3-l3-3', 'chem11-u3-c09', NIT), ('chem11-u3-l3-4', 'chem11-u3-c10', SULF),
          ('chem11-u3-l3-4', 'chem11-u3-c12', ACID)]
GLOSSARY = {
    'chem11-u2': [('Amalgam', 'An alloy of a metal with mercury, e.g. sodium amalgam NaHg formed at a mercury cathode.', 54),
                  ('Anode mud', 'The insoluble impurities (Ag, Au, Pt) that collect below the anode in copper refining.', 57),
                  ('Equivalent mass', 'Atomic mass ÷ charge on the ion (A/z); the mass deposited by one mole of electrons.', 59),
                  ('Faraday constant', 'The charge on one mole of electrons, F = 96 500 C/mol.', 59)],
    'chem11-u3': [('Carbon cycle', 'The circulation of carbon between the air, living things, oceans and fuels, which keeps the CO₂ in air roughly constant.', 82),
                  ('Nitrogen fixation', 'Conversion of N₂ from the air into ammonium or nitrate compounds (by bacteria, lightning or the Haber process).', 97),
                  ('Nitrification', 'Oxidation of ammonium to nitrite and nitrate by nitrifying bacteria in the soil.', 97),
                  ('Denitrification', 'Conversion of nitrates back into nitrogen gas by denitrifying bacteria.', 97),
                  ('Frasch process', 'Extraction of underground sulphur by melting it with superheated water and forcing it up with compressed air.', 101),
                  ('Oleum', 'Fuming sulphuric acid, H₂S₂O₇, formed when SO₃ dissolves in concentrated H₂SO₄.', 108),
                  ('Transition temperature', 'The temperature (96 °C for sulphur) at which one allotrope changes into the other.', 101)],
}

FIXES = [
    ('chem11-u2-c13', 'body', ['In the electrolysis of aqueous solutions, not only the electrolyte but also water dissociates (slightly), so the ions from water (H⁺ and OH⁻) compete with the ions of the electrolyte at the electrodes.',
                               'For example, an aqueous solution of NaCl contains four ions: Na⁺ and Cl⁻ from sodium chloride, and H⁺ and OH⁻ from water.',
                               'Which ion is discharged depends on three factors: (1) its position in the electrochemical series, (2) its relative concentration, (3) the nature of the electrode.',
                               'Keeping the other factors constant, the cation that most readily accepts electrons is discharged: with Na⁺ and H⁺ present, H⁺ is discharged; with Cu²⁺ and H⁺ present, Cu²⁺ is discharged.']),
    ('chem11-u2-c14', 'body', ['Electrolysis has four main applications: (1) electroplating, (2) preparation of gases (H₂, O₂, Cl₂) and extraction of reactive metals (Na, Mg, Al), (3) purification (refining) of metals such as copper, (4) manufacture of sodium hydroxide from brine.',
                               'Activity 2.7: dissolve about three teaspoons of copper(II) chloride in 150 mL of water in a 250 mL beaker, dip in two carbon rods and connect a 6 V battery. Do not touch bare wires or short-circuit the battery.']),
    ('chem11-u3-c06', 'body', ['**Carbon dioxide** is a colourless gas present in the air at about 0.04 % by volume (it was about 0.03 % fifty years ago).',
                               'Human beings inhale oxygen from the air and exhale carbon dioxide.', 'During photosynthesis, plants use carbon dioxide from the atmosphere and give off oxygen.',
                               '**Carbon dioxide** is an important chemical link between the plant and the animal world.']),
]
