r"""Grade 9: 2.1.5 electrical neutrality, 3.2.3 significance of symbols and formulas, 3.4.2 writing and balancing equations,
3.4.3 qualitative and quantitative meaning of a balanced equation."""
from co import Unit, eq, ie

# ====================================================================================== Unit 2 · 2.1.5
U2 = Unit('chem9-u2')
L215 = '2.1.5 Electrical neutrality of an atom'

NEUTRAL = [
    U2.T('c01', '2.1.5 Electrical neutrality of an atom, step by step', 50,
         'An atom contains charged particles, yet a whole atom has **no overall charge**. We say it is **electrically neutral**. Here is why, one step at a time.',
         '**Step 1 — Know the three charges.** A proton carries **+1**, an electron carries **−1** and a neutron carries **0**. The proton and electron charges are **equal in size and opposite in sign**.',
         '**Step 2 — Count the protons.** The number of protons is the **atomic number Z**. Sodium has Z = 11, so it has 11 protons → total positive charge **+11**.',
         '**Step 3 — Count the electrons.** In a neutral atom the number of electrons **equals** the number of protons. Sodium has 11 electrons → total negative charge **−11**.',
         r'**Step 4 — Add the charges.** \((+11) + (-11) = 0\). The charges cancel exactly, so the atom is neutral.',
         '**Step 5 — Ignore the neutrons for charge.** Neutrons add mass but no charge, so the number of neutrons never changes the overall charge.',
         r'**General rule:** overall charge = (number of protons) − (number of electrons). For a neutral atom: \(p = e = Z\).',
         '**What breaks neutrality?** Only **electrons** move in chemical reactions. If an atom **loses** electrons it becomes a **positive ion** (more protons than electrons); if it **gains** electrons it becomes a **negative ion**. The protons (and so the element) never change.'),
    U2.TB('t01', 'The three particles and their charges', 50,
          ['Particle', 'Where it is', 'Relative charge', 'Relative mass', 'Effect on overall charge'],
          [['Proton (p⁺)', 'nucleus', '+1', '1', 'adds +1 each'],
           ['Electron (e⁻)', 'shells around the nucleus', '−1', '1/1840 (almost 0)', 'adds −1 each'],
           ['Neutron (n)', 'nucleus', '0', '1', 'no effect']]),
    U2.SS('s01', 'Model: sodium atom vs sodium ion', 50, 'co_neutral',
          [('atom', 'Na atom', '11 protons (+11) and 11 electrons (−11): total 0 → **neutral**.'),
           ('ion', 'Na⁺ ion', 'One outer electron is lost: 11 protons (+11), 10 electrons (−10): total **+1** → a positive ion, Na⁺.')],
          'Slide between the atom and the ion and compare the charge count.'),
    U2.TB('t02', 'Activity 2.5 completed: charge count for ten atoms', 50,
          ['Atom (Z)', 'Total charge of protons', 'Total charge of electrons', 'Overall charge'],
          [['H (1)', '+1', '−1', '0'], ['He (2)', '+2', '−2', '0'], ['C (6)', '+6', '−6', '0'], ['O (8)', '+8', '−8', '0'], ['Ne (10)', '+10', '−10', '0'],
           ['Na (11)', '+11', '−11', '0'], ['Mg (12)', '+12', '−12', '0'], ['Si (14)', '+14', '−14', '0'], ['Cl (17)', '+17', '−17', '0'], ['Ar (18)', '+18', '−18', '0']],
          '**Result:** every overall charge is zero. **Explanation:** in each neutral atom the number of protons equals the number of electrons, and their charges are equal and opposite. (The mass number A is not needed for the charge — it only tells you protons + neutrons.)'),
    U2.TB('t03', 'Neutral atom, positive ion, negative ion: how they differ', 50,
          ['', 'Neutral atom', 'Positive ion (cation)', 'Negative ion (anion)'],
          [['Protons vs electrons', 'p = e', 'p > e', 'p < e'],
           ['How it forms', '—', 'loses electron(s)', 'gains electron(s)'],
           ['Overall charge', '0', '+ (number lost)', '− (number gained)'],
           ['Example', 'Na: 11 p, 11 e', 'Na⁺: 11 p, 10 e', 'Cl⁻: 17 p, 18 e'],
           ['Same element?', '—', 'yes — protons unchanged', 'yes — protons unchanged']]),
    U2.WK('w01', 'Worked example: is it neutral?', 50,
          'A magnesium atom has atomic number 12 and mass number 24. (a) How many protons, electrons and neutrons does it have? (b) Show that it is electrically neutral.',
          ['Protons = Z = **12**.', 'Neutral atom → electrons = protons = **12**.', 'Neutrons = A − Z = 24 − 12 = **12**.',
           r'Charge: \(12 \times (+1) + 12 \times (-1) + 12 \times 0 = +12 - 12 + 0 = 0\).'],
          '12 p, 12 e, 12 n; overall charge 0 → neutral.'),
    U2.WK('w02', 'Worked example: atom or ion?', 50,
          'A particle has 17 protons, 18 neutrons and 18 electrons. (a) What is its overall charge? (b) Name it and write its symbol. (c) What is its mass number?',
          ['Overall charge = protons − electrons = 17 − 18 = **−1**.', '17 protons → atomic number 17 → the element is **chlorine**.',
           'It has one extra electron → it is the **chloride ion, Cl⁻** (not a neutral atom).', 'Mass number = protons + neutrons = 17 + 18 = **35** (electrons are not counted).'],
          'Charge −1; chloride ion Cl⁻; A = 35.'),
    U2.WK('w03', 'Worked example: working backwards from an ion', 50,
          'An aluminium ion, Al³⁺, has 10 electrons. How many protons does it have, and how many electrons does a neutral aluminium atom have?',
          ['The charge +3 means there are 3 more protons than electrons.', 'Protons = 10 + 3 = **13** (so Z = 13).',
           'A neutral Al atom has electrons = protons = **13**; it lost 3 electrons to become Al³⁺.'],
          '13 protons; the neutral atom has 13 electrons.'),
    U2.CK('k01', 50, 'Why is an atom electrically neutral?',
          ['It has no charged particles', 'Its number of neutrons equals its number of protons', 'Its number of protons equals its number of electrons', 'Its electrons are in the nucleus'], 'C',
          'Protons (+1) and electrons (−1) have equal and opposite charges; in a neutral atom there are equally many of each, so the charges cancel. Neutrons have no charge, so their number does not matter.'),
    U2.CK('k02', 50, 'A particle has 20 protons and 18 electrons. It is …',
          ['a neutral calcium atom', 'a Ca²⁺ ion', 'a Ca²⁻ ion', 'an argon atom'], 'B',
          '20 protons → calcium. Charge = 20 − 18 = +2 → Ca²⁺. It is not argon: the element is fixed by the protons, not the electrons.'),
    U2.RM('r01', 'Tips and common mistakes', 50,
          'Charge = protons − electrons. Mass number = protons + neutrons. Do not mix the two.',
          'Neutrons never affect the charge.',
          'The **element** is decided by the number of **protons** only. Na⁺ is still sodium.',
          'A positive ion has **lost** electrons (not gained protons).'),
]

U2.M('q01', L215, 50, 'The overall charge of an atom with 8 protons, 8 neutrons and 8 electrons is …', ['+8', '−8', '0', '+16'], 'C',
     ['Step 1: positive charge = 8 × (+1) = +8.', 'Step 2: negative charge = 8 × (−1) = −8.', 'Step 3: neutrons add 0.', 'Step 4: total = +8 − 8 = 0, so the atom is neutral.'],
     'Charge = protons − electrons; neutrons do not count.', [('Charge of a particle with 8 protons and 10 electrons?', '−2 (the oxide ion O²⁻).'), ('Charge of 11 protons and 10 electrons?', '+1 (Na⁺).')])
U2.S('q02', L215, 50, 'Explain, using numbers, why a chlorine atom (Z = 17) is electrically neutral.',
     'It has 17 protons (+17) and 17 electrons (−17); +17 + (−17) = 0, so there is no overall charge.',
     ['Step 1: Z = 17 → 17 protons → +17.', 'Step 2: a neutral atom has as many electrons as protons → 17 electrons → −17.', 'Step 3: add: +17 − 17 = 0.',
      'Step 4: equal and opposite charges cancel, so the atom is neutral.'],
     'Always give both totals and the sum.', [('Do the same for argon (Z = 18).', '+18 and −18 → 0.'), ('Do the same for helium (Z = 2).', '+2 and −2 → 0.')])
U2.F('q03', L215, 50, 'In a neutral atom the number of ______ is equal to the number of protons.', 'electrons', ['neutrons', 'electrons', 'nucleons', 'shells'],
     ['Step 1: only protons and electrons carry charge.', 'Step 2: for the charges to cancel there must be equal numbers of them.', 'Step 3: so electrons = protons.'],
     'Neutrons can be any number — they have no charge.', [('Which particle has no charge?', 'The neutron.'), ('Which number tells you the protons?', 'The atomic number Z.')])
U2.M('q04', L215, 50, 'A particle has 12 protons, 12 neutrons and 10 electrons. Which statement is correct?',
     ['It is a neutral magnesium atom', 'It is a Mg²⁺ ion', 'It is a neon atom', 'Its mass number is 34'], 'B',
     ['Step 1: 12 protons → magnesium.', 'Step 2: charge = 12 − 10 = +2 → Mg²⁺.', 'Step 3: mass number = 12 + 12 = 24 (not 34; electrons are not counted).'],
     'Find the element from the protons first, then the charge.', [('Same question for 16 p, 16 n, 18 e.', 'S²⁻ ion, mass number 32.'), ('Same for 3 p, 4 n, 2 e.', 'Li⁺ ion, mass number 7.')])
U2.S('q05', L215, 50, 'An oxide ion is O²⁻. Oxygen has Z = 8. How many protons and electrons does the ion have?', '8 protons and 10 electrons.',
     ['Step 1: Z = 8 → 8 protons (always, for oxygen).', 'Step 2: charge −2 → 2 more electrons than protons.', 'Step 3: electrons = 8 + 2 = 10.'],
     'Negative ion → add electrons; positive ion → subtract.', [('Electrons in F⁻ (Z = 9)?', '10.'), ('Electrons in K⁺ (Z = 19)?', '18.')])
U2.TF('q06', L215, 50, 'When a sodium atom becomes a sodium ion, Na⁺, it gains one proton.', False,
      ['Step 1: in chemical changes the nucleus does not change, so the number of protons stays 11.', 'Step 2: the atom loses one electron (11 → 10).',
       'Step 3: 11 − 10 = +1, which is why the ion is Na⁺.'],
      'Ions form by losing or gaining electrons only.', [('How does Cl become Cl⁻?', 'It gains one electron.'), ('How does Ca become Ca²⁺?', 'It loses two electrons.')])
U2.M('q07', L215, 50, 'Which pair has the same number of electrons?', ['Na and Na⁺', 'Na⁺ and Ne', 'Cl and Ar', 'O and O²⁻'], 'B',
     ['Step 1: Na⁺ has 11 − 1 = 10 electrons.', 'Step 2: Ne (Z = 10) has 10 electrons.', 'Step 3: the others differ: Na 11 vs Na⁺ 10; Cl 17 vs Ar 18; O 8 vs O²⁻ 10.'],
     'Work out the electron number of each particle before comparing.', [('Which ion has the same electrons as argon: K⁺ or Na⁺?', 'K⁺ (18).'), ('Electrons in Mg²⁺?', '10, the same as Ne.')])

# ====================================================================================== Unit 3 · 3.2.3, 3.4.2, 3.4.3
U3 = Unit('chem9-u3')
L323 = '3.2.3 The significance of chemical symbols and formulas'
L342 = '3.4.2 Writing and balancing chemical equations'
L343 = '3.4.3 Meaning of a balanced chemical equation'

SIGNIF = [
    U3.T('c01', '3.2.3 What a symbol and a formula tell you, step by step', 99,
         'Symbols and formulas are a short international language. Each one carries two kinds of information: **qualitative** (what kind of substance) and **quantitative** (how much).',
         '**A symbol, e.g. N, tells you:**',
         '1. **Qualitative:** the element — nitrogen.',
         '2. **Quantitative:** **one atom** of nitrogen, and a mass equal to its atomic mass, **14 u** (atomic mass units).',
         '**A coefficient** (big number in front) counts separate atoms or molecules: **2Na** = two sodium atoms; **3N** = three nitrogen atoms.',
         '**A formula, e.g. H₂O, tells you:**',
         '1. **Qualitative:** the name of the compound (water) and the **kinds of elements** in it (hydrogen and oxygen).',
         '2. **Quantitative:** the **number of atoms of each element** in one molecule (2 H and 1 O) and the **molecular mass** (2 × 1 + 16 = 18 u).',
         '**A subscript** (small number after a symbol) counts atoms **joined together** in one particle: N₂ is one molecule made of two nitrogen atoms.',
         '**Brackets:** a subscript after a bracket multiplies everything inside: Ca(OH)₂ has 1 Ca, 2 O and 2 H.',
         '**For ionic compounds** (e.g. NaCl) the formula gives the simplest ratio of ions, a **formula unit**, and its mass is called the **formula mass** (NaCl = 23 + 35.5 = 58.5 u).'),
    U3.TB('t01', 'N, 2N, N₂ and 2N₂ — similar-looking, different meaning', 99,
          ['Written', 'Read as', 'Atoms of N', 'Particles'],
          [['N', 'one nitrogen atom', '1', '1 atom'], ['2N', 'two separate nitrogen atoms', '2', '2 atoms'],
           ['N₂', 'one nitrogen molecule', '2', '1 molecule'], ['2N₂', 'two nitrogen molecules', '4', '2 molecules']],
          'Coefficient = how many particles. Subscript = how many atoms inside one particle. Atoms of N = coefficient × subscript.'),
    U3.TB('t02', 'Reading one formula: H₂SO₄ (sulphuric acid)', 99,
          ['Information', 'What H₂SO₄ tells you'],
          [['Qualitative: name', 'sulphuric acid'], ['Qualitative: elements', 'hydrogen, sulphur, oxygen (3 elements)'],
           ['Quantitative: atoms', '2 H + 1 S + 4 O = 7 atoms per molecule'],
           ['Quantitative: mass', '2(1) + 32 + 4(16) = 98 u'], ['Ratio by mass H : S : O', '2 : 32 : 64 = 1 : 16 : 32']]),
    U3.WK('w01', 'Worked example: what does 3H₂O mean?', 99,
          'State everything that 3H₂O represents. (H = 1, O = 16)',
          ['**Coefficient 3** → three separate water molecules.', '**Subscripts** → each molecule has 2 H atoms and 1 O atom.',
           'Total atoms: H = 3 × 2 = **6**, O = 3 × 1 = **3**.', 'Mass of one molecule = 2(1) + 16 = 18 u, so 3H₂O = 3 × 18 = **54 u**.'],
          '3 molecules of water; 6 H atoms and 3 O atoms; 54 u.'),
    U3.WK('w02', 'Worked example: atoms in a formula with brackets', 99,
          'How many atoms of each element are in (a) Ca(OH)₂ and (b) 2Al₂(SO₄)₃? Find the formula mass of Ca(OH)₂. (Ca = 40, O = 16, H = 1)',
          ['(a) The 2 after the bracket doubles O and H: Ca = 1, O = 2, H = 2 (5 atoms).',
           '(b) Inside one Al₂(SO₄)₃: Al = 2, S = 3, O = 4 × 3 = 12 (17 atoms).',
           'The coefficient 2 doubles everything: Al = 4, S = 6, O = 24 (34 atoms).',
           'Formula mass of Ca(OH)₂ = 40 + 2(16 + 1) = 40 + 34 = **74 u**.'],
          '(a) Ca 1, O 2, H 2; (b) Al 4, S 6, O 24; Ca(OH)₂ = 74 u.'),
    U3.WK('w03', 'Worked example: Co or CO?', 99,
          'Explain the difference between Co and CO.',
          ['**Co** (capital C, small o) is the **symbol** of one element, **cobalt**, a metal.',
           '**CO** (two capital letters) is a **formula** of a compound of two elements, **carbon monoxide**: 1 C atom + 1 O atom.',
           'A capital letter always starts a new element symbol.'],
          'Co = the element cobalt; CO = the compound carbon monoxide (C + O).'),
    U3.CK('k01', 99, 'Which shows two separate oxygen atoms?', ['O₂', '2O', '2O₂', 'O₃'], 'B',
          'A coefficient counts separate particles: 2O = two oxygen atoms. O₂ is one molecule (two atoms joined).'),
    U3.CK('k02', 99, 'The formula CO₂ does NOT tell you …',
          ['that carbon and oxygen are present', 'that one molecule has 3 atoms', 'the molecular mass (44 u)', 'how fast carbon burns'], 'D',
          'A formula gives the kinds of elements, the number of atoms and the mass. It says nothing about how fast a reaction happens.'),
    U3.RM('r01', 'Tips and common mistakes', 99,
          'Coefficient × subscript = number of atoms (and the bracket subscript multiplies everything inside).',
          'Capital letter = new element: Co (cobalt) ≠ CO (carbon monoxide); NO (nitrogen monoxide) ≠ No (nobelium).',
          'Molecular mass for molecules (H₂O); formula mass for ionic compounds (NaCl).'),
]

U3.M('q01', L323, 99, 'How many atoms are in one formula unit of (NH₄)₃PO₄?', ['12', '16', '20', '9'], 'C',
     ['Step 1: inside the bracket NH₄ = 1 N + 4 H = 5 atoms.', 'Step 2: the 3 multiplies it: 3 × 5 = 15 atoms.', 'Step 3: PO₄ = 1 P + 4 O = 5 atoms.', 'Step 4: total = 15 + 5 = 20.'],
     'Expand the bracket first.', [('Atoms in Mg(NO₃)₂?', '1 + 2 × 4 = 9.'), ('Atoms in 2Fe₂O₃?', '2 × 5 = 10.')])
U3.S('q02', L323, 99, 'Give the qualitative and quantitative meaning of the formula NaCl. (Na = 23, Cl = 35.5)',
     'Qualitative: sodium chloride, made of sodium and chlorine. Quantitative: one formula unit has 1 Na⁺ and 1 Cl⁻ (ratio 1 : 1); formula mass 58.5 u.',
     ['Step 1: qualitative = name and elements: sodium chloride; Na and Cl.', 'Step 2: quantitative = number of each: 1 Na, 1 Cl in a formula unit (ions in a 1 : 1 ratio).',
      'Step 3: mass = 23 + 35.5 = 58.5 u (formula mass, because NaCl is ionic).'],
     'Split your answer into “what” and “how much”.', [('Do the same for CO₂ (C = 12, O = 16).', 'Carbon dioxide, C and O; 1 C + 2 O; 44 u.'), ('Do the same for NH₃.', 'Ammonia, N and H; 1 N + 3 H; 17 u.')])
U3.M('q03', L323, 99, '“2H₂” means …', ['2 hydrogen atoms', '4 hydrogen molecules', '2 hydrogen molecules (4 atoms)', '1 molecule of 4 atoms'], 'C',
     ['Step 1: the coefficient 2 → two molecules.', 'Step 2: the subscript 2 → each molecule has two atoms.', 'Step 3: atoms = 2 × 2 = 4.'],
     'Read the coefficient first, then the subscript.', [('What does 3Cl₂ mean?', '3 chlorine molecules, 6 atoms.'), ('What does 5Fe mean?', '5 iron atoms.')])
U3.S('q04', L323, 99, 'Calculate the molecular mass of glucose, C₆H₁₂O₆. (C = 12, H = 1, O = 16)', '180 u',
     ['Step 1: C: 6 × 12 = 72.', 'Step 2: H: 12 × 1 = 12.', 'Step 3: O: 6 × 16 = 96.', 'Step 4: total = 72 + 12 + 96 = 180 u.'],
     'Multiply each atomic mass by its subscript, then add.', [('Molecular mass of H₂SO₄?', '98 u.'), ('Formula mass of CaCO₃ (Ca = 40)?', '100 u.')])
U3.TF('q05', L323, 99, 'The symbol Fe represents both the element iron and one atom of iron.', True,
      ['Step 1: qualitatively a symbol names the element (iron).', 'Step 2: quantitatively it stands for one atom (and 56 u).', 'Step 3: so the statement is true.'],
      'Every symbol has a “what” and a “how much” meaning.', [('What mass does the symbol O stand for?', '16 u (one atom).'), ('What does 4Fe stand for?', '4 iron atoms, 224 u.')])
U3.M('q06', L323, 99, 'Which formula contains the greatest number of oxygen atoms?', ['3H₂O', 'Ca(NO₃)₂', '2CO₂', 'H₂SO₄'], 'B',
     ['Step 1: 3H₂O → 3 O.', 'Step 2: Ca(NO₃)₂ → 3 × 2 = 6 O.', 'Step 3: 2CO₂ → 4 O.', 'Step 4: H₂SO₄ → 4 O. Greatest: Ca(NO₃)₂.'],
     'Count carefully with brackets and coefficients.', [('Which has more H atoms: 2NH₃ or CH₄?', '2NH₃ (6 vs 4).'), ('O atoms in 2Al₂(SO₄)₃?', '24.')])

BAL = [
    U3.T('c01', '3.4.2 Writing a chemical equation, step by step', 118,
         'A **chemical equation** is the short way chemists all over the world write a chemical change, using symbols and formulas. It is an **international chemical language**.',
         '**How to read it:** reactants (starting substances) on the **left**, products (new substances) on the **right**. “+” is read “reacts with” (on the left) or “and” (on the right); “→” is read “produces” or “gives”.',
         eq('Fe(s) + S(s) -> FeS(s)'),
         'Read: iron reacts with sulphur to produce iron(II) sulphide.',
         '**Why balance? — the law of conservation of mass.** Matter is neither created nor destroyed in a chemical reaction: **total mass of reactants = total mass of products**. Atoms are only rearranged, so every atom on the left must appear on the right.',
         '**Textbook example (Activity 3.11):** silver nitrate + hydrochloric acid → silver chloride (white precipitate) + nitric acid. The beaker weighs the same before and after mixing.',
         eq('AgNO3(aq) + HCl(aq) -> AgCl(s) + HNO3(aq)'),
         '**Mass check with mercury(II) oxide:** 432 g of HgO decomposes into 400 g of mercury and 32 g of oxygen: 400 + 32 = 432 g.',
         eq('2HgO(s) ->{heat} 2Hg(l) + O2(g)'),
         '**Three conditions for a correct equation:** (1) the reaction really happens (found by experiment); (2) every formula is written correctly; (3) it obeys the law of conservation of mass (it is balanced).'),
    U3.T('c02', 'Balancing by inspection, step by step', 121,
         '**Step a — Identify** the reactants and products.',
         '**Step b — Write the word equation.** e.g. nitrogen + hydrogen → ammonia.',
         '**Step c — Write the skeleton equation** with correct formulas: N₂ + H₂ → NH₃. Remember the diatomic elements: H₂, N₂, O₂, F₂, Cl₂, Br₂, I₂.',
         '**Step d — Count the atoms** of each element on both sides (a small table helps).',
         '**Step e — Add coefficients** (numbers in front) to make each element equal. **Never change a subscript** — that would change the substance (H₂O → H₂O₂ turns water into hydrogen peroxide).',
         '**Step f — Reduce** the coefficients to the lowest whole-number ratio (4, 2, 4 → 2, 1, 2).',
         '**Step g — Check** every element once more, and add state symbols.',
         '**Useful order:** balance first the element that appears in only one substance on each side; leave H and O (and any element present as a free element, like O₂ or Fe) until last; keep a polyatomic ion (SO₄, NO₃, OH, CO₃) together as one unit if it appears unchanged on both sides.',
         '**Fraction trick:** if you need an odd number of O₂, use a fraction such as 7/2 O₂, then multiply every coefficient by 2.'),
    U3.ST('s01', 'Model: the balancing flow chart (textbook Fig. 3.4)', 124, 'co_balance',
          [('**Skeleton:** N₂ + H₂ → NH₃ — correct formulas, no coefficients yet.', 'skel'),
           ('**Count:** left N 2, H 2; right N 1, H 3 — not equal.', 'count'),
           ('**Coefficients:** 2 in front of NH₃ (N 2 = 2, H 6), then 3 in front of H₂ (H 6 = 6).', 'coef'),
           ('**Check:** N 2 = 2, H 6 = 6, coefficients 1, 3, 2 are already the lowest ratio: N₂ + 3H₂ → 2NH₃.', 'check')]),
    U3.TB('t01', 'Atom count for N₂ + 3H₂ → 2NH₃', 123,
          ['Element', 'Left (reactants)', 'Right (products)', 'Balanced?'],
          [['N', '2 (in N₂)', '2 × 1 = 2', 'yes'], ['H', '3 × 2 = 6', '2 × 3 = 6', 'yes']]),
    U3.TB('t02', 'Allowed and not allowed when balancing', 122,
          ['Change', 'Allowed?', 'Why'],
          [['Put 2 in front: 2H₂O', 'yes', 'two molecules of the same substance'],
           ['Change subscript: H₂O → H₂O₂', 'no', 'makes a different substance (hydrogen peroxide)'],
           ['Add an atom: H₂ + O → H₂O', 'no', 'oxygen gas exists as O₂ molecules'],
           ['Put a number in the middle: H₂2O', 'no', 'coefficients go only in front'],
           ['Use 7/2 O₂, then double everything', 'yes (then clear the fraction)', 'final answer must be whole numbers']]),
    U3.WK('w01', 'Worked example: aluminium and chlorine (Exercise 3.8 1a)', 125,
          'Balance: Al + Cl₂ → AlCl₃',
          ['Count: left Al 1, Cl 2; right Al 1, Cl 3.', 'Cl: the lowest common multiple of 2 and 3 is 6 → 3Cl₂ (6 Cl) and 2AlCl₃ (6 Cl).',
           'Al is now 2 on the right → 2Al on the left.', 'Check: Al 2 = 2, Cl 6 = 6.'],
          '2Al(s) + 3Cl₂(g) → 2AlCl₃(s)'),
    U3.WK('w02', 'Worked example: phosphorus burning (Exercise 3.8 1b)', 125,
          'Balance: P + O₂ → P₂O₅',
          ['O: 2 on the left, 5 on the right; LCM of 2 and 5 is 10 → 5O₂ and 2P₂O₅.', 'P: right now has 2 × 2 = 4 → 4P on the left.',
           'Check: P 4 = 4, O 10 = 10.'],
          '4P(s) + 5O₂(g) → 2P₂O₅(s)'),
    U3.WK('w03', 'Worked example: sodium and chlorine (Exercise 3.8 1c)', 125,
          'Balance: Na + Cl₂ → NaCl',
          ['Cl: 2 on the left, 1 on the right → 2NaCl.', 'Na: now 2 on the right → 2Na.', 'Check: Na 2 = 2, Cl 2 = 2.'],
          '2Na(s) + Cl₂(g) → 2NaCl(s)'),
    U3.WK('w04', 'Worked example: from words to a balanced equation (Exercise 3.8 2)', 125,
          'Write balanced equations: (a) hydrogen + bromine → hydrogen bromide; (b) carbon monoxide + oxygen → carbon dioxide.',
          ['(a) Skeleton: H₂ + Br₂ → HBr. H: 2 vs 1 → 2HBr; Br is then 2 = 2.', '(a) Balanced: H₂(g) + Br₂(g) → 2HBr(g).',
           '(b) Skeleton: CO + O₂ → CO₂. O: left 1 + 2 = 3, right 2.', '(b) Put 2 in front of CO₂ (O 4) and 2 in front of CO (O 2 + 2 = 4); C 2 = 2.',
           '(b) Balanced: 2CO(g) + O₂(g) → 2CO₂(g).'],
          '(a) H₂ + Br₂ → 2HBr; (b) 2CO + O₂ → 2CO₂'),
    U3.WK('w05', 'Worked example: burning methane', 122,
          'Balance: CH₄ + O₂ → CO₂ + H₂O',
          ['C: 1 = 1 already.', 'H: 4 on the left → 2H₂O on the right (4 H).', 'O: right = 2 (in CO₂) + 2 (in 2H₂O) = 4 → 2O₂ on the left.',
           'Check: C 1 = 1, H 4 = 4, O 4 = 4.'],
          'CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(l)'),
    U3.WK('w06', 'Worked example: the fraction trick (ethane)', 122,
          'Balance: C₂H₆ + O₂ → CO₂ + H₂O',
          ['C: 2 → 2CO₂.', 'H: 6 → 3H₂O.', 'O on the right = 2 × 2 + 3 × 1 = 7 → we need 7/2 O₂.', 'C₂H₆ + 7/2 O₂ → 2CO₂ + 3H₂O; multiply everything by 2.',
           'Check: C 4 = 4, H 12 = 12, O 14 = 14.'],
          '2C₂H₆(g) + 7O₂(g) → 4CO₂(g) + 6H₂O(l)'),
    U3.WK('w07', 'Worked example: keep the polyatomic ion together', 122,
          'Balance: AgNO₃ + CaCl₂ → AgCl + Ca(NO₃)₂',
          ['Treat NO₃ as one unit. Right: 2 NO₃ in Ca(NO₃)₂ → 2AgNO₃ on the left.', 'Ag: now 2 on the left → 2AgCl.', 'Cl: 2 = 2; Ca: 1 = 1; NO₃: 2 = 2.'],
          '2AgNO₃(aq) + CaCl₂(aq) → 2AgCl(s) + Ca(NO₃)₂(aq)'),
    U3.CK('k01', 122, 'Which change is NOT allowed when balancing H₂ + O₂ → H₂O?',
          ['writing 2H₂O', 'writing 2H₂', 'changing H₂O to H₂O₂', 'checking the O atoms'], 'C',
          'Changing a subscript changes the substance (H₂O₂ is hydrogen peroxide). Only coefficients may change: 2H₂ + O₂ → 2H₂O.'),
    U3.CK('k02', 122, 'The balanced equation for Fe + O₂ → Fe₂O₃ is …',
          ['2Fe + 3O₂ → Fe₂O₃', '4Fe + 3O₂ → 2Fe₂O₃', 'Fe + O₂ → Fe₂O₃', '2Fe + O₂ → Fe₂O₃'], 'B',
          'O: 2 and 3 → LCM 6 → 3O₂ and 2Fe₂O₃. Fe: 2 × 2 = 4 → 4Fe. Check: Fe 4 = 4, O 6 = 6.'),
]

MEANING = [
    U3.T('c03', '3.4.3 What a balanced equation tells you, step by step', 124,
         'A balanced equation describes a reaction **qualitatively** (what) and **quantitatively** (how much). Take:',
         eq('H2(g) + Cl2(g) -> 2HCl(g)'),
         '**1 · Identity (qualitative):** hydrogen and chlorine react; hydrogen chloride is formed.',
         '**2 · States:** the state symbols show all three are gases. (s) solid, (l) liquid, (g) gas, (aq) dissolved in water.',
         '**3 · Particles:** 1 molecule of H₂ + 1 molecule of Cl₂ → 2 molecules of HCl. In atoms: 2 H atoms + 2 Cl atoms → 2 HCl molecules.',
         '**4 · Moles:** 1 mol H₂ + 1 mol Cl₂ → 2 mol HCl (coefficients are mole ratios).',
         '**5 · Masses:** using H = 1, Cl = 35.5: 2 g H₂ + 71 g Cl₂ → 73 g HCl. Mass is conserved: 2 + 71 = 73.',
         '**What an equation does not tell you:** how fast the reaction is, the conditions (unless written over the arrow), the energy change (unless ΔH is given), or whether the reaction actually happens — that comes from experiment.'),
    U3.TB('t03', 'Reading H₂ + Cl₂ → 2HCl in four ways', 124,
          ['Way of reading', 'H₂', 'Cl₂', '2HCl'],
          [['Molecules', '1', '1', '2'], ['Atoms', '2 H', '2 Cl', '2 H + 2 Cl'], ['Moles', '1 mol', '1 mol', '2 mol'], ['Mass', '2 g', '71 g', '73 g']]),
    U3.TB('t04', 'State symbols (textbook Table 3.12)', 125,
          ['Symbol', 'Meaning', 'Example'],
          [['(s)', 'solid', 'CaCO₃(s), AgCl(s) precipitate'], ['(l)', 'liquid', 'H₂O(l), Hg(l)'], ['(g)', 'gas', 'O₂(g), CO₂(g)'],
           ['(aq)', 'aqueous: dissolved in water', 'NaCl(aq), HCl(aq)']],
          '(l) and (aq) are different: pure water is H₂O(l); salt water is NaCl(aq).'),
    U3.WK('w08', 'Worked example: reading the equation for water', 124,
          'For 2H₂(g) + O₂(g) → 2H₂O(l), state the meaning in molecules, moles and grams. (H = 1, O = 16)',
          ['Molecules: 2 molecules of hydrogen + 1 molecule of oxygen → 2 molecules of water.', 'Moles: 2 mol H₂ + 1 mol O₂ → 2 mol H₂O.',
           'Grams: 2 × 2 = 4 g H₂; 1 × 32 = 32 g O₂; 2 × 18 = 36 g H₂O.', 'Check: 4 + 32 = 36 g — mass is conserved.'],
          '4 g of hydrogen react with 32 g of oxygen to give 36 g of water.'),
    U3.WK('w09', 'Worked example: mass of product', 124,
          'Magnesium burns: 2Mg(s) + O₂(g) → 2MgO(s). What mass of magnesium oxide forms from 48 g of magnesium? (Mg = 24, O = 16)',
          ['From the equation: 2 mol Mg → 2 mol MgO, i.e. 2 × 24 = 48 g Mg → 2 × 40 = 80 g MgO.', 'We have exactly 48 g Mg, so the mass of MgO = **80 g**.',
           'The oxygen used = 80 − 48 = 32 g (= 1 mol O₂) — consistent with the equation.'],
          '80 g of MgO'),
    U3.WK('w10', 'Worked example: heating limestone', 124,
          'CaCO₃(s) → CaO(s) + CO₂(g). (a) Read the equation in grams. (b) What mass of CO₂ is given off when 50 g of CaCO₃ is heated? (Ca = 40, C = 12, O = 16)',
          ['(a) CaCO₃ = 100 g/mol, CaO = 56, CO₂ = 44: 100 g → 56 g + 44 g (100 = 56 + 44).', '(b) 50 g is half of 100 g, so CO₂ = 44 ÷ 2 = **22 g** (and CaO = 28 g).'],
          '(a) 100 g → 56 g + 44 g; (b) 22 g of CO₂'),
    U3.WK('w11', 'Worked example: adding state symbols', 125,
          'Zinc granules react with dilute hydrochloric acid to give zinc chloride solution and hydrogen gas. Write the balanced equation with state symbols.',
          ['Skeleton: Zn + HCl → ZnCl₂ + H₂.', 'Cl: 1 vs 2 → 2HCl; then H: 2 = 2.', 'States: zinc is a solid (s); dilute acid and the salt solution are (aq); hydrogen is a gas (g).'],
          'Zn(s) + 2HCl(aq) → ZnCl₂(aq) + H₂(g)'),
    U3.CK('k03', 124, 'In N₂ + 3H₂ → 2NH₃, the coefficients tell us that …',
          ['1 g N₂ reacts with 3 g H₂', '1 mol N₂ reacts with 3 mol H₂ to give 2 mol NH₃', '6 molecules react', 'the reaction is fast'], 'B',
          'Coefficients are ratios of particles or moles, not grams. In grams: 28 g N₂ + 6 g H₂ → 34 g NH₃.'),
    U3.CK('k04', 125, 'The symbol (aq) after NaCl means …', ['solid salt', 'molten salt', 'salt dissolved in water', 'salt gas'], 'C',
          '(aq) = aqueous, dissolved in water. Molten (melted) salt is written NaCl(l).'),
    U3.RM('r02', 'Tips and common mistakes', 124,
          'Coefficients give mole (particle) ratios — convert to grams with the molar masses.',
          'Check mass: total grams on the left must equal total grams on the right.',
          'Write diatomic gases as molecules: O₂, H₂, N₂, Cl₂.',
          'An unbalanced equation still tells you “what”, but not “how much”.'),
]

for i, (q, a, steps, tip, sim) in enumerate([
    ('Balance: H₂ + O₂ → H₂O', '2H₂ + O₂ → 2H₂O',
     ['Step 1: O: 2 on the left, 1 on the right → 2H₂O.', 'Step 2: H is now 4 on the right → 2H₂.', 'Step 3: check H 4 = 4, O 2 = 2.'],
     'Balance O first here, then H.', [('Balance: H₂ + Cl₂ → HCl', 'H₂ + Cl₂ → 2HCl'), ('Balance: N₂ + O₂ → NO', 'N₂ + O₂ → 2NO')]),
    ('Balance: Mg + O₂ → MgO', '2Mg + O₂ → 2MgO',
     ['Step 1: O: 2 vs 1 → 2MgO.', 'Step 2: Mg: 2 on the right → 2Mg.', 'Step 3: check Mg 2 = 2, O 2 = 2.'],
     'Metals in oxides: balance the oxygen first.', [('Balance: Ca + O₂ → CaO', '2Ca + O₂ → 2CaO'), ('Balance: Li + O₂ → Li₂O', '4Li + O₂ → 2Li₂O')]),
    ('Balance: KClO₃ → KCl + O₂', '2KClO₃ → 2KCl + 3O₂',
     ['Step 1: O: 3 vs 2 → LCM 6 → 2KClO₃ and 3O₂.', 'Step 2: K and Cl: 2 on the left → 2KCl.', 'Step 3: check K 2, Cl 2, O 6 on each side.'],
     'Use the lowest common multiple for odd/even numbers.', [('Balance: H₂O₂ → H₂O + O₂', '2H₂O₂ → 2H₂O + O₂'), ('Balance: NaNO₃ → NaNO₂ + O₂', '2NaNO₃ → 2NaNO₂ + O₂')]),
    ('Balance: Fe + Cl₂ → FeCl₃', '2Fe + 3Cl₂ → 2FeCl₃',
     ['Step 1: Cl: 2 vs 3 → LCM 6 → 3Cl₂, 2FeCl₃.', 'Step 2: Fe: 2 on the right → 2Fe.', 'Step 3: check Fe 2 = 2, Cl 6 = 6.'],
     'Same pattern as Al + Cl₂.', [('Balance: Al + O₂ → Al₂O₃', '4Al + 3O₂ → 2Al₂O₃'), ('Balance: Cr + Cl₂ → CrCl₃', '2Cr + 3Cl₂ → 2CrCl₃')]),
    ('Balance: C₃H₈ + O₂ → CO₂ + H₂O', 'C₃H₈ + 5O₂ → 3CO₂ + 4H₂O',
     ['Step 1: C: 3 → 3CO₂.', 'Step 2: H: 8 → 4H₂O.', 'Step 3: O on the right = 3 × 2 + 4 = 10 → 5O₂.', 'Step 4: check C 3, H 8, O 10 on each side.'],
     'Hydrocarbons: C first, then H, then O last.', [('Balance: C₂H₄ + O₂ → CO₂ + H₂O', 'C₂H₄ + 3O₂ → 2CO₂ + 2H₂O'), ('Balance: C₄H₁₀ + O₂ → CO₂ + H₂O', '2C₄H₁₀ + 13O₂ → 8CO₂ + 10H₂O')]),
    ('Balance: NaOH + H₂SO₄ → Na₂SO₄ + H₂O', '2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O',
     ['Step 1: keep SO₄ together: 1 = 1.', 'Step 2: Na: 1 vs 2 → 2NaOH.', 'Step 3: H: left 2 + 2 = 4 → 2H₂O; O outside SO₄: 2 = 2.', 'Step 4: check Na 2, S 1, O 6, H 4 on each side.'],
     'Treat SO₄ as a unit when it appears on both sides.', [('Balance: KOH + H₂SO₄ → K₂SO₄ + H₂O', '2KOH + H₂SO₄ → K₂SO₄ + 2H₂O'), ('Balance: Ca(OH)₂ + HCl → CaCl₂ + H₂O', 'Ca(OH)₂ + 2HCl → CaCl₂ + 2H₂O')]),
]):
    U3.S(f'q{10 + i}', L342, 122 if i < 4 else 123, q, a, steps, tip, sim)

U3.M('q16', L342, 122, 'Why must a chemical equation be balanced?',
     ['To make it look neat', 'Because atoms are neither created nor destroyed in a reaction', 'Because the products must be gases', 'To change the formulas'], 'B',
     ['Step 1: the law of conservation of mass says the total mass stays the same.', 'Step 2: mass stays the same only if the same atoms are present before and after.',
      'Step 3: so each element must have equal numbers of atoms on both sides.'],
     'Link “balanced” to “conservation of mass”.', [('State the law of conservation of mass.', 'Matter is neither created nor destroyed in a chemical reaction.'),
                                                    ('432 g HgO gives 400 g Hg. Mass of O₂?', '32 g.')])
U3.TF('q17', L342, 122, 'To balance H₂ + O₂ → H₂O you may write H₂ + O₂ → H₂O₂.', False,
      ['Step 1: H₂O₂ is hydrogen peroxide, a different substance from water.', 'Step 2: subscripts are fixed by the formula; only coefficients may change.',
       'Step 3: the correct balanced equation is 2H₂ + O₂ → 2H₂O.'],
      'Never touch a subscript.', [('Is 2H₂O the same substance as H₂O?', 'Yes — two molecules of it.'), ('Is CO the same as CO₂?', 'No — different compounds.')])
U3.M('q20', L343, 124, 'In 2H₂ + O₂ → 2H₂O, what mass of water is made from 4 g of hydrogen? (H = 1, O = 16)', ['18 g', '36 g', '32 g', '4 g'], 'B',
     ['Step 1: 2 mol H₂ = 4 g.', 'Step 2: 2 mol H₂ → 2 mol H₂O.', 'Step 3: 2 mol H₂O = 2 × 18 = 36 g.'],
     'Go mass → moles → moles → mass.', [('Mass of O₂ needed for 4 g H₂?', '32 g.'), ('Mass of water from 1 g H₂?', '9 g.')])
U3.S('q21', L343, 124, 'State four pieces of information given by the balanced equation 2Na(s) + Cl₂(g) → 2NaCl(s). (Na = 23, Cl = 35.5)',
     '(1) sodium reacts with chlorine to form sodium chloride; (2) Na and NaCl are solids, Cl₂ is a gas; (3) 2 atoms Na + 1 molecule Cl₂ → 2 formula units NaCl, i.e. 2 mol : 1 mol : 2 mol; (4) 46 g Na + 71 g Cl₂ → 117 g NaCl.',
     ['Step 1: identity of reactants and products.', 'Step 2: states from the state symbols.', 'Step 3: particle / mole ratio from the coefficients.', 'Step 4: masses: 2 × 23 = 46; 71; 2 × 58.5 = 117 (46 + 71 = 117).'],
     'Use the four headings: identity, states, particles/moles, masses.', [('Masses in H₂ + Cl₂ → 2HCl?', '2 g + 71 g → 73 g.'), ('Moles in N₂ + 3H₂ → 2NH₃?', '1 : 3 : 2.')])
U3.M('q22', L343, 125, 'Which is the correct way to show a dilute solution of sulphuric acid?', ['H₂SO₄(l)', 'H₂SO₄(s)', 'H₂SO₄(aq)', 'H₂SO₄(g)'], 'C',
     ['Step 1: dilute acid = acid dissolved in water.', 'Step 2: dissolved in water is (aq).', 'Step 3: (l) would be the pure liquid.'],
     '(aq) = in water; (l) = pure liquid.', [('State symbol for steam?', '(g).'), ('State symbol for a precipitate?', '(s).')])
U3.S('q23', L343, 124, 'Calcium carbonate decomposes: CaCO₃ → CaO + CO₂. What mass of CaO is formed from 25 g of CaCO₃? (Ca = 40, C = 12, O = 16)', '14 g',
     ['Step 1: 100 g CaCO₃ → 56 g CaO.', 'Step 2: 25 g is a quarter of 100 g.', 'Step 3: CaO = 56 ÷ 4 = 14 g.'],
     'Scale the equation masses.', [('Mass of CO₂ from 25 g CaCO₃?', '11 g.'), ('Mass of CaCO₃ that gives 5.6 g CaO?', '10 g.')])
U3.TF('q24', L343, 124, 'A balanced equation tells you how fast the reaction is.', False,
      ['Step 1: an equation shows substances, states and amounts.', 'Step 2: speed (rate) must be measured by experiment.', 'Step 3: so the statement is false.'],
      'Equations show “what” and “how much”, not “how fast”.', [('Does an equation show if heat is needed?', 'Only if written over the arrow.'), ('Does it show the mole ratio?', 'Yes.')])

def _tag(cards, tag):
    for c in cards:
        c['id'] = c['id'].replace('-co-', f'-co-{tag}-')


_tag(SIGNIF, 'sym')
_tag(BAL + MEANING, 'eq')

U = {'chem9-u2': (U2, {'co_neutral': 'neutral'}), 'chem9-u3': (U3, {'co_balance': 'balance'})}
BLOCKS = [('chem9-u2-l2-1', 'chem9-u2-tb8', NEUTRAL), ('chem9-u3-l3-2', 'chem9-u3-c03', SIGNIF), ('chem9-u3-l3-4', 'chem9-u3-c18', BAL + MEANING)]
GLOSSARY = {
    'chem9-u2': [('Electrically neutral', 'Having no overall charge: the number of protons equals the number of electrons.', 50)],
    'chem9-u3': [('Coefficient', 'A number written in front of a formula; it tells how many particles (or moles) of that substance.', 122),
                 ('Subscript', 'A small number after a symbol in a formula; it tells how many atoms of that element are in one particle.', 99),
                 ('Skeleton equation', 'An equation written with correct formulas but not yet balanced.', 121),
                 ('State symbol', 'A letter in brackets after a formula showing its state: (s), (l), (g) or (aq).', 125)],
}
FIXES = []
