r"""Grade 10: 1.4.5 patterns of chemical formulas (valency), 2.2.5 metallic bonding, 4.3.3 indicators in a titration,
4.4.4 preparing salts, 4.5.1 measuring pH, 5.1.4 enthalpy of a chemical reaction."""
from co import Unit, eq, ie

# ====================================================================================== Unit 1 · 1.4.5
U1 = Unit('chem10-u1')
L145 = '1.4.5 Patterns of chemical formulas (valency)'

VAL = [
    U1.T('c01', '1.4.5 Valency and the pattern of formulas, step by step', 34,
         '**Valency** is the **bonding capacity** of an atom: the number of electrons it loses, gains or shares when it bonds. Because the group number tells you the valence electrons, it also tells you the valency.',
         '**Step 1 — Read the valency from the group.** Groups I, II, III → valency **1, 2, 3** (they tend to **lose** electrons). Group IV → **4** (tends to **share**). Groups V, VI, VII → **3, 2, 1** (they tend to **gain or share**: 8 − group number).',
         '**Step 2 — Write the symbols with their valencies.** e.g. aluminium (Al, 3) and chlorine (Cl, 1).',
         '**Step 3 — Swap (criss-cross) the valencies** to become the subscripts of the other element: Al₁Cl₃.',
         '**Step 4 — Simplify and drop the 1s:** AlCl₃. If both numbers can be divided by the same number, divide: Mg (2) + O (2) → Mg₂O₂ → **MgO**.',
         '**Step 5 — Check:** total valency of each side must be equal: Al 1 × 3 = 3, Cl 3 × 1 = 3 ✔.',
         '**The pattern:** across a period the formulas of the chlorides follow the valency: NaCl, MgCl₂, AlCl₃, SiCl₄, PCl₃, SCl₂, Cl₂. Elements in the **same group** have the **same pattern**: LiCl, NaCl, KCl; CCl₄, SiCl₄, GeCl₄. So if you know one formula in a group you can predict the others.'),
    U1.TB('t01', 'Valency by group (main groups)', 34,
          ['Group', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII'],
          [['Valence electrons', '1', '2', '3', '4', '5', '6', '7'], ['Valency', '1', '2', '3', '4', '3', '2', '1'],
           ['Tendency', 'lose', 'lose', 'lose', 'share', 'gain / share', 'gain / share', 'gain / share'],
           ['Hydride (period 3)', 'NaH', 'MgH₂', 'AlH₃', 'SiH₄', 'PH₃', 'H₂S', 'HCl']]),
    U1.TB('t02', 'Chlorides of periods 2, 3 and 4 (textbook Table 1.14, corrected)', 34,
          ['Period', 'I', 'II', 'III', 'IV', 'V', 'VI', 'VII'],
          [['2', 'LiCl', 'BeCl₂', 'BCl₃', 'CCl₄', 'NCl₃', 'Cl₂O', 'ClF'], ['3', 'NaCl', 'MgCl₂', 'AlCl₃', 'SiCl₄', 'PCl₃', 'SCl₂', 'Cl₂'],
           ['4', 'KCl', 'CaCl₂', 'GaCl₃', 'GeCl₄', 'AsCl₃', 'SeCl₂', 'BrCl']],
          'Corrections: the Group III, period 2 chloride is **BCl₃** (boron), not “BeCl₃”; chlorine with chlorine is the molecule **Cl₂**, not “ClCl”. Oxygen (Group VI) is more electronegative than chlorine, so its chlorine compound is written Cl₂O.'),
    U1.WK('w01', 'Worked example: formulas from valency', 34,
          'Use valencies to write the formulas of the compounds formed between (a) calcium and chlorine, (b) aluminium and oxygen, (c) carbon and hydrogen, (d) sodium and sulphur.',
          ['(a) Ca (Group II, 2), Cl (VII, 1): swap → Ca₁Cl₂ → **CaCl₂**.', '(b) Al (III, 3), O (VI, 2): swap → **Al₂O₃** (check 2 × 3 = 6 = 3 × 2).',
           '(c) C (IV, 4), H (1): swap → C₁H₄ → **CH₄**.', '(d) Na (I, 1), S (VI, 2): swap → **Na₂S**.'],
          'CaCl₂, Al₂O₃, CH₄, Na₂S'),
    U1.WK('w02', 'Worked example: predicting from the pattern', 34,
          'The chloride of silicon is SiCl₄ and the oxide of magnesium is MgO. Predict (a) the chloride of germanium, (b) the oxide of calcium, (c) the hydride of nitrogen.',
          ['(a) Ge is in the same group (IV) as Si → same pattern → **GeCl₄**.', '(b) Ca is in the same group (II) as Mg → **CaO**.',
           '(c) N is Group V → valency 3 → **NH₃** (like PH₃ below it).'],
          'GeCl₄, CaO, NH₃'),
    U1.WK('w03', 'Worked example: Exercise 1.11 — lose, gain or share?', 34,
          'Which of the following elements tend to lose, share or gain electrons: K, Al, C, S, Br, Si?',
          ['K (Group I) and Al (Group III) are metals → **lose** electrons (K⁺, Al³⁺).', 'C and Si (Group IV) → **share** electrons (covalent bonds, e.g. CH₄, SiO₂).',
           'S (Group VI) and Br (Group VII) are non-metals → **gain** electrons with metals (S²⁻, Br⁻) or **share** with non-metals (H₂S, HBr).'],
          'Lose: K, Al; share: C, Si; gain (or share): S, Br.'),
    U1.CK('k01', 34, 'Phosphorus (Group V) forms a chloride with the formula …', ['PCl', 'PCl₂', 'PCl₃', 'PCl₅ only'], 'C',
          'Group V valency = 8 − 5 = 3 → PCl₃. (Phosphorus can also use all five electrons and form PCl₅, but the simple valency pattern gives PCl₃.)'),
    U1.CK('k02', 34, 'Which pair of elements has chlorides with the same formula pattern?', ['Na and Mg', 'Mg and Ca', 'Al and Si', 'C and N'], 'B',
          'Mg and Ca are both in Group II (valency 2): MgCl₂ and CaCl₂. Elements in the same group give the same pattern.'),
    U1.RM('r01', 'Tips and common mistakes', 34,
          'Valency is a number with no sign; the charge of an ion has a sign (Al has valency 3, its ion is Al³⁺).',
          'After swapping, always simplify: Mg₂O₂ → MgO; C₂O₄ → CO₂.',
          'Many elements (P, S, transition metals) can show more than one valency (PCl₃ and PCl₅; FeCl₂ and FeCl₃).'),
]
U1.M('q01', L145, 34, 'The valency of an element in Group VI is …', ['6', '2', '1', '4'], 'B',
     ['Step 1: Group VI has 6 valence electrons.', 'Step 2: it needs 8 − 6 = 2 more to complete the octet.', 'Step 3: so its valency is 2 (e.g. H₂O, H₂S).'],
     'Groups V–VII: valency = 8 − group number.', [('Valency of Group VII?', '1.'), ('Valency of Group IV?', '4.')])
U1.S('q02', L145, 34, 'Write the formula of the compound formed between magnesium and nitrogen.', 'Mg₃N₂',
     ['Step 1: Mg is Group II → valency 2; N is Group V → valency 3.', 'Step 2: swap: Mg₃N₂.', 'Step 3: check 3 × 2 = 6 and 2 × 3 = 6 ✔; cannot simplify.'],
     'Swap the valencies, then check the totals.', [('Formula of calcium phosphide (Ca, P)?', 'Ca₃P₂.'), ('Formula of lithium oxide?', 'Li₂O.')])
U1.M('q03', L145, 34, 'Which formula does NOT follow the valency pattern?', ['NaCl', 'MgCl₂', 'AlCl₂', 'SiCl₄'], 'C',
     ['Step 1: Al is in Group III → valency 3.', 'Step 2: so its chloride must be AlCl₃.', 'Step 3: AlCl₂ is wrong; the others match valencies 1, 2 and 4.'],
     'Check the valency of the metal against the number of Cl atoms.', [('Correct formula of the boron chloride?', 'BCl₃.'), ('Correct formula of the sulphur chloride?', 'SCl₂.')])
U1.S('q04', L145, 34, 'Element X forms the oxide X₂O₃. What is the valency of X and in which group is X likely to be?', 'Valency 3; Group III (like Al₂O₃).',
     ['Step 1: oxygen has valency 2; three O atoms → total 3 × 2 = 6.', 'Step 2: two X atoms share this total: 6 ÷ 2 = 3.', 'Step 3: valency 3 for a metal → Group III.'],
     'Work backwards: total valency of one element = total of the other.', [('Y forms YCl₂. Valency of Y?', '2 (Group II).'), ('Z forms H₂Z. Valency and group of Z?', '2; Group VI.')])
U1.TF('q05', L145, 34, 'Potassium and sodium form chlorides with the same formula pattern.', True,
      ['Step 1: K and Na are both in Group I (valency 1).', 'Step 2: NaCl and KCl.', 'Step 3: same group → same pattern.'],
      'Same group → same formula pattern.', [('Do C and Si form similar chlorides?', 'Yes: CCl₄ and SiCl₄.'), ('Do Na and Mg?', 'No: NaCl and MgCl₂.')])

# ====================================================================================== Unit 2 · 2.2.5
U2 = Unit('chem10-u2')
L225 = '2.2.5 Metallic bonding'

MET = [
    U2.T('c01', '2.2.5 Metallic bonding, step by step', 50,
         '**Metallic bonding** is the attraction between **positive metal ions** and the **delocalised (free-moving) valence electrons** around them. It holds metals together in the solid.',
         '**Step 1 — Metal atoms lose their valence electrons easily** (low ionisation energy). Sodium gives 1 electron per atom, magnesium 2, aluminium 3.',
         '**Step 2 — The atoms become positive ions (cations)** packed in regular layers (a lattice).',
         '**Step 3 — The released electrons are delocalised:** they do not belong to one atom or one bond; they move freely through the whole metal, like a “sea” of electrons.',
         '**Step 4 — The bond:** every cation is attracted to the electron sea and the sea is attracted to every cation. This attraction acts in **all directions**, so the bond is **non-directional**.',
         '**What makes it stronger?** More delocalised electrons per atom, a higher ion charge and a smaller ion → stronger attraction → higher melting point. Example: Na (1 e⁻) melts at 98 °C, Mg (2 e⁻) at 650 °C, Al (3 e⁻) at 660 °C.',
         '**Note on the textbook model (Fig. 2.3):** the circles labelled “positive nucleus” are really **positive metal ions** — each is a nucleus **plus its inner electrons**; only the valence electrons are in the sea.'),
    U2.SS('s01', 'Model: the electron sea and why metals bend', 51, 'co_metallic',
          [('sea', 'Electron sea', 'Cations in layers, valence electrons free to move everywhere between them.'),
           ('slide', 'Hammered', 'A force slides the layers over each other. The electron sea moves with them and still holds every ion, so the metal bends instead of breaking → **malleable** and **ductile**.')]),
    U2.TB('t01', 'Properties of metals explained by the model', 51,
          ['Property', 'Explanation from metallic bonding', 'Use'],
          [['Good conductor of electricity', 'delocalised electrons move through the metal when a voltage is applied', 'copper wires, aluminium cables'],
           ['Good conductor of heat', 'free electrons (and vibrating ions) pass energy on quickly', 'cooking pots, radiators'],
           ['Malleable and ductile', 'layers of ions slide without breaking the bond', 'sheets, wires'],
           ['Lustrous (shiny)', 'free electrons absorb and re-emit light', 'jewellery, mirrors'],
           ['High melting and boiling points (most)', 'strong attraction between many ions and the sea of electrons', 'iron, tungsten lamp filaments']]),
    U2.TB('t02', 'Ionic, covalent and metallic bonds compared (textbook Table 2.2)', 51,
          ['', 'Ionic', 'Covalent', 'Metallic'],
          [['Formed between', 'metal + non-metal', 'non-metal + non-metal', 'metal atoms'],
           ['Particles', 'positive and negative ions', 'atoms sharing electron pairs', 'cations + delocalised electrons'],
           ['Basis of attraction', 'opposite charges', 'nuclei and shared electron pair(s)', 'cations and the electron sea'],
           ['Conducts as a solid?', 'no (ions fixed)', 'no (except graphite)', 'yes'],
           ['Conducts molten?', 'yes (ions move)', 'no', 'yes'],
           ['Hit with a hammer', 'brittle: like charges meet and repel', 'molecular solids crumble', 'bends (malleable)'],
           ['Example', 'NaCl', 'H₂, H₂O', 'Au, Cu, Fe']]),
    U2.WK('w01', 'Worked example: melting points of Na, Mg, Al', 51,
          'Explain why the melting point rises from sodium (98 °C) to magnesium (650 °C) and aluminium (660 °C).',
          ['Na gives **1**, Mg **2** and Al **3** delocalised electrons per atom.', 'The ions also become more highly charged (Na⁺, Mg²⁺, Al³⁺) and smaller.',
           'More electrons in the sea + higher charge + smaller ions → stronger attraction between ions and electrons.',
           'More energy is needed to loosen the lattice → higher melting point.'],
          'The metallic bond gets stronger from Na to Al.'),
    U2.WK('w02', 'Worked example: why a metal conducts but solid salt does not', 51,
          'Copper conducts electricity as a solid; sodium chloride conducts only when molten or dissolved. Explain.',
          ['A current needs **charged particles that can move**.', 'In copper the delocalised electrons are free to move even in the solid → conducts.',
           'In solid NaCl the ions are locked in the lattice and there are no free electrons → no current.',
           'When NaCl melts or dissolves, the ions become free to move → conducts.'],
          'Metals have mobile electrons; ionic solids have fixed ions.'),
    U2.WK('w03', 'Worked example: hammering a metal and a salt', 51,
          'Why does a piece of copper flatten when hammered, while a crystal of salt shatters?',
          ['In copper, the layers of Cu²⁺ ions slide over each other; the electron sea still surrounds every ion, so the bond is not broken → it flattens.',
           'In NaCl, a slight shift brings ions of the **same charge** next to each other (+ next to +, − next to −).', 'The like charges repel and the crystal splits → brittle.'],
          'Metallic bonding is non-directional; ionic lattices break when like charges meet.'),
    U2.CK('k01', 50, 'Metallic bonding is the attraction between …',
          ['positive and negative ions', 'two nuclei and a shared pair', 'positive metal ions and delocalised electrons', 'neutral metal atoms'], 'C',
          'Metal atoms release their valence electrons; the cations are held by the sea of delocalised electrons.'),
    U2.CK('k02', 51, 'Which property of metals is NOT explained by delocalised electrons?', ['conducting electricity', 'lustre', 'malleability', 'high density'], 'D',
          'Conductivity, lustre and malleability all come from the mobile electron sea. Density depends on how heavy and how closely packed the atoms are.'),
    U2.RM('r01', 'Tips and common mistakes', 51,
          'Say “delocalised electrons”, not “free ions”: in a solid metal it is the **electrons** that move.',
          'Metals are held by cations + electrons, not by positive and negative ions.',
          'More valence electrons per atom → stronger metallic bond.'),
]
U2.M('q01', L225, 50, 'Which particles move when a current flows through a copper wire?', ['Cu²⁺ ions', 'protons', 'delocalised electrons', 'neutrons'], 'C',
     ['Step 1: in a metal the ions are fixed in the lattice.', 'Step 2: the valence electrons are delocalised and free to move.', 'Step 3: so the current is carried by electrons.'],
     'Metals: electrons move. Molten salts and solutions: ions move.', [('What carries current in molten NaCl?', 'Na⁺ and Cl⁻ ions.'), ('Why is graphite a conductor?', 'It has delocalised electrons between its layers.')])
U2.S('q02', L225, 51, 'Explain why metals are malleable.',
     'Metallic bonds are non-directional: when the layers of positive ions slide over one another, the sea of delocalised electrons still holds them, so the metal changes shape without breaking.',
     ['Step 1: metals are layers of cations in a sea of electrons.', 'Step 2: a force makes the layers slide.', 'Step 3: the electrons move with the ions, so attraction is kept everywhere.', 'Step 4: the metal bends instead of breaking.'],
     'Mention layers, sliding and the electron sea.', [('Why are metals ductile?', 'Same reason: layers slide when pulled into a wire.'), ('Why are ionic crystals brittle?', 'Like charges meet and repel when layers move.')])
U2.M('q03', L225, 51, 'Which metal is expected to have the strongest metallic bonding?', ['Na', 'K', 'Mg', 'Al'], 'D',
     ['Step 1: compare delocalised electrons: Na 1, K 1, Mg 2, Al 3.', 'Step 2: Al³⁺ also has the highest charge and smallest size.', 'Step 3: so aluminium has the strongest bonding.'],
     'More valence electrons → stronger bond.', [('Which has a higher melting point, Na or K?', 'Na (smaller ion, stronger attraction).'), ('Which is stronger, Mg or Na?', 'Mg.')])
U2.TF('q04', L225, 51, 'Solid metals conduct electricity because their positive ions move through the lattice.', False,
      ['Step 1: in a solid the ions stay in place.', 'Step 2: the delocalised electrons carry the current.', 'Step 3: so the statement is false.'],
      'In a solid metal only the electrons move.', [('Do metal ions move in molten metal?', 'They can move, but the current is still carried mainly by electrons.'), ('Do ions move in brine?', 'Yes.')])
U2.S('q05', L225, 51, 'Give two differences between metallic bonding and ionic bonding.',
     '(1) Ionic bonding is between positive and negative ions; metallic bonding is between positive ions and delocalised electrons. (2) Ionic solids do not conduct and are brittle; metals conduct as solids and are malleable.',
     ['Step 1: compare the particles: ions + ions vs cations + electron sea.', 'Step 2: compare a property: conduction in the solid (no vs yes).', 'Step 3: compare another: brittle vs malleable.'],
     'Compare like with like: particles, then properties.', [('One difference between metallic and covalent bonding?', 'Covalent: shared pairs between two atoms; metallic: electrons shared by all ions.'), ('Which bond is non-directional?', 'Metallic (and ionic); covalent bonds are directional.')])

# ====================================================================================== Unit 4 · 4.3.3, 4.4.4, 4.5.1
U4 = Unit('chem10-u4')
L433 = '4.3.3 Using indicators in a titration'
L444 = '4.4.4 Methods for preparing salts'
L451 = '4.5.1 Measuring pH'

IND = [
    U4.T('c01', '4.3.3 Indicators in a titration, step by step', 138,
         'An **acid–base indicator** is a dye (itself a weak acid or weak base) whose colour in its acid form differs from its colour in its base form. It changes colour as it **gains or loses H⁺ ions**, so it shows the **end point** of a titration.',
         '**Step 1 — Fill the burette** with the solution of known concentration (e.g. NaOH). Read the starting volume at eye level, bottom of the meniscus.',
         '**Step 2 — Pipette** an exact volume (e.g. 25.0 mL) of the other solution (e.g. HCl) into a conical flask.',
         '**Step 3 — Add 2–3 drops of indicator.** Only a few drops: the indicator is itself a weak acid/base and too much would take part in the reaction.',
         '**Step 4 — Run in the titrant** while swirling, quickly at first, then drop by drop near the end. A white tile under the flask helps you see the colour.',
         '**Step 5 — Stop at the end point:** the first **permanent** colour change (e.g. colourless → pale pink with phenolphthalein).',
         '**Step 6 — Read the final volume;** the difference is the titre. Repeat until two titres agree within 0.10 mL (concordant).',
         '**End point vs equivalence point:** the **equivalence point** is when the acid and base have exactly reacted in the ratio of the equation; the **end point** is when the indicator changes colour. A good indicator makes the two almost the same.'),
    U4.ST('s01', 'Model: the titration set-up', 138, 'co_titration',
          [('**Burette** holds the titrant (e.g. 0.100 M NaOH); read volumes at the bottom of the meniscus.', 'burette'),
           ('**Conical flask** holds the pipetted acid with 2–3 drops of indicator; swirl so the drops mix at once.', 'flask'),
           ('**End point:** the first permanent pale pink with phenolphthalein. Stop and read the burette.', 'end')]),
    U4.TB('t01', 'Common indicators (textbook Table 4.2, with pH ranges)', 138,
          ['Indicator', 'Colour in acid', 'Colour in base', 'Changes over pH (approx.)'],
          [['Methyl orange', 'red / pink', 'yellow', '3.1 – 4.4 (orange in between)'], ['Litmus', 'red', 'blue', '5 – 8'],
           ['Phenolphthalein', 'colourless', 'pink', '8.2 – 10']]),
    U4.TB('t02', 'Choosing the indicator', 138,
          ['Titration', 'pH at equivalence', 'Best indicator', 'Why'],
          [['Strong acid + strong base (HCl + NaOH)', '7', 'phenolphthalein or methyl orange', 'pH jumps from about 3 to 11, through both ranges'],
           ['Strong acid + weak base (HCl + NH₃)', 'below 7 (≈ 5)', 'methyl orange', 'changes in the acid range'],
           ['Weak acid + strong base (CH₃COOH + NaOH)', 'above 7 (≈ 9)', 'phenolphthalein', 'changes in the alkaline range'],
           ['Weak acid + weak base', '≈ 7, no sharp jump', 'no simple indicator', 'use a pH meter']],
          'Litmus is a good test-paper indicator but a poor titration indicator: its colour change is gradual (purple in between), so the end point is not sharp.'),
    U4.WK('w01', 'Worked example: Exercise 4.4 Q1 — products of neutralisation', 138,
          'Complete and balance, with a word equation: (a) KOH + HNO₃; (b) Ba(OH)₂ + HCl; (c) NaOH + H₃PO₄; (d) Ca(OH)₂ + H₃PO₄.',
          [r'(a) potassium hydroxide + nitric acid → potassium nitrate + water: ' + eq('KOH(aq) + HNO3(aq) -> KNO3(aq) + H2O(l)'),
           r'(b) barium hydroxide + hydrochloric acid → barium chloride + water: ' + eq('Ba(OH)2(aq) + 2HCl(aq) -> BaCl2(aq) + 2H2O(l)'),
           r'(c) sodium hydroxide + phosphoric acid → sodium phosphate + water: ' + eq('3NaOH(aq) + H3PO4(aq) -> Na3PO4(aq) + 3H2O(l)'),
           r'(d) calcium hydroxide + phosphoric acid → calcium phosphate (insoluble) + water: ' + eq('3Ca(OH)2(aq) + 2H3PO4(aq) -> Ca3(PO4)2(s) + 6H2O(l)')],
          'Acid + base → salt + water; balance H⁺ with OH⁻.'),
    U4.WK('w02', 'Worked example: Exercise 4.4 Q4 — normality of HCl', 138,
          '50.0 mL of 0.1 N NaOH is needed to titrate 20.0 mL of HCl. Find the normality of the HCl.',
          [r'At the end point, equivalents of acid = equivalents of base: \(N_a V_a = N_b V_b\).', r'\(N_a \times 20.0 = 0.1 \times 50.0\)',
           r'\(N_a = \dfrac{0.1 \times 50.0}{20.0} = 0.25\ \text{N}\)', 'For HCl (one H⁺ per molecule) 0.25 N = 0.25 M.'],
          '0.25 N'),
    U4.WK('w03', 'Worked example: titration with sulphuric acid (mole ratio 1 : 2)', 138,
          '25.0 mL of NaOH solution needs 12.5 mL of 0.100 M H₂SO₄ to reach the end point (phenolphthalein). Find the molarity of the NaOH.',
          [eq('H2SO4(aq) + 2NaOH(aq) -> Na2SO4(aq) + 2H2O(l)'),
           r'Moles of H₂SO₄ = \(0.100 \times \dfrac{12.5}{1000} = 1.25 \times 10^{-3}\) mol.',
           r'Mole ratio 1 : 2 → moles of NaOH = \(2 \times 1.25 \times 10^{-3} = 2.50 \times 10^{-3}\) mol.',
           r'Molarity of NaOH = \(\dfrac{2.50 \times 10^{-3}}{0.0250} = 0.100\ \text{M}\).'],
          '0.100 M'),
    U4.WK('w04', 'Worked example: which indicator, which colour?', 138,
          'Ethanoic acid (vinegar) is titrated with NaOH from the burette. Which indicator should be used and what colour change marks the end point?',
          ['Weak acid + strong base → the solution at equivalence is slightly alkaline (pH ≈ 9).', 'Phenolphthalein changes at pH 8.2–10 → it fits.',
           'In the flask the acid is colourless with phenolphthalein; at the end point the first drop of excess NaOH gives a **permanent pale pink**.'],
          'Phenolphthalein; colourless → pale pink.'),
    U4.CK('k01', 138, 'Methyl orange in a solution of NaOH is …', ['red', 'colourless', 'yellow', 'pink'], 'C',
          'Methyl orange is red/pink in acid and yellow in base. (Phenolphthalein is the one that is pink in base.)'),
    U4.CK('k02', 138, 'The end point of a titration is …',
          ['when the burette is empty', 'when the indicator just changes colour permanently', 'always at pH 7', 'when the flask is warm'], 'B',
          'The end point is shown by the indicator. It is at pH 7 only for strong acid + strong base.'),
    U4.RM('r01', 'Tips and common mistakes', 138,
          'Use only 2–3 drops of indicator. Rinse the burette with the titrant and the pipette with the solution it delivers; rinse the flask with distilled water only.',
          'Phenolphthalein: colourless in acid. Methyl orange: red in acid, yellow in base. Do not mix them up.',
          'Weak acid → phenolphthalein; weak base → methyl orange.'),
]
U4.M('q01', L433, 138, 'Which indicator is best for titrating ammonia solution with hydrochloric acid?', ['phenolphthalein', 'methyl orange', 'litmus', 'no indicator'], 'B',
     ['Step 1: NH₃ is a weak base; HCl is a strong acid.', 'Step 2: the salt NH₄Cl makes the solution slightly acidic at equivalence (pH ≈ 5).', 'Step 3: methyl orange changes in the acid range (3.1–4.4) → best.'],
     'Weak base → methyl orange.', [('Indicator for ethanoic acid + NaOH?', 'Phenolphthalein.'), ('Indicator for HCl + NaOH?', 'Either.')])
U4.S('q02', L433, 138, '20.0 mL of 0.150 M HCl is neutralised by 30.0 mL of KOH. Find the molarity of the KOH.', '0.100 M',
     ['Step 1: HCl + KOH → KCl + H₂O (1 : 1).', 'Step 2: moles HCl = 0.150 × 0.0200 = 3.00 × 10⁻³ mol.', 'Step 3: moles KOH = 3.00 × 10⁻³ mol.', 'Step 4: M = 3.00 × 10⁻³ ÷ 0.0300 = 0.100 M.'],
     'Moles first, then use the mole ratio.', [('Same, but 15.0 mL of KOH?', '0.200 M.'), ('Volume of 0.10 M NaOH for 25 mL of 0.10 M HCl?', '25 mL.')])
U4.M('q03', L433, 138, 'Phenolphthalein is added to HCl in a flask and NaOH is run in. The colour change at the end point is …',
     ['pink → colourless', 'colourless → pink', 'red → yellow', 'yellow → red'], 'B',
     ['Step 1: in acid phenolphthalein is colourless.', 'Step 2: the first slight excess of NaOH makes the solution basic.', 'Step 3: phenolphthalein turns pink.'],
     'Think “from what is in the flask to what is added”.', [('Methyl orange, base in the flask, acid added?', 'yellow → orange/red.'), ('Phenolphthalein, NaOH in the flask, HCl added?', 'pink → colourless.')])
U4.S('q04', L433, 138, 'Which acid and which base would you use to prepare (a) MgCl₂, (b) CaSO₄, (c) KBr? (Exercise 4.4 Q2)',
     '(a) Mg(OH)₂ (or MgO) + HCl; (b) Ca(OH)₂ + H₂SO₄; (c) KOH + HBr.',
     ['Step 1: the metal ion of the salt comes from the base.', 'Step 2: the negative ion comes from the acid: chloride ← HCl, sulphate ← H₂SO₄, bromide ← HBr.',
      'Step 3: e.g. Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O.'],
     'Split the salt name: first part → base, second part → acid.', [('Acid and base for NaCl?', 'NaOH + HCl.'), ('Acid and base for KNO₃?', 'KOH + HNO₃.')])
U4.TF('q05', L433, 138, 'At the end point of every acid–base titration the pH is exactly 7.', False,
      ['Step 1: pH 7 at equivalence only for strong acid + strong base.', 'Step 2: weak acid + strong base gives pH ≈ 9; strong acid + weak base pH ≈ 5.', 'Step 3: so the statement is false.'],
      'The salt formed decides the pH at equivalence.', [('pH at equivalence for CH₃COOH + NaOH?', 'Above 7.'), ('For HCl + NH₃?', 'Below 7.')])
U4.S('q06', L433, 138, 'Why is litmus not used as an indicator in titrations?', 'Its colour changes gradually over a wide pH range (5–8) through purple, so the end point is not sharp.',
     ['Step 1: a good indicator changes sharply with one drop.', 'Step 2: litmus passes slowly from red through purple to blue.', 'Step 3: it is hard to see exactly when to stop.'],
     'A sharp change = a precise end point.', [('Name two titration indicators.', 'Phenolphthalein and methyl orange.'), ('What is litmus used for?', 'Quick acid/base tests (litmus paper).')])

SALT = [
    U4.T('c02', '4.4.4 Preparing salts, step by step', 141,
         'A salt contains the **positive ion of a base (or metal)** and the **negative ion of an acid**. Choose the method from **two questions**: Is the salt soluble in water? Which starting materials are safe and available?',
         '**Method 1 — Neutralisation (acid + alkali).** For soluble salts of Na, K and NH₄. Titrate to find the exact volumes, mix again without indicator, evaporate and crystallise.',
         eq('NaOH(aq) + HCl(aq) -> NaCl(aq) + H2O(l)'),
         '**Method 2 — Acid + metal.** Only metals **more reactive than hydrogen** and not too reactive (Mg, Zn, Fe). Not Cu or Ag (no reaction); never Na or K (explosive).',
         eq('Mg(s) + H2SO4(aq) -> MgSO4(aq) + H2(g)'),
         '**Method 3 — Acid + carbonate or hydrogencarbonate.** Fizzing shows CO₂.',
         eq('BaCO3(s) + 2HCl(aq) -> BaCl2(aq) + H2O(l) + CO2(g)'),
         eq('HNO3(aq) + NaHCO3(aq) -> NaNO3(aq) + H2O(l) + CO2(g)'),
         '**Method 4 — Acid + insoluble base (metal oxide), Activity 4.8.** Black CuO dissolves in warm dilute sulphuric acid to give a **blue** solution of copper(II) sulphate.',
         eq('CuO(s) + H2SO4(aq) -> CuSO4(aq) + H2O(l)'),
         '**For methods 2–4 (excess solid):** add the solid to warm acid until no more dissolves (the acid is used up) → **filter** off the excess → **evaporate** to a saturated solution → **cool to crystallise** → filter and dry the crystals.',
         '**Method 5 — Precipitation (double decomposition)** for **insoluble** salts: mix two solutions that contain the two ions, filter, wash with distilled water, dry.',
         eq('BaCl2(aq) + Na2SO4(aq) -> BaSO4(s) + 2NaCl(aq)'),
         '**(Extra) Direct combination** of a metal and a non-metal: 2Na(s) + Cl₂(g) → 2NaCl(s); Fe(s) + S(s) → FeS(s).'),
    U4.ST('s02', 'Model: choosing the method', 141, 'co_salts',
          [('**First** look up the solubility (textbook Table 4.4).', 'q1'),
           ('**Soluble:** excess metal / oxide / carbonate + acid, filter, crystallise. For Na, K, NH₄ salts use titration (alkali + acid).', 'sol'),
           ('**Insoluble:** precipitation — mix two soluble salts, filter off the solid, wash, dry.', 'insol')]),
    U4.TB('t03', 'Which method for which salt?', 142,
          ['Salt wanted', 'Soluble?', 'Method', 'Starting materials'],
          [['ZnSO₄', 'yes', 'metal + acid', 'zinc + dilute H₂SO₄'], ['CuSO₄', 'yes', 'insoluble base + acid', 'CuO + dilute H₂SO₄ (Cu does not react)'],
           ['KNO₃', 'yes (K salt)', 'titration', 'KOH + HNO₃'], ['MgCl₂', 'yes', 'carbonate + acid', 'MgCO₃ + HCl'],
           ['BaSO₄', 'no', 'precipitation', 'BaCl₂(aq) + Na₂SO₄(aq)'], ['PbI₂', 'no', 'precipitation', 'Pb(NO₃)₂(aq) + KI(aq)'],
           ['CaCO₃', 'no', 'precipitation', 'CaCl₂(aq) + Na₂CO₃(aq)']]),
    U4.WK('w05', 'Worked example: pure, dry copper(II) sulphate crystals', 142,
          'Describe how to make crystals of copper(II) sulphate from copper(II) oxide.',
          ['Warm about 50 mL of dilute H₂SO₄ in a beaker (do not boil).', 'Add CuO a little at a time with stirring until some black solid stays undissolved — the acid is now used up.',
           'Filter to remove the excess CuO; the filtrate is blue CuSO₄(aq).', 'Evaporate the filtrate until it is saturated (crystals form on a cold glass rod), then leave it to cool.',
           'Filter off the blue crystals (CuSO₄·5H₂O), wash with a little cold water and dry between filter papers.',
           eq('CuO(s) + H2SO4(aq) -> CuSO4(aq) + H2O(l)')],
          'Excess oxide → filter → evaporate → crystallise → dry.'),
    U4.WK('w06', 'Worked example: barium sulphate by precipitation', 142,
          'Explain why BaSO₄ cannot be made by reacting barium carbonate with dilute sulphuric acid and give a better method.',
          ['BaSO₄ is insoluble; it would form a coat over the BaCO₃ and stop the reaction.', 'It could not be separated from the excess solid by filtering.',
           'Better: mix BaCl₂(aq) with dilute H₂SO₄ or Na₂SO₄(aq): a white precipitate forms at once.', eq('Ba^2+(aq) + SO4^2-(aq) -> BaSO4(s)'),
           'Filter, wash the precipitate with distilled water to remove the soluble NaCl/HCl, and dry.'],
          'Precipitation from two soluble salts.'),
    U4.WK('w07', 'Worked example: why not copper + acid?', 141,
          'A student tries to make CuCl₂ by adding copper turnings to dilute hydrochloric acid. What happens and what should be done instead?',
          ['Copper is below hydrogen in the activity series, so it does **not** displace H₂ from dilute acids: no reaction.',
           'Use copper(II) oxide or copper(II) carbonate instead:', eq('CuCO3(s) + 2HCl(aq) -> CuCl2(aq) + H2O(l) + CO2(g)')],
          'Use CuO or CuCO₃ with the acid.'),
    U4.CK('k03', 141, 'Which method is best for preparing lead(II) iodide?', ['lead + HI', 'lead oxide + HI', 'precipitation from Pb(NO₃)₂ and KI', 'titration'], 'C',
          'PbI₂ is insoluble (bright yellow precipitate), so mix two soluble salts: Pb(NO₃)₂(aq) + 2KI(aq) → PbI₂(s) + 2KNO₃(aq).'),
    U4.CK('k04', 141, 'In the excess-solid method, why is the solid added until some remains?',
          ['to make the salt insoluble', 'to make sure all the acid has reacted', 'to speed up evaporation', 'to colour the solution'], 'B',
          'Leftover solid shows the acid is used up, so no acid contaminates the crystals; the excess solid is then filtered off.'),
    U4.RM('r02', 'Tips and common mistakes', 142,
          'Soluble salt → crystallise. Insoluble salt → precipitate and filter.',
          'Do not evaporate to dryness: crystals of hydrated salts (CuSO₄·5H₂O) lose their water and may decompose.',
          'Correction: magnesium sulphate is **MgSO₄** (Mg²⁺ with SO₄²⁻), not “Mg₂SO₄” as printed on p.140.'),
]
U4.M('q10', L444, 141, 'Which pair would react to give zinc chloride and hydrogen?', ['Zn + NaCl', 'ZnO + HCl', 'Zn + HCl', 'ZnCO₃ + HCl'], 'C',
     ['Step 1: hydrogen is produced only by metal + acid.', 'Step 2: Zn is above H in the activity series.', 'Step 3: Zn + 2HCl → ZnCl₂ + H₂. ZnO gives water; ZnCO₃ gives CO₂.'],
     'Metal + acid → salt + hydrogen.', [('Products of ZnO + HCl?', 'ZnCl₂ + H₂O.'), ('Products of ZnCO₃ + HCl?', 'ZnCl₂ + H₂O + CO₂.')])
U4.S('q11', L444, 142, 'Write the balanced equation, with state symbols, for making magnesium nitrate from magnesium carbonate.',
     'MgCO₃(s) + 2HNO₃(aq) → Mg(NO₃)₂(aq) + H₂O(l) + CO₂(g)',
     ['Step 1: nitrate → nitric acid.', 'Step 2: carbonate + acid → salt + water + carbon dioxide.', 'Step 3: Mg²⁺ needs two NO₃⁻ → 2HNO₃.', 'Step 4: check H 2 = 2, O 9 = 9.'],
     'Carbonate + acid always gives CO₂ and water.', [('Equation for CaCO₃ + HCl?', 'CaCO₃ + 2HCl → CaCl₂ + H₂O + CO₂.'), ('Equation for Na₂CO₃ + H₂SO₄?', 'Na₂CO₃ + H₂SO₄ → Na₂SO₄ + H₂O + CO₂.')])
U4.M('q12', L444, 142, 'Silver chloride is best prepared by …', ['silver + HCl', 'silver oxide + HCl', 'AgNO₃(aq) + NaCl(aq)', 'evaporating AgCl solution'], 'C',
     ['Step 1: AgCl is insoluble.', 'Step 2: insoluble salts are made by precipitation.', 'Step 3: AgNO₃(aq) + NaCl(aq) → AgCl(s) + NaNO₃(aq); filter, wash, dry.'],
     'Insoluble → precipitation.', [('Which salt is insoluble: AgCl or AgNO₃?', 'AgCl.'), ('Colour of AgCl?', 'White.')])
U4.S('q13', L444, 142, 'List the steps to obtain pure crystals of zinc sulphate from zinc and dilute sulphuric acid.',
     'Add excess zinc to the acid until fizzing stops; filter off unreacted zinc; evaporate the filtrate to the point of crystallisation; cool; filter and dry the crystals.',
     ['Step 1: Zn(s) + H₂SO₄(aq) → ZnSO₄(aq) + H₂(g).', 'Step 2: excess zinc makes sure all the acid reacts (fizzing stops).', 'Step 3: filter to remove the extra zinc.',
      'Step 4: evaporate to saturation, cool, collect and dry the crystals.'],
     'Excess → filter → evaporate → crystallise.', [('Why stop when fizzing stops?', 'All the acid has reacted.'), ('Name the gas given off.', 'Hydrogen.')])
U4.TF('q14', L444, 141, 'Sodium chloride can safely be made by adding sodium metal to hydrochloric acid.', False,
      ['Step 1: sodium is very reactive.', 'Step 2: with acid the reaction is violent (explosive) and dangerous.', 'Step 3: NaCl is made by titrating NaOH with HCl.'],
      'Very reactive metals (Na, K) and unreactive metals (Cu, Ag) are not used with acids.', [('Can copper be used with dilute HCl?', 'No — no reaction.'), ('Can magnesium?', 'Yes.')])
U4.S('q15', L444, 141, 'What do you observe when copper(II) oxide is added to warm dilute sulphuric acid (Activity 4.8)? Write the equation.',
     'The black powder dissolves and the colourless acid turns blue (copper(II) sulphate). CuO(s) + H₂SO₄(aq) → CuSO₄(aq) + H₂O(l).',
     ['Step 1: CuO is a black basic oxide.', 'Step 2: it neutralises the acid to form soluble CuSO₄, which is blue.', 'Step 3: when excess CuO is added, black solid remains undissolved.'],
     'Copper(II) salts in solution are blue.', [('Colour of iron(II) sulphate solution?', 'Pale green.'), ('Colour of zinc sulphate solution?', 'Colourless.')])

PH = [
    U4.T('c03', '4.5.1 Measuring pH, step by step', 147,
         'There are two common ways to measure pH: a **pH meter** and **indicators**. We measure pH in daily life too — for example swimming-pool water must stay at about pH 7.2–7.8, or it irritates skin and lets bacteria grow.',
         '**A · The pH meter (accurate, a number):** a pair of electrodes (a glass probe) is connected to a meter that measures a small voltage. The voltage depends on [H⁺], and the meter is calibrated to show pH.',
         '1. **Calibrate** with buffer solutions of known pH (e.g. pH 4 and 7).', '2. **Rinse** the probe with distilled water and dip it into the sample.',
         '3. **Wait** for a steady reading and record it (e.g. pH 6.84).', '4. **Rinse** again before the next sample and store the probe wet.',
         '**B · Indicators (quick, a colour, less precise):** an indicator has one colour in acid and another in base and changes within a small pH range. Many come from plants: red cabbage, roses, beetroot, grapes, sunflower petals. They are used as solutions or soaked onto paper.',
         '**C · Universal indicator** is a **mixture** of indicators, so it shows a different colour for each pH value. Compare the colour with the chart to estimate the pH.'),
    U4.ST('s03', 'Model: the universal indicator chart', 149, 'co_ph',
          [('**Colours (textbook Table 4.7):** pH 1–4 red, 5 orange, 6 yellow, 7 green, 8 bluish-green, 9 blue, 10 bluish-purple, 11–14 purple.', 'col'),
           ('**Everyday values:** lemon juice ≈ 2–3, coffee ≈ 5, milk ≈ 6.5, blood ≈ 7.4, baking soda ≈ 8–9, bleach ≈ 12–13.', 'ex')]),
    U4.TB('t04', 'pH meter, universal indicator and litmus compared', 148,
          ['', 'pH meter', 'Universal indicator', 'Litmus paper'],
          [['Result', 'a number (e.g. 3.27)', 'a colour → pH to about ±1', 'acid or base only'], ['Accuracy', 'high', 'medium', 'low'],
           ['Coloured or cloudy samples?', 'works', 'colour hard to see', 'hard to see'], ['Needs', 'calibration, electricity', 'colour chart', 'red and blue paper'],
           ['Best for', 'lab, soil, pools, hospitals', 'quick class tests', 'quick acid/base check']]),
    U4.WK('w08', 'Worked example: Exercise 4.7 Q1', 147,
          '[H⁺] of solution A is 1 × 10⁻⁵ M and of solution B is 2.5 × 10⁻⁹ M. Calculate the pH of each and say whether it is acidic, basic or neutral.',
          [r'A: \(\text{pH} = -\log(1\times10^{-5}) = 5\) → below 7 → **acidic**.',
           r'B: \(\text{pH} = -\log(2.5\times10^{-9}) = -(\log 2.5 + \log 10^{-9}) = -(0.40 - 9) = 8.60\)', 'B: above 7 → **basic**.'],
          'A: pH 5, acidic. B: pH 8.6, basic.'),
    U4.WK('w09', 'Worked example: from a colour to a pH', 149,
          'Universal indicator turns (a) orange in a soft drink, (b) blue in a toothpaste solution, (c) green in tap water. Estimate the pH of each and classify it.',
          ['(a) orange → pH ≈ 5 → weakly acidic.', '(b) blue → pH ≈ 9 → weakly alkaline (it neutralises acid in the mouth).', '(c) green → pH ≈ 7 → neutral.'],
          '≈ 5 acidic; ≈ 9 alkaline; ≈ 7 neutral.'),
    U4.WK('w10', 'Worked example: pH from [OH⁻]', 147,
          'A cleaning solution has [OH⁻] = 1 × 10⁻³ M. Find its pH.',
          [r'\(\text{pOH} = -\log(1\times10^{-3}) = 3\)', r'\(\text{pH} = 14 - \text{pOH} = 14 - 3 = 11\)', 'pH 11 → alkaline (purple-blue with universal indicator).'],
          'pH 11'),
    U4.CK('k05', 149, 'Universal indicator turns yellow in a solution. Its pH is about …', ['2', '6', '8', '12'], 'B',
          'From the chart: red 1–4, orange 5, yellow 6, green 7. Yellow → pH ≈ 6, slightly acidic.'),
    U4.CK('k06', 148, 'Why is a pH meter better than universal indicator for testing a dark fruit juice?',
          ['it is cheaper', 'the colour of the juice hides the indicator colour, and the meter gives an exact value', 'indicators do not work in acids', 'meters need no calibration'], 'B',
          'A coloured sample masks the indicator; the meter reads a voltage, not a colour, and gives a precise number (after calibration).'),
    U4.RM('r03', 'Tips and common mistakes', 149,
          'Each pH unit is a factor of 10 in [H⁺]: pH 3 has 100 times more H⁺ than pH 5.',
          'Universal indicator gives a range; only a pH meter gives decimals.',
          'Always calibrate a pH meter first, and rinse the probe between samples.'),
]
U4.M('q20', L451, 149, 'A solution turns universal indicator purple. It is …', ['strongly acidic', 'weakly acidic', 'neutral', 'strongly alkaline'], 'D',
     ['Step 1: purple is at pH 11–14 on the chart.', 'Step 2: pH far above 7 → strongly alkaline.', 'Step 3: e.g. NaOH solution or bleach.'],
     'Red end = acid, purple end = alkali.', [('Colour at pH 1?', 'Red.'), ('Colour at pH 7?', 'Green.')])
U4.S('q21', L451, 147, 'Calculate the pH of a solution with [H⁺] = 3.0 × 10⁻⁴ M.', 'pH = 3.52 (acidic)',
     ['Step 1: pH = −log(3.0 × 10⁻⁴).', 'Step 2: log 3.0 = 0.48; log 10⁻⁴ = −4.', 'Step 3: pH = −(0.48 − 4) = 3.52.', 'Step 4: below 7 → acidic.'],
     'pH = −log[H⁺]; for a×10⁻ⁿ the pH is a little below n.', [('pH for [H⁺] = 1 × 10⁻²?', '2.'), ('pH for [H⁺] = 5.0 × 10⁻⁸?', '7.30.')])
U4.M('q22', L451, 148, 'Which is the most accurate way to measure the pH of soil water?', ['litmus paper', 'universal indicator', 'red cabbage juice', 'a calibrated pH meter'], 'D',
     ['Step 1: indicators give colours (ranges).', 'Step 2: a calibrated pH meter gives a numerical value.', 'Step 3: so the pH meter is most accurate.'],
     'Number beats colour.', [('What must be done before using a pH meter?', 'Calibrate it with buffers.'), ('Name a natural indicator.', 'Red cabbage extract.')])
U4.S('q23', L451, 149, 'Estimate the pH of orange juice, milk, blood and bleach, and say which is the most acidic. (Exercise 4.7 Q2b)',
     'Orange juice ≈ 3–4, milk ≈ 6.5, blood ≈ 7.4, bleach ≈ 12–13; orange juice is the most acidic.',
     ['Step 1: fruit juices contain citric acid → pH 3–4.', 'Step 2: milk is close to neutral, slightly acidic (≈ 6.5).', 'Step 3: blood is slightly alkaline (7.35–7.45).',
      'Step 4: bleach (NaOCl + NaOH) is strongly alkaline; the lowest pH is the most acidic → orange juice.'],
     'Lower pH = more acidic.', [('Is coffee acidic or basic?', 'Acidic (≈ 5).'), ('pH of pure water at 25 °C?', '7.')])
U4.TF('q24', L451, 149, 'A solution of pH 4 has ten times more H⁺ ions than a solution of pH 5.', True,
      ['Step 1: [H⁺] at pH 4 = 10⁻⁴ M; at pH 5 = 10⁻⁵ M.', 'Step 2: 10⁻⁴ ÷ 10⁻⁵ = 10.', 'Step 3: true.'],
      'One pH unit = ×10.', [('pH 2 vs pH 5?', '1000 times more H⁺.'), ('pH 9 vs pH 7: more or less H⁺?', '100 times less.')])

# ====================================================================================== Unit 5 · 5.1.4
U5 = Unit('chem10-u5')
L514 = '5.1.4 Enthalpy of a chemical reaction'

ENTH = [
    U5.T('c01', '5.1.4 Enthalpy and ΔH, step by step', 157,
         'Every substance stores energy in its bonds. The **heat content** of a substance at constant pressure is called its **enthalpy, H**. We cannot measure H itself, but we can measure the **change**, ΔH (“delta H”), during a reaction.',
         '$$\\Delta H = H_{\\text{products}} - H_{\\text{reactants}} = H_P - H_R$$',
         '**Step 1 — Bonds in the reactants are broken.** This never happens by itself: energy must be **supplied** (absorbed), so this stage is endothermic.',
         '**Step 2 — New bonds in the products are formed.** This happens by itself and energy is **released**, so this stage is exothermic.',
         '**Step 3 — Compare the two amounts:**',
         '$$\\Delta H = \\sum(\\text{energy to break bonds}) - \\sum(\\text{energy released forming bonds})$$',
         'If more energy is released than absorbed, ΔH is **negative** (exothermic, H_P < H_R). If more is absorbed, ΔH is **positive** (endothermic, H_P > H_R).',
         '**Unit:** kilojoules per mole, **kJ/mol** — per mole of reaction as written in the equation.',
         '**Activity 5.5 explained:** adding quicklime (CaO) to water makes the beaker hot. Heat flows **from the beaker to your hand**: the reaction CaO + H₂O → Ca(OH)₂ releases energy, so ΔH is negative.'),
    U5.ST('s01', 'Model: break bonds, then make bonds (H₂ + Cl₂ → 2HCl)', 158, 'co_bonds',
          [('**Break:** H–H (436 kJ) and Cl–Cl (243 kJ) need 679 kJ in total — the energy goes **up** to separate atoms.', 'break'),
           ('**Make:** two H–Cl bonds form (2 × 432 = 864 kJ) — energy comes **out**.', 'make'),
           ('**Net:** ΔH = 679 − 864 = **−185 kJ** per mole of reaction: the products are lower, the reaction is exothermic.', 'net')]),
    U5.TB('t01', 'Bond energies (kJ/mol) — textbook Table 5.1 plus values used below', 157,
          ['Bond', 'Energy', 'Bond', 'Energy'],
          [['H–H', '436', 'C–H', '413'], ['Cl–Cl', '243', 'C–C', '348'], ['H–Cl', '432', 'C=C', '614'], ['H–Br', '366', 'C≡C', '839'], ['H–F', '565', 'C–O', '360'],
           ['O=O', '498', 'C=O (in CO₂)', '805'], ['N≡N', '945', 'O–H', '463'], ['N–H', '391', '', '']],
          'Corrections to Table 5.1: the 945 kJ bond is the nitrogen **triple** bond N≡N, and the 839 kJ carbon bond is the **triple** bond C≡C (two lines in the table print “N=N” and a second “C=C”). Triple > double > single.'),
    U5.TB('t02', 'Exothermic and endothermic in terms of enthalpy', 158,
          ['', 'Exothermic', 'Endothermic'],
          [['Bond energy balance', 'released (making) > absorbed (breaking)', 'absorbed (breaking) > released (making)'],
           ['H_P compared with H_R', 'H_P < H_R', 'H_P > H_R'], ['Sign of ΔH', 'negative (−)', 'positive (+)'],
           ['Surroundings', 'get warmer', 'get colder (or must be heated)'], ['Example', 'CaO + H₂O → Ca(OH)₂', 'CaCO₃ → CaO + CO₂']]),
    U5.WK('w01', 'Worked example: ΔH from bond energies (hydrogen chloride)', 158,
          'Use bond energies to find ΔH for H₂(g) + Cl₂(g) → 2HCl(g). (H–H 436, Cl–Cl 243, H–Cl 432 kJ/mol)',
          ['Bonds broken: 1 H–H + 1 Cl–Cl = 436 + 243 = 679 kJ (absorbed).', 'Bonds formed: 2 H–Cl = 2 × 432 = 864 kJ (released).',
           r'\(\Delta H = 679 - 864 = -185\ \text{kJ}\)', 'Negative → exothermic.'],
          'ΔH = −185 kJ/mol (exothermic)'),
    U5.WK('w02', 'Worked example: the Haber reaction', 158,
          'Find ΔH for N₂(g) + 3H₂(g) → 2NH₃(g). (N≡N 945, H–H 436, N–H 391 kJ/mol)',
          ['Broken: 1 N≡N + 3 H–H = 945 + 3 × 436 = 945 + 1308 = 2253 kJ.', 'Formed: each NH₃ has 3 N–H, so 2NH₃ has 6 N–H = 6 × 391 = 2346 kJ.',
           r'\(\Delta H = 2253 - 2346 = -93\ \text{kJ}\)', 'Exothermic. (The measured value is −92 kJ — very close.)'],
          'ΔH ≈ −93 kJ/mol'),
    U5.WK('w03', 'Worked example: burning methane from bond energies', 158,
          'Estimate ΔH for CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(g). (C–H 413, O=O 498, C=O 805, O–H 463 kJ/mol)',
          ['Broken: 4 C–H + 2 O=O = 4(413) + 2(498) = 1652 + 996 = 2648 kJ.', 'Formed: 2 C=O + 4 O–H = 2(805) + 4(463) = 1610 + 1852 = 3462 kJ.',
           r'\(\Delta H = 2648 - 3462 = -814\ \text{kJ}\)',
           'Bond energies are **averages**, and here the water is a gas; that is why the answer differs from the measured −890 kJ (with liquid water).'],
          'ΔH ≈ −814 kJ/mol'),
    U5.WK('w04', 'Worked example: using H_P − H_R', 158,
          'For a reaction the total enthalpy of the reactants is 250 kJ and of the products 120 kJ. Find ΔH and say whether the reaction is exo- or endothermic. What is ΔH of the reverse reaction?',
          [r'\(\Delta H = H_P - H_R = 120 - 250 = -130\ \text{kJ}\)', 'Negative → **exothermic**.', 'Reverse reaction: same size, opposite sign → **+130 kJ** (endothermic).'],
          '−130 kJ (exothermic); reverse +130 kJ'),
    U5.CK('k01', 158, 'Breaking a chemical bond …', ['releases energy', 'absorbs energy', 'needs no energy', 'always makes the surroundings hot'], 'B',
          'Energy must be supplied to pull bonded atoms apart. Energy is released when bonds form.'),
    U5.CK('k02', 158, 'If H_P is greater than H_R, the reaction is …', ['exothermic, ΔH negative', 'endothermic, ΔH positive', 'neither', 'explosive'], 'B',
          'ΔH = H_P − H_R > 0 → energy was taken in → endothermic.'),
    U5.RM('r01', 'Tips and common mistakes', 158,
          'ΔH = (bonds broken) − (bonds formed) — reactant bonds first. Do not reverse it.',
          'Count every bond: 2NH₃ has 6 N–H bonds; CO₂ has 2 C=O bonds; 2O₂ has 2 O=O bonds.',
          'Exothermic → negative ΔH, even though “heat is given out”.'),
]
U5.M('q01', L514, 158, 'Using H–H 436, Br–Br 193 and H–Br 366 kJ/mol, ΔH for H₂ + Br₂ → 2HBr is …', ['+263 kJ', '−103 kJ', '−263 kJ', '+103 kJ'], 'B',
     ['Step 1: broken = 436 + 193 = 629 kJ.', 'Step 2: formed = 2 × 366 = 732 kJ.', 'Step 3: ΔH = 629 − 732 = −103 kJ.'],
     'Broken minus formed.', [('Exo or endo?', 'Exothermic.'), ('ΔH for 2HBr → H₂ + Br₂?', '+103 kJ.')])
U5.S('q02', L514, 157, 'Define enthalpy change of reaction and give its unit.', 'The difference between the heat content of the products and of the reactants, ΔH = H_P − H_R, measured in kJ/mol.',
     ['Step 1: enthalpy H = heat content.', 'Step 2: ΔH = H(products) − H(reactants).', 'Step 3: unit kJ/mol.'],
     'Always write the formula ΔH = H_P − H_R.', [('Sign of ΔH for an exothermic reaction?', 'Negative.'), ('Why is ΔH measured, not H?', 'Absolute H cannot be measured.')])
U5.M('q03', L514, 158, 'In an endothermic reaction …', ['more energy is released forming bonds than absorbed breaking them', 'ΔH is negative', 'more energy is absorbed breaking bonds than released forming them', 'the surroundings get hotter'], 'C',
     ['Step 1: endothermic → energy taken in overall.', 'Step 2: so breaking (in) > making (out).', 'Step 3: ΔH positive; surroundings get colder.'],
     'Compare the two stages.', [('Example of an endothermic reaction?', 'Thermal decomposition of CaCO₃.'), ('Example of an exothermic one?', 'Combustion.')])
U5.S('q04', L514, 158, 'Calculate ΔH for 2H₂(g) + O₂(g) → 2H₂O(g). (H–H 436, O=O 498, O–H 463 kJ/mol)', '−482 kJ',
     ['Step 1: broken = 2(436) + 498 = 872 + 498 = 1370 kJ.', 'Step 2: formed = 2 molecules × 2 O–H = 4(463) = 1852 kJ.', 'Step 3: ΔH = 1370 − 1852 = −482 kJ.', 'Step 4: exothermic.'],
     'Each water molecule has two O–H bonds.', [('ΔH per mole of H₂O formed?', '−241 kJ.'), ('ΔH for 2H₂O(g) → 2H₂ + O₂?', '+482 kJ.')])
U5.TF('q05', L514, 157, 'When quicklime is added to water and the beaker becomes hot, heat flows from the beaker to the hand.', True,
      ['Step 1: the reaction releases heat into the water and beaker.', 'Step 2: heat flows from hot to cold, so from beaker to hand.', 'Step 3: true; ΔH is negative.'],
      'Feels hot → exothermic.', [('Feels cold → ?', 'Endothermic.'), ('Sign of ΔH when NH₄NO₃ dissolves (cold)?', 'Positive.')])

U = {'chem10-u1': (U1, {}), 'chem10-u2': (U2, {'co_metallic': 'metallic'}), 'chem10-u4': (U4, {'co_titration': 'titration', 'co_salts': 'salts', 'co_ph': 'ph'}),
     'chem10-u5': (U5, {'co_bonds': 'bonds'})}
BLOCKS = [('chem10-u1-l1-2', 'chem10-u1-c11', VAL), ('chem10-u2-l2-2', 'chem10-u2-c05', MET), ('chem10-u4-l4-3', 'chem10-u4-c09', IND),
          ('chem10-u4-l4-4', 'chem10-u4-c13', SALT), ('chem10-u4-l4-5', 'chem10-u4-c15', PH), ('chem10-u5-l5-1', 'chem10-u5-c04', ENTH)]
GLOSSARY = {
    'chem10-u1': [('Valency', 'The bonding capacity of an atom: the number of electrons it loses, gains or shares when forming bonds.', 34)],
    'chem10-u2': [('Delocalised electrons', 'Valence electrons that are not tied to one atom or bond but move freely through the whole structure (as in metals).', 50)],
    'chem10-u4': [('End point', 'The point in a titration at which the indicator changes colour permanently.', 138),
                  ('Equivalence point', 'The point at which acid and base have reacted exactly in the ratio of the balanced equation.', 139),
                  ('Universal indicator', 'A mixture of indicators that shows a different colour for each pH value.', 148),
                  ('pH meter', 'An instrument with electrodes that measures a voltage depending on [H⁺] and shows the pH as a number.', 148)],
    'chem10-u5': [('Enthalpy (H)', 'The heat content of a substance; ΔH = H(products) − H(reactants).', 158),
                  ('Bond energy', 'The energy needed to break one mole of a given bond in gaseous molecules (kJ/mol).', 156)],
}

FIXES = [
    ('chem10-u4-c15', 'body', ['Measuring the pH of a swimming pool is important: if the pH is outside the safe range (about 7.2–7.8) it can irritate the skin and allow bacteria to grow.',
                               'A universal indicator shows a series of colour changes at different pH values, so it indicates how acidic or alkaline the solution under investigation is.']),
    ('chem10-u1-c11', 'body', ['Na⁺ has a valency of 1; with Cl⁻ it forms NaCl, which contains one Cl⁻. Similarly, Al³⁺ has a valency of 3; with Cl⁻ it forms AlCl₃, which contains three Cl⁻ ions.']),
    ('chem10-u5-c06', 'body', ['An equation that contains the information about the heat changes involved in a reaction is called a **thermochemical equation**.',
                               'The physical states of reactants and products should be stated.',
                               'The value of ΔH given in kJ/mol refers to the amounts (moles) of reactants and products exactly as written in the equation.']),
    ('chem10-u5-cm-t01', 'rows', lambda rows: [[c.replace('Burning butane, wood, charcoal:', 'Burning methane (natural gas), wood, charcoal:') for c in r] for r in rows]),
]
