// GENERATED by tool/gen_art.py from the Warsay Prep / High web app (icons `P`, illustrations `ART`). Do not edit by hand.
// ignore_for_file: lines_longer_than_80_chars

const Map<String, String> kIcons = {
  'home': r'''<path d="M4 11l8-7 8 7v8a2 2 0 0 1-2 2h-3v-6h-6v6H6a2 2 0 0 1-2-2z"/>''',
  'grid': r'''<rect x="3.5" y="3.5" width="7" height="7" rx="2.2"/><rect x="13.5" y="3.5" width="7" height="7" rx="2.2"/><rect x="3.5" y="13.5" width="7" height="7" rx="2.2"/><rect x="13.5" y="13.5" width="7" height="7" rx="2.2"/>''',
  'bookmark': r'''<path d="M7 3h10a1 1 0 0 1 1 1v17l-6-4-6 4V4a1 1 0 0 1 1-1z"/>''',
  'chat': r'''<path d="M5 4.5h14a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-8l-5 4v-4H5a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2z"/><path d="M8 10.5h.01M12 10.5h.01M16 10.5h.01" stroke-width="3"/>''',
  'check': r'''<path d="M5 12.5l4.5 4.5L19 7.5"/>''',
  'x': r'''<path d="M6.5 6.5l11 11M17.5 6.5l-11 11"/>''',
  'target': r'''<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1.2" fill="currentColor"/>''',
  'clock': r'''<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3.2 2"/>''',
  'flame': r'''<path d="M12 3c1 3.2 5.5 5.2 5.5 10.3A5.5 5.5 0 0 1 6.5 13.3c0-2.2 1-3.8 2.2-4.8 0 2 1 3.3 2.2 3.3C10.9 8.6 10 6.3 12 3z"/>''',
  'flask': r'''<path d="M9 3h6M10 3v6l-5.2 9.1A2 2 0 0 0 6.5 21h11a2 2 0 0 0 1.7-2.9L14 9V3"/><path d="M7.4 15h9.2"/>''',
  'leaf': r'''<path d="M5 19C5 10 11 5 20 5c0 9-5 15-14 15"/><path d="M5 19c3-4 6-6.5 9-8"/>''',
  'sprout': r'''<path d="M12 21v-8M6 21h12"/><path d="M12 13c0-4-3-6.5-7-6.5 0 4 3 6.5 7 6.5zM12 11c0-4 3-6.5 7-6.5 0 4-3 6.5-7 6.5z"/>''',
  'globe': r'''<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c3.2 3.2 3.2 14.8 0 18M12 3c-3.2 3.2-3.2 14.8 0 18"/>''',
  'chart': r'''<path d="M5 20v-6M11 20V9M17 20V4M3 20.5h18"/>''',
  'book': r'''<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H20v15H6.5A2.5 2.5 0 0 0 4 20.5z"/><path d="M4 20.5V5.5M20 18v3H6.5"/><path d="M8.5 7.5h7M8.5 11h5"/>''',
  'atom': r'''<circle cx="12" cy="12" r="1.6" fill="currentColor"/><ellipse cx="12" cy="12" rx="10" ry="4"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(60 12 12)"/><ellipse cx="12" cy="12" rx="10" ry="4" transform="rotate(120 12 12)"/>''',
  'math': r'''<path d="M4 7h6M7 4v6M14 7h6M14.5 15.5l5 5M19.5 15.5l-5 5M4 17.5h6"/>''',
  'landmark': r'''<path d="M3 10l9-6 9 6M5 10v8M9.5 10v8M14.5 10v8M19 10v8M3 21h18"/>''',
  'monitor': r'''<rect x="3" y="4" width="18" height="12" rx="2.5"/><path d="M8 20.5h8M12 16v4.5"/>''',
  'play': r'''<path d="M8 5.5v13l10.5-6.5z" fill="currentColor" stroke="none"/>''',
  'chev': r'''<path d="M6 9l6 6 6-6"/>''',
  'right': r'''<path d="M9 6l6 6-6 6"/>''',
  'back': r'''<path d="M15 18l-6-6 6-6"/>''',
  'moon': r'''<path d="M20 14.5A8 8 0 1 1 9.5 4a6.5 6.5 0 0 0 10.5 10.5z"/>''',
  'sun': r'''<circle cx="12" cy="12" r="4"/><path d="M12 2.5v2M12 19.5v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2.5 12h2M19.5 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>''',
  'star': r'''<path d="M12 3.5l2.6 5.3 5.9.9-4.3 4.1 1 5.8-5.2-2.7-5.2 2.7 1-5.8-4.3-4.1 5.9-.9z"/>''',
  'bulb': r'''<path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-3.5 10.9c.6.5 1 1.2 1 2.1h5c0-.9.4-1.6 1-2.1A6 6 0 0 0 12 3z"/>''',
  'repeat': r'''<path d="M17 2.5l3 3-3 3"/><path d="M4 11.5v-2a4 4 0 0 1 4-4h12M7 21.5l-3-3 3-3"/><path d="M20 12.5v2a4 4 0 0 1-4 4H4"/>''',
  'steps': r'''<path d="M10 6h10M10 12h10M10 18h10"/><circle cx="5" cy="6" r="1.4" fill="currentColor"/><circle cx="5" cy="12" r="1.4" fill="currentColor"/><circle cx="5" cy="18" r="1.4" fill="currentColor"/>''',
  'flag': r'''<path d="M5 21V4M5 4h11.5l-2.2 4 2.2 4H5"/>''',
  'send': r'''<path d="M5 12h14M13 6l6 6-6 6"/>''',
  'search': r'''<circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5"/>''',
  'trophy': r'''<path d="M8 4h8v5a4 4 0 0 1-8 0z"/><path d="M8 6H5a3 3 0 0 0 3 4M16 6h3a3 3 0 0 1-3 4M12 13v4M8 21h8M10 17h4"/>''',
  'sparkle': r'''<path d="M12 3l1.9 5.1L19 10l-5.1 1.9L12 17l-1.9-5.1L5 10l5.1-1.9zM19 16l.8 2.2L22 19l-2.2.8L19 22l-.8-2.2L16 19l2.2-.8z"/>''',
  'user': r'''<circle cx="12" cy="8" r="4"/><path d="M4 21a8 8 0 0 1 16 0"/>''',
  'pen': r'''<path d="M4 20h4L19 9l-4-4L4 16z"/><path d="M13.5 6.5l4 4"/>''',
  'shuffle': r'''<path d="M16 3.5h4.5V8M4 20L20.5 3.5M20.5 16v4.5H16M15 15l5.5 5.5M4 4l5 5"/>''',
  'cal': r'''<rect x="3" y="5" width="18" height="16" rx="3"/><path d="M3 10h18M8 3v4M16 3v4"/>''',
  'sliders': r'''<path d="M4 7h9M18 7h2M4 17h4M13 17h7"/><circle cx="15.5" cy="7" r="2.5"/><circle cx="10.5" cy="17" r="2.5"/>''',
  'zoom': r'''<circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5M8 11h6M11 8v6"/>''',
  'minus': r'''<circle cx="11" cy="11" r="7"/><path d="M20 20l-3.5-3.5M8 11h6"/>''',
};

const Map<String, String> kArt = {
  'student': r'''<svg viewBox="0 0 160 160" aria-hidden="true">
  <defs><radialGradient id="st1s" cx=".38" cy=".32" r=".75"><stop offset="0" stop-color="#B97C5C"/><stop offset="1" stop-color="#8A563C"/></radialGradient>
  <linearGradient id="st1h" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#B9D7B2"/><stop offset="1" stop-color="#8CB788"/></linearGradient>
  <linearGradient id="st1p" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#F9BCA7"/><stop offset="1" stop-color="#E8866B"/></linearGradient>
  <linearGradient id="st1b" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#F8DC8E"/><stop offset="1" stop-color="#EDBF52"/></linearGradient></defs>
  <ellipse cx="80" cy="157" rx="58" ry="6" fill="#000" opacity=".06"/>
  <g fill="#3B2A22"><circle cx="80" cy="60" r="36"/><circle cx="55" cy="45" r="17"/><circle cx="105" cy="45" r="17"/><circle cx="80" cy="31" r="20"/><circle cx="47" cy="66" r="12"/><circle cx="113" cy="66" r="12"/></g>
  <circle cx="80" cy="15" r="12" fill="#4A352B"/><circle cx="76" cy="11" r="4" fill="#fff" opacity=".12"/>
  <path d="M24 160c0-34 23-52 56-52s56 18 56 52z" fill="url(#st1h)"/>
  <path d="M55 112c7 13 43 13 50 0-9-7-41-7-50 0z" fill="#9CC596"/><path d="M73 118v16M87 118v16" stroke="#F7F0E5" stroke-width="2.5" stroke-linecap="round"/>
  <rect x="71" y="90" width="18" height="22" rx="8" fill="#80503A"/>
  <ellipse cx="80" cy="67" rx="25" ry="27" fill="url(#st1s)"/>
  <path d="M55 61c0-19 13-26 26-25 14 0 24 9 22 25-6-9-13-13-23-11-10-2-18 3-25 11z" fill="#3B2A22"/>
  <path d="M66 70q5-5 10 0M84 70q5-5 10 0" stroke="#2E211B" stroke-width="2.8" fill="none" stroke-linecap="round"/>
  <ellipse cx="64.5" cy="79" rx="5.5" ry="3.2" fill="#F07F6E" opacity=".45"/><ellipse cx="95.5" cy="79" rx="5.5" ry="3.2" fill="#F07F6E" opacity=".45"/>
  <path d="M73 82q7 7 14 0" stroke="#5A2B20" stroke-width="2.8" fill="none" stroke-linecap="round"/>
  <path d="M49 67c0-35 62-35 62 0" stroke="url(#st1p)" stroke-width="7.5" fill="none" stroke-linecap="round"/>
  <rect x="41" y="58" width="16" height="25" rx="8" fill="url(#st1p)"/><rect x="103" y="58" width="16" height="25" rx="8" fill="url(#st1p)"/>
  <rect x="44.5" y="61.5" width="4" height="10" rx="2" fill="#fff" opacity=".55"/><rect x="106.5" y="61.5" width="4" height="10" rx="2" fill="#fff" opacity=".55"/>
  <path d="M38 134l42-9 42 9v25l-42-8-42 8z" fill="url(#st1b)"/>
  <path d="M42 132l38-8v25l-38 7z" fill="#FFFCF5"/><path d="M118 132l-38-8v25l38 7z" fill="#FFF1DA"/>
  <path d="M48 137l24-5M48 143l24-5M48 149l16-3M88 132l24 5M88 138l24 5M88 144l16 3" stroke="#E6D3B5" stroke-width="2" stroke-linecap="round"/>
  <ellipse cx="42" cy="141" rx="8.5" ry="7.5" fill="#94593F"/><ellipse cx="118" cy="141" rx="8.5" ry="7.5" fill="#94593F"/>
  <path d="M136 26l3 7.5 7.5 3-7.5 3-3 7.5-3-7.5-7.5-3 7.5-3z" fill="#F5CF6A"/><path d="M20 44l2 5 5 2-5 2-2 5-2-5-5-2 5-2z" fill="#fff" opacity=".85"/>
  <g transform="translate(118 82) rotate(8)"><rect width="30" height="20" rx="8" fill="#FFFAF2"/><text x="15" y="14.5" text-anchor="middle" font-family="Nunito,sans-serif" font-weight="900" font-size="11" fill="#E0765C">A+</text></g>
</svg>''',
  'plant': r'''<svg viewBox="0 0 60 84" aria-hidden="true"><path d="M30 50C30 38 29 28 30 18" stroke="#6E9D6A" stroke-width="3" fill="none" stroke-linecap="round"/>
  <g fill="#8DBA86"><ellipse cx="19" cy="30" rx="12" ry="6.5" transform="rotate(-35 19 30)"/><ellipse cx="41" cy="24" rx="12" ry="6.5" transform="rotate(35 41 24)"/></g>
  <g fill="#A9CFA2"><ellipse cx="20" cy="44" rx="11" ry="6" transform="rotate(-20 20 44)"/><ellipse cx="40" cy="40" rx="11" ry="6" transform="rotate(25 40 40)"/><ellipse cx="30" cy="13" rx="6" ry="11"/></g>
  <path d="M13 54h34l-4 24a4 4 0 0 1-4 3.4H21a4 4 0 0 1-4-3.4z" fill="#F0D5B8"/><rect x="10" y="49" width="40" height="9" rx="4.5" fill="#F7E3CC"/><rect x="16" y="60" width="4" height="14" rx="2" fill="#fff" opacity=".45"/></svg>''',
  'kokob': r'''<svg viewBox="0 0 100 100" class="" aria-hidden="true"><defs><linearGradient id="kk2" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#FFE08A"/><stop offset="1" stop-color="#F3B13E"/></linearGradient></defs>
  <ellipse cx="50" cy="95" rx="24" ry="3.5" fill="#000" opacity=".08"/>
  <path d="M50.0 16.0L61.2 38.6L86.1 42.3L68.1 59.9L72.3 84.7L50.0 73.0L27.7 84.7L31.9 59.9L13.9 42.3L38.8 38.6Z" fill="url(#kk2)" stroke="url(#kk2)" stroke-width="11" stroke-linejoin="round"/>
  <path d="M34 36c4-6 10-9 16-9" stroke="#fff" stroke-width="4" stroke-linecap="round" opacity=".6" fill="none"/>
  <ellipse cx="42" cy="55" rx="3.6" ry="4.6" fill="#3B2A22"/><ellipse cx="58" cy="55" rx="3.6" ry="4.6" fill="#3B2A22"/><circle cx="43.2" cy="53.3" r="1.3" fill="#fff"/><circle cx="59.2" cy="53.3" r="1.3" fill="#fff"/>
  <ellipse cx="35" cy="63" rx="4.5" ry="2.8" fill="#F08A6E" opacity=".55"/><ellipse cx="65" cy="63" rx="4.5" ry="2.8" fill="#F08A6E" opacity=".55"/>
  <path d="M44 63q6 6 12 0" stroke="#7A3E22" stroke-width="2.6" fill="none" stroke-linecap="round"/></svg>''',
  'desk': r'''<svg viewBox="0 0 368 156" preserveAspectRatio="xMidYMid slice" aria-hidden="true">
  <defs><linearGradient id="dk3w" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#F9CDB2"/><stop offset="1" stop-color="#F3A98C"/></linearGradient>
  <linearGradient id="dk3f" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="rgba(120,50,30,0)"/><stop offset="1" stop-color="rgba(120,50,30,.42)"/></linearGradient>
  <radialGradient id="dk3l" cx=".5" cy="0" r="1"><stop offset="0" stop-color="#FFF1B8" stop-opacity=".9"/><stop offset="1" stop-color="#FFF1B8" stop-opacity="0"/></radialGradient></defs>
  <rect width="368" height="156" fill="url(#dk3w)"/>
  <rect x="22" y="16" width="78" height="62" rx="14" fill="#FDE7CC"/><circle cx="76" cy="36" r="10" fill="#F9C865"/><path d="M22 62q20-14 40-2t38-6v10a14 14 0 0 1-14 14H36a14 14 0 0 1-14-14z" fill="#BFD9B4"/>
  <path d="M61 16v62M22 47h78" stroke="#F6D9BA" stroke-width="5"/><rect x="22" y="16" width="78" height="62" rx="14" fill="none" stroke="#F7DCC0" stroke-width="5"/>
  <circle cx="318" cy="34" r="17" fill="#FFF6EA"/><circle cx="318" cy="34" r="17" fill="none" stroke="#EFC9AE" stroke-width="3"/><path d="M318 25v9l6 4" stroke="#C98567" stroke-width="3" stroke-linecap="round" fill="none"/>
  <rect y="126" width="368" height="30" fill="#E99A7E"/>
  <path d="M238 60l40 44H198z" fill="url(#dk3l)" opacity=".7"/>
  <rect x="150" y="100" width="206" height="11" rx="5.5" fill="#C9875F"/><rect x="164" y="111" width="8" height="30" rx="4" fill="#B7764F"/><rect x="334" y="111" width="8" height="30" rx="4" fill="#B7764F"/>
  <path d="M238 100v-26l-16-22" stroke="#7E9C9A" stroke-width="4" stroke-linecap="round" fill="none"/><ellipse cx="238" cy="100" rx="14" ry="4" fill="#7E9C9A"/>
  <path d="M206 58l14-16 18 12-10 12z" fill="#EE7B5F"/><path d="M209 57l12-13" stroke="#fff" stroke-width="2" opacity=".5" stroke-linecap="round"/>
  <rect x="264" y="88" width="62" height="12" rx="3.5" fill="#A9CBA4"/><rect x="268" y="77" width="56" height="11" rx="3.5" fill="#A8C4E0"/><rect x="262" y="66" width="60" height="11" rx="3.5" fill="#C6B3E3"/>
  <path d="M270 91h40M274 80h36M268 69h40" stroke="#fff" stroke-width="2" opacity=".45" stroke-linecap="round"/>
  <rect x="178" y="80" width="20" height="20" rx="5" fill="#FFF6EA"/><path d="M198 85h3a4 4 0 0 1 0 9h-3" stroke="#FFF6EA" stroke-width="3" fill="none"/>
  <path d="M184 74q-3-5 0-9M191 74q-3-5 0-9" stroke="#fff" stroke-width="2.2" fill="none" stroke-linecap="round" opacity=".8"/>
  <g transform="translate(120 88) scale(.6)"><path d="M30 50C30 38 29 28 30 18" stroke="#6E9D6A" stroke-width="3" fill="none" stroke-linecap="round"/>
  <g fill="#8DBA86"><ellipse cx="19" cy="30" rx="12" ry="6.5" transform="rotate(-35 19 30)"/><ellipse cx="41" cy="24" rx="12" ry="6.5" transform="rotate(35 41 24)"/></g>
  <g fill="#A9CFA2"><ellipse cx="20" cy="44" rx="11" ry="6" transform="rotate(-20 20 44)"/><ellipse cx="40" cy="40" rx="11" ry="6" transform="rotate(25 40 40)"/><ellipse cx="30" cy="13" rx="6" ry="11"/></g>
  <path d="M13 54h34l-4 24a4 4 0 0 1-4 3.4H21a4 4 0 0 1-4-3.4z" fill="#F0D5B8"/><rect x="10" y="49" width="40" height="9" rx="4.5" fill="#F7E3CC"/><rect x="16" y="60" width="4" height="14" rx="2" fill="#fff" opacity=".45"/></g>
  <rect width="368" height="156" fill="url(#dk3f)"/></svg>''',
  'sprout': r'''<svg class="ill" viewBox="0 0 140 110" aria-hidden="true"><ellipse cx="70" cy="104" rx="46" ry="5" fill="#000" opacity=".06"/>
  <circle cx="70" cy="48" r="42" fill="var(--sage)"/><path d="M70 72V44" stroke="#6E9D6A" stroke-width="4" stroke-linecap="round"/>
  <path d="M70 52c0-12-10-19-22-19 0 12 10 19 22 19z" fill="#8DBA86"/><path d="M70 46c0-12 10-19 22-19 0 12-10 19-22 19z" fill="#A9CFA2"/>
  <path d="M46 72h48l-5 26a5 5 0 0 1-5 4H56a5 5 0 0 1-5-4z" fill="#F0D5B8"/><rect x="42" y="66" width="56" height="11" rx="5.5" fill="#F7E3CC"/>
  <path d="M110 22l2.4 6 6 2.4-6 2.4-2.4 6-2.4-6-6-2.4 6-2.4z" fill="#F5CF6A"/><path d="M28 30l1.6 4 4 1.6-4 1.6-1.6 4-1.6-4-4-1.6 4-1.6z" fill="#F4A58E"/></svg>''',
};
