"""Grade 11 English grammar notes (textbook PDF was image-scanned / unavailable).
Topics bridge Grade 10 → 12 Eritrea MoE English grammar progression: clause types,
nominalisation, discourse markers, mixed conditionals, advanced passives, register."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from eng_lib import G, U, build

units = [
 U(1, 'Complex sentences', [1, 18],
   'A complex sentence has one independent clause and at least one dependent clause.',
   [G('Independent and dependent clauses',
      ['An **independent clause** can stand alone as a sentence: *Students revise every evening.*',
       'A **dependent (subordinate) clause** cannot stand alone: *because the exam is near*.',
       'Join them without a comma splice: *Students revise every evening **because** the exam is near.*'],
      [('She left early because she felt ill.', True, None),
       ('Because she felt ill.', False, 'Because she felt ill, she left early.'),
       ('She left early, she felt ill.', False, 'She left early because she felt ill.')],
      pattern='independent + subordinating conjunction + dependent'),
    G('Finite and non-finite clauses',
      ['A **finite clause** has a tensed verb: *when he **arrives***.',
       'A **non-finite clause** uses infinitive, -ing, or -ed with no tense: *to arrive early*, *arriving early*, *surprised by the news*.',
       'Non-finite clauses keep writing compact for essays and reports.'],
      [('Hoping to win, they trained harder.', True, None),
       ('Hope to win, they trained harder.', False, 'Hoping to win, they trained harder.'),
       ('To finish on time is important.', True, None)])],
   (['Clause', 'Example'],
    [['Independent', 'The class starts at eight.'],
     ['Dependent (because)', 'because the bus was late'],
     ['Non-finite (-ing)', 'Walking to school, …'],
     ['Non-finite (to-)', 'To pass, you must practise.']]),
   [('She failed. Because she did not revise.', 'She failed because she did not revise.', 'Do not leave a dependent clause as its own sentence.'),
    ('Although tired. He continued.', 'Although tired, he continued.', 'Attach the dependent idea to a main clause.')],
   'Underline the main verb; if the group still needs another clause, it is dependent.',
   'Complex sentences = one free-standing clause + one or more dependent clauses (finite or non-finite).',
   [('m', 'Which group is a dependent clause?',
     ['The lights went out', 'because the power failed', 'Students opened books', 'Open the door'],
     'B', 'B starts with because and cannot stand alone. | A, C, and D can stand alone.'),
    ('f', 'Join with because: The match stopped ____ it rained heavily.', 'because', ['because', 'so', 'and', 'but'],
     'because introduces the reason clause. | so would reverse cause and effect.')],
   [('Which is independent?', 'The lights went out'), ('Which needs a main clause?', 'because the power failed')],
   match=(r'complex', r'clause', r'subordinat'),
   terms=[('independent clause', 'a clause that can be a complete sentence'),
          ('dependent clause', 'a clause that cannot stand alone')]),

 U(2, 'Relative clauses', [19, 36],
   'Relative clauses add information about a noun using who, which, that, whose, where, when.',
   [G('Defining vs non-defining',
      ['A **defining** relative clause identifies which person/thing: *The student **who arrived late** missed the quiz.* (no commas)',
       'A **non-defining** clause adds extra information about an already clear noun: *Asmara, **which is the capital**, is cool in July.* (commas)',
       'Do not use **that** in non-defining clauses.'],
      [('The book that I borrowed is new.', True, None),
       ('Asmara, that is the capital, is cool.', False, 'Asmara, which is the capital, is cool.'),
       ('My brother, who lives in Keren, called.', True, None)],
      pattern='noun + who/which/that …'),
    G('Whose, where, when',
      ['**whose** = possession: *the teacher whose class we joined*',
       '**where** = place: *the school where we study*',
       '**when** = time: *the year when Eritrea became independent*'],
      [('the girl whose bag was lost', True, None),
       ('the girl who bag was lost', False, 'the girl whose bag was lost'),
       ('the town where I was born', True, None)])],
   (['Relative', 'Use'],
    [['who', 'people (subject)'],
     ['which', 'things / non-defining'],
     ['that', 'people or things (defining only)'],
     ['whose', 'possession'],
     ['where / when', 'place / time']]),
   [('The man which helped us…', 'The man who helped us…', 'Use who for people.'),
    ('My phone, that is new, …', 'My phone, which is new, …', 'Non-defining → which, with commas.')],
   'If removing the clause still leaves a clear noun, use commas (non-defining).',
   'Defining clauses identify; non-defining clauses add extras with commas; never use that after a comma.',
   [('m', 'Choose the correct relative pronoun: Asmara, ____ is highland, has mild summers.',
     ['that', 'which', 'who', 'whose'], 'B',
     'Non-defining clause about a place → which. | that is wrong after a comma.'),
    ('f', 'The student ____ essay won the prize is in Grade 11.', 'whose', ['whose', 'who', 'which', 'where'],
     'whose marks possession (essay belongs to the student).')],
   [('Defining (no commas)', 'the student who arrived late'), ('Non-defining (commas)', 'Asmara, which is the capital, …')],
   match=(r'relative', r'who', r'which', r'clause'),
   terms=[('defining clause', 'identifies which noun you mean'),
          ('non-defining clause', 'adds extra information, set off by commas')]),

 U(3, 'Conditionals (mixed and review)', [37, 54],
   'Review types 0–3, then mix time references for past cause + present result.',
   [G('Types 0–3 in brief',
      ['**0** facts: *If you heat ice, it melts.* (present + present)',
       '**1** real future: *If it rains, we will stay in.* (present + will)',
       '**2** unreal present: *If I had time, I would help.* (past + would)',
       '**3** unreal past: *If she had revised, she would have passed.* (had + would have)'],
      [('If I were you, I would apologise.', True, None),
       ('If I will see her, I tell her.', False, 'If I see her, I will tell her.'),
       ('If they had left earlier, they would have arrived on time.', True, None)]),
    G('Mixed conditionals',
      ['Past cause → present result: *If I **had studied** medicine, I **would be** a doctor now.*',
       'Present (ongoing) cause → past result: *If she **were** more careful, she **would not have broken** it.*',
       'Keep the if-clause and main clause times consistent with the meaning you intend.'],
      [('If he had taken the bus, he would be here now.', True, None),
       ('If he took the bus, he would have been here now.', False, 'If he had taken the bus, he would be here now.'),
       ('If I were taller, I would have joined the team last year.', True, None)])],
   (['Type', 'Form'],
    [['0', 'If + present, present'],
     ['1', 'If + present, will + V'],
     ['2', 'If + past, would + V'],
     ['3', 'If + had + PP, would have + PP'],
     ['Mixed', 'If + had + PP, would + V (now)']]),
   [('If I would have known…', 'If I had known…', 'Never put would in the if-clause of type 2/3.'),
    ('If she studied, she would have passed.', 'If she had studied, she would have passed.', 'Unreal past needs had + past participle.')],
   'Ask: is the cause past or present? Is the result past or present? Then pick the matching half.',
   'Conditionals link cause and result; mixed forms combine past if-clauses with present results (and the reverse).',
   [('m', 'If they ____ harder last term, they would be in the top class now.',
     ['study', 'studied', 'had studied', 'would study'], 'C',
     'Past cause → had studied; present result → would be. | Mixed conditional.'),
    ('f', 'If it rains tomorrow, we ____ indoors.', 'will stay', ['will stay', 'would stay', 'stayed', 'had stayed'],
     'Type 1 real future uses will + verb.')],
   [('Type 3', 'If she had revised, she would have passed.'), ('Mixed', 'If I had studied medicine, I would be a doctor now.')],
   match=(r'conditional', r'if ', r'would'),
   terms=[('mixed conditional', 'if-clause and result clause refer to different times')]),

 U(4, 'Advanced passives and reporting', [55, 72],
   'Passives shift focus to the action or receiver; reporting verbs introduce other people’s words or views.',
   [G('Passive with modals and perfects',
      ['Modal + be + past participle: *The essay **must be submitted** today.*',
       'Perfect passive: *The results **have been published**.* / *The room **had been cleaned**.*',
       'Use passive when the doer is unknown, obvious, or less important.'],
      [('The work must be finished by Friday.', True, None),
       ('The work must finished by Friday.', False, 'The work must be finished by Friday.'),
       ('The notices have been posted.', True, None)]),
    G('Reporting verbs and structures',
      ['Say/tell/ask + clause: *She said (that) she was ready.* / *He told us to wait.*',
       'Suggest/recommend + -ing or that-clause: *They suggested revising together.*',
       'Claim/argue/insist that… are useful in formal essays.'],
      [('He told me to arrive early.', True, None),
       ('He said me to arrive early.', False, 'He told me to arrive early. / He said (that) I should arrive early.'),
       ('The writer argues that literacy builds opportunity.', True, None)])],
   (['Active', 'Passive'],
    [['Someone stole the phone.', 'The phone was stolen.'],
     ['They must submit forms.', 'Forms must be submitted.'],
     ['They have published results.', 'Results have been published.']]),
   [('The letter sent yesterday.', 'The letter was sent yesterday.', 'Passive needs be + past participle.'),
    ('She said me the truth.', 'She told me the truth.', 'tell takes an object person; say usually does not.')],
   'Ask: do I need the doer? If not, prefer passive for formal tone.',
   'Advanced passives use modals and perfects; reporting verbs package other voices for essays and news.',
   [('m', 'Choose the correct passive: The homework ____ before Friday.',
     ['must submit', 'must be submitted', 'must submitted', 'must be submit'], 'B',
     'must + be + past participle.'),
    ('f', 'Rewrite focus: Someone has opened the gate. → The gate ____.', 'has been opened',
     ['has been opened', 'has opened', 'was open', 'is opening'],
     'Present perfect passive = has/have been + past participle.')],
   [('Modal passive', 'must be submitted'), ('Reporting', 'She argued that …')],
   match=(r'passive', r'report', r'modal'),
   terms=[('reporting verb', 'a verb that introduces speech or opinion (say, claim, argue)')]),

 U(5, 'Nominalisation and formal register', [73, 88],
   'Academic writing often turns verbs and adjectives into nouns (nominalisation) and prefers formal vocabulary.',
   [G('Nominalisation',
      ['Verb → noun: *decide → decision*, *develop → development*, *fail → failure*.',
       'Adjective → noun: *important → importance*, *possible → possibility*.',
       'Nominal style: *The **rapid expansion** of towns creates pressure on services.*'],
      [('Their decision surprised everyone.', True, None),
       ('They decide surprised everyone.', False, 'Their decision surprised everyone.'),
       ('The importance of literacy is clear.', True, None)],
      pattern='the + noun (+ of …)'),
    G('Formal vs informal',
      ['Prefer precise verbs: *obtain, require, demonstrate* over *get, need, show* in formal essays.',
       'Avoid chatty fillers (*well, you know, lots of*) and contractions in formal exams.',
       'Keep a respectful tone: *Could you clarify…?* rather than *What do you want?*'],
      [('The study demonstrates a clear trend.', True, None),
       ('The study shows stuff pretty well.', False, 'The study demonstrates a clear trend.'),
       ('Candidates are required to arrive early.', True, None)])],
   (['Everyday', 'More formal'],
    [['get better', 'improve / recover'],
     ['a lot of', 'many / a large number of'],
     ['kids', 'children / young people'],
     ['find out', 'discover / determine']]),
   [('Because of the rain, cancel happened.', 'Because of the rain, cancellation occurred. / The rain caused cancellation.',
     'Use a real noun form of the verb.'),
    ('We gotta finish ASAP.', 'We must finish as soon as possible.', 'Avoid slang in exam writing.')],
   'When a sentence feels “spoken”, try replacing a verb with a noun phrase of the same idea.',
   'Nominalisation and formal word choice raise register for academic and exam writing.',
   [('m', 'Which sentence is most formal?',
     ['Kids gotta learn stuff.', 'Young people must acquire knowledge.', 'Guys need to get facts.', 'We wanna know things.'],
     'B', 'B uses formal vocabulary (acquire, knowledge) without slang.'),
    ('f', 'Nominalise: They decided quickly. → Their ____ was quick.', 'decision',
     ['decision', 'decide', 'deciding', 'decided'],
     'decide → decision.')],
   [('Nominalisation', 'the expansion of towns'), ('Formal', 'demonstrate / require / obtain')],
   match=(r'nominal', r'formal', r'register', r'academic'),
   terms=[('nominalisation', 'forming a noun from a verb or adjective'),
          ('register', 'level of formality in language')]),

 U(6, 'Cohesion and discourse markers', [89, 104],
   'Cohesion links sentences so the paragraph reads as one argument, not a list of facts.',
   [G('Discourse markers',
      ['Addition: *moreover, furthermore, in addition*',
       'Contrast: *however, nevertheless, on the other hand*',
       'Cause/result: *therefore, consequently, as a result*',
       'Example/clarifying: *for instance, that is, in other words*'],
      [('The roads flooded; therefore schools closed.', True, None),
       ('The roads flooded; however schools closed.', False, 'The roads flooded; therefore schools closed.'),
       ('Moreover, attendance improved after the campaign.', True, None)]),
    G('Reference and lexical cohesion',
      ['Use pronouns carefully: *this / these / such* to point back to a clear noun idea.',
       'Repeat key nouns or use synonyms to keep the topic visible.',
       'Avoid vague *this* when the reader cannot see what it refers to.'],
      [('Pollution rose. This increase worried officials.', True, None),
       ('Pollution rose. This worried.', False, 'Pollution rose. This increase worried officials.'),
       ('Farmers and growers both need water.', True, None)])],
   (['Marker', 'Job'],
    [['however', 'contrast'],
     ['therefore', 'result'],
     ['for example', 'illustration'],
     ['in conclusion', 'closing']]),
   [('And then also too…', 'Furthermore, … / In addition, …', 'Stacking casual add-ons weakens formal cohesion.'),
    ('This proves it.', 'This result / This evidence proves the claim.', 'Make the reference noun clear.')],
   'After each sentence, ask: how does the next sentence connect—add, contrast, or result?',
   'Discourse markers and clear reference glue sentences into coherent paragraphs.',
   [('m', 'Best marker: Rain fell for three days; ____ the river burst its banks.',
     ['however', 'for example', 'therefore', 'although'], 'C',
     'therefore shows result.'),
    ('f', 'Choose a contrast marker: The plan looked easy; ____ it failed.', 'however',
     ['however', 'therefore', 'moreover', 'for instance'],
     'however signals contrast.')],
   [('Result', 'therefore / consequently'), ('Contrast', 'however / on the other hand')],
   match=(r'cohesion', r'discourse', r'however', r'therefore', r'paragraph'),
   terms=[('discourse marker', 'a word/phrase that shows how ideas connect'),
          ('cohesion', 'links that hold a text together')]),

 U(7, 'Verb patterns: gerunds and infinitives', [105, 118],
   'After some verbs you must use -ing; after others to + verb; a few allow both with a meaning change.',
   [G('Common patterns',
      ['**enjoy / avoid / suggest / finish / keep** + -ing: *She enjoys reading.*',
       '**want / decide / hope / plan / afford** + to-infinitive: *They decided to wait.*',
       '**stop + -ing** = quit a habit; **stop + to-infinitive** = pause in order to do something.'],
      [('He suggested revising together.', True, None),
       ('He suggested to revise together.', False, 'He suggested revising together.'),
       ('We stopped to rest.', True, None)]),
    G('Adjective + infinitive; preposition + -ing',
      ['*easy / hard / important / ready* + to-infinitive: *It is important to listen.*',
       'After a preposition use -ing: *interested in learning*, *good at solving*, *before leaving*.'],
      [('She is interested in studying history.', True, None),
       ('She is interested in to study history.', False, 'She is interested in studying history.'),
       ('It is hard to refuse help.', True, None)])],
   (['Pattern', 'Example'],
    [['enjoy + -ing', 'enjoy swimming'],
     ['decide + to', 'decide to stay'],
     ['stop + -ing', 'stop smoking'],
     ['stop + to', 'stop to smoke (pause)']]),
   [('I look forward to meet you.', 'I look forward to meeting you.', 'to is a preposition here → -ing.'),
    ('He avoided to answer.', 'He avoided answering.', 'avoid takes -ing.')],
   'Memorise high-frequency verb lists; when unsure, check whether a preposition is present.',
   'Gerund and infinitive patterns are fixed by the verb or preposition that comes before them.',
   [('m', 'Choose correctly: She decided ____ the scholarship.',
     ['applying for', 'to apply for', 'apply for', 'to applying for'], 'B',
     'decide + to-infinitive.'),
    ('f', 'After a preposition: He is good at ____ maps.', 'reading', ['reading', 'to read', 'read', 'reads'],
     'preposition + -ing.')],
   [('Gerund', 'enjoy reading'), ('Infinitive', 'hope to win')],
   match=(r'gerund', r'infinitive', r'verb pattern'),
   terms=[('gerund', 'the -ing form used as a noun'),
          ('infinitive', 'to + base verb')]),

 U(8, 'Sentence combining and punctuation', [119, 132],
   'Clear punctuation prevents run-ons and fragments in exam essays.',
   [G('Avoiding run-ons and comma splices',
      ['Two independent clauses need a full stop, semicolon, or conjunction: *It rained. We stayed in.* / *It rained; we stayed in.* / *It rained, so we stayed in.*',
       'A **comma splice** joins two full sentences with only a comma — fix it.',
       'Fragments lack a main clause: *While waiting for the bus.* → complete it.'],
      [('It rained, so we stayed in.', True, None),
       ('It rained, we stayed in.', False, 'It rained, so we stayed in. / It rained; we stayed in.'),
       ('While waiting for the bus, we revised notes.', True, None)]),
    G('Useful combining tools',
      ['Coordinators: *and, but, or, so, yet*',
       'Subordinators: *because, although, when, if, while*',
       'Semicolon + conjunctive adverb: *however, therefore, meanwhile*'],
      [('Although the test was hard, she scored well.', True, None),
       ('Although the test was hard. She scored well.', False, 'Although the test was hard, she scored well.'),
       ('The lights failed; however, the exam continued.', True, None)])],
   (['Problem', 'Fix'],
    [['Comma splice', 'add so/but or use a full stop'],
     ['Fragment', 'attach to a main clause'],
     ['Run-on', 'split or add a conjunction']]),
   [('I was tired, I slept early.', 'I was tired, so I slept early.', 'Comma alone cannot join two sentences.'),
    ('Because I was tired.', 'Because I was tired, I slept early.', 'Complete the dependent clause.')],
   'Read aloud: if you hear two finished thoughts, check the join.',
   'Combine sentences with coordinators, subordinators, or semicolons; never with a bare comma.',
   [('m', 'Which sentence is correctly punctuated?',
     ['He studied, he passed.', 'He studied he passed.', 'He studied, so he passed.', 'He studied. so he passed.'],
     'C', 'C joins with a comma + coordinating conjunction.'),
    ('f', 'Fix the fragment: While the teacher explained. → While the teacher explained, ____.',
     'we took notes', ['we took notes', 'taking notes', 'and notes', 'notes'],
     'Add an independent clause after the dependent clause.')],
   [('Comma splice fix', '…, so …'), ('Semicolon', '…; however, …')],
   match=(r'punctuation', r'comma', r'sentence', r'run-?on'),
   terms=[('comma splice', 'joining two sentences with only a comma'),
          ('fragment', 'a group of words that is not a complete sentence')]),
]

if __name__ == '__main__':
    build(11, 'English Grade 11 · Grammar', units,
          'Topics follow the Grade 10→12 Eritrea MoE English grammar progression (complex sentences, relative clauses, mixed conditionals, passives/reporting, nominalisation, cohesion, verb patterns, punctuation). Textbook PDF on Drive was image-based and could not be OCR’d in this pass; regenerate from the PDF when text extraction is available.')
    print('english_11 built')
