#!/usr/bin/env python3
"""GENERATOR: lib/high/widgets/art_data.dart from the web app. Icons (`P`, 24x24 stroke paths) and the original
illustrations (`ART.student/plant/kokob/desk/sprout`) are evaluated in the real page (Playwright) so the Dart strings are
exactly what the web draws. var(--x) / currentColor are themed at runtime by widgets/art.dart.
    python3 tool/gen_art.py [/workspace/high/design/reference.html]"""
import asyncio, json, os, sys
from playwright.async_api import async_playwright
HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = sys.argv[1] if len(sys.argv) > 1 else '/workspace/high/design/reference.html'

async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch(); pg = await b.new_page()
        await pg.goto('file://' + SRC)
        d = await pg.evaluate("""() => { gid = 0; return {P, art: {student: ART.student(), plant: ART.plant(), kokob: ART.kokob(), desk: ART.desk(), sprout: ART.sprout()}}; }""")
        await b.close()
    def raw(x):
        assert "'''" not in x
        return "r'''" + x + "'''"
    out = ['// GENERATED by tool/gen_art.py from the Warsay Prep / High web app (icons `P`, illustrations `ART`). Do not edit by hand.',
           '// ignore_for_file: lines_longer_than_80_chars', '', 'const Map<String, String> kIcons = {']
    out += ['  %s: %s,' % (json.dumps(k), raw(v)) for k, v in d['P'].items()]
    out += ['};', '', 'const Map<String, String> kArt = {']
    out += ['  %s: %s,' % (json.dumps(k), raw(v)) for k, v in d['art'].items()]
    out += ['};', '']
    dst = os.path.join(HERE, 'lib', 'high', 'widgets', 'art_data.dart')
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    open(dst, 'w', encoding='utf-8').write('\n'.join(out).replace('  "', "  '").replace('": r', "': r"))
    print(len(d['P']), 'icons,', len(d['art']), 'illustrations ->', dst)

asyncio.run(main())
