// High: notes content. A file unit_<id>.json replaces that unit when present.
//
// Opening a unit reads only that unit: assets/high/notes/split/<unitId>.json (a one-unit book made at build time by
// tool/split_notes.py, ~25-100 KB) is parsed in a background isolate and the last few units stay cached ([unitBook]).
// When the split file is missing (a build without the split step) the full book file is read instead, and still only
// the opened unit is turned into models.
import 'dart:async';
import 'dart:convert';
import '../../../data/off_thread.dart';

import '../../../media/media.dart' show MediaLib;
import 'package:flutter/services.dart';
import 'notes_models.dart';
import 'subjects.dart';

class IndexUnit {
  IndexUnit(this.id, this.number, this.title, this.pages, this.questions, this.topics);
  final String id, title;
  final int number, questions;
  final List<int> pages;
  final List<({String id, String number, String title, int? page, List<String> cards})> topics;
}

class IndexBook {
  IndexBook(this.id, this.file, this.title, this.subject, this.grade, this.units);
  final String id, file, title, subject;
  final int grade;
  final List<IndexUnit> units;
  NotesSubject get look => notesSubject(subject);
}

class MapNode {
  MapNode(this.id, this.label, this.kind, this.cards);
  final String id, label, kind;
  final List<String> cards;
}

class UnitMap {
  UnitMap(this.root, this.nodes, this.edges);
  final String root;
  final List<MapNode> nodes;
  final List<({String from, String to, String label})> edges;
}

class BookExtras {
  BookExtras(this.maps, this.cardKey);
  final Map<String, UnitMap> maps;
  final Map<String, String> cardKey;
}

class NotesRepo {
  NotesRepo({AssetBundle? bundle, this.useIsolate = false, this.deferExtras = false}) : bundle = bundle ?? rootBundle;
  final AssetBundle bundle;
  final bool useIsolate;

  /// app: unit_questions.json (0.8 MB) and the media placements are read in the background after [init] instead of
  /// before the first screen; [extrasReady] completes when they are in
  final bool deferExtras;
  Future<void> extrasReady = Future.value();
  static const base = 'assets/high/notes/notes';

  /// per-unit files generated by tool/split_notes.py (git-ignored, made in CI before `flutter build`)
  static const splitBase = 'assets/high/notes/split';

  /// opened units kept in memory (a 1 GB phone should not hold whole textbooks)
  static const keepUnits = 4;

  final List<IndexBook> books = [];
  final Map<String, List<Map<String, dynamic>>> unitQuestions = {};
  final Map<String, NotesBook> _books = {};
  final Map<String, BookExtras> _extras = {};
  final Map<String, Future<NotesBook>> _loads = {};
  final Map<String, (NotesBook, BookExtras)> _units = {}; // insertion order = LRU order
  final Map<String, Future<NotesBook>> _unitLoads = {};

  /// how the last [unitBook] call got its unit: 'split', 'book' (fallback to the full file) or 'cache'
  String? lastUnitSource;
  bool loaded = false;
  List<Map<String, dynamic>> placements = [];

  Future<void> init() async {
    Map<String, dynamic> idx;
    try {
      final raw = await bundle.loadString('$base/index.json', cache: false);
      idx = (useIsolate ? await offThread(decodeJson, raw) : jsonDecode(raw)) as Map<String, dynamic>;
    } catch (_) {
      loaded = true;
      return;
    }
    _addGradeMap((idx['grades'] as Map?) ?? const {});
    try {
      final extra = jsonDecode(await bundle.loadString('$base/english_index.json')) as Map<String, dynamic>;
      _addGradeMap((extra['grades'] as Map?) ?? const {});
    } catch (_) {}
    books.sort((a, b) => a.grade != b.grade ? a.grade - b.grade : _ord(a.subject) - _ord(b.subject));
    if (deferExtras) {
      loaded = true;
      extrasReady = _loadExtras();
      return;
    }
    await _loadExtras();
    loaded = true;
  }

  Future<void> _loadExtras() async {
    try {
      final raw = await bundle.loadString('assets/high/notes/unit_questions.json', cache: false);
      final uq = (useIsolate ? await offThread(decodeJson, raw) : jsonDecode(raw)) as Map<String, dynamic>;
      for (final e in ((uq['units'] as Map?) ?? const {}).entries) {
        unitQuestions['${e.key}'] = [for (final x in (e.value as List? ?? const [])) if (x is Map) Map<String, dynamic>.from(x)];
      }
    } catch (_) {}
    // credits loaded on first book open (see book())
    placements = [];
    for (final path in ['assets/high/media/placements.json', 'assets/high/media/taxonomy_extra.json', 'assets/high/media/g11_extra.json', 'assets/high/media/commons_extra.json']) {
      try {
        final pj = jsonDecode(await bundle.loadString(path)) as Map<String, dynamic>;
        placements.addAll([for (final x in (pj['cards'] as List? ?? const [])) if (x is Map) Map<String, dynamic>.from(x)]);
      } catch (_) {}
    }
  }

  void _addGradeMap(Map grades) {
    for (final ge in grades.entries) {
      final g = int.tryParse('${ge.key}') ?? 0;
      for (final se in ((ge.value as Map?) ?? const {}).entries) {
        final b = se.value as Map;
        final id = '${b['book']}';
        if (books.any((x) => x.id == id)) continue;
        books.add(IndexBook(id, '${b['file']}', '${b['title'] ?? ''}', '${se.key}', g, [
          for (final u in (b['units'] as List? ?? const []))
            if (u is Map)
              IndexUnit('${u['id']}', (u['number'] as num?)?.toInt() ?? 0, '${u['title'] ?? ''}', [for (final p in (u['pages'] as List? ?? const [])) (p as num).toInt()], (u['questions'] as num?)?.toInt() ?? 0, [
                for (final t in (u['topics'] as List? ?? const []))
                  if (t is Map) (id: '${t['id']}', number: '${t['number'] ?? ''}', title: '${t['title'] ?? ''}', page: (t['page'] as num?)?.toInt(), cards: [for (final c in (t['cards'] as List? ?? const [])) '$c']),
              ]),
        ]));
      }
    }
  }

  static void injectMedia(Object? raw, List<Map<String, dynamic>> pl) {
    if (pl.isEmpty || raw is! Map) return;
    final by = <String, List<Map<String, dynamic>>>{};
    for (final x in pl) {
      (by['${x['lesson']}'] ??= []).add(Map<String, dynamic>.from(x['card'] as Map));
    }
    for (final u in (raw['units'] as List? ?? const [])) {
      if (u is! Map) continue;
      for (final l in (u['lessons'] as List? ?? const [])) {
        if (l is! Map) continue;
        final add = by[l['id']];
        if (add == null) continue;
        final pg = (l['pages'] as List?)?.firstOrNull ?? 0;
        (l['cards'] as List).addAll([for (final c in add) {'type': 'media', 'page': pg, ...c}]);
      }
    }
  }

  static int _ord(String s) {
    final i = kNotesOrder.indexOf(s);
    return i < 0 ? 99 : i;
  }

  List<int> get grades => ({for (final b in books) b.grade}.toList()..sort());
  List<IndexBook> grade(int g) => books.where((b) => b.grade == g).toList();
  IndexBook? byId(String id) => books.where((b) => b.id == id).firstOrNull;
  int get totalUnits => books.fold(0, (a, b) => a + b.units.length);

  ({IndexBook book, IndexUnit unit})? unitById(String uid) {
    for (final b in books) {
      for (final u in b.units) {
        if (u.id == uid) return (book: b, unit: u);
      }
    }
    return null;
  }

  NotesBook? bookIfLoaded(String id) => _books[id];
  BookExtras? extras(String id) => _extras[id];

  /// concept maps / card keys of one unit, from the full book if it is loaded, else from the unit's own load
  BookExtras? unitExtras(String bookId, String unitId) => _extras[bookId] ?? _units[unitId]?.$2;

  /// A book holding just [unitId] (with the book's info), for the unit page. Reads the unit's split file
  /// (`assets/high/notes/split/<unitId>.json`); falls back to the full book file. Parsed off the UI thread.
  Future<NotesBook> unitBook(String bookId, String unitId) {
    final full = _books[bookId];
    if (full != null && full.unit(unitId) != null) {
      lastUnitSource = 'cache';
      return Future.value(full);
    }
    final hit = _units.remove(unitId);
    if (hit != null) {
      _units[unitId] = hit; // most recently used
      lastUnitSource = 'cache';
      return Future.value(hit.$1);
    }
    return _unitLoads[unitId] ??= () async {
      try {
        await extrasReady;
        await MediaLib.load(bundle);
        final file = byId(bookId)?.file ?? '$bookId.json';
        String? split;
        try {
          split = await bundle.loadString('$splitBase/$unitId.json', cache: false);
        } catch (_) {}
        (NotesBook, BookExtras)? r;
        if (split != null && split.isNotEmpty) {
          final job = (book: split, unitId: unitId, override: null, placements: placements, file: file);
          try {
            r = useIsolate ? await offThread(_parseUnit, job) : _parseUnit(job);
          } catch (_) {
            r = null; // broken / foreign split file: use the book
          }
        }
        if (r != null && r.$1.unit(unitId) != null) {
          lastUnitSource = 'split';
        } else {
          final s = await bundle.loadString('$base/$file', cache: false);
          String? ov;
          try {
            ov = await bundle.loadString('$base/unit_$unitId.json', cache: false);
          } catch (_) {}
          final job = (book: s, unitId: unitId, override: ov, placements: placements, file: file);
          r = useIsolate ? await offThread(_parseUnit, job) : _parseUnit(job);
          lastUnitSource = 'book';
        }
        final got = r!;
        _units[unitId] = got;
        while (_units.length > keepUnits) {
          _units.remove(_units.keys.first);
        }
        return got.$1;
      } finally {
        _unitLoads.remove(unitId);
      }
    }();
  }

  /// book JSON (full, or a one-unit split file) -> a book with only [unitId] in it (static: runs in an isolate).
  /// Units other than the requested one are dropped before any model is built.
  static (NotesBook, BookExtras) _parseUnit(({String book, String unitId, String? override, List<Map<String, dynamic>> placements, String file}) j) {
    final raw = jsonDecode(j.book);
    if (raw is Map && raw['units'] is List) {
      Object? one;
      for (final u in raw['units'] as List) {
        if (u is Map && '${u['id']}' == j.unitId) {
          one = u;
          break;
        }
      }
      if (one != null && j.override != null) {
        try {
          one = jsonDecode(j.override!);
        } catch (_) {}
      }
      raw['units'] = [?one];
    }
    injectMedia(raw, j.placements);
    return (NotesBook.fromJson(raw, j.file), _parseExtras(raw));
  }

  Future<NotesBook> book(String id) {
    final hit = _books[id];
    if (hit != null) return Future.value(hit);
    return _loads[id] ??= () async {
      await extrasReady;
      await MediaLib.load(bundle);
      final file = byId(id)?.file ?? '$id.json';
      final s = await bundle.loadString('$base/$file', cache: false);
      // all JSON work happens off the UI thread (it used to decode the book, every unit file and re-encode the merge
      // here, a long frame drop when a unit was first opened): ask for the unit ids, then load the unit files together
      final ids = useIsolate ? await offThread(_unitIds, s) : _unitIds(s);
      final unitRaw = <String, String>{};
      await Future.wait([
        for (final id in ids)
          bundle.loadString('$base/unit_$id.json', cache: false).then((t) => unitRaw[id] = t, onError: (Object _) => ''),
      ]);
      final job = (book: s, units: unitRaw, placements: placements, file: file);
      final r = useIsolate ? await offThread(_parseBook, job) : _parseBook(job);
      _books[id] = r.$1;
      _extras[id] = r.$2;
      return r.$1;
    }();
  }

  /// book JSON + its unit files -> models (static: runs in a background isolate, see off_thread.dart)
  static (NotesBook, BookExtras) _parseBook(({String book, Map<String, String> units, List<Map<String, dynamic>> placements, String file}) j) {
    final raw = jsonDecode(j.book);
    if (raw is Map && raw['units'] is List) {
      final units = raw['units'] as List;
      for (var i = 0; i < units.length; i++) {
        final u = units[i];
        if (u is! Map || u['id'] == null) continue;
        final t = j.units['${u['id']}'];
        if (t == null) continue;
        try {
          units[i] = jsonDecode(t);
        } catch (_) {}
      }
    }
    injectMedia(raw, j.placements);
    return (NotesBook.fromJson(raw, j.file), _parseExtras(raw));
  }

  /// ids of the units a book file lists (each has its own `unit_<id>.json`)
  static List<String> _unitIds(String bookJson) {
    final raw = jsonDecode(bookJson);
    if (raw is! Map || raw['units'] is! List) return const [];
    return [
      for (final u in raw['units'] as List)
        if (u is Map && u['id'] != null) '${u['id']}',
    ];
  }

  static BookExtras _parseExtras(Object? raw) {
    final maps = <String, UnitMap>{}, keys = <String, String>{};
    for (final u in ((raw as Map)['units'] as List? ?? const [])) {
      if (u is! Map) continue;
      for (final l in (u['lessons'] as List? ?? const [])) {
        if (l is! Map) continue;
        final cs = l['cards'] as List? ?? const [];
        for (var i = 0; i < cs.length; i++) {
          final c = cs[i];
          if (c is Map && c['id'] != null) keys['${c['id']}'] = '${l['id']}~$i';
        }
      }
      final m = u['unitMap'];
      if (m is Map) {
        maps['${u['id']}'] = UnitMap('${m['root']}', [
          for (final n in (m['nodes'] as List? ?? const []))
            if (n is Map) MapNode('${n['id']}', '${n['label']}', '${n['kind'] ?? 'idea'}', [for (final c in (n['cards'] as List? ?? const [])) '$c']),
        ], [
          for (final e in (m['edges'] as List? ?? const []))
            if (e is Map) (from: '${e['from']}', to: '${e['to']}', label: '${e['label'] ?? ''}'),
        ]);
      }
    }
    return BookExtras(maps, keys);
  }

  String svgPath(String svg) => '$base/$svg';
}
