"""Unit 1 (Endocrine system), lesson 1.1: 1.1.1 pituitary, 1.1.2 thyroid, 1.1.4 adrenal, 1.1.5 pancreas, 1.1.6 sex glands, 1.1.7 thymus.
Textbook: Biology for Grade 11 (Eritrea), pp. 1-20. Hormone chemical nature / feedback / excess-deficiency details that the
textbook does not print are standard Grade 11-12 biology and are marked as such in the cards."""
from common import *

set_unit('bio11-u1')
L11 = 'bio11-u1-l1-1'

# ------------------------------------------------------------------ 1.1 basics (before the glands)
BASICS = [
    T('s110-c1', 'Before the glands: hormone, target, feedback — the four words you need', 1,
      '**Step 1 — two kinds of gland.** An **exocrine gland** (exo = out) pours its juice through a **duct** onto a surface or into a cavity: sweat, saliva, tears, pancreatic juice. An **endocrine gland** (endo = within) has **no duct**: it releases its product straight into the **blood** (or lymph) that flows through it. That is why endocrine glands have a **rich blood supply**.',
      '**Step 2 — the product is a hormone.** “Hormone” means “to urge on”. A hormone is a **chemical messenger**, made in very small (minute) amounts, released in response to a **specific stimulus**, and carried by the blood to the whole body.',
      '**Step 3 — only target cells answer.** Every cell meets the hormone, but only cells with the matching **receptor** respond. These are the **target cells / target organ**. Example: TSH reaches every organ, but only the thyroid has TSH receptors.',
      '**Step 4 — the level is kept steady by feedback.** The brain (hypothalamus) and the pituitary measure the hormone level. When the level is too high they **switch the gland off**; when it is too low they switch it on. This is **negative feedback** — the result works against (negates) the change.',
      '**Step 5 — two ways a gland is told to secrete** (textbook p.2): (i) by **nerve impulses** from the central nervous system (e.g. adrenal medulla), or (ii) by a **hormone from another gland** (e.g. the thyroid obeys TSH from the pituitary).'),
    TB('s110-t1', 'Endocrine vs exocrine glands', 1, ['Feature', 'Endocrine (ductless)', 'Exocrine (duct)'], [
        ['Duct', 'None', 'Has a duct'],
        ['Product', 'Hormones', 'Enzymes, sweat, mucus, tears…'],
        ['Goes to', 'Blood → whole body → target cells', 'A surface or cavity (skin, mouth, gut)'],
        ['Amount', 'Minute amounts', 'Often large volumes'],
        ['Speed of effect', 'Slow, long-lasting', 'Local, fairly quick'],
        ['Examples', 'Pituitary, thyroid, adrenal, islets', 'Sweat, salivary, tear glands'],
        ['Both in one organ', 'Pancreas (islets) and gonads (hormones)', 'Pancreas (juice) and gonads (gametes)'],
    ]),
    TB('s110-t2', 'Chemical nature of hormones — three families', 1, ['Family', 'Made from', 'Dissolves in', 'How it works', 'Examples in this unit'], [
        ['**Protein / peptide**', 'Chains of amino acids', 'Water (blood plasma)', 'Binds a receptor on the cell **surface**; a second messenger inside acts', 'GH, TSH, ACTH, FSH, LH, prolactin, ADH, oxytocin, insulin, glucagon, calcitonin, PTH, thymosin'],
        ['**Amine** (amino-acid derived)', 'One amino acid (tyrosine, tryptophan)', 'Adrenaline: water · thyroxine: fat', 'Adrenaline: surface receptor · thyroxine: enters the cell', 'Adrenaline, noradrenaline, thyroxine, melatonin'],
        ['**Steroid**', 'Cholesterol (a lipid)', 'Fat — passes through membranes', 'Enters the cell, binds a receptor inside, switches genes on/off', 'Cortisol, aldosterone, testosterone, oestrogen, progesterone'],
    ]),
    RM('s110-r1', 'Why chemical nature matters in exams', 1,
       '**Insulin is a protein**, so if swallowed it is digested like meat in the stomach and intestine — that is why diabetics **inject** insulin.',
       '**Steroids are lipids**, so they are made in cells rich in smooth ER (adrenal cortex, gonads) and can be given as tablets (e.g. the contraceptive pill).',
       '**Rule of thumb:** “-one / -ol / -sterone” endings (cortis**ol**, aldoster**one**, testoster**one**, progester**one**) and oestrogen = **steroids**. Hormones with “-in” or a long name of letters (insul**in**, glucag**on**, GH, TSH, FSH) = **proteins/peptides**. Adrenaline and thyroxine = **amines**.'),
    TB('s110-t3', 'Endocrine vs nervous co-ordination (Activity 1.4)', 2, ['Feature', 'Nervous system', 'Endocrine system'], [
        ['Messenger', 'Electrical impulse (+ chemical at synapse)', 'Hormone (chemical)'],
        ['Pathway', 'Nerve fibres to one exact place', 'Blood to the whole body'],
        ['Speed', 'Very fast (milliseconds)', 'Slow (seconds to days)'],
        ['Duration', 'Short', 'Long-lasting'],
        ['Typical job', 'Reflexes, movement', 'Growth, metabolism, reproduction, water and sugar balance'],
        ['Link between them', 'Hypothalamus (nervous tissue) …', '… controls the pituitary (endocrine)'],
    ]),
]

# ------------------------------------------------------------------ 1.1.1 Pituitary
PIT = [
    T('c07', '1.1.1 The pituitary gland — the “master gland”', 3,
      '**Where and what:** a small, **bean (pea)-sized** gland hanging by a stalk from the **hypothalamus** at the base of the brain. It is called the **master gland** because its hormones control the activity of almost all the other endocrine glands (thyroid, adrenal cortex, gonads, breasts).',
      '**Two lobes, two different jobs.** Structurally and functionally the pituitary is two glands joined together:',
      '**Anterior lobe (front)** — **makes and releases six hormones**: growth hormone (GH, somatotropin), thyroid-stimulating hormone (TSH), adrenocorticotropic hormone (ACTH), prolactin (lactogenic hormone), and the two gonadotropins, follicle-stimulating hormone (FSH) and luteinising hormone (LH).',
      '**Posterior lobe (back)** — **makes no hormone**. It **stores and releases two** hormones that are **made in the hypothalamus** by neurosecretory cells and passed down nerve fibres in the stalk: **antidiuretic hormone (ADH, also called vasopressin)** and **oxytocin**.',
      '**Who controls the master?** The **hypothalamus**, a small part of the brain below the thalamus. It is the main control centre of the endocrine system: it sends **releasing hormones** through tiny blood vessels to the anterior lobe and **nerve impulses** to the posterior lobe. So the hypothalamus links the **nervous system** to the **endocrine system**.',
      '**Why “tropic”?** A tropic hormone (TSH, ACTH, FSH, LH) has **another endocrine gland** as its target. GH and prolactin act directly on body tissues.'),
    DG('s111-d1', 'Hypothalamus and the two lobes of the pituitary', 3, 'pit',
       'Read top to bottom: the hypothalamus controls the anterior lobe through **blood vessels** (releasing hormones) and the posterior lobe through **nerve fibres** (ADH and oxytocin travel down them).'),
    TB('s111-t1', 'Anterior lobe hormones (1) — GH, TSH, ACTH', 3, ['Feature', 'Growth hormone (GH, somatotropin)', 'TSH (thyroid-stimulating)', 'ACTH (adrenocorticotropic)'], [
        ['Chemical nature', 'Protein', 'Glycoprotein (protein + sugar)', 'Polypeptide'],
        ['Target', 'Bones, muscles, soft tissues (most cells)', 'Thyroid gland', 'Adrenal cortex'],
        ['Function', 'Growth: cell division, protein synthesis (amino acids enter cells faster), bone growth', 'Makes the thyroid grow and release thyroxine', 'Makes the adrenal cortex release its hormones (mainly cortisol)'],
        ['Excess', 'Child: **gigantism** (very tall, normal proportions). Adult: **acromegaly** (thick bones of face, hands, feet)', 'Thyroid over-active and enlarged (goitre, hyperthyroid signs)', 'Too much cortisol → **Cushing’s disease** (weakness, high blood pressure, bruises)'],
        ['Deficiency', 'Child: **pituitary dwarfism** (short, normal proportions, normal intelligence)', 'Thyroid shrinks → low thyroxine (sluggish, cold)', 'Low cortisol → weakness, low blood sugar, poor response to stress'],
        ['Feedback', 'Hypothalamus releasing/inhibiting hormones; high GH effects switch it down (negative)', 'High thyroxine → less TRH and TSH (negative)', 'High cortisol → less CRH and ACTH (negative)'],
    ]),
    TB('s111-t2', 'Anterior lobe hormones (2) — prolactin, FSH, LH', 3, ['Feature', 'Prolactin (lactogenic)', 'FSH (follicle-stimulating)', 'LH (luteinising)'], [
        ['Chemical nature', 'Protein', 'Glycoprotein', 'Glycoprotein'],
        ['Target', 'Mammary glands (breasts)', 'Ovary (follicles) / testis (seminiferous tubules)', 'Ovary (corpus luteum) / testis (Leydig cells)'],
        ['Function', 'Breast development and **milk production** after birth', '♀ follicle (egg) grows and makes oestrogen · ♂ sperm production', '♀ ovulation, corpus luteum makes progesterone · ♂ testosterone release'],
        ['Excess', 'Milk at the wrong time, no menses, infertility (♀); breast enlargement, impotence (♂) — textbook p.18', 'Rare; early (precocious) puberty', 'Rare; early puberty'],
        ['Deficiency', 'Little or no milk after childbirth', 'No egg or sperm production → infertility; puberty delayed', 'No ovulation; low testosterone → infertility'],
        ['Feedback', 'Hypothalamus normally holds it back; **suckling** switches it on (reflex)', 'Sex hormones → less GnRH, FSH (negative; Fig. 1.2)', 'Negative; but a high oestrogen peak gives the mid-cycle **LH surge** (positive)'],
    ]),
    TB('s111-t3', 'Posterior lobe hormones — ADH and oxytocin (made in the hypothalamus)', 4, ['Feature', 'ADH (antidiuretic hormone, vasopressin)', 'Oxytocin'], [
        ['Chemical nature', 'Small peptide (9 amino acids)', 'Small peptide (9 amino acids)'],
        ['Made / released', 'Made in hypothalamus · released by posterior lobe', 'Made in hypothalamus · released by posterior lobe'],
        ['Target', 'Kidney tubules (collecting ducts); arterioles at high dose', 'Uterus muscle; mammary glands'],
        ['Function', 'More water **reabsorbed** → less, concentrated urine; protects from dehydration. High doses narrow blood vessels (vasoconstriction → “vasopressin”)', 'Strong **uterine contractions** in childbirth; **milk ejection** (let-down) when the baby sucks'],
        ['Excess', 'Too much water kept; blood diluted; scanty concentrated urine', 'Contractions too strong (hospital drug overdose)'],
        ['Deficiency', '**Diabetes insipidus**: huge volumes of dilute urine, intense thirst — **no sugar in the urine**', 'Weak labour, poor milk let-down'],
        ['Feedback', 'Negative: blood too concentrated → more ADH; dilute → ADH stops', 'Positive: stretch of cervix → more oxytocin → stronger push → more stretch, until birth'],
    ]),
    ST('s111-s1', 'Negative feedback of gonadotropins (Figure 1.2) step by step', 4, 'fb_gon', [
        ('**Step 1:** the hypothalamus releases **GnRH** (gonadotropin-releasing hormone) into the blood vessels of the stalk.', 'k1'),
        ('**Step 2:** GnRH makes the anterior pituitary release **FSH and LH**.', 'k2'),
        ('**Step 3:** FSH and LH make the testes or ovaries produce gametes and **sex hormones** (testosterone / oestrogen, progesterone).', 'k3'),
        ('**Step 4:** the sex hormones act on target cells (secondary sexual characteristics, uterus, sperm production).', 'k4'),
        ('**Step 5 — feedback:** a high level of sex hormone acts back on the hypothalamus and pituitary: **less GnRH, FSH and LH** are released, so sex-hormone production falls back to normal.', 'k5'),
    ]),
    T('s111-c2', 'ADH step by step: how the body saves water', 4,
      '**Step 1 — sensing:** neurons in the hypothalamus are sensitive to the water–salt balance of the blood (osmoreceptors).',
      '**Step 2 — too concentrated** (you sweated, ate salty food, did not drink): the hypothalamus signals and **ADH is released** from the posterior lobe.',
      '**Step 3 — action:** in the kidneys ADH makes the collecting ducts more permeable, so **more water is reabsorbed** from the filtered plasma back into the blood. Urine becomes **small in volume and concentrated** (dark).',
      '**Step 4 — back to normal:** the blood becomes more dilute, the hypothalamus detects it and **ADH release stops** (negative feedback).',
      '**Step 5 — too dilute** (you drank a lot): almost no ADH → little water reabsorbed → **large volume of dilute urine**.',
      '**Exam link (Review Q8):** **alcohol inhibits ADH release**, so a drinker fails to reabsorb water, produces a lot of dilute urine and becomes dehydrated (headache, thirst next morning).'),
    MN('s111-m1', 'Anterior lobe = “FLAT PG”; posterior = “ADH & OXY live in the back”', 3,
       ['**FLAT PG** — the six anterior hormones: **F**SH, **L**H, **A**CTH, **T**SH, **P**rolactin, **G**H. (Picture a flat PG-rated film shown at the **front** of the cinema.)',
        '**Posterior = storeroom at the back:** it only keeps **ADH** and **OXY**tocin that the hypothalamus made. Say: “The back room stores what the boss (hypothalamus) made.”',
        '**ADH = Anti-Diuresis = Anti-“lots of urine”** → saves water. **Oxytocin = “Ox-y-quick birth”** → strong push in labour and milk let-down.'],
       [('F', 'FSH', 'follicle / sperm'), ('L', 'LH', 'ovulation, testosterone'), ('A', 'ACTH', 'adrenal cortex'), ('T', 'TSH', 'thyroid'), ('P', 'Prolactin', 'milk'), ('G', 'GH', 'growth')]),
    RM('s111-r1', 'Exam traps — pituitary', 4,
       '**Trap 1:** “The posterior pituitary produces ADH” → **false**: it **stores and releases**; the hypothalamus **produces** it.',
       '**Trap 2:** **Thymosin, insulin, thyroxine** are NOT pituitary hormones (Review Q3 → thymosin).',
       '**Trap 3:** **Diabetes insipidus** is an **ADH (posterior pituitary / hypothalamus)** problem: much dilute urine and thirst, **no glucose** in urine. (Your textbook p.18 mistakenly calls it a pancreas disorder with glucose in urine — that describes **diabetes mellitus**. Learn the correct version.)',
       '**Trap 4:** pituitary dwarf = **normal intelligence**, normal proportions; cretin (thyroid) = **mental retardation**, disproportionate body.'),
    WK('s111-w1', 'Worked example: why is the pituitary called the master gland? (Exercise 1.1 Q4)', 3,
       'Explain why the pituitary is called the “master gland”, and why this name is only partly true.',
       ['**Step 1 — list what it controls:** TSH → thyroid; ACTH → adrenal cortex; FSH and LH → testes and ovaries; prolactin → breasts; GH → growth of the whole body.',
        '**Step 2 — conclude the first part:** because its hormones switch other endocrine glands on and off, it “masters” them.',
        '**Step 3 — the limit:** the pituitary itself obeys the **hypothalamus** (releasing hormones and nerve fibres) and is switched off by **feedback** from the hormones of its target glands.'],
       'It is called the master gland because its tropic hormones (TSH, ACTH, FSH, LH) control the thyroid, adrenal cortex and gonads, and GH and prolactin act on the whole body. Strictly, the hypothalamus is the real control centre, so the pituitary is a “master” under the brain’s command.'),
    WK('s111-w2', 'Worked example: Activity 1.2 — the stalk nerves are damaged', 7,
       'All the neuron connections between the hypothalamus and the pituitary are severely damaged. Which pituitary hormones are affected, and which are not?',
       ['**Step 1 — recall which lobe uses nerves:** ADH and oxytocin are **made in hypothalamic neurons** and travel **down nerve fibres** to the posterior lobe.',
        '**Step 2 — so cutting the nerves stops them:** ADH and oxytocin are no longer released → large volumes of dilute urine (diabetes insipidus) and weak labour/milk let-down.',
        '**Step 3 — the anterior lobe** is controlled through **blood vessels** (releasing hormones), not nerve fibres, and it **makes its own hormones** → GH, TSH, ACTH, prolactin, FSH and LH can still be produced (the textbook answer: “not affected” by nerve damage).'],
       'Affected: ADH and oxytocin (posterior lobe). Not affected by the nerve damage: the six anterior-lobe hormones (GH, TSH, ACTH, prolactin, FSH, LH), because they are made in the anterior lobe and controlled through blood vessels.'),
    WK('s111-w3', 'Worked example: urine after drinking two litres of water', 5,
       'A student drinks two litres of water quickly. Describe step by step what happens to ADH and to her urine.',
       ['**Step 1:** water is absorbed → blood becomes **dilute** (lower salt concentration).',
        '**Step 2:** hypothalamus osmoreceptors detect this → **less ADH** is released from the posterior pituitary.',
        '**Step 3:** collecting ducts become less permeable → **less water reabsorbed**.',
        '**Step 4:** a **large volume of pale, dilute urine** is produced until the blood returns to normal; then ADH rises again to its usual level.'],
       'ADH secretion falls, less water is reabsorbed in the kidneys, and she passes a large volume of dilute urine (negative feedback restores the blood concentration).'),
    CK('s111-k1', 3, 'Which pair of hormones is released, but not made, by the posterior pituitary?', ['GH and TSH', 'ADH and oxytocin', 'FSH and LH', 'ACTH and prolactin'], 'B',
       '**Step 1:** the posterior lobe only stores and releases. **Step 2:** what it releases (ADH and oxytocin) is made by neurosecretory cells in the **hypothalamus**.'),
    CK('s111-k2', 3, 'A hormone that “stimulates the rate at which amino acids enter cells” and promotes bone growth is', ['prolactin', 'growth hormone', 'oxytocin', 'ADH'], 'B',
       'Growth hormone (somatotropin) speeds amino-acid uptake → more **protein synthesis**, cell division and bone growth.'),
    CK('s111-k3', 3, 'In males, LH acts on the', ['seminiferous tubules to make sperm', 'Leydig (interstitial) cells to release testosterone', 'prostate gland', 'epididymis'], 'B',
       'FSH → seminiferous tubules (sperm). **LH → Leydig cells → androgens (testosterone)** into the blood.'),
    CK('s111-k4', 4, 'A person passes very large volumes of dilute urine with no glucose in it and is always thirsty. The hormone most likely lacking is', ['insulin', 'ADH', 'thyroxine', 'aldosterone'], 'B',
       'Dilute urine + thirst + **no** glucose = **diabetes insipidus** = lack of ADH. Glucose in urine would point to insulin (diabetes mellitus).'),
]

# ------------------------------------------------------------------ 1.1.2 Thyroid
THY = [
    T('c08', '1.1.2 The thyroid gland — the body’s throttle', 6,
      '**Where and what:** a **butterfly-shaped** gland at the **base of the neck in front of the trachea** (windpipe): two lobes joined by a narrow bridge (isthmus). It is the **largest endocrine gland** in the body. Inside, tiny round sacs (follicles) store the hormone.',
      '**Two hormones:** **thyroxine (T4)** and **calcitonin**.',
      '**Thyroxine — needs iodine.** Iodine is an essential part of the thyroxine molecule, so the diet must contain iodine (sea food, **iodised salt**). Chief jobs: (1) controls the body’s **metabolic rate** — how fast cells use oxygen and food to release energy and heat; (2) regulates **growth of bones** and (3) the **development of the brain and nervous system in children**; (4) controls metamorphosis in amphibians (tadpole → frog).',
      '**Calcitonin — lowers blood calcium.** It is secreted when blood calcium **rises**, and it lowers it by promoting **deposition of calcium into bone**. Calcium is needed for nerve conduction, muscle contraction, blood clotting and bone and teeth formation. Its partner (opposite) is **PTH from the parathyroids**, which raises blood calcium.',
      '**What controls the thyroid?** The amount of **iodine** in the body and a **feedback system** involving the hypothalamus and pituitary (TRH → TSH → thyroxine).'),
    TB('s112-t1', 'Thyroid hormones in detail', 6, ['Feature', 'Thyroxine (T4)', 'Calcitonin'], [
        ['Gland / cells', 'Thyroid follicle cells', 'Thyroid (C-cells between follicles)'],
        ['Chemical nature', 'Amine: iodine + the amino acid tyrosine (acts inside the cell)', 'Peptide (32 amino acids)'],
        ['Stimulus', 'TSH from anterior pituitary', 'High blood calcium'],
        ['Target', 'Almost all cells (muscle, bone, brain, heart, sex organs)', 'Bone, kidney, intestine'],
        ['Function', 'Raises metabolic rate, heat, heart rate; bone growth; brain development in children', 'Lowers blood Ca²⁺: Ca²⁺ into bone, less taken from gut and kidney'],
        ['Excess', '**Hyperthyroidism**: high metabolic rate, weight loss, heat intolerance, sweating, fast heart, restless, irritable, bulging eyes; thyroid may swell (goitre)', 'Blood calcium too low (rare)'],
        ['Deficiency', 'Child: **cretinism** (dwarfed, mental retardation). Adult: **myxoedema** (puffy face, slow, cold, weight gain). No iodine: **goitre**', 'No well-known disease (PTH and vitamin D keep calcium normal)'],
        ['Feedback', 'Negative: high thyroxine → less TRH and TSH', 'Direct: blood Ca²⁺ level itself (no pituitary)'],
    ]),
    ST('s112-s1', 'Negative feedback of thyroxine (Figure 1.5) step by step', 7, 'fb_thy', [
        ('**Step 1:** the hypothalamus senses a **low thyroxine** level (or cold) and releases **TRH**.', 'k1'),
        ('**Step 2:** TRH makes the anterior pituitary release **TSH** into the blood.', 'k2'),
        ('**Step 3:** TSH makes the thyroid take up **iodine** and release **thyroxine**.', 'k3'),
        ('**Step 4:** thyroxine raises the metabolic rate of target cells.', 'k4'),
        ('**Step 5 — feedback:** if the thyroid secretes **too much thyroxine**, the high level signals the hypothalamus and pituitary to release **less TRH and TSH**, so thyroxine secretion **falls**. Too little thyroxine → the brake is released → more TSH.', 'k5'),
    ]),
    T('s112-c1', 'Why a lack of iodine makes the neck swell (goitre) — step by step', 18,
      '**Step 1:** no iodine in food → the thyroid **cannot make thyroxine**.',
      '**Step 2:** thyroxine level in blood is **low**, so there is **no negative feedback** on the pituitary.',
      '**Step 3:** the pituitary keeps pouring out **TSH**.',
      '**Step 4:** TSH keeps stimulating the thyroid to **grow** — the gland enlarges and the neck swells: **goitre** (simple or iodine-deficiency goitre, common in mountain areas far from the sea).',
      '**Prevention and treatment:** a balanced diet with **iodised salt**; iodine tablets if needed (textbook p.19).',
      '**Two kinds of goitre:** your textbook (pp.18–20) lists goitre under **over-secretion** (an overactive, enlarged thyroid — hyperthyroid goitre, caused by plasma proteins that over-stimulate the gland). The goitre from **iodine deficiency** comes with **low** thyroxine. In an exam: “goitre = swelling of the thyroid”; “disease caused by lack of iodine = goitre” (Review Part II Q6).'),
    TB('s112-t2', 'Thyroid disorders compared', 18, ['Disorder', 'Hormone level', 'Age', 'Main signs', 'Cause / help'], [
        ['**Cretinism**', 'Too little thyroxine', 'Childhood', 'Stunted, deformed legs, dry leathery skin, large tongue, sluggish, **mental retardation**', 'Thyroid failure or no iodine; thyroxine given early'],
        ['**Myxoedema**', 'Too little', 'Adult', 'Puffy swollen face (fluid), low metabolic rate, sleepy, weight gain, feels cold, slow thinking, weak muscles', 'Thyroid failure; thyroxine tablets'],
        ['**Simple goitre**', 'Too little (no iodine)', 'Any', 'Swollen neck', 'Lack of iodine; iodised salt'],
        ['**Hyperthyroidism** (with goitre)', 'Too much', 'Usually adult', 'High metabolic rate, fast heart and breathing, high temperature, sweaty skin, weight loss, nervous, irritable, bulging eyes', 'Plasma proteins over-stimulate the gland; drugs or surgery'],
    ]),
    MN('s112-m1', 'Thyroid memory: “Hypo = slow & cold, Hyper = hot & fast”', 18,
       ['**Hypo** (too little): **S**low, **C**old, **F**at, **T**ired — “**SCFT**: Slow Cold Fat Tired”. Child → **C**retin (**C**hild), adult → **M**yxoedema (**M**ature).',
        '**Hyper** (too much): **H**ot, **T**hin, **F**ast heart, **N**ervous, bulging eyes — like an engine with the throttle stuck open.',
        '**Calci-TONE-in tones DOWN calcium** (into bone). **PTH Pulls calcium To the blood (raises it).**'],
       [('S', 'Slow', 'low metabolic rate'), ('C', 'Cold', 'little heat made'), ('F', 'Fat', 'weight gain'), ('T', 'Tired', 'sluggish, sleepy')]),
    WK('s112-w1', 'Worked example: poor growth in a one-year-old (Activity 1.5 Q2)', 19,
       'Without measuring hormones, how would you tell thyroid deficiency from growth-hormone deficiency as the cause of poor growth in a one-year-old child?',
       ['**Step 1 — recall what thyroxine does in children:** it controls **brain development** and metabolic rate as well as growth.',
        '**Step 2 — signs of thyroid deficiency (cretinism):** slow mental development, sluggish, large tongue, dry skin, feels cold, **body out of proportion**.',
        '**Step 3 — signs of GH deficiency (pituitary dwarfism):** small but **well-proportioned**, **normal mental development**, normal skin and activity.',
        '**Step 4 — decide:** mental/behavioural development and body proportions separate the two.'],
       'A thyroid-deficient child is mentally slow, sluggish, with dry skin, large tongue and disproportionate body (cretinism); a GH-deficient child is small but proportionate with normal intelligence and activity.'),
    WK('s112-w2', 'Worked example: hormone high but signs of deficiency (Review Part I Q1)', 22,
       'A person shows the signs of thyroid hormone deficiency, but has above-average levels of thyroid hormone in the blood. What might the problem be? A. inadequate TSH B. too much TSH C. too few thyroid-hormone receptors in body cells D. too few TSH receptors in thyroid cells',
       ['**Step 1:** the hormone is **present in plenty**, so the gland and TSH are not the problem (A, B, D would change the hormone level).',
        '**Step 2:** a hormone acts only through its **receptors**. If target cells lack receptors they cannot “hear” it → deficiency signs.',
        '**Step 3:** choose the receptor problem in the **target cells**.'],
       'C — the body cells have too few thyroid-hormone receptors, so the hormone cannot act.'),
    WK('s112-w3', 'Worked example: a man takes extra thyroxine tablets', 7,
       'A man takes thyroxine tablets he does not need for several months. Predict what happens to (a) his TSH level, (b) the size of his own thyroid gland, (c) his body weight.',
       ['**Step 1 — blood thyroxine is high** (from tablets).',
        '**Step 2 — negative feedback:** high thyroxine → hypothalamus and pituitary release **less TRH and TSH**.',
        '**Step 3 — no TSH stimulation** → his own thyroid becomes inactive and **shrinks**.',
        '**Step 4 — high metabolic rate** → more food burned → **weight loss**, sweating, fast heart.'],
       '(a) TSH falls; (b) his thyroid shrinks (no TSH stimulation); (c) he loses weight because his metabolic rate is high.'),
    CK('s112-k1', 6, 'Which element must be in the diet for the thyroid to make thyroxine?', ['Iron', 'Calcium', 'Iodine', 'Sodium'], 'C',
       '**Iodine** is part of the thyroxine molecule. Lack of it → low thyroxine → goitre.'),
    CK('s112-k2', 7, 'Calcitonin is released when', ['blood calcium falls', 'blood calcium rises', 'blood glucose rises', 'TSH rises'], 'B',
       'Calcitonin **lowers** blood calcium (Ca²⁺ into bone), so it is released when calcium is **high**. PTH works the opposite way.'),
    CK('s112-k3', 18, 'An adult with a puffy face, low metabolic rate, weight gain and feeling of cold most likely has', ['cretinism', 'myxoedema', 'hyperthyroidism', 'acromegaly'], 'B',
       'Under-secretion of thyroxine in an **adult** = **myxoedema**. In a child it would be cretinism.'),
    CK('s112-k4', 7, 'In iodine-deficiency goitre, the thyroid enlarges mainly because', ['thyroxine level is high', 'TSH stays high when there is little thyroxine to switch it off', 'calcitonin is too high', 'ADH is lacking'], 'B',
       'Low thyroxine → no negative feedback → **TSH stays high** → TSH keeps the gland growing.'),
]

# ------------------------------------------------------------------ 1.1.4 Adrenal
ADR = [
    T('c10', '1.1.4 The adrenal glands — the stress (emergency) glands', 8,
      '**Where and what:** a pair of small, **yellow** masses of tissue, **one on top of each kidney** (ad = near, renal = kidney). They are called the **stress glands** or the “emergency gland”.',
      '**Two glands in one.** Each adrenal has an outer **cortex** and an inner **medulla**; they differ in structure, in the hormones they make and in how they are controlled.',
      '**Adrenal cortex (outer, bulky part)** — secretes many **steroid** hormones called **corticosteroids (corticoids)**, in three groups:',
      '**a. Glucocorticoids**, mainly **cortisol**: regulate the metabolism of fats, proteins and carbohydrates (raise blood glucose by breaking down fats and proteins), help the body **adapt to long-term stress**, repair damaged tissues, and also affect blood pressure, energy balance and white blood cell production.',
      '**b. Mineralocorticoids**, mainly **aldosterone**: regulate **water and mineral balance**, especially **sodium (Na⁺) and potassium (K⁺)**. Secreted when blood Na⁺ is **low** or K⁺ is **high**; makes the kidney tubules **reabsorb (keep) sodium** and **excrete potassium**; water follows the sodium.',
      '**c. Sex steroids**: small amounts of androgens (and oestrogen). The most potent androgen, testosterone, comes mainly from the testes.',
      '**Adrenal medulla (inner part)** — behaves like part of the nervous system: it **receives nerve impulses from the brain** and releases **adrenaline (epinephrine)** and **noradrenaline (norepinephrine)**. Adrenaline is the **“fight or flight”** hormone; noradrenaline mainly **constricts blood vessels** throughout the body.'),
    DG('s114-d1', 'Adrenal gland: cortex and medulla', 9, 'adr',
       'Outer **cortex** = steroids (Salt, Sugar, Sex), controlled by ACTH and blood Na⁺/K⁺. Inner **medulla** = amines (adrenaline, noradrenaline), controlled by **nerves**.'),
    TB('s114-t1', 'Adrenal cortex hormones (steroids)', 9, ['Feature', 'Cortisol (glucocorticoid)', 'Aldosterone (mineralocorticoid)', 'Sex steroids'], [
        ['Chemical nature', 'Steroid', 'Steroid', 'Steroid'],
        ['Stimulus', 'ACTH (stress, low blood sugar)', 'Low Na⁺, high K⁺ in blood (low blood volume)', 'ACTH'],
        ['Target', 'All tissues (liver, muscle, fat), kidneys', 'Kidney tubules', 'Sex organs, skin, muscle'],
        ['Function', 'Raises blood glucose (from fat and protein); long-term stress; tissue repair; reduces inflammation', 'Keeps Na⁺ and water, removes K⁺ → controls blood volume and pressure', 'Small effect on body hair, sex drive'],
        ['Excess', '**Cushing’s disease**: weakness, high blood pressure, bruises, round face, high blood sugar', 'High blood pressure, low K⁺ (Conn’s syndrome — extra)', 'Masculine features in females, early puberty'],
        ['Deficiency', '**Addison’s disease** (with aldosterone): anorexia, nausea, vomiting, weight loss, low blood glucose, weak muscles, bronzed skin', 'Salt and water lost in urine → dehydration, low blood pressure (part of Addison’s)', 'Little effect'],
        ['Feedback', 'Negative: high cortisol → less CRH and ACTH', 'Negative: Na⁺/K⁺ back to normal → aldosterone stops', 'Negative via ACTH'],
    ]),
    TB('s114-t2', 'Adrenal medulla hormones (amines)', 10, ['Feature', 'Adrenaline (epinephrine)', 'Noradrenaline (norepinephrine)'], [
        ['Chemical nature', 'Amine (catecholamine, from tyrosine)', 'Amine (catecholamine)'],
        ['Stimulus', '**Nerve impulses** from the brain (fear, excitement, anger)', 'Nerve impulses'],
        ['Target', 'Heart, liver, muscles, fat (adipose) tissue, blood vessels, eyes, lungs', 'Blood vessels throughout the body'],
        ['Function', '**Fight or flight**: faster heart, more glucose (glycogen → glucose), blood to muscles, wider airways, pupils dilate', 'Constricts blood vessels → raises blood pressure'],
        ['Excess', 'Tumour of the medulla: high blood pressure, severe headache, sweating, faintness (textbook p.19)', 'High blood pressure'],
        ['Deficiency', 'No serious disease — sympathetic nerves can do the job (the cortex, not the medulla, is essential for life)', '—'],
        ['Feedback / control', 'Not by the pituitary: nerves switch it on; it stops when the danger passes', 'Same'],
    ]),
    TB('s114-t3', 'Fight or flight: what adrenaline does and why it helps', 10, ['Effect', 'How', 'Why useful in danger'], [
        ['Heart beats faster and stronger', 'Acts on heart muscle', 'Oxygen and glucose delivered rapidly to brain and muscles'],
        ['Blood glucose rises', 'Liver breaks down **glycogen → glucose**', 'Muscles have fuel for respiration'],
        ['Blood diverted to muscles', 'Arterioles to muscles widen, to gut and skin narrow', 'Muscles ready to fight or run; digestion can wait'],
        ['Breathing faster, airways wider', 'Bronchioles relax', 'More oxygen in, more CO₂ out'],
        ['Pupils dilate', 'Iris muscles', 'More light → better vision'],
        ['Hair stands, sweating', 'Skin', 'Cooling during effort'],
    ]),
    ST('s114-s1', 'A dog chases you — the adrenal response step by step', 10, 'adr', [
        ('**Step 1:** your eyes see the danger; the brain sends **nerve impulses** down a nerve to the **adrenal medulla**.', 'md'),
        ('**Step 2:** within seconds the medulla releases **adrenaline** into the blood: heart races, glucose rises, you run.', 'md'),
        ('**Step 3:** if stress lasts (days of worry, illness), the hypothalamus–pituitary send **ACTH** → the **cortex** releases **cortisol**, keeping blood glucose up from fat and protein.', 'cx'),
        ('**Step 4:** if you lose a lot of salt and water (sweating, bleeding), the cortex releases **aldosterone** so the kidneys keep Na⁺ and water.', 'cx'),
    ]),
    MN('s114-m1', 'Adrenal memory: “Cortex = Salt, Sugar, Sex · Medulla = Moment of danger”', 9,
       ['**Cortex → 3 S’s:** **S**alt (aldosterone), **S**ugar (cortisol), **S**ex (sex steroids). All are **steroids** — another S.',
        '**Medulla → M for Moment:** works in the moment of danger, switched on by **nerves**, not by the pituitary.',
        '**Addison = Adds nothing** (too little cortex hormone). **Cushing = Cushion** (too much cortisol: round, padded face and body).'],
       [('S', 'Salt', 'aldosterone keeps Na⁺'), ('S', 'Sugar', 'cortisol raises glucose'), ('S', 'Sex', 'sex steroids')]),
    WK('s114-w1', 'Worked example: how the adrenals help with stress or fear (Exercise 1.1 Q2)', 8,
       '(a) State the location of the adrenal glands. (b) Explain how they help the body cope with stress or fear.',
       ['**(a)** One adrenal gland sits on top of each kidney.',
        '**(b) Step 1 — sudden fear:** nerve impulses → medulla → **adrenaline** → faster heart and breathing, glycogen → glucose in the liver, blood to muscles, wider pupils → energy to fight or run.',
        '**Step 2 — long stress:** ACTH → cortex → **cortisol** → blood glucose kept high from fats and proteins, tissue repair.',
        '**Step 3 — loss of salt/water:** **aldosterone** keeps sodium and water, protecting blood pressure.'],
       '(a) On top of each kidney. (b) The medulla releases adrenaline for immediate “fight or flight” (heart rate, glucose, blood to muscles); the cortex releases cortisol for long-term stress (raises glucose, repairs tissues) and aldosterone to keep salt and water.'),
    WK('s114-w2', 'Worked example: glucocorticoid — like glucagon or insulin? (Exercise 1.1 Q6)', 9,
       'Does the action of a glucocorticoid (cortisol) more closely resemble that of glucagon or of insulin? Explain.',
       ['**Step 1 — insulin:** lowers blood glucose (glucose → glycogen, into cells).',
        '**Step 2 — glucagon:** raises blood glucose (glycogen → glucose).',
        '**Step 3 — cortisol:** raises blood glucose by breaking down fats and proteins as an energy source (textbook Table 1.1: “raise blood glucose level”).',
        '**Step 4 — compare:** cortisol and glucagon both **raise** blood glucose.'],
       'Glucagon — both raise the blood glucose level (cortisol by breaking down fats and proteins), whereas insulin lowers it.'),
    WK('s114-w3', 'Worked example: nerves to the adrenal medulla are cut (Activity 1.3 Q1)', 12,
       'In an experimental animal the sympathetic nerve fibres to the adrenal medulla are cut. What happens to adrenaline (epinephrine) concentration at rest and during stress?',
       ['**Step 1:** the medulla releases adrenaline only when **nerve impulses** arrive.',
        '**Step 2 — at rest:** the level is normally low anyway → stays low (little change).',
        '**Step 3 — during stress:** no impulses reach the medulla → **no rise** in adrenaline (only the sympathetic nerves themselves can help with noradrenaline).'],
       'At rest the level stays low; during stress adrenaline does not rise, because the medulla is switched on only by nerve impulses.'),
    CK('s114-k1', 9, 'Which hormone makes the kidney tubules keep sodium and excrete potassium?', ['Cortisol', 'Aldosterone', 'Adrenaline', 'ADH'], 'B',
       '**Aldosterone** (mineralocorticoid of the adrenal cortex) — Review Q5. ADH controls **water**, aldosterone controls **salts**.'),
    CK('s114-k2', 10, 'The adrenal medulla is stimulated to release adrenaline mainly by', ['ACTH', 'nerve impulses from the brain', 'high blood sodium', 'TSH'], 'B',
       'The medulla is controlled by **nerves** (fight or flight). ACTH controls the **cortex**.'),
    CK('s114-k3', 19, 'Weakness, weight loss, low blood glucose, vomiting and bronzed skin suggest', ['Cushing’s disease', 'Addison’s disease', 'acromegaly', 'goitre'], 'B',
       'Too little cortex hormone (glucocorticoids + aldosterone) = **Addison’s disease**. Cushing’s is the opposite (too much cortisol).'),
    CK('s114-k4', 10, 'Adrenaline raises blood glucose by', ['changing glucose to glycogen', 'making the liver break down glycogen to glucose', 'stopping respiration', 'increasing insulin'], 'B',
       'Adrenaline activates the **liver** to break down stored **glycogen**, releasing glucose for the muscles.'),
]

# ------------------------------------------------------------------ 1.1.5 Pancreas
PAN = [
    T('c11', '1.1.5 The pancreas — a double gland', 10,
      '**Where and what:** a soft, flattened organ **below the stomach**, in the loop of the duodenum (“pan” = all, “kreas” = flesh). It is both an **exocrine** and an **endocrine** gland.',
      '**Exocrine part (most of the pancreas):** cells make **pancreatic juice** (digestive enzymes) that flows through the **pancreatic duct** into the duodenum.',
      '**Endocrine part:** small groups of cells scattered through the pancreas — the **islets of Langerhans**. Each islet contains **alpha (α) cells**, which secrete **glucagon**, and **beta (β) cells**, which secrete **insulin**. (Delta cells make a third hormone, somatostatin — extra.)',
      '**The islets are glucose sensors.** They constantly monitor the blood glucose level. Normal: about **100 mg of glucose in every 100 cm³ of blood** (textbook p.11).',
      '**Glucose too high** (after a meal) → β-cells release **insulin** → liver (and muscle) cells take up glucose and **convert excess glucose into glycogen**; body cells take in and respire more glucose → level falls.',
      '**Glucose too low** (fasting, exercise) → α-cells release **glucagon** → liver **converts stored glycogen into glucose** and releases it → level rises.',
      'Insulin and glucagon are **antagonistic** hormones: they have opposite effects and together keep the level steady (Figure 1.8).'),
    ST('s115-s1', 'Antagonistic control of blood sugar (Figure 1.8) step by step', 11, 'glu', [
        ('**High glucose (after a meal):** β-cells sense it and release **insulin**. Liver and muscle take glucose in and store it as **glycogen**; cells respire more → glucose falls back to normal.', 'hi'),
        ('**Low glucose (fasting, hard work):** α-cells release **glucagon**. The liver breaks **glycogen → glucose** and releases it into the blood → glucose rises back to normal.', 'lo'),
        ('**Negative feedback:** the change itself (glucose level) is what the islets detect — no pituitary hormone is involved.', None),
    ]),
    TB('s115-t1', 'Insulin and glucagon in detail', 10, ['Feature', 'Insulin', 'Glucagon'], [
        ['Gland / cells', 'Islets of Langerhans — **β (beta) cells**', 'Islets of Langerhans — **α (alpha) cells**'],
        ['Chemical nature', 'Small protein (51 amino acids in two chains) — digested if swallowed, so it is injected', 'Peptide (29 amino acids)'],
        ['Stimulus', 'High blood glucose', 'Low blood glucose'],
        ['Target', 'Liver, muscle, fat (adipose) tissue — most cells', 'Mainly liver'],
        ['Function', '**Lowers** blood glucose: glucose into cells, glucose → glycogen (and fat), more respiration', '**Raises** blood glucose: glycogen → glucose, released into blood'],
        ['Excess', 'Overdose or tumour → **hypoglycaemia**: shaking, sweating, hunger, confusion, fainting, coma', 'Rare tumour → high blood glucose'],
        ['Deficiency', '**Diabetes mellitus**: high blood glucose, glucose in urine, thirst, much urine, weight loss; very high levels → coma, death', 'Risk of low blood glucose'],
        ['Feedback', 'Negative: glucose back to normal → insulin release falls', 'Negative: glucose back to normal → glucagon release falls'],
    ]),
    T('s115-c1', 'Diabetes mellitus step by step', 19,
      '**Step 1 — cause:** the β-cells fail to make insulin (**type 1**, usually starts young; needs insulin injections) or the body cells stop responding to insulin (**type 2**, usually adults, linked to overweight and inactivity; diet, exercise and tablets help).',
      '**Step 2 — glucose stays in the blood:** without insulin, cells cannot take up glucose and the liver cannot store it as glycogen → blood glucose is **abnormally high**.',
      '**Step 3 — glucose in urine:** the kidneys cannot reabsorb so much glucose → glucose appears in the urine (a simple urine test shows it).',
      '**Step 4 — water follows:** glucose in urine carries water with it → **excessive urination** → **intense thirst**.',
      '**Step 5 — energy crisis:** cells are “starving in plenty” → they break down fats and proteins → **weight loss**, tiredness.',
      '**Step 6 — danger:** very high blood glucose can damage brain cells → **coma and possibly death** (textbook p.19). Too much injected insulin causes the opposite danger, **hypoglycaemia**.',
      '**Why a sugary diet is dangerous for a diabetic (Let us discuss p.17):** extra sugar is absorbed into the blood, but without insulin it cannot be stored or used, so blood glucose rises even higher.'),
    TB('s115-t2', 'Diabetes mellitus vs diabetes insipidus', 19, ['Feature', 'Diabetes mellitus', 'Diabetes insipidus'], [
        ['Hormone missing', 'Insulin (or cells resistant to it)', 'ADH'],
        ['Gland', 'Pancreas (β-cells of islets)', 'Hypothalamus / posterior pituitary'],
        ['Blood glucose', 'High', 'Normal'],
        ['Urine', 'Large volume, **contains glucose** (“mellitus” = honey-sweet)', 'Very large volume, dilute, **no glucose** (“insipidus” = tasteless)'],
        ['Thirst', 'Yes', 'Yes, intense'],
        ['Treatment', 'Insulin injections (type 1), diet and exercise (type 2)', 'ADH (vasopressin) as nose spray or tablets'],
    ]),
    MN('s115-m1', 'Pancreas memory: “β Builds, α Away; insulin IN, glucaGON = glucose gone”', 10,
       ['**β-cells → insulin → Builds glycogen** (stores glucose). **α-cells → glucagon → takes glucose Away from the store.**',
        '**Insulin puts glucose IN** (into cells, into the glycogen store). **GlucaGON**: “the glucose is GONE — bring it back!”',
        '**Glycogen vs glucagon:** glycogen is the **store** (a carbohydrate, like a **gen**erator in the liver); glucagon is the **hormone** (it is **gone** after acting).'],
       [('β', 'Beta', 'insulin, lowers glucose'), ('α', 'Alpha', 'glucagon, raises glucose')]),
    WK('s115-w1', 'Worked example: a diabetic breaks a leg (Exercise 1.2 Q3)', 21,
       'A person with diabetes mellitus breaks a leg. Would you advise an increase or a decrease in the insulin dose? Explain.',
       ['**Step 1 — injury is stress:** stress raises **adrenaline** and **cortisol**.',
        '**Step 2 — both raise blood glucose** (glycogen → glucose; fats and proteins used).',
        '**Step 3 — a diabetic cannot make extra insulin** to bring the glucose down.',
        '**Step 4 — so the dose usually needs to go up** (under a doctor’s supervision, with blood glucose checked often).'],
       'Increase it (with medical advice): the stress of injury releases adrenaline and cortisol, which raise blood glucose, and the diabetic cannot produce extra insulin.'),
    WK('s115-w2', 'Worked example: reading blood glucose after a meal', 11,
       'A student’s blood glucose is 100 mg/100 cm³ before breakfast, 150 mg/100 cm³ 45 minutes after eating injera with honey, and 100 mg/100 cm³ again after 2½ hours. Explain each change and name the hormone involved.',
       ['**Step 1 — rise (100 → 150):** digested carbohydrate is absorbed from the small intestine into the blood.',
        '**Step 2 — detection:** β-cells of the islets sense the high level and release **insulin**.',
        '**Step 3 — fall (150 → 100):** insulin makes liver and muscle cells take up glucose and store it as **glycogen**; cells respire more.',
        '**Step 4 — later, between meals:** if it drops below normal, α-cells release **glucagon** to release glucose from glycogen.'],
       'The rise is absorption of digested food; insulin from β-cells brings it back to about 100 mg/100 cm³ by glucose uptake and glycogen formation (negative feedback); glucagon would prevent a later fall.'),
    WK('s115-w3', 'Worked example: urine changes (Review Part IV Q3b)', 24,
       'How does hyposecretion of insulin affect the quantity and composition of urine?',
       ['**Step 1:** too little insulin → blood glucose too high.',
        '**Step 2:** the kidney tubules cannot reabsorb all the filtered glucose → **glucose in the urine**.',
        '**Step 3:** glucose holds water in the tubules (osmosis) → **larger volume** of urine.'],
       'Urine becomes larger in volume and contains glucose.'),
    CK('s115-k1', 10, 'Glucagon is secreted by the', ['β-cells of the islets', 'α-cells of the islets', 'exocrine cells of the pancreas', 'adrenal medulla'], 'B',
       'α (alpha) → **glucagon**; β (beta) → insulin (Review Q4).'),
    CK('s115-k2', 11, 'Insulin lowers blood glucose mainly by', ['changing glycogen into glucose', 'changing excess glucose into glycogen in the liver and muscles', 'increasing glucose in urine', 'stopping digestion'], 'B',
       'Insulin = store it: glucose → **glycogen**, and glucose into cells.'),
    CK('s115-k3', 11, 'The normal blood glucose given in the textbook is about', ['10 mg per 100 cm³', '100 mg per 100 cm³', '1000 mg per 100 cm³', '100 g per 100 cm³'], 'B',
       'About **100 mg of glucose for every 100 cm³ of blood**.'),
    CK('s115-k4', 10, 'Why is the pancreas called a mixed (double) gland?', ['It makes two hormones', 'It has both duct (exocrine) cells and ductless (endocrine) islets', 'It lies near two organs', 'It works by day and night'], 'B',
       'Exocrine cells → pancreatic juice through a duct; islets → hormones into blood.'),
]

# ------------------------------------------------------------------ 1.1.6 Sex glands
SEX = [
    T('c12', '1.1.6 The sex glands (gonads) — hormones and gametes', 12,
      '**What:** the **testes** (male) and **ovaries** (female) are the primary reproductive organs (**gonads**). They do two jobs: they produce **gametes** (sperm, ova) and secrete **sex hormones** that create the male or female characteristics.',
      '**Testes:** two oval glands in the scrotum. Between the sperm-forming tubules lie **Leydig (interstitial) cells** — the endocrine tissue. When stimulated by **LH** from the pituitary, Leydig cells release **androgens**, mainly **testosterone**, into the blood. **FSH** stimulates the seminiferous tubules to produce **sperm** (testosterone is needed too).',
      '**When it starts:** at the beginning of adolescence (**puberty**), when the hypothalamus increases GnRH and so FSH and LH.',
      '**Testosterone causes male secondary sexual characteristics:** deeper voice, body and facial hair (beard), increased muscle, broader chest and shoulders, growth of the penis and testes, sex drive and sperm production.',
      '**Ovaries:** two almond-shaped glands beside the uterus. Under **FSH** a follicle grows and its cells make **oestrogen**; after ovulation, under **LH**, the empty follicle becomes the **corpus luteum**, which makes **progesterone** (and some oestrogen).',
      '**Oestrogen causes female secondary sexual characteristics** — breast enlargement, broadening of the hips, pubic and armpit hair — and **rebuilds the uterine lining** each month. **Progesterone** **thickens and maintains** the uterine lining for a possible pregnancy and keeps it during pregnancy.'),
    TB('s116-t1', 'Sex hormones in detail', 12, ['Feature', 'Testosterone', 'Oestrogen', 'Progesterone'], [
        ['Gland / cells', 'Testes — Leydig (interstitial) cells', 'Ovary — follicle cells (also placenta)', 'Ovary — corpus luteum (also placenta)'],
        ['Chemical nature', 'Steroid', 'Steroid', 'Steroid'],
        ['Stimulus', 'LH', 'FSH', 'LH'],
        ['Target', 'Testes, muscle, bone, skin, voice box, brain', 'Uterus, breasts, bone, muscle, skin, brain', 'Uterus (lining), breasts'],
        ['Function', 'Sperm formation; male secondary characteristics; testes descend into scrotum before birth', 'Female secondary characteristics; repairs and thickens uterine lining; LH surge mid-cycle', 'Thickens and **maintains** lining; keeps pregnancy; stops new ovulation in pregnancy'],
        ['Excess', 'Steroid abuse: acne, aggression, testes shrink, infertility', 'Males: breast growth. Females: heavy, irregular bleeding', 'High levels (pill, pregnancy) block ovulation'],
        ['Deficiency', 'Weak male characters, low sperm count, infertility', 'No breast growth or periods; after menopause thin bones, hot flushes', 'Lining not kept → infertility, miscarriage'],
        ['Feedback', 'Negative: high testosterone → less GnRH and LH', 'Negative most of the cycle; **positive** at the mid-cycle peak (LH surge)', 'Negative: high progesterone → less GnRH, FSH, LH'],
    ]),
    TB('s116-t2', 'What the sex hormones change at puberty', 12, ['In both', 'Boys (testosterone)', 'Girls (oestrogen)'], [
        ['Growth spurt', 'Voice deepens', 'Breasts develop'],
        ['Pubic and armpit hair', 'Beard and body hair', 'Hips broaden (wider pelvis)'],
        ['Sex organs mature', 'Muscles develop; chest and shoulders broaden', 'Menstrual cycle starts; ova mature'],
        ['Interest in the opposite sex', 'Testes enlarge; sperm production begins', 'Body fat on hips and thighs'],
    ]),
    DG('s116-d1', 'Hypothalamus → pituitary → gonads, with feedback', 12, 'fb_gon',
       'The same loop as Figure 1.2: GnRH → FSH + LH → testis/ovary → testosterone/oestrogen/progesterone, which switch GnRH, FSH and LH down again.'),
    MN('s116-m1', 'Sex-gland memory', 12,
       ['**L**H → **L**eydig cells → testosterone (“**L**H **L**ets testosterone out”). **F**SH → **F**ollicle (♀) and **F**actory of sperm (♂).',
        '**Pro-gest-erone = PRO-GESTation**: it is “for pregnancy” — keeps the uterine lining.',
        '**Oestrogen = builds the woman and rebuilds the lining** each month.'],
       [('L', 'LH', 'Leydig cells / corpus luteum'), ('F', 'FSH', 'follicle / sperm factory')]),
    WK('s116-w1', 'Worked example: testes removed before puberty', 12,
       'A boy’s testes are removed before puberty because of disease. Predict (a) his secondary sexual characteristics, (b) his blood LH level. Explain.',
       ['**Step 1:** testes = source of testosterone (Leydig cells).',
        '**Step 2:** no testosterone → voice stays high, little beard or body hair, less muscle; no sperm.',
        '**Step 3 — feedback:** testosterone normally switches GnRH and LH **down**. With no testosterone, the brake is gone → **LH (and FSH) rise** to high levels.'],
       '(a) Male secondary characteristics do not develop (high voice, little facial hair, small muscles) and he is infertile. (b) LH rises, because there is no testosterone to give negative feedback.'),
    WK('s116-w2', 'Worked example: why athletes who abuse steroids can become infertile', 12,
       'Some athletes inject large doses of testosterone-like steroids. Explain why their own testes may shrink and sperm production fall.',
       ['**Step 1:** the injected steroid raises the androgen level in blood.',
        '**Step 2 — negative feedback:** the hypothalamus and pituitary sense a high level → **less GnRH, FSH and LH**.',
        '**Step 3:** without LH, Leydig cells stop working; without FSH, sperm production falls → testes shrink.'],
       'High steroid levels switch off GnRH, FSH and LH by negative feedback, so the testes are no longer stimulated: they shrink and make few sperm.'),
    CK('s116-k1', 12, 'Testosterone is produced by the', ['seminiferous tubules', 'Leydig (interstitial) cells', 'epididymis', 'prostate gland'], 'B',
       'Leydig (interstitial) cells, when stimulated by **LH**.'),
    CK('s116-k2', 12, 'Which hormone is made by the corpus luteum?', ['FSH', 'Oestrogen only', 'Progesterone', 'Testosterone'], 'C',
       'After ovulation the follicle becomes the corpus luteum, which secretes **progesterone**.'),
    CK('s116-k3', 12, 'Broadening of the hips and breast enlargement are caused mainly by', ['progesterone', 'oestrogen', 'prolactin', 'oxytocin'], 'B',
       'Female secondary sexual characteristics = **oestrogen**. Prolactin makes milk; oxytocin releases it.'),
    CK('s116-k4', 12, 'Sex hormones belong to which chemical group?', ['Proteins', 'Amines', 'Steroids', 'Peptides'], 'C',
       'Testosterone, oestrogen and progesterone are made from cholesterol → **steroids**.'),
]

# ------------------------------------------------------------------ 1.1.7 Thymus
THM = [
    T('c13', '1.1.7 The thymus gland — school for T cells', 13,
      '**Where:** in the central chest cavity, **behind the breastbone (sternum), below the thyroid and above the heart**.',
      '**Changes with age:** relatively **large in newborns and children**, it **shrinks sharply after puberty**. In adults it gradually degenerates until it almost disappears and becomes filled with fibrous and fatty connective tissue. So the thymus is **functional mainly in childhood**.',
      '**Hormone:** **thymosin** (a group of small peptides).',
      '**Function:** thymosin stimulates the production and maturation of white blood cells called **T cells (T lymphocytes)**, which defend the body against pathogens (germs). Young lymphocytes from the bone marrow come to the thymus, **multiply, differentiate and mature** there, then leave to guard the body for life.',
      '**Why it matters:** T cells direct the immune response and kill infected cells. The HIV virus attacks one kind of T cell (helper T cells), which is why AIDS weakens immunity. A child born without a working thymus has very few T cells and suffers repeated infections.',
      '**Is it under the pituitary?** No well-known pituitary control: its activity is mainly set by **age** (large in childhood, shrinks after puberty — sex hormones speed the shrinking).'),
    TB('s117-t1', 'Thymosin in detail', 13, ['Feature', 'Thymosin'], [
        ['Gland', 'Thymus (behind the sternum, above the heart)'],
        ['Chemical nature', 'Peptides (small proteins)'],
        ['Target', 'White blood cells — young lymphocytes (T cells)'],
        ['Function', 'T cells multiply, differentiate and mature → **immunity** against pathogens'],
        ['Excess', 'No known disease'],
        ['Deficiency / no thymus', 'Few T cells → weak immunity, frequent and serious infections (children)'],
        ['Control / feedback', 'Not by the pituitary; activity falls with age after puberty'],
    ]),
    TB('s117-t2', 'The thymus through life', 13, ['Age', 'Size', 'Activity'], [
        ['Newborn and child', 'Relatively large', 'Very active — most T cells are trained now'],
        ['Puberty', 'Largest absolute size, then starts shrinking', 'Activity begins to fall'],
        ['Adult', 'Small; replaced by fat and fibrous tissue', 'Low — T cells already made keep working'],
    ]),
    MN('s117-m1', 'Thymus memory: “T cells are Thymus-trained”', 13,
       ['**T** cell = **T**hymus cell. The thymus is a **school**: young lymphocytes enrol in childhood, graduate as T cells, and the school closes (shrinks) after puberty.',
        '**Thym-O-sin = Thymus Orders Soldiers IN** (white blood cell soldiers).'], None),
    WK('s117-w1', 'Worked example: thymus removed at birth vs in adulthood', 13,
       'In experiments, removing the thymus from newborn mice causes very weak immunity, but removing it from adult mice has little effect. Explain.',
       ['**Step 1:** the thymus (thymosin) trains T cells mainly **early in life**.',
        '**Step 2 — newborn:** no thymus → T cells never mature → the immune system cannot fight infections.',
        '**Step 3 — adult:** most T cells have already matured and live on in blood and lymph nodes → removal now changes little.'],
       'In newborns the thymus is needed to produce mature T cells; in adults the T-cell population has already been made, so the shrinking (or removed) thymus is no longer essential.'),
    CK('s117-k1', 13, 'Thymosin mainly stimulates the production of', ['red blood cells', 'platelets', 'T lymphocytes', 'antibodies by the liver'], 'C',
       'Thymosin → **T cells (T lymphocytes)** that defend against pathogens.'),
    CK('s117-k2', 13, 'The thymus gland is most active', ['in old age', 'in childhood', 'only during pregnancy', 'only at night'], 'B',
       'Large and active in **childhood**; it shrinks after puberty.'),
    CK('s117-k3', 23, 'In the matching question (Review Part III), the thymus gland matches', ['source of cortisol', 'plays a role in immunity', 'raises blood calcium', 'insulin and glucagon'], 'B',
       'Thymus → **immunity** (T cells). Cortisol = adrenal cortex; raises calcium = parathyroids; insulin/glucagon = pancreatic islets.'),
]

SUMMARY = [
    TB('s110-t4', 'One-page summary: gland → hormone → nature → main job (corrected Table 1.1)', 14, ['Gland', 'Hormone', 'Nature', 'Main job'], [
        ['Anterior pituitary', 'GH · TSH · ACTH · prolactin · FSH · LH', 'Proteins / glycoproteins', 'Growth · thyroid · adrenal cortex · milk · gametes and sex hormones'],
        ['Posterior pituitary', 'ADH · oxytocin (made in hypothalamus)', 'Peptides', 'Water reabsorption · labour and milk ejection'],
        ['Thyroid', 'Thyroxine · calcitonin', 'Amine (with iodine) · peptide', 'Metabolic rate, growth, brain development · lowers blood Ca²⁺'],
        ['Parathyroids', 'PTH', 'Peptide', 'Raises blood Ca²⁺'],
        ['Adrenal cortex', 'Cortisol · aldosterone · sex steroids', 'Steroids', 'Raises glucose, stress · keeps Na⁺/water · minor sex effects'],
        ['Adrenal medulla', 'Adrenaline · noradrenaline', 'Amines', 'Fight or flight · constricts vessels'],
        ['Pancreas (islets)', 'Insulin (β) · glucagon (α)', 'Protein · peptide', 'Lowers · raises blood glucose'],
        ['Testes', 'Testosterone', 'Steroid', 'Sperm formation, male characteristics'],
        ['Ovaries', 'Oestrogen · progesterone', 'Steroids', 'Female characteristics, lining · maintains lining and pregnancy'],
        ['Thymus', 'Thymosin', 'Peptide', 'T-cell maturation (immunity)'],
        ['Pineal', 'Melatonin', 'Amine', 'Day–night rhythms, seasons'],
    ]),
    RM('s110-r2', 'Corrections to the printed Table 1.1 (p.15)', 15,
       'The printed table repeats “required for sperm formation” for **oestrogen** — that is a printing slip. Oestrogen is required for **female secondary sexual characteristics and rebuilding the uterine lining**; testosterone is the one required for sperm formation.',
       'The printed table also gives thyroxine the function “growth metamorphosis in amphibians” — read it as “increases metabolic rate and growth; controls metamorphosis in amphibians”.'),
]

# order of the lesson (strings = existing cards kept in place)
LESSON = [
    'bio11-u1-c01', 'bio11-u1-c02', 'bio11-u1-c03', *BASICS, 'bio11-u1-c04', 'bio11-u1-c05', 'bio11-u1-c06',
    *PIT, 'bio11-u1-chk1', 'bio11-u1-chk2', 'bio11-u1-l1-1-mx1',
    *THY, 'bio11-u1-c09',
    *ADR, *PAN, *SEX, *THM, 'bio11-u1-c14',
    *SUMMARY, 'bio11-u1-wrk1', 'bio11-u1-wrk2', 'bio11-u1-wrk-extra1',
]
LESSONS = {L11: LESSON}
DIAGRAM_KEYS = ['pit', 'fb_thy', 'adr', 'glu', 'fb_gon']
