"""Unit 2 (Reproductive system): 2.2 male reproductive system, 2.3 female reproductive system (2.3.1-2.3.4).
Textbook: Biology for Grade 11 (Eritrea), pp. 27-44."""
from common import *

set_unit('bio11-u2')
L22, L23 = 'bio11-u2-l2-2', 'bio11-u2-l2-3'

# =================================================================== 2.2 MALE
MALE_A = [
    T('c02', '2.2 The male reproductive system — organ by organ', 27,
      '**What the system must do.** The male system has three jobs: (1) **make sperm cells** (male gametes), (2) **deliver them into the female tract**, and (3) **make the male sex hormone testosterone**.',
      '**The nine organs to know** (textbook p.28): **testes, epididymis, vas deferens, urethra, seminal vesicles, prostate gland, Cowper’s glands, scrotum, penis.** Group them so they are easy to remember:',
      '**① Primary sex organs (gonads)** — the two **testes**: make sperm and testosterone.',
      '**② Ducts (tubes)** — **epididymis → vas deferens → urethra**: store, mature and carry sperm.',
      '**③ Accessory glands** — **seminal vesicles, prostate, Cowper’s glands**: add the fluid part of semen.',
      '**④ External organs** — **scrotum** (holds and cools the testes) and **penis** (places semen in the vagina).',
      '**Primary vs secondary characters:** the genital organs above are **primary sexual characters** (present at birth). Changes at puberty — deep voice, beard, broad shoulders — are **secondary sexual characters** caused by testosterone.'),
    ST('s22-s1', 'Follow one sperm: the route out of the body', 28, 'mpath', [
        ('**Testis** — sperm are made in the seminiferous tubules.', 'p1'),
        ('**Epididymis** — hundreds of millions are stored and matured; they learn to swim.', 'p2'),
        ('**Vas deferens** (sperm duct) — muscular tube carries sperm up and round the bladder.', 'p3'),
        ('**Glands add fluid** — seminal vesicles, prostate and Cowper’s glands; sperm + fluid = semen.', 'p4'),
        ('**Urethra** in the penis — semen leaves the body during ejaculation.', 'p5'),
    ]),
    T('s22-t1', 'The testes — where sperm and testosterone are made', 28,
      '**Shape and size:** two **oval (ovoid)** organs, about **5 cm long and 3 cm wide**. Each hangs from a **spermatic cord** (carrying blood vessels, nerves and the vas deferens) inside the sac-like **scrotum**.',
      '**Why outside the body?** Body temperature (37 °C) is **too high** for normal sperm production. Sperm form best at **3–5 °C below** body temperature, so the testes hang outside the abdominal cavity.',
      '**How they got there:** in the unborn baby the testes form inside the abdomen. **Testosterone**, secreted by the developing testes, makes them **descend into the scrotum**, usually before birth.',
      '**Inside a testis:** it is packed with **highly coiled seminiferous tubules** (if stretched out, several hundred metres). The cells lining the inside of the tubules divide actively in mature males to make sperm (**spermatogenesis**).',
      '**Between the tubules** are the **interstitial (Leydig) cells**, which secrete **testosterone** when stimulated by **LH**. Inside the tubules, nurse (**Sertoli**) cells feed the developing sperm (extra detail).',
      '**So the testis is a mixed gland:** sperm leave through ducts (exocrine-like), testosterone goes into the blood (endocrine) — exactly what you met in 1.1.6.'),
    T('s22-t2', 'Spermatogenesis — how a sperm is made, step by step', 29,
      '**Step 1 — the stock.** Germ cells called **spermatogonia** are formed during **fetal life** and stored in the walls of the seminiferous tubules.',
      '**Step 2 — the start.** At **puberty**, FSH (and testosterone) switch the tubules on. Spermatogonia divide by **mitosis** to keep up their numbers.',
      '**Step 3 — halving the chromosomes.** Some cells grow into **primary spermatocytes** and divide by **meiosis**: 46 chromosomes → **23** in each **spermatid**. This is why a sperm carries only half the father’s genes.',
      '**Step 4 — shaping.** Each round spermatid changes shape — grows a tail, packs its mitochondria, forms an acrosome — and becomes a **spermatozoon** (sperm).',
      '**Step 5 — finishing school.** Sperm move to the **epididymis** to be stored and mature. The whole process takes about **two months**, and a healthy man makes **millions every day** from puberty to old age.',
      '**Exam definition:** spermatogenesis is **the process of sperm cell formation** in the seminiferous tubules of the testes.'),
    ST('s22-s2', 'Structure of the sperm cell — part by part', 29, 'sperm', [
        ('**Head** — oval; holds a large **nucleus** with the father’s genetic material (23 chromosomes). Its front cap, the **acrosome**, contains **dissolving enzymes** to get through the coats of the ovum.', 'h'),
        ('**Middle piece** — packed with **mitochondria**, which release energy (respiration) to drive the tail.', 'm'),
        ('**Tail (flagellum)** — long and whip-like; lashes from side to side to **swim** through the uterus to the fallopian tube.', 't'),
    ], 'Sperm cells are among the **smallest** human cells, yet they must carry the father’s traits to the child.'),
    TB('s22-tb1', 'Sperm parts and how each is adapted', 29, ['Part', 'Contains', 'Function', 'Adaptation idea'], [
        ['Acrosome (front of head)', 'Dissolving (digestive) enzymes', 'Penetrate the ovum’s coats', 'Enzymes ready at the very tip'],
        ['Head', 'Large nucleus, 23 chromosomes', 'Carry the father’s genes', 'Small, streamlined, little cytoplasm'],
        ['Middle piece', 'Many mitochondria', 'Energy for swimming', 'Mitochondria spiral round the tail base'],
        ['Tail (flagellum)', 'Contractile fibres', 'Movement', 'Long whip pushes the cell forward'],
    ]),
    RM('c03', 'Male path', 28,
       'Testis (sperm + testosterone) → epididymis → vas deferens → urethra. Glands (seminal vesicles, prostate, Cowper’s) add fluid. Sperm need a bag 3–5 °C cooler than the body — that is why the testes hang outside.'),
    T('s22-t3', 'The ducts — epididymis, vas deferens, urethra', 29,
      '**Epididymis:** a long, tightly coiled tube formed by the **union of the seminiferous tubules**; it lies in close contact with the **outer surface of each testis**. Here **hundreds of millions of sperm are temporarily stored and matured**. The epididymis and tubules make secretions in which the sperm live and move.',
      '**Vas deferens (sperm duct):** one from each epididymis. They run up into the body, loop over the bladder, **join together and open into the urethra**. Their muscular walls squeeze sperm along during ejaculation. (Cutting and tying them is **vasectomy**, a permanent family-planning method — semen still forms, but contains no sperm.)',
      '**Urethra:** a **common tube** running through the centre of the penis. Both **urine and semen** pass through it — but **never at the same time**: during ejaculation a muscle closes the bladder neck.',
      '**If sperm are not released** they break down and are **absorbed by the male’s body** (Exercise 2.2 Q1).'),
    TB('s22-tb2', 'The three accessory glands — what each adds to semen', 30, ['Gland', 'Secretion', 'Why it helps sperm'], [
        ['Seminal vesicles (two, behind bladder)', 'Slightly **alkaline** fluid with **prostaglandins** (and fructose sugar — extra)', 'Regulates pH; prostaglandins make the female tract **contract**, helping sperm move towards the ovum; sugar = fuel'],
        ['Prostate gland (one, below bladder)', '**Thin, milky, alkaline** fluid', '**Neutralises** the acidic sperm fluid (acid from wastes of stored sperm) and the acid of the vagina'],
        ['Cowper’s glands (two, below prostate)', '**Mucus-like** fluid', '**Lubricates** the end of the penis before intercourse'],
    ]),
    T('s22-t4', 'Semen and ejaculation', 30,
      '**Semen** = sperm + secretions of the seminal vesicles, prostate and Cowper’s glands. It is a **creamy-white suspension** that contains sperm **plus food and enzymes that make the sperm active**.',
      '**Functions of the seminal fluid** (Exercise 2.2 Q3): (1) a **liquid medium** in which sperm swim; (2) **food** (sugar) for energy; (3) **alkali** to neutralise acids that would kill sperm; (4) **enzymes** that activate sperm; (5) **prostaglandins** that help sperm reach the ovum; (6) lubrication.',
      '**Ejaculation:** a series of muscular **contractions** squeezes semen from the vas deferens and glands through the urethra and out of its **external opening**.'),
    T('s22-t5', 'Scrotum and penis — the external organs', 30,
      '**Scrotum:** a skin pouch that holds the **testes, the lower part of the spermatic cords and the epididymides**. It lies outside the body, behind the penis and in front of the upper thighs.',
      '**The scrotum is a thermostat** (Do you know? p.31): normally its muscles are **relaxed** and the testes hang **away** from the warm body. If the temperature **drops too much**, the scrotal muscles **contract** and pull the testes **close to the body** to warm them. Even **tight underwear** that warms the testes can lower fertility.',
      '**Penis:** made of **spongy (erectile) tissue and muscle**. During sexual arousal the spaces in the spongy tissue **fill with blood**, so the penis enlarges and hardens — an **erection** — and can enter the vagina to deposit semen.',
      '**Foreskin and circumcision:** the tip of the penis is covered by a loose skin, the **foreskin**. Its surgical removal is **circumcision**. Hygiene point: an uncircumcised man must clean under the foreskin daily to avoid odour and bacterial infection.'),
    TB('s22-tb3', 'Male organs at a glance', 28, ['Organ', 'Type', 'Main function'], [
        ['Testis', 'Primary sex organ (gonad)', 'Makes sperm (seminiferous tubules) and testosterone (Leydig cells)'],
        ['Scrotum', 'External sac', 'Holds testes 3–5 °C below body temperature'],
        ['Epididymis', 'Duct', 'Stores and matures sperm'],
        ['Vas deferens', 'Duct', 'Carries sperm from epididymis to urethra'],
        ['Seminal vesicles', 'Accessory gland', 'Alkaline fluid with prostaglandins (and sugar)'],
        ['Prostate gland', 'Accessory gland', 'Thin milky alkaline fluid that neutralises acid'],
        ['Cowper’s glands', 'Accessory gland', 'Mucus that lubricates'],
        ['Urethra', 'Duct (shared)', 'Carries semen or urine out'],
        ['Penis', 'External organ', 'Deposits semen in the vagina; carries urine'],
    ]),
]

MALE_B = [
    T('l2-2-r3x1', 'Step by step: the male reproductive system', 28,
      '**Step 1:** Testes (in the scrotum) produce sperm and the hormone testosterone; the scrotum keeps them about **3–5 °C below** body temperature, which sperm production needs.',
      '**Step 2:** Sperm mature and are stored in the epididymis.',
      '**Step 3:** During ejaculation sperm travel through the vas deferens (sperm duct) to the urethra.',
      '**Step 4:** Glands add seminal fluid: seminal vesicles (alkaline fluid, prostaglandins, sugar), prostate gland (thin milky alkaline fluid that neutralises acidity) and Cowper’s glands (lubricating mucus); sperm + fluid = semen.',
      '**Step 5:** The urethra in the penis carries semen out of the body.'),
    MN('s22-m1', 'Memory hook — what the three glands add: “SPC”', 30,
       'Go down the urethra in order of the glands: **S**eminal vesicles → **P**rostate → **C**owper’s.',
       [('S', 'Seminal vesicles', 'Sugar + Stimulators (prostaglandins), slightly alkaline'),
        ('P', 'Prostate', 'Protects — milky alkali neutralises acid'),
        ('C', 'Cowper’s', 'Coats — mucus lubricates')]),
    RM('s22-r1', 'Traps examiners love (2.2)', 29,
       '**Made vs stored:** sperm are **made** in the seminiferous tubules but **stored and matured** in the epididymis.',
       '**Tubules vs Leydig cells:** tubules = sperm (FSH); Leydig (interstitial) cells = testosterone (LH).',
       '**Vas deferens ≠ urethra:** the vas deferens carries only sperm; the urethra carries semen **or** urine.',
       '**Which part enters the ovum?** The **head** (with its nucleus). The middle piece and tail are left outside.',
       '**Prostate fluid is alkaline, not acidic** — it neutralises acid.',
       '**Descent of the testes** is caused by **testosterone**, not by FSH.'),
    WK('s22-w1', 'Activity 2.2 Q1 — undescended testes', 29, 'What happens if the testes fail to descend into the scrotum? Why?', [
        'Step 1: Recall where sperm are made best — at 3–5 °C **below** body temperature.',
        'Step 2: A testis that stays in the abdomen is kept at full body temperature (37 °C).',
        'Step 3: At this temperature spermatogenesis fails, so few or no healthy sperm are made.',
        'Step 4: If both testes stay inside, the man is **sterile (infertile)**, although testosterone may still be made, so he still develops male characters.',
        'Step 5: The condition (cryptorchidism) is usually corrected by a small operation in early childhood.',
    ], 'The man becomes infertile because the higher body temperature stops sperm production; testosterone and male features may be normal.'),
    WK('s22-w2', 'Activity 2.2 Q2 — adaptations of sperm', 29, 'How are sperm cells adapted to perform their function?', [
        'Step 1: Function = reach the ovum, enter it and deliver the father’s genes.',
        'Step 2: Reach it → long **tail** for swimming; **mitochondria** in the middle piece supply energy.',
        'Step 3: Enter it → **acrosome** enzymes dissolve the ovum’s outer coats.',
        'Step 4: Deliver genes → head with a **haploid nucleus** (23 chromosomes); little cytoplasm so it is small and streamlined.',
        'Step 5: Made in huge numbers → greater chance that one reaches the ovum.',
    ], 'Tail (swimming), mitochondria (energy), acrosome (enzymes to penetrate the ovum), haploid nucleus (genes), small streamlined shape and huge numbers.'),
    WK('s22-w3', 'Exercise 2.2 Q1', 30, 'What will happen to mature sperm cells that are not released from the body?', [
        'Step 1: Sperm are stored in the epididymis for a limited time.',
        'Step 2: Old sperm that are not ejaculated break down.',
        'Step 3: Their materials are reabsorbed by the body.',
    ], 'They break down and are absorbed by the male’s body.'),
    WK('s22-w4', 'Exercise 2.2 Q2', 29, 'What is spermatogenesis?', [
        'Step 1: “Sperm” + “genesis” (origin, making).',
        'Step 2: Where — seminiferous tubules of the testes; when — from puberty.',
        'Step 3: How — spermatogonia → mitosis → meiosis → spermatids → sperm.',
    ], 'Spermatogenesis is the formation of sperm cells from spermatogonia in the seminiferous tubules of the testes, beginning at puberty.'),
    WK('s22-w5', 'Exercise 2.2 Q3', 30, 'What is the function of the seminal fluid?', [
        'Step 1: Name the source — seminal vesicles, prostate and Cowper’s glands.',
        'Step 2: Medium — gives a liquid for sperm to swim in.',
        'Step 3: Food and enzymes — sugar for energy, enzymes that activate sperm.',
        'Step 4: Alkaline — neutralises acid in the male urethra and the vagina.',
        'Step 5: Prostaglandins — cause contractions in the female tract that help sperm move to the ovum; mucus lubricates.',
    ], 'It carries the sperm, feeds and activates them, neutralises acids, helps their movement in the female tract and lubricates.'),
    WK('s22-w6', 'Exercise 2.2 Q4', 29, 'Which part of the sperm cell enters the ovum and is involved in fertilization?', [
        'Step 1: The acrosome releases enzymes that open a path through the ovum’s coats.',
        'Step 2: The **head** with its nucleus enters the ovum.',
        'Step 3: The sperm nucleus fuses with the ovum nucleus → zygote.',
    ], 'The head (its nucleus fuses with the egg nucleus); the acrosome helps it get in.'),
    WK('s22-w7', 'Let us discuss — is one parent’s gamete enough?', 27, 'In sexual reproduction, is the gamete produced by one parent enough to produce a zygote? Why?', [
        'Step 1: Gametes are made by meiosis, so each has only **half** the chromosomes (23 in humans).',
        'Step 2: A zygote must have the full **46**.',
        'Step 3: So a sperm (23) must fuse with an ovum (23) → 46.',
    ], 'No. Each gamete is haploid (23 chromosomes); fusion of a male and a female gamete restores the diploid number (46) in the zygote.'),
    WK('s22-w8', 'Apply it — vasectomy', 29, 'A man has both vasa deferentia cut and tied. Explain whether he still (a) ejaculates, (b) is fertile, (c) has a deep voice.', [
        'Step 1: (a) The glands are untouched, so he still ejaculates semen — but it contains **no sperm**.',
        'Step 2: (b) With no sperm in the semen he is **infertile** (vasectomy is a permanent contraceptive).',
        'Step 3: (c) Testosterone goes into the **blood**, not through the vas deferens, so male characters stay normal.',
    ], '(a) Yes, semen without sperm; (b) no, he is sterile; (c) yes, testosterone still reaches the blood.'),
    CK('s22-k1', 28, 'Why are the testes outside the abdominal cavity?', ['To make room for the bladder', 'Body temperature is too high for normal sperm production', 'To produce more testosterone', 'So that semen can be stored'], 'B',
       '**Step 1:** Sperm are made best at 3–5 °C below body temperature.\n\n**Step 2:** The scrotum holds the testes outside the warm abdomen.\n\n**Answer: B.**'),
    CK('s22-k2', 29, 'Which part of the sperm contains many mitochondria?', ['Acrosome', 'Head', 'Middle piece', 'Tail'], 'C',
       '**Step 1:** Mitochondria release energy.\n\n**Step 2:** They are packed in the middle piece, close to the tail they power.\n\n**Answer: C.**'),
    CK('s22-k3', 29, 'Sperm are stored and matured in the', ['seminiferous tubules', 'epididymis', 'prostate gland', 'urethra'], 'B',
       '**Step 1:** Tubules make sperm.\n\n**Step 2:** The epididymis, on the outside of each testis, stores and matures them.\n\n**Answer: B.**'),
    CK('s22-k4', 30, 'Which secretion lubricates the end of the penis before intercourse?', ['Seminal vesicle fluid', 'Prostate fluid', 'Cowper’s gland mucus', 'Testosterone'], 'C',
       '**Step 1:** Lubricate = slippery = mucus.\n\n**Step 2:** Cowper’s glands secrete mucus-like fluid.\n\n**Answer: C.**'),
    CK('s22-k5', 31, 'If the scrotum becomes too cold, its muscles', ['relax and the testes hang lower', 'contract and pull the testes close to the body', 'secrete warm fluid', 'stop all blood flow'], 'B',
       '**Step 1:** Too cold → testes must be warmed.\n\n**Step 2:** Scrotal muscles contract and pull the testes towards the warm body.\n\n**Answer: B.**'),
]

# =================================================================== 2.3 FEMALE
FEM_A = [
    T('s23-t0', '2.3 The female reproductive system — what it must do', 32,
      '**Five jobs:** make **ova** (eggs) and female sex hormones; receive sperm (**conception**); hold and feed the **developing fetus**; give **birth**; and **feed the baby** with milk.',
      '**Internal (major) organs:** **ovaries, fallopian tubes (oviducts), uterus, vagina** — all inside the pelvis.',
      '**External (accessory) organs:** the **vulva** and the **mammary glands** (breasts).',
      '**Compare with the male:** ovary ↔ testis (gonad); oviduct ↔ sperm duct (tube); but the female has a uterus to carry the baby, so her system has **more jobs** than the male’s.'),
    ST('s23-s1', 'The female organs — from ovary to the outside', 33, 'fem', [
        ('**Ovaries** — two oval glands; make ova and the hormones oestrogen and progesterone.', 'ov'),
        ('**Fallopian tubes** — funnel with fimbriae catches the ovum; cilia move it; **fertilization happens here** (upper part).', 'tb'),
        ('**Uterus (womb)** — muscular, pear-shaped; the embryo implants in its lining (endometrium).', 'ut'),
        ('**Cervix** — the muscular neck of the uterus that projects into the vagina.', 'cx'),
        ('**Vagina** — 10–15 cm tube; receives the penis and sperm; the birth canal.', 'vg'),
    ]),
    T('s23-t1', 'Ovaries — the female gonads', 33,
      '**Position:** two **oval** organs in the pelvis, **one on each side of the uterus**, attached to the body wall and anchored to the uterus by the **ovarian ligament**.',
      '**When they start:** at **puberty** the **pituitary** (FSH and LH) stimulates them to become functional.',
      '**Job 1 — ova.** Each ovum develops inside a fluid-filled **follicle**. About once a month one follicle bursts and releases its ovum — **ovulation**.',
      '**Job 2 — hormones.** The **follicle** makes **oestrogen** (female characters, rebuilds the uterine lining). After ovulation the empty follicle turns into the **corpus luteum** (“yellow body”), which makes **progesterone** to prepare and keep the uterus ready for a fertilized ovum.',
      '**So the ovary, like the testis, is a mixed gland:** gametes out, hormones into the blood.'),
    T('s23-t2', 'Oogenesis — the numbers behind the eggs', 34,
      '**Step 1 — at birth:** a girl’s ovaries already hold about **two million** potential ova. No new ones are made after birth (very different from sperm).',
      '**Step 2 — before puberty:** about **75 %** degenerate, leaving a few **hundred thousand**.',
      '**Step 3 — puberty to menopause:** each month **one** ovary releases **one** ovum ready for fertilization. Over a lifetime only **400–500** become mature ova.',
      '**Step 4 — the meiosis twist (extra):** egg cells start meiosis before birth and pause; the ovum completes meiosis only if a sperm enters. Each division gives **one large ovum** (with nearly all the cytoplasm) and tiny **polar bodies** that die.',
      '**Definitions:** **oogenesis** = production of ova in the ovaries; **ovulation** = release of a mature ovum from the ovary; **menopause** = the end of menstrual cycles.'),
    DG('s23-d1', 'Structure of the ovum', 34, 'ovum',
       '**Nucleus** — the mother’s 23 chromosomes. **Cytoplasm with yolk** — food for the first days after fertilization. **Jelly coat** and **follicle cells** — protective layers the sperm’s acrosome enzymes must dissolve. **No tail** — the ovum is moved by cilia and muscle in the oviduct.'),
    TB('s23-tb1', 'Sperm vs ovum', 34, ['Feature', 'Sperm', 'Ovum'], [
        ['Size', 'Tiny (≈0.05 mm long)', 'Large (≈0.1 mm), just visible'],
        ['Movement', 'Swims with a tail', 'No tail; moved by cilia'],
        ['Food store', 'Almost none', 'Yolk in the cytoplasm'],
        ['Number made', 'Millions per day', 'One per month; 400–500 in a lifetime'],
        ['Made from', 'Puberty to old age', 'Stock fixed at birth; released puberty → menopause'],
        ['Chromosomes', '23 (X or Y)', '23 (always X)'],
        ['Life after release', 'A few days in the female tract', 'About 24 hours'],
    ]),
    T('s23-t3', 'Fallopian tubes (oviducts) — the meeting place', 34,
      '**Structure:** two tubes, one each side of the uterus. Each starts as a **funnel** with finger-like **fimbriae** lying close to (but **not joined to**) the ovary, runs downward and inward, and joins the top of the uterus.',
      '**Catching the ovum:** at ovulation the fimbriae sweep over the ovary and the ovum is drawn into the funnel.',
      '**Moving the ovum:** the ovum cannot swim. **Cilia** lining the tube beat towards the uterus and the muscular wall contracts gently (peristalsis).',
      '**Fertilization site:** sperm swim up to meet the ovum in the **upper region of the fallopian tube**. The zygote then takes several days to reach the uterus.',
      '**Why a blocked tube matters:** if the tubes are blocked (e.g. by infection) sperm and ovum cannot meet → infertility; tying the tubes (tubal ligation) is a permanent contraceptive.'),
    T('s23-t4', 'The uterus (womb) and cervix — the life-support system', 34,
      '**Shape and size:** a hollow, muscular, **pear-shaped** organ (the textbook prints “pearl-shaped” — it means pear), about the size of a **fist** when not pregnant. It lies **behind the bladder** (and in front of the rectum).',
      '**Three layers (extra detail):** outer covering; thick **muscle (myometrium)** that contracts strongly in labour; inner lining (**endometrium**) rich in blood vessels and glands — thickens every month and is shed at menstruation.',
      '**Function:** the place where the fertilized egg **implants, receives nourishment and develops into a fetus**. It stretches enormously during pregnancy and pushes the baby out at birth.',
      '**Cervix:** the lower, muscular **neck** of the uterus that projects into the vagina. It stays tightly closed during pregnancy and **dilates (widens)** during childbirth.'),
    T('s23-t5', 'Vagina, vulva and mammary glands', 35,
      '**Vagina:** a muscular tube **10–15 cm** long connecting the uterus (cervix) to the outside. It **receives the penis and sperm**, lets the menstrual flow out, and is the **birth canal**. It is **separate from the urethra** (unlike the male, the female has separate openings for urine and reproduction).',
      '**Hymen:** a thin mucous membrane partly covering the vaginal opening. It usually has **one or more holes**, which let menstrual blood out; the openings are usually enlarged at first intercourse — but the hymen can also stretch or tear in **sport, heavy exercise or accidents**, so its state is **not** proof of virginity.',
      '**Vulva:** the **external genitalia** — the **vestibule** (space into which the vagina and urethra open) with its surrounding structures: outer lips (**labia majora**), inner lips (**labia minora**) and, in front, the small sensitive **clitoris** with erectile tissue.',
      '**Mammary glands:** organs of **milk production** inside the breasts. They enlarge at puberty under **oestrogen and progesterone**; after birth **prolactin** makes milk and **oxytocin** ejects it.'),
    TB('s23-tb2', 'Female organs at a glance', 33, ['Organ', 'Where / what', 'Main function'], [
        ['Ovary (×2)', 'Oval, beside the uterus', 'Ova; oestrogen (follicle), progesterone (corpus luteum)'],
        ['Fallopian tube (×2)', 'Funnel + fimbriae + ciliated tube', 'Catches ovum; site of fertilization; carries zygote'],
        ['Uterus', 'Muscular, pear-shaped, behind bladder', 'Implantation, nourishment, growth of fetus; labour'],
        ['Cervix', 'Neck of uterus', 'Closes uterus in pregnancy; dilates at birth'],
        ['Vagina', '10–15 cm tube', 'Receives sperm; menstrual exit; birth canal'],
        ['Vulva', 'External: labia, clitoris, vestibule', 'Protects openings; sensation'],
        ['Mammary glands', 'In the breasts', 'Milk production'],
    ]),
    MN('s23-m1', 'Memory hook — the egg’s route: “Only The Ugly Cat Visits”', 33,
       'Say it as you trace the diagram from the side to the middle and down.',
       [('O', 'Ovary', 'egg released'), ('T', 'Tube (oviduct)', 'fertilized here'), ('U', 'Uterus', 'implants here'), ('C', 'Cervix', 'the neck'), ('V', 'Vagina', 'birth canal')]),
    RM('c04', 'Female path', 33, 'Ovary (egg + oestrogen/progesterone) → oviduct (fertilisation address) → uterus (implants) → cervix → vagina.'),
    WK('s23-w1', 'Exercise 2.3 Q1 / Activity 2.4 — the hymen', 35, 'What is the hymen? How does the menstrual flow leave the uterus when the hymen is present? Does the absence of an intact hymen show that a woman has had intercourse?', [
        'Step 1: Definition — a thin mucous membrane that partly covers the vaginal opening.',
        'Step 2: It normally has **one or more openings**, so menstrual blood flows out through them.',
        'Step 3: The hymen can stretch or tear during heavy exercise, sport, cycling, horse-riding or accidents; some girls are born with very little hymen.',
        'Step 4: So an absent or torn hymen is **not proof** of intercourse.',
    ], 'A thin membrane over the vaginal opening with small holes through which the menstrual flow passes; it can be broken without intercourse, so its absence is not proof of sexual activity.'),
    WK('s23-w2', 'Number work — how many eggs?', 34, 'A girl is born with 2 000 000 potential ova. 75 % degenerate before puberty. How many remain at puberty, and what percentage of these will ever mature if 450 do?', [
        'Step 1: Remaining = 25 % of 2 000 000 = 0.25 × 2 000 000 = **500 000**.',
        'Step 2: Fraction maturing = 450 ÷ 500 000 = 0.0009.',
        'Step 3: As a percentage = 0.0009 × 100 = **0.09 %**.',
    ], '500 000 remain; fewer than 0.1 % (450) ever mature.'),
    WK('s23-w3', 'Activity 2.5', 35, '(1) What is the role of the ovum in reproduction? (2) What is the function of the uterus?', [
        'Step 1: The ovum is the female gamete — it carries the mother’s 23 chromosomes and food (yolk).',
        'Step 2: When fertilized it forms the zygote, which grows into the new individual.',
        'Step 3: The uterus receives the embryo, lets it implant, nourishes it through the placenta, protects it, and pushes it out at birth.',
    ], '(1) Supplies the mother’s genes and the first food for the zygote. (2) Implantation, nourishment, protection and growth of the fetus; contractions at birth.'),
    CK('s23-k1', 33, 'The corpus luteum develops from', ['the uterus lining', 'the empty follicle after ovulation', 'the cervix', 'the fimbriae'], 'B',
       '**Step 1:** After the ovum leaves, the follicle remains.\n\n**Step 2:** Under LH it becomes the corpus luteum, which secretes progesterone.\n\n**Answer: B.**'),
    CK('s23-k2', 34, 'The ovum moves along the fallopian tube by', ['swimming with a tail', 'cilia and muscular contractions', 'gravity only', 'blood flow'], 'B',
       '**Step 1:** The ovum has no tail.\n\n**Step 2:** Cilia lining the tube and gentle muscle contractions move it.\n\n**Answer: B.**'),
    CK('s23-k3', 35, 'Which structure is the birth canal?', ['Urethra', 'Cervix only', 'Vagina', 'Fallopian tube'], 'C',
       '**Step 1:** The baby passes through the dilated cervix and then the vagina.\n\n**Step 2:** The vagina is the corridor to the outside.\n\n**Answer: C.**'),
]

# ---------------------------------------------------------------- 2.3.1 Menstruation
MENS = [
    T('c08', '2.3.1 Menstruation and the menstrual cycle', 36,
      '**Step 1 — preparing a bed.** After ovulation the **corpus luteum** produces **progesterone**, which makes the uterine wall (endometrium) **thick, soft and rich in blood vessels**, ready to receive a fertilized ovum.',
      '**Step 2 — no baby, no bed.** If the ovum is **not fertilized** or **implantation fails**, the corpus luteum dies, progesterone falls, and the thick wall **breaks down**.',
      '**Step 3 — the flow.** The endometrial lining and the unfertilized ovum are discharged **with blood** through the vagina. This periodic flow of blood and tissue is **menstruation** (a “period”).',
      '**Step 4 — rebuild.** After menstruation, oestrogen from a new growing follicle makes the lining **build up again**.',
      '**The menstrual cycle** = this repeated building up and shedding of the lining plus the release of an ovum, about **every 28 days**, from **puberty** to **menopause**.'),
    ST('s231-s1', 'The three phases on a 28-day timeline', 36, 'cycle', [
        ('**Menstrual phase (days 1–5, 4–5 days):** blood, vessels and endometrial tissue are shed.', 'm'),
        ('**Proliferative / follicular phase (days 5–14, 9–10 days):** the lining **proliferates** (grows rapidly) while ovarian follicles develop and make oestrogen.', 'f'),
        ('**Ovulation (about day 14):** an LH surge makes the ripe follicle burst and release the ovum. The day varies between women and between cycles.', 'o'),
        ('**Secretory / luteal phase (days 14–28, 12–14 days):** uterine glands mature and **secrete**; the **corpus luteum** (luteal) makes progesterone.', 'l'),
    ]),
    TB('s231-tb1', 'Menstrual cycle phases', 36, ['Phase (other name)', 'Days', 'In the ovary', 'In the uterus'], [
        ['Menstrual', '1–5', 'New follicles start to grow (FSH)', 'Lining shed with blood'],
        ['Proliferative (follicular)', '5–14', 'Follicle grows, makes oestrogen', 'Lining rebuilt and thickens'],
        ['Ovulation', '≈14', 'LH surge → follicle bursts, ovum released', 'Lining thick'],
        ['Secretory (luteal)', '14–28', 'Corpus luteum makes progesterone', 'Glands secrete; lining kept ready'],
    ]),
    RM('s231-r1', 'Why the names make sense', 36,
       '**Proliferative** = proliferation (fast growth) of the uterine mucosa. **Follicular** = the ovarian follicles develop.',
       '**Secretory** = uterine glands secrete. **Luteal** = the corpus **luteum** is present.',
       '**Rule:** the uterus name and the ovary name describe the **same days** from two organs.'),
    T('s231-t1', 'Menopause — when the cycles stop', 37,
      '**When:** at about **40–50 years**, cycles become **irregular**, ovulation stops, and finally cycles stop completely — **menopause**.',
      '**Why:** age-related changes in the ovaries — **very few follicles remain**, and those that remain are **less sensitive to FSH and LH**, however high these hormones are.',
      '**Result:** oestrogen and progesterone fall, so FSH and LH actually **rise** (no negative feedback).',
      '**Males (Activity 2.7 Q3):** men have **no true menopause** — sperm and testosterone production fall only slowly with age.'),
    WK('s231-w1', 'Calculate — ovulation and the fertile days', 36, 'Ruth’s period started on 3 March and her cycles are a regular 28 days. (a) On what date does she probably ovulate? (b) Ovulation happens about 14 days before the NEXT period. If Selam has a regular 32-day cycle, on which cycle day does she ovulate?', [
        'Step 1: Day 1 = 3 March, so day 14 = 3 + 13 = **16 March**.',
        'Step 2: For a 32-day cycle, the luteal phase is still about 14 days.',
        'Step 3: Ovulation day = 32 − 14 = **day 18**.',
        'Step 4: Fertile window: sperm live a few days and the ovum ≈ 24 h, so the days just before and on ovulation are most fertile — this is why “safe-period” counting is unreliable when cycles vary.',
    ], '(a) About 16 March. (b) About day 18.'),
    WK('s231-w2', 'Explain — why menstruation stops in pregnancy', 40, 'Why does a pregnant woman not menstruate?', [
        'Step 1: Menstruation happens when progesterone falls.',
        'Step 2: In pregnancy the corpus luteum, and later the **placenta**, keep secreting progesterone (and oestrogen).',
        'Step 3: High progesterone keeps the lining in place and stops new follicles developing, so no ovulation or menstruation.',
    ], 'Progesterone stays high (corpus luteum, then placenta), so the lining is not shed and ovulation is prevented.'),
    CK('s231-k1', 36, 'The secretory phase is also called the luteal phase because', ['the lining is shed', 'the corpus luteum is present', 'FSH is highest', 'the follicle is growing'], 'B',
       '**Step 1:** Luteal comes from corpus luteum.\n\n**Step 2:** It is present from ovulation to the end of the cycle.\n\n**Answer: B.**'),
]

# ---------------------------------------------------------------- 2.3.2 Hormonal control
HORM = [
    T('c09', '2.3.2 Hormonal control of reproduction — the chain of command', 38,
      '**Step 1 — brain.** The **hypothalamus** produces **gonadotropin-releasing hormone (GnRH)**, which travels to the anterior pituitary.',
      '**Step 2 — pituitary.** GnRH makes the pituitary secrete **FSH** and **LH**.',
      '**Step 3 — puberty switch.** Before puberty a small amount of testosterone and other **androgens** **inhibit** GnRH release. At puberty the hypothalamus becomes **less sensitive** to this inhibition, GnRH rises, and so do LH and FSH.',
      '**Step 4 — FSH** stimulates the **seminiferous tubules** (sperm formation) in males and the **growth of follicles** in females; the cells round a developing ovum make **oestrogen**.',
      '**Step 5 — LH** makes the **interstitial cells** of the testes secrete more **testosterone**; in females it causes ovulation and makes the **corpus luteum** produce **progesterone**.',
      '**Step 6 — the outcome.** If the egg is fertilized, progesterone **keeps the uterine lining** from breaking down. If not, the corpus luteum breaks down, progesterone stops, and **menstruation** follows.'),
    TB('s232-tb1', 'Table 2.1 expanded — reproductive hormones', 39, ['Hormone', 'Main source', 'Target', 'Main effect'], [
        ['GnRH', 'Hypothalamus', 'Anterior pituitary', 'Releases FSH and LH'],
        ['FSH', 'Anterior pituitary', 'Ovary follicles / seminiferous tubules', 'Gamete production (ovum and sperm); oestrogen production'],
        ['LH', 'Anterior pituitary', 'Ovary / Leydig cells', 'Ovulation; progesterone (corpus luteum); testosterone'],
        ['Oestrogen', 'Ovary (follicle)', 'Uterus, body', 'Thickens uterine lining; female sexual characteristics'],
        ['Progesterone', 'Corpus luteum (later placenta)', 'Uterus', 'Prepares and maintains lining for implantation'],
        ['Testosterone', 'Testes (interstitial cells)', 'Tubules, body', 'Sperm production; male sexual characteristics'],
    ]),
    T('s232-t1', 'Feedback — how the hormones talk to each other', 38,
      '**Negative feedback (most of the cycle):** rising oestrogen and progesterone (or testosterone in males) **reduce** GnRH, FSH and LH. This keeps only **one** follicle developing at a time and keeps male hormone levels steady.',
      '**Positive feedback (just before ovulation):** when oestrogen from the ripe follicle reaches a **high peak**, it does the opposite and triggers a **surge of LH** → ovulation.',
      '**After ovulation:** high progesterone holds FSH and LH down, so no new follicle grows; when the corpus luteum dies, the brake is released and FSH rises again → a new cycle.',
      '**Application:** the contraceptive pill supplies oestrogen/progesterone, keeping FSH and LH low, so no follicle matures and no ovulation occurs.'),
    MN('s232-m1', 'Memory hook — order of hormones in a cycle: FOLP', 38,
       '“**F**irst **O**pen the **L**ining, then **P**rotect it.”',
       [('F', 'FSH', 'grows the follicle'), ('O', 'Oestrogen', 'rebuilds the lining'), ('L', 'LH (surge)', 'ovulation, corpus luteum'), ('P', 'Progesterone', 'keeps the lining')]),
    WK('s232-w1', 'Activity 2.6 Q1', 39, 'What is the function of the testosterone found in males before puberty?', [
        'Step 1: Before birth, testosterone from the developing testes makes them **descend into the scrotum** and the male organs form.',
        'Step 2: In childhood the small amount present **inhibits GnRH**, so FSH and LH stay low.',
        'Step 3: This keeps puberty from starting too early.',
    ], 'It causes descent of the testes (before birth) and, in childhood, inhibits GnRH release so that puberty does not start early.'),
    WK('s232-w2', 'Activity 2.6 Q2', 39, 'Can fertilization take place in the uterus? Why?', [
        'Step 1: The ovum lives only about **24 hours** after ovulation.',
        'Step 2: It moves slowly down the tube and needs several days to reach the uterus.',
        'Step 3: So by the time it reaches the uterus it has degenerated; normally fertilization occurs in the **upper fallopian tube**.',
    ], 'Normally no — the ovum dies within about 24 hours, long before it reaches the uterus, so fertilization happens in the upper oviduct.'),
    CK('s232-k1', 38, 'At puberty GnRH secretion increases because the hypothalamus', ['makes more androgens', 'becomes less sensitive to the inhibitory effect of androgens', 'is stimulated by oxytocin', 'stops making FSH'], 'B',
       '**Step 1:** Before puberty androgens hold GnRH back.\n\n**Step 2:** At puberty the hypothalamus becomes less sensitive to that brake → more GnRH.\n\n**Answer: B.**'),
]

# ---------------------------------------------------------------- 2.3.3 Fertilization and pregnancy
FERT = [
    T('c10', '2.3.3 Fertilization and pregnancy — the journey step by step', 39,
      '**Step 1 — ovulation.** Roughly every **28 days** one ovum is released, usually **alternately** from the two ovaries. Cilia move it down the fallopian tube. It lives only about **24 hours**.',
      '**Step 2 — sperm arrive.** During intercourse (copulation) millions of sperm are released into the vagina. They swim through the cervix and uterus into the fallopian tube. (The textbook gives 3–5 million per cm³ of semen; medical references give tens of millions per cm³ — remember simply “millions”.) Sperm can live in the female tract for **a few days**.',
      '**Step 3 — fertilization.** Several sperm reach the ovum, but **only one** enters. Its nucleus **fuses** with the ovum nucleus → **zygote** (46 chromosomes). This happens in the **upper region of the fallopian tube**.',
      '**Step 4 — cleavage.** The zygote divides by **mitosis** — 2, 4, 8, 16 cells… — forming a ball of cells while moving down the tube. Pregnancy has begun.',
      '**Step 5 — implantation.** The ball of cells reaches the uterus and the embryo **implants** in the thickened wall, obtaining food from it.',
      '**Step 6 — keeping the pregnancy.** Progesterone (corpus luteum) maintains the uterus and stops follicles developing → no ovulation, no menstruation.'),
    T('s233-t1', 'Placenta, membranes and umbilical cord', 40,
      '**Placenta:** a special tissue made by the growing embryo and firmly joined to the uterine wall. It **absorbs nutrients and oxygen** from the mother and passes **wastes (CO₂, urea)** back. As it grows it secretes **oestrogen and progesterone**; then the corpus luteum degenerates and the placenta keeps the embryo attached.',
      '**Chorion:** the outer membrane that protects the embryo (and forms part of the placenta).',
      '**Amnion:** a sac containing **amniotic fluid** — a watery environment and a **shock absorber**.',
      '**Umbilical cord:** a long cord joining the embryo to the placenta. The **umbilical vein** carries **food and oxygenated blood** to the embryo; the **umbilical arteries** carry **wastes and deoxygenated blood** back to the placenta. (Vessels are named by direction — veins go **towards** the heart, arteries **away** — not by how much oxygen they carry.)',
      '**No direct mixing:** mother’s and baby’s blood do **not** mix; materials diffuse across the thin barrier **in the placenta** (the textbook says “through the umbilical cord” — the cord only carries the baby’s blood to and from the placenta).',
      '**Gestation:** pregnancy usually lasts **38–40 weeks** (about 9 months).'),
    TB('s233-tb1', 'Exchange across the placenta', 41, ['From mother to fetus', 'From fetus to mother', 'Kept apart'], [
        ['Oxygen', 'Carbon dioxide', 'Blood cells (no direct mixing)'],
        ['Glucose, amino acids, fats, vitamins, minerals', 'Urea and other wastes', 'Most bacteria'],
        ['Antibodies; but also alcohol, nicotine, some drugs and viruses (e.g. HIV) can cross', '—', 'Different blood pressures kept separate'],
    ]),
    TB('s233-tb2', 'Twins compared (Exercise 2.3 Q3)', 40, ['Type', 'How formed', 'Genes and sex', 'Placenta / body'], [
        ['Fraternal (non-identical)', 'Two ova released and each fertilized by a different sperm', 'Different, like ordinary siblings; may be different sexes', 'Separate placentas; separate bodies'],
        ['Identical', 'One fertilized ovum (zygote) divides into two embryos', 'Genetically identical; always same sex', 'Often share a placenta; separate bodies'],
        ['Siamese (conjoined)', 'One zygote divides but fails to separate fully', 'Identical; same sex', 'Born joined; may share vital organs'],
    ]),
    WK('s233-w1', 'Exercise 2.3 Q3 — twins', 40, 'What are the differences between fraternal, identical and Siamese twins?', [
        'Step 1: Count the eggs and sperm — fraternal: **2 ova + 2 sperm**; identical and Siamese: **1 ovum + 1 sperm**.',
        'Step 2: Genes — fraternal twins differ (may be boy and girl); identical/Siamese have the same genes and sex.',
        'Step 3: Separation — identical twins separate fully; Siamese twins do not and are born joined.',
    ], 'Fraternal: two eggs fertilized by two sperm — genetically different. Identical: one zygote splits into two — genetically identical. Siamese: one zygote splits incompletely — identical twins born joined.'),
    WK('s233-w2', 'Number work — cleavage', 40, 'A zygote divides by mitosis every 12 hours. How many cells are there after 2 days (assume all divisions are regular)?', [
        'Step 1: 2 days = 48 hours = 48 ÷ 12 = 4 divisions.',
        'Step 2: Cells double each time: 1 → 2 → 4 → 8 → 16.',
        'Step 3: Formula: 2ⁿ = 2⁴ = 16.',
    ], '16 cells.'),
    WK('s233-w3', 'Why only a short fertile period?', 40, 'Sperm can live a few days in the female tract. Why is the period in which fertilization can occur still short?', [
        'Step 1: The limiting cell is the ovum.',
        'Step 2: The ovum degenerates about 24 hours after ovulation.',
        'Step 3: So fertilization is possible only if sperm are present in the tube in the days just before or within a day after ovulation.',
    ], 'Because the ovum survives only about 24 hours after ovulation.'),
    CK('s233-k1', 41, 'The umbilical vein carries', ['deoxygenated blood to the placenta', 'oxygenated blood and food to the embryo', 'urine to the mother', 'amniotic fluid'], 'B',
       '**Step 1:** Vein = towards the baby’s heart.\n\n**Step 2:** It carries food and oxygen from the placenta.\n\n**Answer: B.**'),
    CK('s233-k2', 41, 'The function of amniotic fluid is to', ['feed the embryo', 'act as a shock absorber and give a watery environment', 'make progesterone', 'carry oxygen'], 'B',
       '**Step 1:** The amnion is a fluid-filled sac.\n\n**Step 2:** The fluid cushions the embryo.\n\n**Answer: B.**'),
]

# ---------------------------------------------------------------- 2.3.4 Childbirth
BIRTH = [
    T('c11', '2.3.4 Childbirth (parturition) — step by step', 42,
      '**Step 1 — labour begins.** Towards the end of gestation the thick muscular wall of the uterus starts **regular, powerful contractions** (labour). **Oxytocin** from the posterior pituitary strengthens them by **positive feedback** (link to 1.1.1).',
      '**Step 2 — the waters break.** The abdominal wall contracts too; the **amnion bursts** and amniotic fluid flows out through the vagina, **lubricating the birth canal**.',
      '**Step 3 — opening.** The **cervix and vagina dilate** (widen).',
      '**Step 4 — birth.** The fetus, usually **head first** towards the cervix, gradually emerges through the vagina — **birth or parturition**.',
      '**Step 5 — afterbirth.** The cord is clamped and cut. Further contractions push out the **placenta** and the remaining part of the umbilical cord — together called the **afterbirth**.',
      '**Step 6 — the navel.** The stump of cord on the baby dries and falls off, leaving a scar — the **navel**.',
      '**Step 7 — care.** By instinct the baby suckles; **prolactin** makes milk and **oxytocin** lets it flow. Breast milk gives nutrients and antibodies. Humans care for their young for many years.'),
    WK('s234-w1', 'Exercise 2.3 Q2 — afterbirth', 43, 'What is afterbirth?', [
        'Step 1: After the baby is born the uterus keeps contracting.',
        'Step 2: These contractions expel the placenta and the part of the umbilical cord left inside.',
    ], 'The placenta and the remaining umbilical cord, pushed out by contractions of the uterus and abdominal wall after the baby is born.'),
    WK('s234-w2', 'Activity 2.7 Q1', 42, 'Is it possible to know the sex of an unborn baby? How?', [
        'Step 1: Yes — sex is fixed at fertilization (XX girl, XY boy).',
        'Step 2: An **ultrasound** scan (from about 18–20 weeks) shows the external genitals.',
        'Step 3: Tests of fetal cells (amniocentesis) can show the chromosomes, but are used only for medical reasons.',
    ], 'Yes, mainly by ultrasound scanning; chromosome tests of fetal cells can also show it.'),
    CK('s234-k1', 43, 'Which hormone increases uterine contractions during labour?', ['Prolactin', 'Oxytocin', 'Progesterone', 'FSH'], 'B',
       '**Step 1:** Contractions of the uterus = oxytocin.\n\n**Step 2:** Prolactin is for milk production; progesterone actually relaxes the uterus.\n\n**Answer: B.**'),
    RM('s23-r1', 'Traps examiners love (2.3)', 39,
       '**Fertilization** happens in the **oviduct**; **implantation** in the **uterus**.',
       '**Follicle → oestrogen; corpus luteum → progesterone.** Do not swap them.',
       '**The ovum has no tail**; it is moved by cilia.',
       '**Umbilical vein = oxygenated** (to the baby).',
       '**Fraternal = 2 eggs; identical = 1 egg.**',
       '**Menstruation** = shedding of the lining because progesterone falls — not because oestrogen rises.'),
]

LESSONS = {
    L22: MALE_A + ['bio11-u2-chk3', 'bio11-u2-chk4', 'bio11-u2-c16'] + MALE_B[:1] +
         ['bio11-u2-l2-2-r3x2'] + MALE_B[1:3] + ['bio11-u2-l2-2-r3x3'] + MALE_B[3:] + ['bio11-u2-l2-2-mx1', 'bio11-u2-chk5', 'bio11-u2-wrk5'],
    L23: FEM_A + ['bio11-u2-c05', 'bio11-u2-c06', 'bio11-u2-c07'] + MENS + HORM + FERT + ['bio11-u2-xtra2'] + BIRTH +
         ['bio11-u2-chk6', 'bio11-u2-wrk6', 'bio11-u2-l2-3-mx1', 'bio11-u2-l2-3-r3r1'],
}
MOVE = {'bio11-u2-xtra2': L23}
RETITLE = {'bio11-u2-c07': 'Fertilisation to contraception — 30-second story'}
DIAGRAM_KEYS = ['mpath', 'sperm', 'fem', 'ovum', 'cycle']
