"""Unit 3 (Skeletal system), lesson 3.1: 3.1.3 Axial and appendicular skeletons. Textbook pp. 58-66."""
from common import *

set_unit('bio11-u3')
L31 = 'bio11-u3-l3-1'

AXIAL = [
    T('c04', '3.1.3 Axial and appendicular skeletons — the two halves of the body’s frame', 58,
      '**Step 1 — the big split.** The human skeleton (about **206 bones** in an adult) is divided into two parts: the **axial skeleton** (80 bones) and the **appendicular skeleton** (126 bones).',
      '**Step 2 — axial = the axis.** Picture a line down the middle of your body. The bones **on that central axis** form the axial skeleton: **skull, vertebral column (backbone) and thorax (sternum + ribs)**.',
      '**Step 3 — appendicular = the appendages.** Bones **hanging from** (appended to) that axis — the **limbs (arms and legs)** and the **girdles** that join them to the axis — form the appendicular skeleton.',
      '**Step 4 — the jobs differ.** Axial: mainly **protection** of vital organs (brain, spinal cord, heart, lungs) and a **central framework**. Appendicular: mainly **movement** and handling objects; the girdles give the limbs their wide range of movement.',
      '**Step 5 — where they meet.** The two parts join at the **shoulders** (pectoral girdle ↔ sternum) and the **hips** (pelvic girdle ↔ sacrum).'),
    ST('s313-s1', 'Counting to 206 — the bone tree', 59, 'bones', [
        ('**Axial skeleton = 80 bones:** skull 22, ear ossicles 6, hyoid 1, vertebral column 26, sternum 1, ribs 24.', 'ax'),
        ('**Appendicular skeleton = 126 bones:** pectoral girdle 4, arms 60, pelvic girdle 2, legs 60.', 'ap'),
    ], 'The textbook counts 8 cranial + 14 facial bones + 3 tiny bones in each ear. The **hyoid** (a U-shaped bone in the neck that holds the tongue) completes the 80.'),
    T('s313-t1', 'A. The axial skeleton — skull', 60,
      '**Cranium (8 bones):** a strong bony box that **protects the brain**. It has small holes (perforations) through which **blood vessels and nerves** pass to and from the brain.',
      '**Facial bones (14):** include the **upper jaw (maxilla)** and the **lower jaw (mandible)** — the only skull bone that moves (for chewing and speaking). The skull also protects the **olfactory organs (nose), the middle and inner ear and the eyes** (eye sockets).',
      '**Ear ossicles (3 in each ear):** malleus, incus, stapes — the smallest bones in the body; they pass sound vibrations to the inner ear.',
      '**Sutures and fontanels:** the skull bones are tightly fitted together by immovable joints (sutures). At birth many are not yet joined, leaving **“soft spots” (fontanels)** that let the skull squeeze slightly during birth and let the brain grow. They close by about **two years** of age.'),
    T('s313-t2', 'The vertebral column (backbone)', 61,
      '**Length and number:** about **70 cm** long in an adult. It is made of **33 vertebrae** in a child; in the adult the lower ones fuse, so there are **26 separate bones** (24 vertebrae + sacrum + coccyx).',
      '**Discs of cartilage** lie between the vertebrae. They **absorb shock, reduce friction** and let the column **bend** a little at each joint — together this gives a flexible backbone.',
      '**Three jobs:** (1) the **main support** from which the rest of the upper body branches; (2) **protects the spinal cord** (and spinal nerves) inside the vertebral canal; (3) gives **attachment** for ribs and back muscles.',
      '**Atlas and axis:** the first two cervical vertebrae are special. The **atlas (C1)** carries the skull and allows **nodding** (“yes”); the **axis (C2)** has a peg on which the atlas turns, allowing **rotation** (“no”).',
      '**Caudal vertebrae** vary between animals with the size of the tail. In humans the tail is **vestigial**, so the four caudal vertebrae fuse to form the **coccyx**.'),
    ST('s313-s2', 'The five regions of the vertebral column', 62, 'spine', [
        ('**Cervical — 7** (neck). Atlas and axis move the head.', 'c'),
        ('**Thoracic — 12** (chest). Each carries a pair of ribs.', 'th'),
        ('**Lumbar — 5** (lower back). Largest and strongest, carry most body weight.', 'lu'),
        ('**Sacral — 5 fused → sacrum.** Joins the pelvic girdle.', 's'),
        ('**Caudal (coccygeal) — 4 fused → coccyx.** Remnant of a tail.', 'co'),
    ]),
    TB('s313-tb1', 'Vertebral regions', 62, ['Region', 'Number', 'Where', 'Special feature'], [
        ['Cervical', '7', 'Neck', 'Atlas (nodding), axis (rotation)'],
        ['Thoracic', '12', 'Chest', 'Articulate with 12 pairs of ribs'],
        ['Lumbar', '5', 'Lower back', 'Largest bodies — weight bearing'],
        ['Sacral', '5 → 1 sacrum', 'Pelvis', 'Fused; joins the hip girdle'],
        ['Caudal', '4 → 1 coccyx', 'Tail end', 'Fused; vestigial tail'],
        ['**Total**', '33 (child) / 26 (adult)', '', ''],
    ]),
    MN('s313-m1', 'Memory hook — vertebrae per region: “breakfast at 7, lunch at 12, dinner at 5”', 62,
       'Cervical 7 → Thoracic 12 → Lumbar 5, then Sacral 5 and Caudal 4. Say “7-12-5-5-4” like a phone number.',
       [('C', 'Cervical', '7 (breakfast at 7)'), ('T', 'Thoracic', '12 (lunch at 12)'), ('L', 'Lumbar', '5 (dinner at 5)'), ('S', 'Sacral', '5 fused'), ('C', 'Coccyx', '4 fused')]),
    T('s313-t3', 'The thorax — sternum and ribs', 62,
      '**Sternum (breastbone):** a flat bone about **15 cm** long in the middle of the chest.',
      '**Ribs:** **12 pairs** (24 ribs). Every pair joins a thoracic vertebra at the back. Their main purpose is to **protect the heart and lungs**; their **cartilage** joints make the rib cage **flexible for breathing**.',
      '**True ribs — upper 7 pairs:** joined **directly** to the sternum by their own cartilage.',
      '**False ribs — next 3 pairs (8–10):** joined **indirectly** — their cartilage joins the cartilage of the rib above.',
      '**Floating ribs — last 2 pairs (11–12):** **not attached to the sternum at all**; they are fixed only to the vertebrae at the back. (The textbook’s wording “the sternum is connected to all ribs except the last pair” and “attached to the last pair of ribs” is loose — remember **7 true, 3 false, 2 floating**.)'),
    TB('s313-tb2', 'Three kinds of ribs', 63, ['Kind', 'Pairs', 'Link to sternum'], [
        ['True ribs', '1–7 (7 pairs)', 'Direct, by own cartilage'],
        ['False ribs', '8–10 (3 pairs)', 'Indirect, through cartilage of rib 7'],
        ['Floating ribs', '11–12 (2 pairs)', 'None — free at the front'],
    ]),
]

APPEND = [
    T('s313-t4', 'B. The appendicular skeleton — girdles', 63,
      '**What it is:** the bones of the **appendages (limbs)** and the **girdles** that attach them to the axial skeleton.',
      '**Pectoral (shoulder) girdle — 4 bones:** two **scapulae** (shoulder blades) and two **clavicles** (collar bones). It forms a **loose attachment** with the sternum, which lets the arms move very freely. The **scapula** rests on the back of the rib cage and gives a **broad flat surface** for arm muscles and a **socket** for the head of the humerus. The **clavicle** props the shoulder outwards and **stops it collapsing inward**.',
      '**Pelvic (hip) girdle — 2 hip bones:** each hip bone is several bones (ilium, ischium, pubis) **fused together**; with the sacrum they form a strong **ring**. Its functions: (1) **socket** for the femur, (2) surface for **muscle attachment**, (3) **protects** lower abdominal organs (bladder, reproductive organs), (4) **transmits body weight** from the backbone to the legs.',
      '**Why the difference?** The shoulder girdle is light and loose → **range of movement**. The hip girdle is heavy and fused → **strength and weight bearing**.'),
    TB('s313-tb3', 'Pectoral vs pelvic girdle', 63, ['Feature', 'Pectoral (shoulder) girdle', 'Pelvic (hip) girdle'], [
        ['Bones', '2 scapulae + 2 clavicles', '2 hip bones (each = 3 fused bones)'],
        ['Joined to axis', 'Loosely, at the sternum', 'Firmly, to the sacrum'],
        ['Socket for', 'Humerus (shallow socket)', 'Femur (deep socket)'],
        ['Main advantage', 'Wide range of arm movement', 'Strength; carries body weight'],
        ['Protects', '—', 'Lower abdominal organs'],
    ]),
    T('s313-t5', 'i. The upper appendages — arm and hand (30 bones each)', 64,
      '**Upper arm — humerus (1):** the single long bone from shoulder to elbow.',
      '**Forearm — radius and ulna (2):** the **ulna** forms the elbow joint with the humerus; the **radius** is on the **thumb side**. Two bones instead of one allow the forearm and wrist to **twist** (turn the palm up and down).',
      '**Wrist — carpals (8):** small bones in **two irregular rows** joined by **gliding joints**, giving the wrist flexibility.',
      '**Palm — metacarpals (5):** extend from the wrist; covered with skin they form the palm.',
      '**Fingers — phalanges (14):** the **thumb has 2**, each other finger **3** (2 + 4×3 = 14). Phalanges are **long bones** (long in shape, though small).',
      '**The opposable thumb:** the first metacarpal joins the wrist by a **saddle joint** while the others lie in one plane. So the thumb can swing across to touch each fingertip — letting humans **grasp objects, use tools and do skilful work**. This is one feature that makes the human skeleton unique.'),
    T('s313-t6', 'ii. The lower appendages — leg and foot (30 bones each)', 65,
      '**Thigh — femur (1):** the upper bone of the leg; the **longest, largest and strongest** bone of the body.',
      '**Knee cap — patella (1):** a thick bone in the tendon in front of the knee; it **covers and protects** the front of the knee joint.',
      '**Lower leg — tibia and fibula (2):** connect the femur to the ankle. The **tibia** (shin bone) is the thick, weight-bearing one; the **fibula** is thin, on the outer side.',
      '**Ankle — tarsals (7):** include the heel bone.',
      '**Sole — metatarsals (5).** **Toes — phalanges (14):** 2 in the big toe and 3 in each other toe — the same pattern as the hand, but **much shorter** and (in the first row) flattened sideways. (The textbook says toes are “composed of metatarsals” — the toes are phalanges; the metatarsals form the sole.)',
      '**Foot at a right angle to the leg:** gives a broad, stable base for **standing upright and walking on two legs**.'),
    TB('s313-tb4', 'Arm and leg are built on the same plan', 64, ['Part', 'Arm (upper limb)', 'Leg (lower limb)'], [
        ['Upper bone', 'Humerus (1)', 'Femur (1)'],
        ['Joint cap', '—', 'Patella (1)'],
        ['Lower pair', 'Radius + ulna (2)', 'Tibia + fibula (2)'],
        ['Small cluster', 'Carpals (8) — wrist', 'Tarsals (7) — ankle'],
        ['Middle bones', 'Metacarpals (5) — palm', 'Metatarsals (5) — sole'],
        ['Digits', 'Phalanges (14) — thumb 2, others 3', 'Phalanges (14) — big toe 2, others 3'],
        ['Total per limb', '30', '30'],
    ]),
    MN('s313-m2', 'Memory hook — limb bones in order: “1-2-many-5-14”', 64,
       'Every limb goes **1** long bone → **2** bones → a **cluster** of small bones → **5** long bones → **14** phalanges. The leg adds the patella.',
       [('1', 'One upper bone', 'humerus / femur'), ('2', 'Two lower bones', 'radius + ulna / tibia + fibula'), ('M', 'Many small', '8 carpals / 7 tarsals'), ('5', 'Five', 'metacarpals / metatarsals'), ('14', 'Fourteen', 'phalanges')]),
    RM('s313-r1', 'Traps examiners love (3.1.3)', 59,
       '**Girdles belong to the appendicular skeleton**, not the axial — even though they touch the axis.',
       '**Sternum and ribs are axial**, the clavicle and scapula are appendicular.',
       '**Radius = thumb side; ulna = little-finger side** (forms the elbow).',
       '**Thumb and big toe have 2 phalanges**; all other digits have 3.',
       '**33 vs 26:** 33 vertebrae before fusion; 26 separate bones in an adult.',
       '**Floating ribs** are free at the front — they are not joined to the sternum.'),
    WK('s313-w1', 'Exercise 3.1 Q1', 63, 'What is the appendicular skeleton? Why is it called appendicular?', [
        'Step 1: List the bones — limbs (arms, legs) and the girdles (pectoral, pelvic).',
        'Step 2: Explain the name — these bones are **appendages**, “hung onto” (appended to) the central axial skeleton.',
        'Step 3: Add the number — 126 bones.',
    ], 'The appendicular skeleton is the 126 bones of the limbs and their girdles; it is called appendicular because these bones are appendages attached to the axial skeleton.'),
    WK('s313-w2', 'Exercise 3.1 Q2', 66, 'What is the advantage of the foot forming a right angle to the leg?', [
        'Step 1: Humans stand and walk upright on two legs (bipedal).',
        'Step 2: A foot at right angles gives a **broad flat base**, so the body is **balanced** and its weight is spread over the sole.',
        'Step 3: The foot acts as a **lever** — the heel strikes and the toes push off — making walking and running efficient.',
    ], 'It provides a broad, stable base for upright posture and balance, spreads body weight, and acts as a lever for walking and running.'),
    WK('s313-w3', 'Exercise 3.1 Q3', 65, 'Why is the femur the longest, largest and strongest bone of the body?', [
        'Step 1: The femur carries the **whole weight of the upper body** passed down from the pelvis.',
        'Step 2: It must resist large forces in walking, running and jumping.',
        'Step 3: The most **powerful muscles** of the body (thigh and buttock) attach to it, so it needs a big surface.',
        'Step 4: Its length gives a long stride (long lever).',
    ], 'Because it bears the body’s weight transmitted from the pelvis, withstands the forces of walking and running, gives attachment to the strongest muscles and acts as a long lever.'),
    WK('s313-w4', 'Exercise 3.1 Q4', 57, 'What are the types of bones found in the human body, as classified by their shapes? Give examples.', [
        'Step 1: Long bones — longer than wide: femur, humerus, phalanges.',
        'Step 2: Short bones — cube-like: carpals, tarsals.',
        'Step 3: Flat bones — thin plates that protect or anchor muscles: cranial bones, sternum, ribs, scapula.',
        'Step 4: Irregular bones — complex shapes: vertebrae, some facial bones. (The patella is a small bone inside a tendon, often called sesamoid.)',
    ], 'Long, short, flat and irregular bones (e.g. femur; carpals; skull bones and ribs; vertebrae).'),
    WK('s313-w5', 'Count it — the arm', 64, 'Show that each upper limb has 30 bones and that both upper limbs plus the pectoral girdle make 64.', [
        'Step 1: Humerus 1 + radius 1 + ulna 1 = 3.',
        'Step 2: Carpals 8 + metacarpals 5 = 13 → running total 16.',
        'Step 3: Phalanges: thumb 2 + 4 fingers × 3 = 14 → 16 + 14 = **30**.',
        'Step 4: Two arms = 60; pectoral girdle = 2 clavicles + 2 scapulae = 4; 60 + 4 = **64**.',
    ], '30 per arm; 60 + 4 = 64.'),
    WK('s313-w6', 'Apply it — why two forearm bones?', 64, 'A student turns a door handle and a screwdriver. Which bones make this possible and how?', [
        'Step 1: Turning the hand palm-up/palm-down needs a twisting forearm.',
        'Step 2: The **radius** rotates around the **ulna**, which stays fixed at the elbow.',
        'Step 3: With a single bone this twisting would be impossible.',
    ], 'The radius rotating around the ulna allows twisting of the forearm and wrist.'),
    CK('s313-k1', 59, 'Which bone belongs to the axial skeleton?', ['Clavicle', 'Sternum', 'Scapula', 'Femur'], 'B',
       '**Step 1:** Axial = skull, vertebral column, sternum, ribs.\n\n**Step 2:** Clavicle and scapula are pectoral girdle (appendicular).\n\n**Answer: B.**'),
    CK('s313-k2', 62, 'How many thoracic vertebrae are there?', ['5', '7', '12', '4'], 'C',
       '**Step 1:** 7-12-5-5-4.\n\n**Step 2:** Thoracic = 12, one for each pair of ribs.\n\n**Answer: C.**'),
    CK('s313-k3', 63, 'Ribs 11 and 12 are called floating ribs because they', ['are made of cartilage only', 'are not attached to the sternum', 'move freely in the abdomen', 'have no vertebra'], 'B',
       '**Step 1:** They are joined to vertebrae at the back.\n\n**Step 2:** At the front they are free — no link to the sternum.\n\n**Answer: B.**'),
    CK('s313-k4', 65, 'The thumb can be opposed because its metacarpal joins the wrist by a', ['hinge joint', 'saddle joint', 'suture', 'gliding joint'], 'B',
       '**Step 1:** The other metacarpals lie in one plane.\n\n**Step 2:** The thumb’s saddle joint lets it swing across the palm.\n\n**Answer: B.**'),
    CK('s313-k5', 63, 'Which is a function of the pelvic girdle?', ['Protects the brain', 'Transmits body weight from the backbone to the legs', 'Allows nodding of the head', 'Produces the voice'], 'B',
       '**Step 1:** The pelvic girdle is a strong ring joined to the sacrum.\n\n**Step 2:** It passes the weight of the upper body to the femurs.\n\n**Answer: B.**'),
]

LESSONS = {L31: ['bio11-u3-c01', 'bio11-u3-c02', 'bio11-u3-c03'] + AXIAL + APPEND +
           ['bio11-u3-tbl1', 'bio11-u3-wrk1', 'bio11-u3-wrk2', 'bio11-u3-chk1', 'bio11-u3-chk2', 'bio11-u3-l3-1-mx1']}
DIAGRAM_KEYS = ['bones', 'spine']
