"""Unit 6 (Plant systems): 6.1.3 plant growth hormones, 6.3.2 root growth regions, 6.4 the shoot (6.4.1 stem, 6.4.2 leaf, 6.4.3 flower).
Textbook: Biology for Grade 11 (Eritrea), pp. 109-131."""
from common import *

set_unit('bio11-u6')
L61, L63, L64 = 'bio11-u6-l6-1', 'bio11-u6-l6-3', 'bio11-u6-l6-4'

# =================================================================== 6.1.3 plant hormones
HORM = [
    T('c04', '6.1.3 Plant growth hormones — chemical messengers of plants', 109,
      '**Step 1 — what they are.** Plant hormones are **chemical substances** that affect a plant’s ability to **respond to its environment**. They are usually **made in one part** of the plant and **transported to another** where they act — just like animal hormones, but plants have no glands; growing tips, young leaves, seeds and fruits make them.',
      '**Step 2 — why “growth regulators”.** They can **stimulate or inhibit** growth, so they are also called **plant growth regulators**.',
      '**Step 3 — they act on targets.** They interact with specific **target tissues** to cause responses such as **growth, flowering, fruit ripening, leaf fall or dormancy**.',
      '**Step 4 — teamwork.** Each response is often the result of **two or more hormones acting together** — sometimes helping each other, sometimes opposing (antagonism).',
      '**Step 5 — the five groups:** **auxins, gibberellins, cytokinins, ethylene and abscisic acid (ABA).** The first three mostly **promote** growth; ABA mostly **inhibits**; ethylene **ripens** fruit and speeds leaf fall.'),
    TB('s613-tb1', 'The five plant hormones at a glance', 109, ['Hormone', 'Made mainly in', 'Main effects', 'Farm / garden use'], [
        ['Auxin (IAA)', 'Shoot tips (apical meristem), developing fruits', 'Cell elongation; phototropism and geotropism; apical dominance; root initiation; fruit development; delays abscission', 'NAA roots cuttings; more tomato fruits; 2,4-D weed killer'],
        ['Gibberellins (GA)', 'Young leaves, seeds', 'Stem elongation (taller plants); seed germination; lateral buds; fruit development; inhibit root initiation', 'Bigger, more spaced grapes'],
        ['Cytokinins', 'Root tips, seeds', 'Cell division; lateral buds; germination; cell elongation', 'Plant tissue culture (with auxin)'],
        ['Abscisic acid (ABA)', 'Leaves, seeds', 'Inhibits other hormones (e.g. IAA); bud dormancy; keeps seeds dormant; (closes stomata in drought)', '—'],
        ['Ethylene (a gas)', 'Ripening fruits, ageing tissues', 'Fruit ripening; with ABA speeds abscission of leaves and fruits', 'Ripening stored fruit'],
    ]),
    T('s613-t1', 'Auxins — the elongation and bending hormone', 109,
      '**The natural auxin** is **indoleacetic acid (IAA)**, produced in the **apical meristem of the shoot**, in actively growing shoot tips and in developing fruits.',
      '**Main job — cell elongation.** IAA makes cells just behind the tip **stretch**, so the shoot grows longer.',
      '**Phototropism (bending to light):** when light comes from one side, auxin collects on the **shaded side**; cells there elongate **more**, so the shoot **curves towards the light**.',
      '**Geotropism:** auxin also redistributes under gravity, helping shoots grow up and roots grow down.',
      '**Apical dominance:** auxin from the terminal bud **inhibits the lateral (side) buds**, so an intact plant grows tall with few branches. Remove the tip and the side buds grow — the plant becomes **bushy**.',
      '**Other effects:** inhibits **abscission** (leaf/fruit fall), promotes **fruit development**, stimulates **root initiation**, and helps **cell division** and growth.'),
    ST('s613-s1', 'Phototropism step by step', 110, 'photo', [
        ('**The tip makes auxin**, which moves down the shoot.', 'a'),
        ('**Light from one side** → auxin moves to the **shaded side**.', 'b'),
        ('**Shaded-side cells elongate more** → the shoot bends towards the light.', 'c'),
    ]),
    ST('s613-s2', 'Apical dominance — why pruning makes a plant bushy', 110, 'apical', [
        ('**Intact plant:** auxin from the terminal bud flows down and holds back the lateral buds → tall, few branches.', 'a'),
        ('**Tip removed (pruned):** no auxin from the top → lateral buds grow → bushy plant. Gardeners “pinch out” tips of hedges, tea and tomato plants for this reason.', 'b'),
    ]),
    T('s613-t2', 'Synthetic auxins — chemistry on the farm', 110,
      '**What:** cheap compounds made by chemists with structures **similar to IAA**.',
      '**NAA (naphthalene acetic acid):** used to **promote root formation** in stem and leaf cuttings (rooting powder) — useful for propagating roses, coffee, grapevines.',
      '**Fruit set:** gardeners spray auxins on **tomato** plants to **increase the number of fruits** on each plant.',
      '**2,4-D — a selective herbicide (weed killer):** it **kills dicots** (broad-leaved weeds such as dandelion and pigweed) **without injuring monocots** (lawn grasses and cereals such as wheat, barley, maize, sorghum and teff). The dicot weeds grow so fast and abnormally that they die.'),
    T('s613-t3', 'Gibberellins — the “grow taller” hormone', 110,
      '**Main effect:** **stimulate the elongation of stems.** Spraying a plant with gibberellins usually makes it grow **taller than normal**. (Dwarf varieties often make little gibberellin.)',
      '**Other effects:** stimulate **lateral buds**, **seed germination** (they switch on enzymes that digest the seed’s food store), **fruit development**, cell division and elongation; they **inhibit root initiation** (the opposite of auxin).',
      '**Use:** sprayed on **grapes** to **increase fruit size** and the **distance between fruits** (less crowding, less rot).'),
    T('s613-t4', 'Cytokinins — the cell-division hormone', 110,
      '**Main effect:** **promote cell division** (cyto = cell, kinesis = division).',
      '**Other effects:** stimulate **lateral buds**, **seed germination** and **cell elongation**; (they also delay ageing of leaves — extra).',
      '**Tissue culture:** cytokinins are very important when plant tissue is grown in the laboratory. The **ratio of auxin to cytokinin** in the medium decides what the tissue makes.'),
    TB('s613-tb2', 'Tissue culture — the auxin : cytokinin ratio', 110, ['Ratio in the medium', 'What forms'], [
        ['High auxin : low cytokinin', '**Roots**'],
        ['Low auxin : high cytokinin', '**Shoots**'],
        ['About equal (extra)', 'Undifferentiated mass of cells (callus)'],
    ]),
    T('s613-t5', 'Abscisic acid (ABA) and ethylene — the “stop” and “ripen” hormones', 110,
      '**ABA generally inhibits other hormones**, such as the auxin IAA. It was first thought to cause **abscission** (leaf fall) — hence its name — but botanists now know that **ethylene is the main abscission hormone**.',
      '**ABA and dormancy:** ABA brings about **dormancy in buds** (e.g. before a dry season) and **maintains dormancy in seeds**, so they do not germinate at the wrong time. (In drought it also closes stomata to save water.)',
      '**Ethylene** is responsible for **fruit ripening** — softening, sweetening (starch → sugar) and colour change. With ABA it speeds the **abscission** of leaves and fruits.',
      '**The odd one out:** unlike the other four, **ethylene is a gas** at room temperature, so it spreads through the air from one fruit to another — “one ripe fruit ripens the basket”.'),
    TB('s613-tb3', 'Who promotes and who opposes?', 110, ['Process', 'Promoted by', 'Inhibited / opposed by'], [
        ['Stem (cell) elongation', 'Auxin, gibberellin, cytokinin', 'ABA'],
        ['Cell division', 'Cytokinin (also auxin, gibberellin)', 'ABA'],
        ['Lateral bud growth', 'Cytokinin, gibberellin', 'Auxin (apical dominance)'],
        ['Root initiation', 'Auxin', 'Gibberellin'],
        ['Seed germination', 'Gibberellin, cytokinin', 'ABA (dormancy)'],
        ['Fruit development', 'Auxin, gibberellin', '—'],
        ['Fruit ripening', 'Ethylene', '—'],
        ['Abscission (leaf/fruit fall)', 'Ethylene, ABA', 'Auxin'],
    ]),
    MN('s613-m1', 'Memory hook — one verb per hormone: “All Good Cooks Ask Eggs”', 109,
       'Read the first letters in textbook order: Auxin, Gibberellin, Cytokinin, ABA, Ethylene.',
       [('A', 'Auxin', 'Aims the shoot at light (elongation, bending)'), ('G', 'Gibberellin', 'Grows tall (stem elongation)'), ('C', 'Cytokinin', 'Cuts cells in two (division)'),
        ('A', 'Abscisic acid', 'Asleep (dormancy, inhibits)'), ('E', 'Ethylene', 'Eat-ready fruit (ripening) — a gas')]),
    RM('s613-r1', 'Traps examiners love (6.1.3)', 110,
       '**Abscisic acid is NOT the main abscission hormone** — ethylene is. ABA = dormancy/inhibition.',
       '**Ethylene is the only gas.**',
       '**Auxin inhibits lateral buds; cytokinin stimulates them.**',
       '**Root initiation:** auxin promotes, gibberellin inhibits.',
       '**Tissue culture:** high auxin → roots; low auxin (high cytokinin) → shoots.',
       '**2,4-D kills dicots** (broad leaves), not monocots (grasses, cereals).'),
    WK('s613-w1', 'Activity 6.3 — guavas and a ripe banana', 109, 'Unripe guavas were sealed in bags alone (bags 1–4) or with a ripe banana (bags 5–8). After 2–3 days the cut guavas were tested with iodine. Describe the expected observations and explain them.', [
        'Step 1: Identify the variable — the only difference is the **ripe banana**; bags 1–4 are the control.',
        'Step 2: Observation — guavas with a banana turn **yellow, soften and smell sweet sooner**; control guavas stay greener and harder.',
        'Step 3: Iodine test — control guavas stain **blue-black strongly** (much starch); test guavas stain **less** (starch has changed to sugar).',
        'Step 4: Explanation — the ripe banana gives off **ethylene gas**; in a sealed bag it builds up and **speeds ripening** of the guava, which converts starch to sugars.',
        'Step 5: Conclusion — ethylene is a gaseous hormone that ripens fruit; this is why one ripe fruit can ripen others nearby.',
    ], 'Guavas with a banana ripen faster and show less starch (weaker blue-black) because the banana releases ethylene gas, which promotes ripening.'),
    WK('s613-w2', 'Apply it — weeds in a wheat field', 110, 'A farmer near Mendefera sprays 2,4-D on a wheat field full of broad-leaved weeds. Predict and explain the result.', [
        'Step 1: Wheat is a **monocot**; broad-leaved weeds are **dicots**.',
        'Step 2: 2,4-D is a synthetic auxin that is **selective** — it kills dicots but not monocots.',
        'Step 3: The weeds grow abnormally and die; the wheat is unharmed and gets more water, light and minerals.',
    ], 'The broad-leaved (dicot) weeds die while the wheat (monocot) survives, so the crop yield increases.'),
    WK('s613-w3', 'Apply it — making a bushy hedge', 110, 'A gardener wants a thick, bushy hedge. What should she do, and which hormone explains it?', [
        'Step 1: The terminal bud makes **auxin**, which suppresses lateral buds (apical dominance).',
        'Step 2: Cutting off the shoot tips removes this auxin source.',
        'Step 3: Lateral buds now grow into side branches → bushy hedge.',
    ], 'Trim (pinch out) the shoot tips regularly; removing the auxin source ends apical dominance so side branches grow.'),
    WK('s613-w4', 'Apply it — tissue culture', 110, 'In a tissue-culture lab, a piece of potato tissue produced many roots but no shoots. How should the medium be changed to get shoots?', [
        'Step 1: Many roots → the medium has a **high auxin : cytokinin ratio**.',
        'Step 2: Shoots need a **low** ratio.',
        'Step 3: So reduce auxin and/or add more cytokinin.',
    ], 'Lower the auxin-to-cytokinin ratio (more cytokinin, less auxin).'),
    CK('s613-k1', 110, 'Which plant hormone is a gas?', ['Auxin', 'Gibberellin', 'Ethylene', 'Cytokinin'], 'C',
       '**Step 1:** Four plant hormones are dissolved chemicals.\n\n**Step 2:** Ethylene is a gas at room temperature.\n\n**Answer: C.**'),
    CK('s613-k2', 110, 'Spraying grapes to make the fruits bigger and further apart uses', ['ABA', 'gibberellins', 'ethylene', '2,4-D'], 'B',
       '**Step 1:** Gibberellins stimulate elongation and fruit development.\n\n**Step 2:** They are sprayed on grapes for size and spacing.\n\n**Answer: B.**'),
    CK('s613-k3', 110, 'A seed that will not germinate even in good conditions probably contains a lot of', ['gibberellin', 'cytokinin', 'abscisic acid', 'auxin'], 'C',
       '**Step 1:** Germination is blocked = dormancy.\n\n**Step 2:** ABA maintains seed dormancy.\n\n**Answer: C.**'),
]

# =================================================================== 6.3.2 root growth regions
ROOT = [
    T('c10', '6.3.2 Root growth regions — four zones behind the root tip', 118,
      '**Step 1 — the big picture.** A young root grows in length only at its **tip**. A long section of the tip shows **four regions** (from the tip upwards): **root cap → region of cell division → region of elongation → region of maturation**.',
      '**Step 2 — not walls, but a gradient.** The regions are **not strictly separate**: cells made in one region gradually develop into those of the next as the tip moves on.',
      '**Step 3 — follow one cell.** A cell is made by division just behind the cap, then **stretches** in the elongation zone, then **specialises** (e.g. into a root-hair cell or a xylem vessel) in the maturation zone. So reading the zones from tip to top is like watching a cell’s life story.'),
    ST('s632-s1', 'The root tip, region by region', 118, 'root', [
        ('**Root cap** — cup of parenchyma cells protecting the delicate tip; outer cells are worn away by soil.', 'cap'),
        ('**Region of cell division** — meristem; small cube-shaped cells with large nuclei, few tiny vacuoles; makes all root tissues and new cap cells.', 'div'),
        ('**Region of elongation** — cells take in lots of water and grow long; small vacuoles merge into one or two large ones (up to 90 % of the cell).', 'elo'),
        ('**Region of maturation (differentiation, root-hair zone)** — cells become permanent tissues; root hairs absorb most water and minerals.', 'mat'),
    ]),
    T('s632-t1', 'Root cap and region of cell division', 118,
      '**Root cap:** made of **parenchyma** cells forming an **inverted cup** over the tip of each root. Its outer part is **rough and uneven** because cells are constantly **worn away** as the root pushes through the soil. **Main function: protect the delicate root tip** (the meristem). (Extra: its cells make slimy mucilage that eases the way and they sense gravity.)',
      '**Where new cap cells come from:** the textbook says the cap “arises from cells in the region of elongation”, but in the next paragraph it states correctly that the **growing point (region of cell division) gives rise to new root cap cells**. Use the second statement in exams: **the meristem replaces the worn cap cells**.',
      '**Region of cell division:** the zone **next to the root cap**, made of **actively dividing meristematic cells** from which **all other root tissues** are formed. Cells are **cube-shaped**, with **fairly large nuclei** and **few, if any, small vacuoles** — typical of cells that spend their energy dividing.'),
    T('s632-t2', 'Region of elongation and region of maturation', 118,
      '**Region of elongation:** immediately behind the growing point. Cells become **longer and somewhat wider**, remain **undifferentiated**, and grow rapidly by **taking in large quantities of water**. The tiny vacuoles **merge into one or two large vacuoles** that may fill **90 % or more** of the cell. This zone **pushes the tip forward** through the soil.',
      '**Why growth stops above it:** only the **root cap and apical meristem actually move** through the soil, so there is **no further increase in length above the region of elongation** — older parts are anchored.',
      '**Region of maturation** (also **region of differentiation** or **root-hair zone**): cells **mature and differentiate** into the **permanent tissues** — epidermis, cortex, endodermis, pericycle, xylem, phloem.',
      '**Root hairs:** each is a **slender lateral projection of a single epidermal cell**. The **cuticle is very thin** here. Any epidermal cell can absorb, but root hairs give a **much larger surface**, so **most water and minerals enter through root hairs**. They are **short-lived**: they wither as the root grows and new ones form nearer the tip.'),
    TB('s632-tb1', 'Four regions compared', 118, ['Region', 'Cell features', 'Main job'], [
        ['Root cap', 'Parenchyma cup; outer cells worn, rough', 'Protects the tip'],
        ['Cell division (meristem)', 'Small, cube-shaped, large nucleus, few tiny vacuoles', 'Makes new cells for root and cap'],
        ['Elongation', 'Long cells, 1–2 large vacuoles (≈90 %), undifferentiated', 'Increase in length; pushes tip on'],
        ['Maturation (root-hair zone)', 'Differentiated tissues; root hairs; thin cuticle', 'Absorption; forms permanent tissues'],
    ]),
    MN('s632-m1', 'Memory hook — tip to top: “Can Dogs Eat Meat?”', 118,
       'Start at the very tip and move up the root.',
       [('C', 'Cap', 'protects'), ('D', 'Division', 'makes cells'), ('E', 'Elongation', 'stretches cells'), ('M', 'Maturation', 'specialises; root hairs')]),
    WK('s632-w1', 'Experiment — where does a root grow?', 118, 'A germinating bean root is marked with ink lines 1 mm apart, starting at the tip. After 24 hours the spacing is measured. Predict and explain the result.', [
        'Step 1: Lines on the cap stay close; the cap only moves forward.',
        'Step 2: Lines about 2–5 mm behind the tip become **widely spaced** — this is the **region of elongation**, where cells stretch.',
        'Step 3: Lines further back (maturation zone) stay **1 mm apart** — no more growth there.',
        'Step 4: Conclusion: growth in length happens in a short zone just behind the tip.',
    ], 'Marks just behind the tip (elongation zone) spread apart most; marks further back do not move apart, showing growth happens only near the tip.'),
    WK('s632-w2', 'Exercise 6.3 Q1, Q2 and Q4', 118, '(1) What are the regions of root development? (2) What is the function of the root cap? (4) Describe the region of cell maturation.', [
        'Step 1 (Q1): Root cap, region of cell division, region of elongation, region of maturation.',
        'Step 2 (Q2): The root cap protects the delicate root tip (meristem) as it pushes through the soil; its worn cells are replaced from the meristem.',
        'Step 3 (Q4): In the maturation (root-hair) zone cells differentiate into permanent tissues; epidermal cells grow root hairs with a thin cuticle that absorb most water and minerals; the hairs are short-lived.',
    ], '(1) Root cap, region of cell division, region of elongation, region of maturation. (2) It protects the delicate root tip as the root pushes through the soil. (4) Cells differentiate into permanent tissues; epidermal cells form short-lived root hairs with a thin cuticle that absorb most water and minerals.'),
    WK('s632-w3', 'Apply it — transplanting seedlings', 119, 'Why should seedlings be transplanted with a ball of soil round their roots?', [
        'Step 1: Most water is absorbed by delicate **root hairs** near the tip.',
        'Step 2: Pulling a seedling out bare tears off the root hairs.',
        'Step 3: With few root hairs the plant cannot absorb enough water and wilts; keeping soil round the roots protects them.',
    ], 'To avoid damaging the root hairs, which absorb most of the water and minerals.'),
    RM('s632-r1', 'Traps examiners love (6.3.2)', 118,
       '**Growth in length = elongation zone**, not the division zone (division makes cells; elongation makes the root longer).',
       '**Root hairs are in the maturation zone**, not at the very tip.',
       '**A root hair is one cell**, not many.',
       '**Vacuoles:** tiny in the division zone, huge in the elongation zone.'),
    CK('s632-k1', 118, 'Cells with large nuclei and almost no vacuoles are found in the', ['root cap', 'region of cell division', 'region of elongation', 'root-hair zone'], 'B',
       '**Step 1:** Large nucleus + no vacuole = dividing cell.\n\n**Step 2:** That is the meristem (region of cell division).\n\n**Answer: B.**'),
    CK('s632-k2', 119, 'A root hair is', ['a group of cortex cells', 'a projection of a single epidermal cell', 'part of the root cap', 'a tiny lateral root'], 'B',
       '**Step 1:** Root hairs grow from epidermal cells.\n\n**Step 2:** Each hair is an outgrowth of one cell.\n\n**Answer: B.**'),
]
CHK6 = CK('chk6', 118, 'In which root tip region do cells undergo rapid increase in length by absorbing large quantities of water?', ['Root Cap', 'Zone of cell division', 'Zone of elongation', 'Zone of maturation'], 'C',
          '**Step 1:** “Increase in length by absorbing water” describes cells that stretch.\n\n**Step 2:** Cap = protection; division = making cells; maturation = specialising.\n\n**Step 3:** Stretching happens in the zone of elongation, where small vacuoles merge into large ones.\n\n**Answer: C.**')
WRK6 = WK('wrk6', 'Step-by-step', 118, 'In which root tip region do cells undergo rapid increase in length by absorbing large quantities of water?', [
    'Step 1: Recall the four regions from the tip: cap, division, elongation, maturation.',
    'Step 2: Match each to its job — protect, divide, stretch, specialise.',
    'Step 3: “Increase in length by taking in water” = stretch → elongation.',
    'Step 4: Check: vacuoles grow to 90 % of the cell in this zone.',
], 'Zone of elongation')

# =================================================================== 6.4 the shoot
STEM = [
    T('s64-t0', '6.4 The shoot — stem, leaves and flowers', 122,
      '**The shoot system** is everything above the ground: **stems, leaves and flowers**. The stem is the frame and pipeline, the leaves are the food factories, and the flowers are the reproductive organs.',
      '**Order of this lesson:** 6.4.1 stem → 6.4.2 leaf → 6.4.3 flower, each with external structure, internal structure and functions.'),
    T('c12', '6.4.1 The stem — functions and external structure', 122,
      '**Four functions of the stem:** (i) it **bears the leaves**; (ii) holds them where they get **plenty of light**; (iii) **conducts** water and minerals up to the leaves and manufactured food from the leaves to other parts; (iv) in some plants it **stores food** (e.g. potato tuber, sugar cane).',
      '**What a stem is:** an **axis** with leaves attached and a **growing point at the tip**. The tip is protected by overlapping young leaves forming the **terminal bud**.',
      '**Leaf arrangement:** **alternate** (one leaf per node, on alternate sides), **opposite** (two per node, facing each other) or **whorled** (three or more per node).',
      '**Nodes and internodes:** a **node** is where a leaf attaches; the stretch between two nodes is the **internode**.',
      '**Axil and axillary bud:** the angle between a leaf and the stem is the **axil**; the bud in it is the **axillary bud** (the textbook calls the angle itself the axillary bud). Axillary buds grow into **new branches or flowers**.'),
    TB('s641-tb1', 'External features of a stem', 122, ['Feature', 'Meaning', 'Why it matters'], [
        ['Terminal bud', 'Growing tip covered by young leaves', 'Growth in length; makes auxin'],
        ['Node', 'Point where a leaf joins', 'Distinguishes a stem from a root'],
        ['Internode', 'Stem between two nodes', 'Spaces leaves so they do not shade each other'],
        ['Axil / axillary bud', 'Angle above a leaf / bud in it', 'Becomes a branch or flower'],
        ['Leaf arrangement', 'Alternate, opposite, whorled', 'Used to identify plants'],
    ]),
    T('s641-t1', 'Internal structure of a young dicot stem (sunflower)', 123,
      'A thin transverse section seen under the microscope shows **four regions, from outside to centre**:',
      '**a. Epidermis** — **one cell thick**; outer walls thickened with **cutin**, forming a waterproof **cuticle** that stops water loss and keeps out gases and germs.',
      '**b. Cortex** — just inside the epidermis, outside the conducting tissue; **parenchyma** cells with **large intercellular spaces** (for gas exchange and storage).',
      '**c. Vascular bundles** — arranged in a **ring**. Each has **phloem** on the outside (carries **manufactured food** from leaves to other parts) and **xylem** on the inside (carries **water and minerals** from roots to leaves). Between them, **cambium** cells divide constantly to make **new phloem and xylem**, so the stem can grow thicker.',
      '**d. Pith** — the **centre**; the **most extensive tissue**, of **parenchyma** with the **largest cells** in the section; stores food and water.'),
    ST('s641-s1', 'Dicot vs monocot stem sections', 123, 'stems', [
        ('**Dicot (sunflower):** bundles in a **ring**, cambium between xylem and phloem, cortex outside the ring, large pith in the centre.', 'd'),
        ('**Monocot (maize):** bundles **scattered** throughout, **no cambium**, **no distinct pith**, very little cortex.', 'm'),
    ]),
    TB('s641-tb2', 'Dicot and monocot stems compared', 124, ['Feature', 'Dicot stem (sunflower)', 'Monocot stem (maize)'], [
        ['Vascular bundles', 'In a ring', 'Scattered throughout'],
        ['Cambium', 'Present', 'Absent'],
        ['Pith', 'Large, central', 'No distinct pith'],
        ['Cortex', 'Clear zone', 'Very little'],
        ['Growth in thickness', 'Possible (cambium)', 'Little or none'],
    ]),
    MN('s641-m1', 'Memory hook — outside to centre: “Every Cat Visits Paris”', 123,
       'Exercise 6.4 Q1 asks exactly this order.',
       [('E', 'Epidermis', 'cuticle, one cell thick'), ('C', 'Cortex', 'parenchyma, air spaces'), ('V', 'Vascular bundles', 'phloem–cambium–xylem, in a ring'), ('P', 'Pith', 'largest cells, centre')]),
    WK('s641-w1', 'Exercise 6.4 Q1', 123, 'List the pattern of tissues in a young dicot stem from the outside to the centre.', [
        'Step 1: Outermost — epidermis (with cuticle).',
        'Step 2: Then cortex (parenchyma).',
        'Step 3: Then the ring of vascular bundles — phloem, cambium, xylem (outside → inside).',
        'Step 4: Centre — pith.',
    ], 'Epidermis → cortex → vascular bundles (phloem, cambium, xylem) → pith.'),
    WK('s641-w2', 'Apply it — ring-barking a tree', 123, 'Goats strip a complete ring of bark from a young tree. The leaves stay green for weeks, but the tree later dies. Explain.', [
        'Step 1: Bark includes the **phloem**, which lies outside the xylem.',
        'Step 2: The xylem (inside) is untouched, so water still reaches the leaves — they stay green.',
        'Step 3: Food made in the leaves cannot pass the ring through phloem to the roots.',
        'Step 4: The roots starve, stop absorbing, and the whole tree dies.',
    ], 'Removing the ring removes the phloem: water still rises in the xylem, but food can no longer reach the roots, which die, and then the tree dies.'),
    WK('s641-w3', 'Activity 6.8 — identify the slide', 124, 'A slide of a stem section shows vascular bundles scattered all over, with no central pith. Is it a dicot or a monocot? Give two reasons.', [
        'Step 1: Scattered bundles → monocot.',
        'Step 2: No pith → monocot.',
        'Step 3: Check for cambium — absent in monocots.',
    ], 'Monocot — scattered bundles, no pith (and no cambium).'),
    CK('s641-k1', 123, 'Which tissue carries manufactured food from the leaves to other parts?', ['Xylem', 'Phloem', 'Cambium', 'Pith'], 'B',
       '**Step 1:** Xylem = water and minerals up.\n\n**Step 2:** Phloem = food from leaves.\n\n**Answer: B.**'),
    CK('s641-k2', 122, 'The part of a stem between two nodes is the', ['axil', 'internode', 'terminal bud', 'petiole'], 'B',
       '**Step 1:** Node = where a leaf joins.\n\n**Step 2:** Between two nodes = internode.\n\n**Answer: B.**'),
]

LEAF = [
    T('c13', '6.4.2 The leaf — the food factory: external structure', 125,
      '**Job:** the leaf is the **site of food production**. Here the plant takes in **light energy** and **carbon dioxide** for photosynthesis and **releases oxygen**.',
      '**Monocot vs dicot leaves:** monocots typically have **simple leaves with parallel venation**; dicots have **branching (net) venation** and many shapes.',
      '**Three parts of a typical dicot leaf:**',
      '**① Blade (lamina)** — the flat, extended part. Its edge is the **margin**: **toothed** in sunflower, **smooth** in bean. **Veins** run through it carrying water and nutrients.',
      '**② Petiole** — the short stalk attaching the leaf to the stem; it continues into the centre of the lamina as the **midrib**.',
      '**③ Leaf base** — the point of attachment. Some leaves have **stipules** (small scale-like or leaf-like outgrowths) at the base; in most monocots the base widens into a **sheath** around the stem.'),
    TB('s642-tb1', 'Monocot and dicot leaves', 125, ['Feature', 'Monocot (maize, grass)', 'Dicot (bean, sunflower)'], [
        ['Venation', 'Parallel', 'Branching (net)'],
        ['Petiole', 'Usually absent', 'Usually present'],
        ['Leaf base', 'Sheath round the stem', 'Small; may have stipules'],
        ['Shape', 'Usually long and narrow', 'Many shapes'],
    ]),
    T('s642-t1', 'Internal structure of the leaf — layer by layer', 126,
      '**Upper epidermis:** a **single layer** of closely fitting, comparatively large, water-filled cells, covered by a **thick waxy cuticle** that reduces water loss. Cells are **transparent**, so light passes through.',
      '**Palisade layer (upper mesophyll):** **2–3 layers** of **long, cylindrical** cells packed with **many chloroplasts** — the main photosynthetic tissue, placed where light is strongest.',
      '**Spongy layer (lower mesophyll):** **loosely packed** cells in a network with **many air spaces**; they also contain chloroplasts. The air spaces let gases diffuse through the leaf.',
      '**Veins (vascular bundles):** continuous with those of the stem — **xylem** brings water and minerals; **phloem** takes food away. They also support the blade.',
      '**Lower epidermis:** a single layer of **small cells** with **very numerous stomata** between them. Each stoma is a pore between two guard cells. (In some plants stomata occur on both surfaces; in others only on the lower surface.)',
      '**Stomata** control **water loss** and allow **free diffusion of CO₂ and O₂**.'),
    ST('s642-s1', 'Leaf transverse section — top to bottom', 126, 'leaf', [
        ('**Cuticle** — waxy, waterproof layer.', 'cu'),
        ('**Upper epidermis** — one layer, clear, no gaps.', 'ue'),
        ('**Palisade mesophyll** — tall cells crammed with chloroplasts.', 'pa'),
        ('**Spongy mesophyll** — loose cells, big air spaces.', 'sp'),
        ('**Vein** — xylem (water in) and phloem (food out).', 'vb'),
        ('**Lower epidermis with stomata** — gas exchange.', 'le'),
    ]),
    TB('s642-tb2', 'Leaf layers and their jobs (Exercise 6.4 Q2)', 126, ['Layer', 'Structure', 'Function'], [
        ['Cuticle', 'Waxy, non-cellular', 'Reduces water loss; protection'],
        ['Upper epidermis', 'One layer, transparent, tightly fitted', 'Protects; lets light through'],
        ['Palisade mesophyll', '2–3 rows of long cells, many chloroplasts', 'Main site of photosynthesis'],
        ['Spongy mesophyll', 'Loose cells, air spaces, some chloroplasts', 'Gas diffusion; some photosynthesis'],
        ['Vein', 'Xylem + phloem', 'Brings water; removes food; support'],
        ['Lower epidermis', 'Small cells, many stomata (guard cells)', 'Gas exchange; controls water loss'],
    ]),
    T('s642-t2', 'Gas exchange through the stomata — step by step (Activity 6.9)', 127,
      '**Step 1:** In light, photosynthesis uses CO₂, so CO₂ concentration inside the leaf falls.',
      '**Step 2:** CO₂ **diffuses in** through the open **stomata** (mostly on the lower surface) into the **air spaces** of the spongy layer.',
      '**Step 3:** It moves through the air channels to the **palisade cells**, passes through the **wet cell walls** and **dissolves** in the cell sap, reaching the chloroplasts.',
      '**Step 4:** **Oxygen** made by photosynthesis diffuses the opposite way and out through the stomata.',
      '**Step 5:** Water vapour also escapes through open stomata (**transpiration**). Stomata **close at night** or in drought, saving water but stopping CO₂ entry.'),
    T('s642-t3', 'From glucose to starch', 127,
      '**Photosynthesis:** in sunlight, **water and carbon dioxide react inside the chloroplast** to form **glucose** (and oxygen). The flat, expanded leaf gives a **large surface area** — the best shape for absorbing light.',
      '**Storage:** glucose is **removed from the cell sap quickly** and turned into **insoluble starch**, stored as small solid **starch grains** in the chloroplasts. Insoluble starch does not upset the water balance (osmosis) of the cell.',
      '**Note on “leucoplasts”:** the textbook says starch is deposited “in the form of leucoplasts”. Leucoplasts are actually **colourless plastids that store starch in non-green parts** (e.g. potato tubers, roots); in the leaf itself, starch grains lie **inside the chloroplasts**.'),
    TB('s642-tb3', 'How the leaf is adapted for photosynthesis', 127, ['Feature', 'How it helps'], [
        ['Broad, flat blade', 'Large surface to absorb light and CO₂'],
        ['Thin', 'Short diffusion distance for gases'],
        ['Transparent upper epidermis', 'Light reaches the palisade'],
        ['Palisade near the top, many chloroplasts', 'Most chlorophyll where light is strongest'],
        ['Air spaces in spongy layer', 'CO₂ reaches every cell'],
        ['Stomata', 'Gas exchange; controlled water loss'],
        ['Network of veins', 'Water in, food out; supports the blade'],
    ]),
    MN('s642-m1', 'Memory hook — top to bottom: “Clever Unicorns Prefer Sweet Vanilla Lollipops”', 126,
       'Cuticle, Upper epidermis, Palisade, Spongy, Vein, Lower epidermis.',
       [('C', 'Cuticle', 'wax'), ('U', 'Upper epidermis', 'clear'), ('P', 'Palisade', 'chloroplasts'), ('S', 'Spongy', 'air spaces'), ('V', 'Vein', 'xylem + phloem'), ('L', 'Lower epidermis', 'stomata')]),
    WK('s642-w1', 'Exercise 6.4 Q2', 126, 'Name the different tissue layers of a leaf.', [
        'Step 1: Start at the top — cuticle on the upper epidermis.',
        'Step 2: Mesophyll — palisade layer then spongy layer, with veins (vascular bundles) running through.',
        'Step 3: Bottom — lower epidermis with stomata.',
    ], 'Upper epidermis (with cuticle), palisade mesophyll, spongy mesophyll (with vascular bundles/veins), lower epidermis (with stomata).'),
    WK('s642-w2', 'Explain — why most stomata are on the lower surface', 127, 'Why do many plants have more stomata on the lower surface of the leaf?', [
        'Step 1: The upper surface faces the sun and is hotter.',
        'Step 2: Stomata there would lose much more water by evaporation.',
        'Step 3: On the shaded, cooler lower surface water loss is less, while CO₂ can still enter the air spaces of the spongy layer just above.',
    ], 'To reduce water loss: the lower surface is cooler and shaded, yet still opens directly into the spongy air spaces.'),
    CK('s642-k1', 126, 'The main photosynthetic tissue of a leaf is the', ['upper epidermis', 'palisade layer', 'spongy layer', 'lower epidermis'], 'B',
       '**Step 1:** Photosynthesis needs chloroplasts and light.\n\n**Step 2:** The palisade layer is near the top and packed with chloroplasts.\n\n**Answer: B.**'),
    CK('s642-k2', 125, 'The petiole continues into the lamina as the', ['margin', 'midrib', 'stipule', 'sheath'], 'B',
       '**Step 1:** The petiole is the leaf stalk.\n\n**Step 2:** It runs up the centre of the blade as the midrib.\n\n**Answer: B.**'),
]

FLOWER = [
    T('c14', '6.4.3 The flower — structure', 128,
      '**What a flower is:** the part of the shoot **specially modified for reproduction**. It sits on a **flower stalk (pedicel)** whose swollen tip is the **receptacle**.',
      '**Four whorls (rings) of floral parts**, from the **outside towards the centre**: **calyx (sepals) → corolla (petals) → androecium (stamens) → gynoecium (pistil/carpels)**. (The textbook lists gynoecium before androecium; in a real flower the **stamens form a ring outside the central pistil**.)',
      '**Calyx:** the outermost whorl of **sepals** — modified leaves that **protect the flower in the bud**; usually green, sometimes brightly coloured.',
      '**Corolla:** the **petals** — often brightly coloured and scented to **attract insects** (pollinators); they may be **joined into a tube** or **free**.',
      '**Androecium (male):** the **stamens**. Each stamen = a **filament** (stalk) supporting an **anther** (sac containing **pollen grains**).',
      '**Gynoecium (female):** one or more **pistils (carpels)**. Each pistil = **stigma** (flattened or branched top with a **sticky surface** that catches pollen) + **style** (stalk joining stigma to ovary) + **ovary** (enlarged base housing the **ovules**).'),
    ST('s643-s1', 'Flower long section — the four whorls', 128, 'flower', [
        ('**Calyx — sepals:** protect the bud.', 'ca'),
        ('**Corolla — petals:** attract pollinators.', 'co'),
        ('**Androecium — stamens** (filament + anther): make pollen.', 'an'),
        ('**Gynoecium — pistil** (stigma + style + ovary): receives pollen; ovules inside.', 'gy'),
    ]),
    TB('s643-tb1', 'Floral whorls', 128, ['Whorl', 'Made of', 'Function'], [
        ['Calyx (outermost)', 'Sepals', 'Protect the flower bud'],
        ['Corolla', 'Petals', 'Attract insects (colour, scent)'],
        ['Androecium (male)', 'Stamens = filament + anther', 'Produce pollen'],
        ['Gynoecium (female, centre)', 'Pistil/carpel = stigma + style + ovary', 'Catch pollen; contain ovules; become fruit'],
    ]),
    T('s643-t1', 'Describing flowers and plants — six terms', 129,
      '**Complete flower:** has all four parts (sepals, petals, stamens, pistil). **Incomplete:** one or more missing.',
      '**Essential parts** are the **stamens and pistil** (they make the gametes).',
      '**Perfect (bisexual) flower:** has **both** stamens and pistil (e.g. bean, hibiscus). **Imperfect (unisexual):** has **only one** of them.',
      '**Monoecious plant** (“one house”): **separate male and female flowers on the same plant** — e.g. **maize** (tassel = male, cob = female), **pumpkin**.',
      '**Dioecious plant** (“two houses”): **male and female flowers on different plants** — e.g. **papaya**; a farmer needs at least one male tree near the female trees to get fruit.'),
    TB('s643-tb2', 'Flower and plant terms (Exercise 6.4 Q5 b, c)', 129, ['Pair', 'First term', 'Second term'], [
        ['Complete / incomplete', 'All four whorls present', 'At least one whorl missing'],
        ['Perfect / imperfect', 'Stamens + pistil (bisexual)', 'Only stamens or only pistil (unisexual)'],
        ['Monoecious / dioecious', 'Male + female flowers on one plant (maize, pumpkin)', 'Male and female flowers on separate plants (papaya)'],
    ]),
    T('s643-t2', 'Function of the flower — pollination', 129,
      '**Main function:** produce **male and female gametes** and bring them together. The **pollen grains** (which carry the male gametes) are made in the **anthers**; the **ovules** (which contain the egg) are made inside the **ovary**.',
      '**Pollination** = the **transfer of pollen grains from an anther to a stigma** of a flower of the **same kind (species)**.',
      '**Self-pollination:** pollen goes to the stigma of the **same flower** or **another flower on the same plant**.',
      '**Cross-pollination:** pollen goes to the stigma of a flower on **another plant** (of the same species) — carried by insects, wind, birds or water. It mixes genes from two parents, giving **more variation**.'),
    TB('s643-tb3', 'Self- vs cross-pollination (Exercise 6.4 Q5 a)', 129, ['Feature', 'Self-pollination', 'Cross-pollination'], [
        ['Pollen goes to', 'Same flower or same plant', 'A flower on another plant'],
        ['Parents', 'One', 'Two'],
        ['Variation in offspring', 'Little', 'More'],
        ['Needs an agent?', 'Often not', 'Yes — insects, wind, etc.'],
    ]),
    T('s643-t3', 'Fertilization and double fertilization — step by step', 130,
      '**Step 1 — germination of pollen.** Pollen landing on the stigma is nourished by a **sticky (sugary) substance** and **germinates**, growing a **pollen tube**.',
      '**Step 2 — two nuclei become three.** A pollen grain has a **generative nucleus** and a **tube nucleus**. The generative nucleus divides into **two male nuclei**. The tube nucleus and the two male nuclei travel down the tube **within the style**.',
      '**Step 3 — reaching the ovule.** The tube grows to the **ovary**, enters the **ovule through the micropyle**, and its tip **bursts**, releasing the two male nuclei.',
      '**Step 4 — inside the ovule (embryo sac):** an **egg nucleus**, **two polar nuclei**, **three antipodal cells** and **two synergids**.',
      '**Step 5 — fusion one:** one male nucleus + **egg nucleus** → **zygote** (grows into the embryo).',
      '**Step 6 — fusion two:** the second male nucleus + the **two polar nuclei** → **endosperm** nucleus (grows into the food store of the seed).',
      '**Step 7 — name it:** two fusions at once = **double fertilization**, found **only in flowering plants**.',
      '**Step 8 — after fertilization:** petals, stamens and style **wither**; the **ovule becomes the seed** and the **ovary becomes the fruit**.'),
    ST('s643-s2', 'Double fertilization in the ovule', 130, 'dfert', [
        ('**Pollen tube** grows down the style and enters the ovule through the micropyle, carrying two male nuclei.', 'p'),
        ('**Male nucleus 1 + egg → zygote** (2n) → embryo.', 'e'),
        ('**Male nucleus 2 + two polar nuclei → endosperm** (3n, extra detail) → food store.', 'pn'),
    ]),
    TB('s643-tb4', 'Before and after fertilization (Exercise 6.4 Q4)', 130, ['Flower part', 'Becomes'], [
        ['Ovule', 'Seed'],
        ['Ovary', 'Fruit'],
        ['Zygote', 'Embryo (young plant in the seed)'],
        ['Endosperm nucleus', 'Endosperm (food store)'],
        ['Ovule coats (integuments)', 'Seed coat (testa)'],
        ['Ovary wall', 'Fruit wall'],
        ['Petals, stamens, style, stigma', 'Wither and fall'],
    ]),
    MN('s643-m1', 'Memory hook — whorls outside → in: “Some People Sing Professionally”', 128,
       'Sepals, Petals, Stamens, Pistil — and remember **STAMEN has “MEN” = male**.',
       [('S', 'Sepals', 'calyx, protect'), ('P', 'Petals', 'corolla, attract'), ('S', 'Stamens', 'androecium, male'), ('P', 'Pistil', 'gynoecium, female')]),
    RM('s643-r1', 'Traps examiners love (6.4.3)', 130,
       '**Pollination ≠ fertilization.** Pollination moves pollen; fertilization fuses nuclei.',
       '**Ovule → seed; ovary → fruit.** Students often swap them.',
       '**Double fertilization:** egg + male nucleus = zygote; two polar nuclei + male nucleus = endosperm.',
       '**Monoecious = one plant has both kinds of flower**; dioecious = separate male and female plants.',
       '**Stamens lie outside the pistil** in the flower.'),
    WK('s643-w1', 'Exercise 6.4 Q3 and Q4', 129, '(3) What are the components of the stamen and the pistil? (4) Which parts of the flower give rise to a seed and to a fruit?', [
        'Step 1 (Q3): Stamen = filament + anther (with pollen).',
        'Step 2 (Q3): Pistil = stigma + style + ovary (with ovules).',
        'Step 3 (Q4): After double fertilization the ovule develops into the seed.',
        'Step 4 (Q4): The ovary enlarges into the fruit.',
    ], 'Stamen: filament and anther. Pistil: stigma, style and ovary. Ovule → seed; ovary → fruit.'),
    WK('s643-w2', 'Exercise 6.4 Q5', 129, 'Distinguish: (a) self- and cross-pollination; (b) perfect and imperfect flowers; (c) monoecious and dioecious plants.', [
        'Step 1 (a): Self — pollen to a stigma of the same flower or same plant; cross — to a flower on another plant of the same species.',
        'Step 2 (b): Perfect — has both stamens and pistil; imperfect — has only one of them.',
        'Step 3 (c): Monoecious — male and female flowers on the same plant (maize); dioecious — on different plants (papaya).',
    ], '(a) Self: pollen to the same flower/plant; cross: to another plant of the same species. (b) Perfect: both stamens and pistil; imperfect: only one. (c) Monoecious: male and female flowers on one plant (maize); dioecious: on separate plants (papaya).'),
    WK('s643-w3', 'Apply it — a lonely papaya tree', 129, 'A farmer plants one papaya tree. It flowers every year but never bears fruit. Explain and advise.', [
        'Step 1: Papaya is **dioecious** — male and female flowers are on different trees.',
        'Step 2: If the tree is male it can never fruit; if female, it has no pollen source nearby.',
        'Step 3: Without pollination there is no fertilization, so no ovary becomes a fruit.',
        'Step 4: Advice — plant several trees, including at least one male, near the female trees.',
    ], 'Papaya is dioecious; the single tree cannot be pollinated (or is male). Plant male and female trees together.'),
    CK('s643-k1', 129, 'Which part of the pistil catches pollen?', ['Style', 'Ovary', 'Stigma', 'Anther'], 'C',
       '**Step 1:** The pistil = stigma, style, ovary.\n\n**Step 2:** The sticky stigma catches pollen.\n\n**Answer: C.**'),
    CK('s643-k2', 130, 'In double fertilization, the second male nucleus fuses with', ['the egg', 'two polar nuclei', 'the synergids', 'the tube nucleus'], 'B',
       '**Step 1:** First male nucleus + egg = zygote.\n\n**Step 2:** Second male nucleus + two polar nuclei = endosperm.\n\n**Answer: B.**'),
    CK('s643-k3', 129, 'Maize has male tassels and female cobs on the same plant. Maize is', ['dioecious', 'monoecious', 'perfect-flowered', 'complete-flowered'], 'B',
       '**Step 1:** Separate male and female flowers → imperfect flowers.\n\n**Step 2:** Both on one plant → monoecious.\n\n**Answer: B.**'),
]

LESSONS = {
    L61: ['bio11-u6-c01', 'bio11-u6-c02', 'bio11-u6-c03'] + HORM + ['bio11-u6-tbl1', 'bio11-u6-wrk1', 'bio11-u6-wrk2', 'bio11-u6-chk1', 'bio11-u6-chk2', 'bio11-u6-l6-1-mx1'],
    L63: ['bio11-u6-c06', 'bio11-u6-c07', 'bio11-u6-c08', 'bio11-u6-c09'] + ROOT + [CHK6, WRK6, 'bio11-u6-c11', 'bio11-u6-chk5', 'bio11-u6-wrk5', 'bio11-u6-l6-3-r2c1', 'bio11-u6-chk7', 'bio11-u6-wrk7'],
    L64: STEM + LEAF + FLOWER + ['bio11-u6-chk8', 'bio11-u6-wrk8', 'bio11-u6-l6-4-mx1', 'bio11-u6-l6-4-r3r1'],
}
DIAGRAM_KEYS = ['photo', 'apical', 'root', 'stems', 'leaf', 'flower', 'dfert']
