r"""Grade 10 additions: Unit 2 polar molecules + London forces, Unit 3 concentration units + boiling point elevation + osmotic
pressure, Unit 4 acid-base theories, Unit 5 exo/endothermic examples, energy diagrams and types of heat of reaction."""
from common import Unit

# ============================================================== Unit 2 Chemical bonding and structure
U2 = Unit('chem10-u2')
L2 = '2.2–2.3 Polarity and London forces'
DIAG2 = {'cm_polar': 'polar', 'cm_london': 'london'}

POLAR = [
    U2.T('c01', 'From polar bonds to polar molecules, step by step', 46,
         'A **polar bond** has a partly negative end (δ−) and a partly positive end (δ+) because the two atoms have different **electronegativities**. A **polar molecule** has a δ− side and a δ+ side **overall**. A molecule can contain polar bonds and still be non-polar — the **shape** decides.',
         '**Step 1 — Compare electronegativities (EN) for each bond.** ΔEN ≈ 0 → non-polar covalent bond (H–H, Cl–Cl, C–H is nearly non-polar). Small to moderate ΔEN → polar covalent bond (H–Cl, O–H, C=O). Large ΔEN (about 1.7–2 or more) → ionic bond (Na⁺Cl⁻). The change is gradual (textbook Fig 2.2).',
         '**Step 2 — Draw each bond dipole** as an arrow from δ+ towards δ− (towards the more electronegative atom).',
         '**Step 3 — Work out the shape.** Count the bonding pairs and lone pairs on the central atom: CO₂ linear, H₂O bent, NH₃ pyramidal, CH₄ and CCl₄ tetrahedral, BF₃ trigonal planar.',
         '**Step 4 — Add the arrows.** If the shape is **symmetrical** and all outer atoms are the same, the bond dipoles cancel → **non-polar molecule**. If not, they leave a net dipole → **polar molecule**.',
         'The textbook explains bond polarity (2.2.3); deciding the polarity of a whole molecule from its shape is added here because exam questions ask it.',
         '**Shortcut:** a **lone pair on the central atom** (H₂O, NH₃, SO₂) almost always makes the molecule polar; symmetrical molecules with identical outer atoms (CO₂, CH₄, CCl₄, BF₃) are non-polar.'),
    U2.ST('s01', 'Model: polar and non-polar molecules', 47, 'cm_polar',
          [('**HCl** — one polar bond, nothing to cancel it → **polar** molecule. Cl is δ−, H is δ+.', 'hcl'),
           ('**H₂O** — two polar O–H bonds in a **bent** shape (104.5°). The arrows both point up towards O and add → **polar**.', 'h2o'),
           ('**CO₂** — two polar C=O bonds, but the molecule is **linear**: equal arrows point in opposite directions and cancel → **non-polar**.', 'co2'),
           ('**CH₄** — four C–H bonds in a symmetrical **tetrahedron**; the small dipoles cancel → **non-polar**.', 'ch4')],
          'Tap each molecule: the arrows show the bond dipoles.'),
    U2.TB('t01', 'Polarity of common molecules', 47,
          ['Molecule', 'Shape', 'Polar bonds?', 'Dipoles cancel?', 'Molecule is'],
          [['H₂, Cl₂, O₂, N₂', 'linear (2 atoms)', 'no', '—', 'non-polar'],
           ['HCl, HF', 'linear (2 atoms)', 'yes', 'no', 'polar'],
           ['H₂O', 'bent', 'yes', 'no', 'polar'],
           ['NH₃', 'trigonal pyramidal', 'yes', 'no', 'polar'],
           ['CO₂', 'linear', 'yes', 'yes', 'non-polar'],
           ['BF₃', 'trigonal planar', 'yes', 'yes', 'non-polar'],
           ['CH₄, CCl₄', 'tetrahedral', 'yes (C–Cl)', 'yes', 'non-polar'],
           ['CHCl₃', 'tetrahedral', 'yes', 'no (one H differs)', 'polar']]),
    U2.T('c02', 'How polarity shows up in real life', 47,
         '**Charged rod test:** hold a rubbed plastic ruler near a thin stream of water — the stream **bends** towards it (polar). A stream of hexane or CCl₄ does not bend (non-polar).',
         '**“Like dissolves like”:** polar and ionic substances dissolve in polar water (salt, sugar, ethanol); non-polar substances dissolve in non-polar solvents (grease and oil in kerosene).',
         '**Boiling points:** for molecules of similar size, polar molecules have **higher** boiling points because dipole–dipole attractions add to London forces.'),
    U2.WK('w01', 'Worked example: is NH₃ polar? is CCl₄ polar?', 47,
          'Decide whether ammonia, NH₃, and carbon tetrachloride, CCl₄, are polar molecules.',
          ['NH₃: N (EN 3.0) is more electronegative than H (2.1) → three polar N–H bonds, N is δ−.',
           'N has 3 bonding pairs + 1 lone pair → trigonal **pyramidal**, not symmetrical.',
           'The three dipoles all point up towards N and do not cancel → NH₃ is **polar**.',
           'CCl₄: Cl (3.0) is more electronegative than C (2.5) → four polar C–Cl bonds.',
           'C has 4 bonding pairs, no lone pair → regular **tetrahedron** with four identical outer atoms.',
           'The four dipoles cancel exactly → CCl₄ is **non-polar** (even though every bond is polar).'],
          'NH₃ polar (pyramidal, lone pair); CCl₄ non-polar (symmetrical tetrahedron).'),
    U2.WK('w02', 'Worked example: CO₂ vs SO₂', 47,
          'CO₂ is non-polar but SO₂ is polar, although both have two polar bonds to oxygen. Explain.',
          ['Both have polar bonds: O is more electronegative than C and than S.',
           'CO₂: C has no lone pair → **linear** O=C=O; the two dipoles are equal and opposite → cancel.',
           'SO₂: S has a lone pair → **bent** shape; the two dipoles point partly the same way → net dipole.'],
          'Shape decides: linear CO₂ cancels, bent SO₂ does not.'),
    U2.CK('k01', 47, 'Which molecule is non-polar even though it contains polar bonds?',
          ['H₂O', 'NH₃', 'CO₂', 'HCl'], 'C',
          'CO₂ is linear, so its two C=O dipoles cancel. H₂O (bent) and NH₃ (pyramidal) keep a net dipole; HCl has only one bond.'),
    U2.CK('k02', 46, 'A thin stream of liquid is bent by a charged rod. The liquid is most likely …',
          ['hexane', 'carbon tetrachloride', 'water', 'liquid nitrogen'], 'C',
          'Only **polar** molecules are attracted to the rod. Water is polar; the other three are non-polar.'),
]

LONDON = [
    U2.T('c03', 'London (dispersion) forces, step by step', 53,
         'London forces (dispersion forces) are the **weakest** intermolecular forces, but they act between **all** molecules and atoms — and they are the **only** attraction between non-polar molecules and noble-gas atoms.',
         '**Step 1 — Electrons move.** In a non-polar molecule the electron cloud is evenly spread *on average*, but at any instant it may be a little more on one side.',
         '**Step 2 — Instantaneous dipole.** For that instant the molecule has a δ− side and a δ+ side.',
         '**Step 3 — Induced dipole.** That tiny dipole pushes or pulls the electrons of the neighbouring molecule, creating a dipole in it, lined up so that δ+ faces δ−.',
         '**Step 4 — Attraction.** The two short-lived dipoles attract. Millions of these flickering attractions together hold the molecules (Fig 2.10: two iodine molecules).',
         '**What makes them stronger?** (1) **More electrons / bigger molecules** — a large electron cloud is easily distorted (more polarisable). (2) **Larger contact area** — long, straight molecules touch more than compact, round ones.'),
    U2.SS('s02', 'Model: how a London force forms', 54, 'cm_london',
          [('a', 'Even cloud', 'Two non-polar molecules; on average the electrons are spread evenly — no dipole.'),
           ('b', 'Instant dipole', 'Electrons drift to one side of the left molecule: δ− on one side, δ+ on the other.'),
           ('c', 'Induced dipole', 'The δ+ end attracts the electrons of the right molecule → an induced dipole. δ+ … δ− attraction = London force.')],
          'Slide to see the three stages.'),
    U2.TB('t02', 'More electrons → stronger London forces → higher boiling point', 54,
          ['Substance', 'Electrons per molecule', 'Boiling point', 'State at 25 °C'],
          [['F₂', '18', '−188 °C', 'gas'], ['Cl₂', '34', '−34 °C', 'gas'], ['Br₂', '70', '59 °C', 'liquid'], ['I₂', '106', '184 °C', 'solid'],
           ['He', '2', '−269 °C', 'gas'], ['Ne', '10', '−246 °C', 'gas'], ['Ar', '18', '−186 °C', 'gas'], ['Xe', '54', '−108 °C', 'gas']],
          'Down a group the molecules get bigger, London forces get stronger, so boiling points rise.'),
    U2.TB('t03', 'The intermolecular forces compared', 58,
          ['Force', 'Acts between', 'Cause', 'Strength', 'Example'],
          [['London (dispersion)', 'all molecules; only force for non-polar ones', 'instantaneous and induced dipoles', 'weakest (grows with size)', 'I₂, CH₄, noble gases'],
           ['Dipole–dipole', 'polar molecules', 'permanent δ+ … δ−', 'stronger', 'HCl, SO₂'],
           ['Hydrogen bond', 'H on N, O or F … lone pair on N, O, F', 'very polar H–N, H–O, H–F', 'strongest of these', 'H₂O, NH₃, HF'],
           ['Ion–dipole', 'ions and polar molecules', 'ion charge … dipole', 'strong', 'NaCl dissolving in water']],
          'Order to remember: dispersion < dipole–dipole < hydrogen bond (textbook p.58).'),
    U2.MN('m01', 'Memory trick', 54, '**“Big clouds wobble more.”** More electrons → a bigger, softer cloud → easier to distort → stronger London forces → higher boiling point.'),
    U2.WK('w03', 'Worked example: why is I₂ a solid but Cl₂ a gas?', 54,
          'Chlorine is a gas and iodine a solid at room temperature, yet both are non-polar X₂ molecules. Explain.',
          ['Both molecules are non-polar, so the only forces between molecules are **London forces**.',
           'I₂ has 106 electrons; Cl₂ has 34. I₂ has the much larger electron cloud.',
           'A larger cloud is more easily distorted → bigger instantaneous dipoles → stronger London forces.',
           'More energy is needed to separate I₂ molecules → higher melting and boiling points → solid at 25 °C.'],
          'Stronger London forces between the larger I₂ molecules.'),
    U2.WK('w04', 'Worked example: HCl vs F₂', 53,
          'HCl (M = 36.5) boils at −85 °C; F₂ (M = 38) boils at −188 °C. Why the big difference for molecules of similar mass?',
          ['Similar mass and number of electrons → similar London forces.',
           'F₂ is non-polar: London forces only.',
           'HCl is polar: London forces **plus dipole–dipole** attractions.',
           'Extra attraction → more energy needed to boil → HCl has the higher boiling point.'],
          'HCl has dipole–dipole forces in addition to London forces.'),
    U2.CK('k03', 54, 'Which noble gas has the highest boiling point?', ['He', 'Ne', 'Ar', 'Xe'], 'D',
          'Xe has the most electrons → strongest London forces → highest boiling point.'),
    U2.CK('k04', 53, 'The only intermolecular force between CH₄ molecules is …',
          ['hydrogen bonding', 'dipole–dipole', 'London (dispersion) forces', 'ionic bonding'], 'C',
          'CH₄ is non-polar and has no H on N, O or F, so only London forces act.'),
    U2.RM('r01', 'Tips and common mistakes', 54,
          'Polar **bonds** ≠ polar **molecule**: always check the shape.',
          'London forces are present in **every** molecular substance — even polar ones. They are not “only for non-polar molecules”; they are just the *only* force there.',
          'Compare boiling points in this order: first check for hydrogen bonding, then polarity, then size (electrons).'),
]

U2.M('q1', L2, 47, 'Which of these molecules is polar?', ['CO₂', 'CH₄', 'BF₃', 'NH₃'], 'D',
     ['Step 1: CO₂ (linear), CH₄ (tetrahedral) and BF₃ (trigonal planar) are symmetrical with identical outer atoms — dipoles cancel.',
      'Step 2: NH₃ has a lone pair on N → pyramidal → dipoles do not cancel.'],
     'Lone pair on the central atom → usually polar.',
     [('Is H₂S polar?', 'Yes — bent like water.'), ('Is CCl₄ polar?', 'No — symmetrical tetrahedron.')])
U2.TF('q2', L2, 47, 'A molecule that contains polar bonds must be a polar molecule.', False,
      ['Step 1: polarity of the molecule depends on bond polarity **and** shape.', 'Step 2: in symmetrical CO₂, CH₄, CCl₄ the bond dipoles cancel.', 'Step 3: so the statement is false.'],
      'Draw the shape before deciding.', [('Give a molecule with polar bonds that is non-polar.', 'CO₂ (or CCl₄, BF₃).'), ('Why is water polar?', 'Its two O–H dipoles are in a bent shape and do not cancel.')])
U2.M('q3', L2, 54, 'Which halogen has the strongest London forces between its molecules?', ['F₂', 'Cl₂', 'Br₂', 'I₂'], 'D',
     ['Step 1: all are non-polar → London forces only.', 'Step 2: London forces grow with the number of electrons.', 'Step 3: I₂ is the largest → strongest.'],
     'Down the group: bigger → stronger London forces → higher b.p.',
     [('Which halogen is a liquid at room temperature?', 'Bromine.'), ('Arrange Ar, He, Kr in order of increasing b.p.', 'He < Ar < Kr.')])
U2.S('q4', L2, 53, 'Explain, step by step, how London forces arise between two non-polar molecules.',
     'Electrons move, so for an instant one molecule has an uneven cloud (instantaneous dipole); this distorts the neighbour’s cloud (induced dipole); the δ+ and δ− of the two dipoles attract.',
     ['Step 1: random electron movement → instantaneous dipole.', 'Step 2: it induces a dipole in a neighbouring molecule.', 'Step 3: the opposite partial charges attract — a London force.', 'Step 4: the dipoles keep changing, so the force is weak and short-lived.'],
     'Key words: instantaneous dipole, induced dipole, attraction.',
     [('Why do London forces increase with molecular size?', 'Larger electron clouds are more easily distorted (more polarisable).'), ('Which force holds solid iodine together?', 'London forces between I₂ molecules.')])
U2.M('q5', L2, 53, 'HCl and F₂ have similar molar masses, but HCl has the higher boiling point. The best reason is that HCl …',
     ['is ionic', 'has hydrogen bonds', 'has dipole–dipole forces as well as London forces', 'has more electrons'], 'C',
     ['Step 1: similar size → similar London forces.', 'Step 2: HCl is polar, so dipole–dipole attraction is added.', 'Step 3: H is bonded to Cl, not N/O/F, so it is not hydrogen bonding.'],
     'Hydrogen bonds need H on N, O or F.',
     [('Which has the higher b.p., H₂O or H₂S?', 'H₂O — hydrogen bonding.'), ('Which has the higher b.p., CH₄ or SiH₄?', 'SiH₄ — more electrons, stronger London forces.')])

# ============================================================== Unit 3 Solutions
U3 = Unit('chem10-u3')
L3 = '3.2 Concentration units'
L3b = '3.3 Boiling point and osmosis'
DIAG3 = {'cm_concmap': 'concmap', 'cm_bpe': 'bpe', 'cm_osmosis': 'osmosis'}

CONC = [
    U3.T('c01', 'Five ways to express concentration', 75,
         'Concentration tells you **how much solute** is in a given amount of **solution** (or solvent). Learn each formula with its units:',
         r'$$\text{mass \%} = \frac{\text{mass of solute}}{\text{mass of solution}} \times 100$$',
         r'$$\text{volume \%} = \frac{\text{volume of solute}}{\text{volume of solution}} \times 100$$',
         r'$$M = \frac{n_{\text{solute}}}{V_{\text{solution}}\,(\text{L})} \quad (\text{mol/L})$$',
         r'$$m = \frac{n_{\text{solute}}}{\text{mass of solvent (kg)}} \quad (\text{mol/kg})$$',
         r'$$N = \frac{\text{number of equivalents}}{V_{\text{solution}}\,(\text{L})} = M \times (\text{replaceable H}^+ \text{ or OH}^-)$$',
         r'Always find the **moles** first: \(n = \dfrac{\text{mass}}{\text{molar mass}}\).'),
    U3.TB('t01', 'Concentration units at a glance', 75,
          ['Unit', 'Symbol', 'Per …', 'SI-type units', 'Changes with temperature?'],
          [['Mass percent', '% (w/w)', '100 g of solution', 'g per 100 g', 'no (masses do not change)'],
           ['Volume percent', '% (v/v)', '100 mL of solution', 'mL per 100 mL', 'yes (volumes expand)'],
           ['Molarity', 'M', '1 L of solution', 'mol/L', 'yes'],
           ['Molality', 'm', '1 kg of solvent', 'mol/kg', 'no'],
           ['Normality', 'N', '1 L of solution', 'equivalents/L', 'yes']],
          'Molality and mass percent use only masses, so they do not change when the solution warms up — that is why molality is used for boiling-point elevation.'),
    U3.ST('s01', 'Model: how the units connect', 79, 'cm_concmap',
          [('Everything goes through **moles of solute**: n = mass ÷ molar mass.', 'n'),
           ('**Molarity**: divide moles by litres of **solution**.', 'M'),
           ('**Molality**: divide moles by kilograms of **solvent** (not solution).', 'm'),
           ('**Normality**: multiply molarity by the number of replaceable H⁺ (acid) or OH⁻ (base).', 'N'),
           ('**Mass percent**: needs masses only. To switch between percent and molarity you also need the **density** of the solution.', 'p')]),

    U3.T('c02', 'Mass percent, step by step', 75,
         '1. Find the mass of solute and the mass of **solution** (solution = solute + solvent).',
         '2. Divide and multiply by 100.',
         '“A 10% salt solution” means 10 g of salt in every 100 g of solution, i.e. 10 g salt + 90 g water.'),
    U3.WK('w01', 'Worked example: mass percent', 75,
          '25 g of sodium chloride is dissolved in 100 g of water. Find the mass percent of NaCl.',
          ['Mass of solution = 25 g + 100 g = 125 g (do not forget to add the solute).',
           r'\(\text{mass \%} = \dfrac{25}{125} \times 100\)',
           '= 20 %'],
          '20 % NaCl by mass'),
    U3.WK('w02', 'Worked example: making a solution of given mass percent', 76,
          'How many grams of KNO₃ and of water are needed to make 250 g of an 8.0 % (by mass) KNO₃ solution?',
          [r'Mass of solute = \(\dfrac{8.0}{100} \times 250 \text{ g}\) = 20 g KNO₃',
           'Mass of water = 250 g − 20 g = 230 g'],
          '20 g KNO₃ dissolved in 230 g water'),
    U3.T('c03', 'Volume percent, step by step', 77,
         'Used when both solute and solvent are **liquids** (alcohol in water, antiseptics).',
         '1. Find the volume of the liquid solute and the total volume of **solution**.',
         '2. Divide and multiply by 100.',
         '**Careful:** volumes are not always additive — 50 mL ethanol + 50 mL water gives a little **less** than 100 mL. Use the measured volume of solution.'),
    U3.WK('w03', 'Worked example: volume percent', 77,
          'How much pure ethanol is in 500 mL of a 70 % (v/v) ethanol hand-sanitiser solution?',
          [r'Volume of ethanol = \(\dfrac{70}{100} \times 500 \text{ mL}\)', '= 350 mL ethanol (the rest, about 150 mL, is water)'],
          '350 mL ethanol'),
    U3.T('c04', 'Molarity, step by step', 79,
         '1. Convert the mass of solute into **moles**: n = m ÷ M.',
         '2. Convert the volume of **solution** into **litres** (mL ÷ 1000).',
         r'3. \(M = \dfrac{n}{V}\). Rearranged: \(n = M \times V\) and mass = \(M \times V \times\) molar mass.',
         r'**Dilution:** adding water does not change the moles of solute, so \(M_1V_1 = M_2V_2\) (textbook 3.2.2, p.92).'),
    U3.WK('w04', 'Worked example: molarity from mass', 79,
          '11.7 g of NaCl (M = 58.5 g/mol) is dissolved in water to make 500 mL of solution. Find the molarity.',
          [r'Moles: \(n = \dfrac{11.7}{58.5} = 0.200\text{ mol}\)', 'Volume: 500 mL = 0.500 L',
           r'\(M = \dfrac{0.200}{0.500} = 0.400\text{ mol/L}\)'],
          '0.400 M NaCl'),
    U3.WK('w05', 'Worked example: mass needed for a molar solution', 80,
          'What mass of NaOH (M = 40 g/mol) is needed to make 250 mL of 0.20 M solution?',
          [r'Moles needed: \(n = M \times V = 0.20 \times 0.250 = 0.050\text{ mol}\)',
           r'Mass: \(0.050 \times 40 = 2.0\text{ g}\)',
           'Dissolve 2.0 g NaOH in a little water, then add water up to the 250 mL mark of a volumetric flask.'],
          '2.0 g NaOH'),
    U3.WK('w06', 'Worked example: dilution', 92,
          'What volume of 2.0 M HCl is needed to make 500 mL of 0.10 M HCl?',
          [r'\(M_1V_1 = M_2V_2\)', r'\(2.0 \times V_1 = 0.10 \times 500\text{ mL}\)', r'\(V_1 = \dfrac{50}{2.0} = 25\text{ mL}\)',
           'Measure 25 mL of 2.0 M HCl and add water to make 500 mL (add acid to water, never water to acid).'],
          '25 mL of 2.0 M HCl'),
    U3.T('c05', 'Molality, step by step', 84,
         '1. Find the moles of solute.',
         '2. Find the mass of **solvent** only, in **kilograms** (g ÷ 1000).',
         r'3. \(m = \dfrac{n_{\text{solute}}}{\text{kg of solvent}}\)',
         '**Molarity vs molality:** molarity divides by litres of **solution**; molality divides by kilograms of **solvent**. For dilute water solutions the two numbers are almost equal (1 L of water ≈ 1 kg).'),
    U3.WK('w07', 'Worked example: molality', 84,
          '10.0 g of NaOH (M = 40 g/mol) is dissolved in 500 g of water. Find the molality.',
          [r'Moles: \(n = \dfrac{10.0}{40} = 0.250\text{ mol}\)', 'Solvent: 500 g = 0.500 kg',
           r'\(m = \dfrac{0.250}{0.500} = 0.500\text{ mol/kg}\)'],
          '0.500 m NaOH'),
    U3.WK('w08', 'Worked example: molality of urea', 85,
          '6.0 g of urea, CO(NH₂)₂ (M = 60 g/mol), is dissolved in 200 g of water. Find the molality.',
          [r'\(n = \dfrac{6.0}{60} = 0.10\text{ mol}\)', '200 g = 0.200 kg', r'\(m = \dfrac{0.10}{0.200} = 0.50\text{ mol/kg}\)'],
          '0.50 m urea'),
    U3.T('c06', 'Normality, step by step', 86,
         'Normality counts **equivalents** — for acids and bases, the moles of H⁺ or OH⁻ that can react.',
         r'1. **Equivalent mass** of an acid = \(\dfrac{\text{molar mass}}{\text{number of replaceable H}}\); of a base = \(\dfrac{\text{molar mass}}{\text{number of OH}}\). HCl: 36.5 g; H₂SO₄: 98 ÷ 2 = 49 g; NaOH: 40 g; Ca(OH)₂: 74 ÷ 2 = 37 g.',
         r'2. Equivalents = \(\dfrac{\text{mass}}{\text{equivalent mass}}\).',
         r'3. \(N = \dfrac{\text{equivalents}}{V(\text{L})}\) — or simply \(N = M \times\) (number of replaceable H⁺ or OH⁻) (textbook p.91).',
         'So 1 M HCl = 1 N, but 1 M H₂SO₄ = 2 N and 1 M H₃PO₄ = 3 N (if all three H react).'),
    U3.WK('w09', 'Worked example: normality of sulfuric acid', 87,
          '4.9 g of H₂SO₄ (M = 98 g/mol) is dissolved to make 500 mL of solution. Find (a) the molarity and (b) the normality.',
          [r'Moles: \(n = \dfrac{4.9}{98} = 0.050\text{ mol}\)', r'(a) \(M = \dfrac{0.050}{0.500} = 0.10\text{ M}\)',
           'H₂SO₄ has 2 replaceable H → equivalent mass = 49 g; equivalents = 4.9 ÷ 49 = 0.10',
           r'(b) \(N = \dfrac{0.10}{0.500} = 0.20\text{ N}\) — check: \(N = M \times 2 = 0.20\text{ N}\)'],
          '0.10 M, 0.20 N'),
    U3.WK('w10', 'Worked example: normality of bases', 91,
          'Find the normality of (a) 0.50 M NaOH and (b) 0.10 M Ca(OH)₂.',
          ['(a) NaOH gives 1 OH⁻ → N = 0.50 × 1 = 0.50 N', '(b) Ca(OH)₂ gives 2 OH⁻ → N = 0.10 × 2 = 0.20 N'],
          '(a) 0.50 N; (b) 0.20 N'),
    U3.T('c07', 'Converting between units, step by step', 89,
         '**Mass % ⇄ molarity** needs the **density** of the solution. Work with a convenient amount: **1 L of solution** (its mass = density × 1000 mL).',
         '**Molarity → molality:** take 1 L of solution, find its mass (density), subtract the mass of solute → mass of solvent, then divide moles by kg of solvent.',
         '**Mass % → molality:** take 100 g of solution: solute grams = the percent, solvent = 100 − percent.',
         '**Molarity ⇄ normality:** N = M × (H⁺ or OH⁻ per formula).'),
    U3.WK('w11', 'Worked example: concentrated HCl', 89,
          'Concentrated hydrochloric acid is 36.5 % HCl by mass and has density 1.18 g/mL. Find its molarity and molality (HCl = 36.5 g/mol).',
          ['Take 1 L = 1000 mL of solution: mass = 1000 × 1.18 = 1180 g.',
           'Mass of HCl = 36.5 % of 1180 g = 430.7 g.',
           r'Moles of HCl = \(\dfrac{430.7}{36.5} = 11.8\text{ mol}\) → molarity = **11.8 M**.',
           'Mass of water = 1180 − 430.7 = 749.3 g = 0.7493 kg.',
           r'Molality = \(\dfrac{11.8}{0.7493} = 15.7\text{ mol/kg}\).'],
          '11.8 M and 15.7 m'),
    U3.WK('w12', 'Worked example: from molarity to molality and mass %', 89,
          'A 2.00 M NaCl solution has density 1.08 g/mL. Find its molality and mass percent (NaCl = 58.5 g/mol).',
          ['1 L of solution has mass 1080 g and contains 2.00 mol NaCl.', 'Mass of NaCl = 2.00 × 58.5 = 117 g.',
           'Mass of water = 1080 − 117 = 963 g = 0.963 kg.', r'Molality = \(\dfrac{2.00}{0.963} = 2.08\text{ m}\).',
           r'Mass % = \(\dfrac{117}{1080} \times 100 = 10.8\,\%\).'],
          '2.08 m; 10.8 % NaCl by mass'),
    U3.MN('m01', 'Memory trick: big M, small m', 84,
          '**Big M** = the big flask (whole **solution**, litres). **Small m** = the small bit that is only **solvent** (kilograms). **N** = **N**umber of H⁺/OH⁻ times M.'),
    U3.CK('k01', 79, 'What is the molarity of a solution containing 0.5 mol of glucose in 250 mL of solution?',
          ['0.125 M', '0.5 M', '2.0 M', '125 M'], 'C', 'M = n ÷ V = 0.5 mol ÷ 0.250 L = 2.0 M. Change mL to L first.'),
    U3.CK('k02', 84, 'Molality is defined as moles of solute per …',
          ['litre of solution', 'kilogram of solution', 'kilogram of solvent', 'litre of solvent'], 'C',
          'Molality uses the mass of the **solvent** in kg. Molarity uses litres of **solution**.'),
    U3.CK('k03', 91, 'The normality of 0.2 M H₂SO₄ is …', ['0.1 N', '0.2 N', '0.4 N', '0.6 N'], 'C',
          'H₂SO₄ has 2 replaceable H, so N = 0.2 × 2 = 0.4 N.'),
    U3.CK('k04', 75, 'Which concentration unit does NOT change when the solution is heated?',
          ['Molarity', 'Normality', 'Volume percent', 'Molality'], 'D',
          'Molality uses masses only; volumes (and so M, N and v/v %) change as the liquid expands.'),
    U3.RM('r01', 'Tips and common mistakes', 75,
          'Change **mL → L** for M and N, and **g → kg** for molality.',
          'Mass % uses mass of **solution** (solute + solvent) on the bottom; molality uses mass of **solvent** only.',
          'Write the units at every step — the units tell you which formula you are using.',
          'For any conversion between % and M you need the **density**.'),
]

COLLIG = [
    U3.T('c08', 'Boiling point elevation, step by step', 103,
         '**Boiling** happens when the vapour pressure of a liquid equals the atmospheric pressure. Pure water at sea level boils at 100 °C.',
         '**Step 1 — Solute lowers the vapour pressure.** Non-volatile solute particles take up part of the surface, so fewer solvent molecules escape per second.',
         '**Step 2 — More heating is needed.** At 100 °C the solution’s vapour pressure is still below atmospheric pressure, so it does not boil yet.',
         '**Step 3 — The solution boils higher.** It must be heated above 100 °C until its vapour pressure reaches atmospheric pressure. The rise is the **boiling point elevation**, ΔTb.',
         r'$$\Delta T_b = T_b(\text{solution}) - T_b(\text{solvent}) = K_b \times m$$',
         'Kb is the **molal boiling point constant** of the solvent (water: 0.52 °C kg/mol) and m is the **molality**. ΔTb depends only on the **number** of solute particles, not on what they are — it is a **colligative property**.',
         '**Ionic solutes (extension):** NaCl splits into Na⁺ and Cl⁻, so 1 mol gives about 2 mol of particles and roughly doubles ΔTb. CaCl₂ gives 3 particles.'),
    U3.ST('s02', 'Model: why a solution boils higher', 104, 'cm_bpe',
          [('**Pure water** boils at 100 °C: its vapour pressure reaches 1 atm (760 mmHg).', 'p'),
           ('The **solution** (blue) has a lower vapour pressure at every temperature, so it reaches 1 atm only at a higher temperature.', 's'),
           ('The gap between the two boiling points is **ΔTb = Kb·m**.', 'd')]),
    U3.TB('t02', 'Boiling point constants (textbook Table 3.6)', 104,
          ['Solvent', 'Normal b.p.', 'Kb (°C kg/mol)'],
          [['Water', '100.0 °C', '0.52'], ['Ethanol', '78.4 °C', '1.22'], ['Benzene', '80.1 °C', '2.53'], ['Acetic acid', '118 °C', '2.93']]),
    U3.WK('w13', 'Worked example: boiling point of a sugar solution', 104,
          'Find the boiling point of a 0.40 m aqueous sugar solution (Kb of water = 0.52 °C kg/mol).',
          [r'\(\Delta T_b = K_b \times m = 0.52 \times 0.40\)', r'\(\Delta T_b = 0.208 \approx 0.21\,^\circ\text{C}\)',
           'Boiling point = 100 + 0.21 = 100.21 °C'],
          '100.21 °C'),
    U3.WK('w14', 'Worked example: from grams to boiling point', 104,
          '9.0 g of glucose, C₆H₁₂O₆ (M = 180 g/mol), is dissolved in 100 g of water. Find the boiling point of the solution.',
          [r'Moles of glucose: \(n = \dfrac{9.0}{180} = 0.050\text{ mol}\)', r'Molality: \(m = \dfrac{0.050}{0.100\text{ kg}} = 0.50\text{ mol/kg}\)',
           r'\(\Delta T_b = 0.52 \times 0.50 = 0.26\,^\circ\text{C}\)', 'Boiling point = 100.26 °C'],
          '100.26 °C'),
    U3.WK('w15', 'Worked example: molar mass from boiling point elevation', 104,
          '3.0 g of a non-volatile, non-electrolyte solute is dissolved in 50 g of benzene (Kb = 2.53 °C kg/mol). The boiling point rises by 0.60 °C. Find the molar mass of the solute.',
          [r'Molality: \(m = \dfrac{\Delta T_b}{K_b} = \dfrac{0.60}{2.53} = 0.237\text{ mol/kg}\)',
           r'Moles of solute = \(0.237 \times 0.050\text{ kg} = 0.0119\text{ mol}\)',
           r'Molar mass = \(\dfrac{3.0\text{ g}}{0.0119\text{ mol}} \approx 253\text{ g/mol}\)'],
          'about 253 g/mol'),
    U3.T('c09', 'Osmosis and osmotic pressure, step by step', 106,
         '**Osmosis** is the movement of **solvent** (water) molecules through a **semi-permeable membrane** from a **dilute** solution (or pure water) into a **more concentrated** solution. The membrane lets water through but not the solute particles.',
         '**Step 1 — Unequal water concentration.** Pure water has more free water molecules per volume than the solution, so more water crosses into the solution each second than comes back.',
         '**Step 2 — The level rises.** The solution side gains water and its level rises in the tube (textbook Fig 3.9).',
         '**Step 3 — Balance.** The extra weight of the raised column pushes water back. When the two flows are equal, osmosis stops.',
         '**Osmotic pressure (π)** is the pressure that must be applied to the concentrated solution to **stop** osmosis. It is proportional to the height of the column and, like other colligative properties, depends on the **number** of solute particles.',
         r'**Formula (extension, beyond the textbook):** \(\pi = MRT\), with M in mol/L, R = 0.0821 L·atm/(mol·K) and T in kelvin.',
         '**Uses and examples:** a drip (infusion) must have the **same** osmotic pressure as blood (0.9 % NaCl, “isotonic”); red blood cells swell and burst in pure water and shrink in very salty water; salting meat or fish draws water out of germs and preserves the food; plant roots take in water by osmosis; **reverse osmosis** (pushing harder than π) makes drinking water from sea water.'),
    U3.SS('s03', 'Model: osmosis in a U-tube', 106, 'cm_osmosis',
          [('a', 'Start', 'Pure water on the left, sugar solution on the right, same level. The membrane lets only water through.'),
           ('b', 'Osmosis', 'More water moves right (into the solution) than left — the solution level rises.'),
           ('c', 'Osmotic pressure', 'Pushing on the solution side with a pressure π stops the net flow: that pressure is the osmotic pressure.')]),
    U3.WK('w16', 'Worked example: osmotic pressure of glucose (extension)', 106,
          'Calculate the osmotic pressure of a 0.10 M glucose solution at 27 °C.',
          ['T = 27 + 273 = 300 K', r'\(\pi = MRT = 0.10 \times 0.0821 \times 300\)', r'\(\pi = 2.46\text{ atm}\)'],
          '≈ 2.5 atm'),
    U3.WK('w17', 'Worked example: which has the higher osmotic pressure?', 106,
          'Which has the higher osmotic pressure at the same temperature: 0.10 M glucose or 0.10 M NaCl? Which has the higher boiling point?',
          ['Glucose does not ionise: 0.10 mol of particles per litre.', 'NaCl → Na⁺ + Cl⁻: about 0.20 mol of particles per litre.',
           'Colligative properties depend on the number of particles → NaCl solution has the higher osmotic pressure **and** the higher boiling point.'],
          '0.10 M NaCl (about twice as many particles) for both.'),
    U3.TB('t03', 'Colligative properties summary', 101,
          ['Property', 'What happens', 'Formula', 'Everyday example'],
          [['Vapour-pressure lowering', 'solution evaporates more slowly', '—', 'salt water dries more slowly than pure water'],
           ['Boiling-point elevation', 'solution boils higher', 'ΔTb = Kb·m', 'salted cooking water boils slightly above 100 °C'],
           ['Freezing-point depression', 'solution freezes lower', 'ΔTf = Kf·m', 'salt on icy roads; antifreeze'],
           ['Osmotic pressure', 'water moves into the more concentrated solution', 'π = MRT (extension)', 'drips, salting meat, plant roots']]),
    U3.CK('k05', 104, 'Which aqueous solution has the highest boiling point?',
          ['0.1 m sugar', '0.2 m sugar', '0.3 m sugar', 'pure water'], 'C',
          'ΔTb = Kb·m: the largest molality (0.3 m) gives the largest rise.'),
    U3.CK('k06', 106, 'During osmosis, water moves …',
          ['from concentrated to dilute solution', 'from dilute to concentrated solution', 'only when heated', 'together with the solute particles'], 'B',
          'Water moves from where it is more plentiful (dilute) into the more concentrated solution; the membrane stops the solute.'),
    U3.CK('k07', 106, 'Why must a hospital drip have the same osmotic pressure as blood?',
          ['To keep it sterile', 'So red blood cells neither swell and burst nor shrink', 'So it boils at 100 °C', 'To make it flow faster'], 'B',
          'If the drip were more dilute, water would enter the cells (swell, burst); if more concentrated, water would leave them (shrink).'),
    U3.RM('r02', 'Tips', 104,
          'ΔTb uses **molality** (kg of solvent), not molarity.',
          'Count **particles**: 1 mol NaCl ≈ 2 mol particles, 1 mol CaCl₂ ≈ 3 mol, 1 mol sugar = 1 mol.',
          'Osmosis: **water** moves, not the solute. “Water follows salt.”'),
]

U3.M('q1', L3, 79, 'What is the molarity of 500 mL of solution containing 20 g of NaOH (M = 40 g/mol)?', ['0.5 M', '1.0 M', '2.0 M', '0.04 M'], 'B',
     ['Step 1: n = 20 ÷ 40 = 0.50 mol.', 'Step 2: V = 0.500 L.', 'Step 3: M = 0.50 ÷ 0.500 = 1.0 M.'],
     'n = mass ÷ molar mass, then ÷ litres.',
     [('How many grams of NaOH are in 100 mL of 0.5 M NaOH?', '0.05 mol × 40 = 2.0 g.'), ('Find the molarity of 5.85 g NaCl in 250 mL.', '0.10 mol ÷ 0.250 L = 0.40 M.')])
U3.S('q2', L3, 84, '18 g of glucose (M = 180 g/mol) is dissolved in 500 g of water. Find the molality.', '0.20 m',
     ['Step 1: n = 18 ÷ 180 = 0.10 mol.', 'Step 2: solvent = 500 g = 0.500 kg.', 'Step 3: m = 0.10 ÷ 0.500 = 0.20 mol/kg.'],
     'Molality divides by kg of solvent.', [('Find the molality of 4 g NaOH in 250 g water.', '0.10 mol ÷ 0.250 kg = 0.40 m.'), ('What mass of urea (60 g/mol) in 1 kg water gives 0.5 m?', '30 g.')],
     accept=['0.2 m', '0.20 mol/kg', '0.2'])
U3.M('q3', L3, 91, 'The normality of 0.3 M H₃PO₄ (all three H replaceable) is …', ['0.1 N', '0.3 N', '0.6 N', '0.9 N'], 'D',
     ['Step 1: H₃PO₄ has 3 replaceable H.', 'Step 2: N = M × 3 = 0.9 N.'],
     'N = M × (H⁺ or OH⁻ per formula).', [('Normality of 0.5 M Ca(OH)₂?', '1.0 N.'), ('Equivalent mass of H₂SO₄?', '98 ÷ 2 = 49 g.')])
U3.S('q4', L3, 75, 'How many grams of sugar are needed to make 200 g of a 15 % (by mass) sugar solution, and how much water?', '30 g sugar and 170 g water',
     ['Step 1: solute = 15/100 × 200 g = 30 g.', 'Step 2: water = 200 − 30 = 170 g.'],
     'Percent × total mass of solution.', [('What is the mass % of 5 g salt in 45 g water?', '5/50 × 100 = 10 %.'), ('How much ethanol is in 250 mL of 40 % (v/v) solution?', '100 mL.')])
U3.S('q5', L3, 89, 'A 98 % (by mass) H₂SO₄ solution has density 1.84 g/mL. Find its molarity.', '18.4 M',
     ['Step 1: 1 L of solution has mass 1840 g.', 'Step 2: mass of H₂SO₄ = 0.98 × 1840 = 1803 g.', 'Step 3: moles = 1803 ÷ 98 = 18.4 mol in 1 L → 18.4 M.'],
     'Use 1 L of solution and the density.', [('What is the normality of that acid?', '36.8 N.'), ('What volume of it is needed for 1 L of 0.92 M H₂SO₄?', 'M₁V₁ = M₂V₂ → V₁ = 0.92 × 1000 ÷ 18.4 = 50 mL.')],
     accept=['18.4', '18.4 mol/L'])
U3.M('q6', L3b, 104, 'A 0.5 m aqueous solution of a non-electrolyte boils at (Kb water = 0.52 °C kg/mol) …', ['100.26 °C', '100.52 °C', '99.74 °C', '101.04 °C'], 'A',
     ['Step 1: ΔTb = 0.52 × 0.5 = 0.26 °C.', 'Step 2: b.p. = 100 + 0.26 = 100.26 °C.'],
     'Solutions boil higher, never lower.', [('What is ΔTb for a 1 m sugar solution in water?', '0.52 °C.'), ('Which boils higher: 0.1 m NaCl or 0.1 m sugar?', '0.1 m NaCl (twice as many particles).')])
U3.TF('q7', L3b, 106, 'In osmosis, solute particles move through the membrane into the dilute solution.', False,
      ['Step 1: the semi-permeable membrane stops the solute.', 'Step 2: only the solvent (water) moves.', 'Step 3: water moves from the dilute side into the concentrated side.'],
      'Osmosis = movement of solvent.', [('What is osmotic pressure?', 'The pressure needed on the concentrated solution to stop osmosis.'), ('Why does salting fish preserve it?', 'Water leaves germs by osmosis, so they cannot grow.')])
U3.S('q8', L3b, 106, 'Calculate the osmotic pressure of a 0.20 M sucrose solution at 25 °C (R = 0.0821 L·atm/(mol·K)).', '4.9 atm',
     ['Step 1: T = 298 K.', 'Step 2: π = MRT = 0.20 × 0.0821 × 298.', 'Step 3: π = 4.89 ≈ 4.9 atm.'],
     'Always use kelvin.', [('What is π for 0.10 M glucose at 27 °C?', '2.46 atm.'), ('Which has the higher π: 0.1 M glucose or 0.1 M CaCl₂?', 'CaCl₂ (3 particles per formula).')],
     accept=['4.9', '4.89 atm', '4.89'])

# ============================================================== Unit 4 Acids, bases and salts
U4 = Unit('chem10-u4')
L4 = '4.1 Acid–base theories'
DIAG4 = {'cm_acidbase': 'acidbase'}

THEORIES = [
    U4.T('c01', 'Arrhenius theory, step by step', 115,
         '**Acid:** a substance that produces **hydrogen ions, H⁺**, in water. **Base:** a substance that produces **hydroxide ions, OH⁻**, in water.',
         'HCl(aq) → H⁺(aq) + Cl⁻(aq); H₂SO₄(aq) → 2H⁺(aq) + SO₄²⁻(aq); NaOH(aq) → Na⁺(aq) + OH⁻(aq).',
         '**Neutralisation** is then simply H⁺(aq) + OH⁻(aq) → H₂O(l).',
         '**Limitations:** (1) it works only in **water**; (2) it cannot explain why **ammonia, NH₃**, is a base — NH₃ contains no OH; (3) a bare H⁺ does not exist in water — it is attached to a water molecule as **H₃O⁺** (hydronium ion).'),
    U4.T('c02', 'Brønsted–Lowry theory, step by step', 115,
         '**Acid = proton (H⁺) donor. Base = proton (H⁺) acceptor.** An acid–base reaction is a **proton transfer**.',
         '**Step 1 — Find which particle loses an H⁺.** That is the acid. HCl + H₂O → H₃O⁺ + Cl⁻: HCl loses H⁺ → acid; H₂O gains it → base.',
         '**Step 2 — Find the conjugate pairs.** When an acid loses H⁺ it becomes its **conjugate base** (HCl → Cl⁻). When a base gains H⁺ it becomes its **conjugate acid** (H₂O → H₃O⁺). The two members of a pair differ by **exactly one H⁺**.',
         '**Step 3 — Ammonia now makes sense:** NH₃ + H₂O ⇌ NH₄⁺ + OH⁻. NH₃ accepts H⁺ → base; H₂O donates H⁺ → acid.',
         '**Amphiprotic (amphoteric) species** can act as acid or base: H₂O, HCO₃⁻, HSO₄⁻, H₂PO₄⁻.',
         '**Strength rule:** the stronger the acid, the weaker its conjugate base (HCl is strong, Cl⁻ has almost no tendency to take H⁺ back).'),
    U4.T('c03', 'Lewis theory, step by step (extension)', 115,
         'The textbook covers Arrhenius and Brønsted–Lowry. The **Lewis** theory is the broadest and is met again in Grade 12 and university entrance questions:',
         '**Lewis acid = electron-pair acceptor. Lewis base = electron-pair donor.** The product has a new **coordinate (dative) bond**.',
         '**Step 1 — Look for a lone pair.** The particle that gives the lone pair is the base (NH₃, H₂O, OH⁻, F⁻, Cl⁻).',
         '**Step 2 — Look for an empty orbital.** The particle that receives the pair is the acid (H⁺, BF₃, AlCl₃, metal ions such as Ag⁺, Cu²⁺, Fe³⁺).',
         '**Example:** BF₃ + :NH₃ → F₃B←NH₃. BF₃ has only 6 electrons around B, so it accepts the pair; there is no proton at all, so only the Lewis theory calls this an acid–base reaction.',
         'Every Brønsted base is also a Lewis base (it needs a lone pair to take an H⁺), and H⁺ itself is a Lewis acid.'),
    U4.ST('s01', 'Model: the three theories side by side', 115, 'cm_acidbase',
          [('**Arrhenius** — in water: acids give H⁺, bases give OH⁻.', 'ar'),
           ('**Brønsted–Lowry** — the acid gives a proton to the base: HCl + H₂O → H₃O⁺ + Cl⁻.', 'bl'),
           ('**Lewis** — the base gives an electron pair to the acid: NH₃ → BF₃.', 'lw')],
          'Each theory includes everything the one before it explained, and more.'),
    U4.TB('t01', 'Comparison of the three theories', 115,
          ['Theory', 'Acid', 'Base', 'Example', 'Scope / limitation'],
          [['Arrhenius', 'gives H⁺ in water', 'gives OH⁻ in water', 'HCl → H⁺ + Cl⁻; NaOH → Na⁺ + OH⁻', 'water only; cannot explain NH₃'],
           ['Brønsted–Lowry', 'proton (H⁺) donor', 'proton acceptor', 'NH₃ + H₂O ⇌ NH₄⁺ + OH⁻', 'any solvent or gas; needs a proton'],
           ['Lewis (extension)', 'electron-pair acceptor', 'electron-pair donor', 'BF₃ + NH₃ → F₃B–NH₃', 'broadest; no H⁺ needed']]),
    U4.TB('t02', 'Conjugate acid–base pairs (differ by one H⁺)', 116,
          ['Acid', 'Conjugate base', 'Base', 'Conjugate acid'],
          [['HCl', 'Cl⁻', 'H₂O', 'H₃O⁺'], ['H₂SO₄', 'HSO₄⁻', 'NH₃', 'NH₄⁺'], ['HSO₄⁻', 'SO₄²⁻', 'OH⁻', 'H₂O'],
           ['CH₃COOH', 'CH₃COO⁻', 'CO₃²⁻', 'HCO₃⁻'], ['H₂CO₃', 'HCO₃⁻', 'HCO₃⁻', 'H₂CO₃'], ['NH₄⁺', 'NH₃', 'CH₃COO⁻', 'CH₃COOH']],
          'Conjugate base: remove one H and lower the charge by 1. Conjugate acid: add one H and raise the charge by 1.'),
    U4.MN('m01', 'Memory trick: A–B–L', 115, 'Match the first letters:',
          [('A', 'Arrhenius', '**A**queous: H⁺ and OH⁻ in water'), ('B', 'Brønsted–Lowry', '**B**are proton passed from acid to base'), ('L', 'Lewis', '**L**one pair given by the base')]),
    U4.WK('w01', 'Worked example: ammonia in water', 124,
          'For NH₃(aq) + H₂O(l) ⇌ NH₄⁺(aq) + OH⁻(aq), identify the Brønsted acid, base and the two conjugate pairs.',
          ['H₂O loses an H⁺ and becomes OH⁻ → H₂O is the **acid**, OH⁻ its **conjugate base**.',
           'NH₃ gains an H⁺ and becomes NH₄⁺ → NH₃ is the **base**, NH₄⁺ its **conjugate acid**.',
           'Pairs: H₂O/OH⁻ and NH₄⁺/NH₃. Each pair differs by one H⁺.',
           'Arrhenius could not call NH₃ a base (it has no OH); Brønsted–Lowry can.'],
          'Acid H₂O, base NH₃; pairs H₂O/OH⁻ and NH₄⁺/NH₃.'),
    U4.WK('w02', 'Worked example: HCO₃⁻ is amphiprotic', 116,
          'Show with equations that the hydrogen carbonate ion, HCO₃⁻, can act as both a Brønsted acid and a Brønsted base.',
          ['As an **acid** (with OH⁻): HCO₃⁻ + OH⁻ → CO₃²⁻ + H₂O — it donates H⁺; conjugate base CO₃²⁻.',
           'As a **base** (with H₃O⁺): HCO₃⁻ + H₃O⁺ → H₂CO₃ + H₂O — it accepts H⁺; conjugate acid H₂CO₃.',
           'A species that can both donate and accept H⁺ is **amphiprotic**.'],
          'HCO₃⁻ donates H⁺ to OH⁻ and accepts H⁺ from H₃O⁺.'),
    U4.WK('w03', 'Worked example: which theory fits?', 115,
          'Classify each reaction as acid–base under Arrhenius, Brønsted–Lowry and/or Lewis: (a) HCl(aq) + NaOH(aq) → NaCl(aq) + H₂O(l); (b) HCl(g) + NH₃(g) → NH₄Cl(s); (c) BF₃ + F⁻ → BF₄⁻.',
          ['(a) In water, HCl gives H⁺ and NaOH gives OH⁻ → **Arrhenius**; H⁺ is transferred → **Brønsted**; OH⁻ gives a lone pair to H⁺ → **Lewis**. All three.',
           '(b) No water, so not Arrhenius. HCl gives H⁺ to NH₃ → **Brønsted** (and Lewis).',
           '(c) No proton is transferred. F⁻ donates an electron pair to BF₃ → **Lewis only**.'],
          '(a) all three; (b) Brønsted–Lowry and Lewis; (c) Lewis only.'),
    U4.CK('k01', 116, 'What is the conjugate base of H₂SO₄?', ['SO₄²⁻', 'HSO₄⁻', 'H₃SO₄⁺', 'H₂O'], 'B',
          'Remove one H⁺: H₂SO₄ → HSO₄⁻ (charge goes from 0 to −1).'),
    U4.CK('k02', 116, 'What is the conjugate acid of NH₃?', ['NH₂⁻', 'NH₄⁺', 'N₂', 'NH₃⁺'], 'B',
          'Add one H⁺: NH₃ → NH₄⁺.'),
    U4.CK('k03', 115, 'Why does the Arrhenius theory fail for ammonia?',
          ['NH₃ is not soluble', 'NH₃ contains no OH⁻ but still makes a solution basic', 'NH₃ is an acid', 'NH₃ has no hydrogen'], 'B',
          'Arrhenius bases must contain and release OH⁻. NH₃ makes OH⁻ by taking H⁺ from water — explained by Brønsted–Lowry.'),
    U4.CK('k04', 115, 'In BF₃ + NH₃ → F₃B–NH₃, BF₃ acts as a …',
          ['Brønsted acid', 'Lewis acid', 'Lewis base', 'Arrhenius base'], 'B',
          'BF₃ accepts the lone pair of NH₃ → Lewis acid. No proton is involved, so Brønsted does not apply.'),
    U4.RM('r01', 'Tips and common mistakes', 116,
          'A conjugate pair differs by **one** H⁺ only: H₂SO₄/SO₄²⁻ is **not** a pair.',
          'Water can be an acid (with NH₃) or a base (with HCl) — always decide from the reaction.',
          'In exam answers write H₃O⁺ (hydronium) rather than a bare H⁺ when water is involved.'),
]

U4.M('q1', L4, 115, 'According to Brønsted–Lowry, a base is a …', ['proton donor', 'proton acceptor', 'electron-pair acceptor', 'OH⁻ producer only'], 'B',
     ['Step 1: Brønsted–Lowry is about proton (H⁺) transfer.', 'Step 2: the acid donates H⁺; the base accepts it.'],
     'Brønsted = protons; Lewis = electron pairs.', [('What is a Lewis base?', 'An electron-pair donor.'), ('What is an Arrhenius acid?', 'A substance that gives H⁺ in water.')])
U4.S('q2', L4, 116, 'In HNO₃ + H₂O → H₃O⁺ + NO₃⁻, name the acid, the base and both conjugate pairs.',
     'Acid HNO₃, base H₂O; pairs HNO₃/NO₃⁻ and H₃O⁺/H₂O.',
     ['Step 1: HNO₃ loses H⁺ → acid; it becomes NO₃⁻ (conjugate base).', 'Step 2: H₂O gains H⁺ → base; it becomes H₃O⁺ (conjugate acid).'],
     'Track the H⁺: who loses it, who gains it.',
     [('Identify the pairs in CH₃COOH + H₂O ⇌ CH₃COO⁻ + H₃O⁺.', 'CH₃COOH/CH₃COO⁻ and H₃O⁺/H₂O.'), ('In CO₃²⁻ + H₂O ⇌ HCO₃⁻ + OH⁻, which is the base?', 'CO₃²⁻.')])
U4.M('q3', L4, 116, 'Which species is amphiprotic?', ['Cl⁻', 'HCO₃⁻', 'NH₄⁺', 'Na⁺'], 'B',
     ['Step 1: amphiprotic = can donate and accept H⁺.', 'Step 2: HCO₃⁻ can lose H⁺ (→ CO₃²⁻) or gain H⁺ (→ H₂CO₃).'],
     'Look for an ion that still has an H and a negative charge (HCO₃⁻, HSO₄⁻, H₂PO₄⁻) — or water.',
     [('Is water amphiprotic?', 'Yes.'), ('Give the conjugate acid of HSO₄⁻.', 'H₂SO₄.')])
U4.TF('q4', L4, 115, 'Every Arrhenius acid is also a Brønsted–Lowry acid.', True,
      ['Step 1: an Arrhenius acid releases H⁺ in water.', 'Step 2: releasing H⁺ means donating a proton (to water).', 'Step 3: so it is also a Brønsted acid; the reverse is not always true.'],
      'Each newer theory contains the older one.', [('Is every Lewis acid a Brønsted acid?', 'No — BF₃ is a Lewis acid with no proton.'), ('Which theory explains NH₃ as a base?', 'Brønsted–Lowry (and Lewis).')])
U4.S('q5', L4, 115, 'Explain why AlCl₃ is called a Lewis acid.', 'Al in AlCl₃ has only 6 outer electrons and an empty orbital, so it accepts an electron pair (e.g. from Cl⁻ or NH₃).',
     ['Step 1: Al has 3 valence electrons; with three Cl it has 6 around it.', 'Step 2: it has room for one more pair.', 'Step 3: accepting an electron pair = Lewis acid.'],
     'Electron-deficient central atom → Lewis acid.', [('Is NH₃ a Lewis acid or base?', 'Lewis base (lone pair).'), ('Why is H⁺ a Lewis acid?', 'It has an empty orbital and accepts a lone pair.')])

# ============================================================== Unit 5 Energy and chemical reactions
U5 = Unit('chem10-u5')
L5 = '5.1–5.2 Energy changes'
DIAG5 = {'cm_energy': 'energy'}

EXO = [
    U5.T('c01', 'Exothermic or endothermic? Step by step', 158,
         'The **system** is the reacting chemicals; the **surroundings** are everything else (the beaker, the water, the air, your hand).',
         '**Step 1 — Bonds.** Breaking bonds **absorbs** energy; making bonds **releases** energy.',
         '**Step 2 — Compare.** If more energy is released making the new bonds than was absorbed breaking the old ones, the reaction is **exothermic**; otherwise it is **endothermic**.',
         '**Step 3 — Sign of ΔH.** Exothermic: heat leaves the system, **ΔH < 0** (negative), the surroundings get **warmer**. Endothermic: heat enters the system, **ΔH > 0** (positive), the surroundings get **colder**.',
         r'$$\Delta H = H_{\text{products}} - H_{\text{reactants}}$$',
         '**Step 4 — Check with a thermometer:** temperature of the mixture rises → exothermic; falls → endothermic.'),
    U5.TB('t01', 'Everyday examples', 164,
          ['Exothermic (ΔH negative, gets hot)', 'Endothermic (ΔH positive, gets cold or needs heating)'],
          [['Burning butane, wood, charcoal: CH₄ + 2O₂ → CO₂ + 2H₂O, ΔH = −890 kJ', 'Photosynthesis: 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂ (needs sunlight)'],
           ['Respiration in our cells (the reverse of photosynthesis)', 'Thermal decomposition: CaCO₃ → CaO + CO₂, ΔH = +178 kJ (lime kilns)'],
           ['Neutralisation: H⁺ + OH⁻ → H₂O, ΔH = −57.1 kJ', 'Dissolving NH₄NO₃ or NH₄Cl in water (instant cold packs)'],
           ['Slaking quicklime: CaO + H₂O → Ca(OH)₂ (very hot)', 'Electrolysis of water: 2H₂O → 2H₂ + O₂'],
           ['Dissolving NaOH or concentrated H₂SO₄ in water', 'Melting ice, boiling water, sweat evaporating (cools the skin)'],
           ['Rusting of iron, condensation of steam, freezing of water', 'Baking soda + vinegar (the mixture feels cold); cooking an egg']]),
    U5.ST('s01', 'Model: reading an energy-level diagram', 161, 'cm_energy',
          [('**Exothermic:** the products are **lower** than the reactants. The drop is ΔH (negative): energy given out.', 'exo'),
           ('**Endothermic:** the products are **higher** than the reactants. The rise is ΔH (positive): energy taken in.', 'endo'),
           ('**Activation energy, Ea:** from the reactants up to the top of the hump. Even exothermic reactions must climb it first (a match is needed to light gas).', 'ea'),
           ('A **catalyst** gives a lower hump (smaller Ea) but does **not** change ΔH.', 'cat')]),
    U5.T('c02', 'How to draw an energy-level diagram, step by step', 161,
         '1. Draw a vertical axis labelled **energy (enthalpy, H)** and a horizontal axis **reaction progress**.',
         '2. Draw a short line for the **reactants** on the left.',
         '3. Draw the **products** on the right: **lower** for exothermic, **higher** for endothermic. Write the formulas on the lines.',
         '4. Join them with a curve that rises to a **hump** (the activated complex).',
         '5. Add arrows: **Ea** from reactants up to the top of the hump; **ΔH** from reactants to products (pointing down for exothermic, up for endothermic). Write its value with the sign.',
         r'**Reverse reaction:** ΔH changes sign, and \(E_a(\text{reverse}) = E_a(\text{forward}) - \Delta H\).'),
    U5.WK('w01', 'Worked example: burning methane', 170,
          'CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(l), ΔH = −890 kJ/mol. (a) Is it exo- or endothermic? (b) Describe its energy diagram. (c) How much heat is released by burning 8.0 g of methane (M = 16 g/mol)?',
          ['(a) ΔH is negative → **exothermic**.', '(b) Products (CO₂ + 2H₂O) are drawn 890 kJ **below** the reactants (CH₄ + 2O₂), with a hump between them; ΔH arrow points down.',
           r'(c) Moles of CH₄ = \(\dfrac{8.0}{16} = 0.50\text{ mol}\)', r'Heat released = \(0.50 \times 890 = 445\text{ kJ}\)'],
          'Exothermic; 445 kJ released'),
    U5.WK('w02', 'Worked example: nitrogen monoxide', 170,
          'N₂(g) + O₂(g) → 2NO(g), ΔH = +180 kJ. (a) Exo or endo? (b) What is ΔH for 2NO → N₂ + O₂? (c) Why does NO form in a car engine or during lightning but not in ordinary air?',
          ['(a) ΔH positive → **endothermic**; the products are 180 kJ above the reactants.', '(b) The reverse reaction has the opposite sign: ΔH = −180 kJ.',
           '(c) The reaction needs a large energy input (and a high Ea); the very high temperatures in engines and lightning supply it.'],
          'Endothermic; reverse ΔH = −180 kJ; needs very high temperature.'),
    U5.WK('w03', 'Worked example: numbers from a diagram', 162,
          'On an energy diagram the reactants are at 50 kJ, the top of the hump at 150 kJ and the products at 20 kJ. Find Ea, ΔH and Ea of the reverse reaction.',
          ['Ea (forward) = 150 − 50 = 100 kJ', 'ΔH = H(products) − H(reactants) = 20 − 50 = −30 kJ (exothermic)', 'Ea (reverse) = 150 − 20 = 130 kJ'],
          'Ea = 100 kJ, ΔH = −30 kJ, Ea(reverse) = 130 kJ'),
    U5.CK('k01', 164, 'Ammonium nitrate dissolves in water and the beaker feels cold. The process is …',
          ['exothermic, ΔH negative', 'endothermic, ΔH positive', 'exothermic, ΔH positive', 'neither'], 'B',
          'Heat is taken from the surroundings (beaker feels cold) → endothermic, ΔH > 0.'),
    U5.CK('k02', 161, 'On an energy diagram of an exothermic reaction, the products are …',
          ['higher than the reactants', 'lower than the reactants', 'at the top of the hump', 'at the same level'], 'B',
          'Energy is given out, so the products have less enthalpy than the reactants.'),
    U5.CK('k03', 162, 'A catalyst changes …', ['ΔH only', 'Ea only', 'both Ea and ΔH', 'neither'], 'B',
          'A catalyst provides a lower-energy pathway (lower Ea); the start and end levels — and so ΔH — stay the same.'),
]

HEATS = [
    U5.T('c03', 'Types of heat of reaction, step by step', 175,
         'Each “heat of …” is ΔH for a stated process and a stated amount — usually **1 mol** of the substance named. Read the definition carefully: it tells you what goes on the left and right of the equation.',
         '**Heat of combustion:** heat released when **1 mol** of a substance burns **completely** in oxygen. Always **negative**. CH₄(g) + 2O₂(g) → CO₂(g) + 2H₂O(l), ΔH = −890 kJ/mol.',
         '**Heat of solution:** enthalpy change when **1 mol** of a substance dissolves in a large amount of water. Can be **negative** (NaOH, about −44 kJ/mol) or **positive** (NH₄NO₃, about +26 kJ/mol).',
         '**Heat of neutralisation:** heat released when an acid and a base react to form **1 mol of water**. For any strong acid + strong base: H⁺(aq) + OH⁻(aq) → H₂O(l), ΔH = **−57.1 kJ/mol**. A weak acid gives a smaller value because some energy is used to ionise it.',
         '**Heat of formation:** enthalpy change when **1 mol of a compound** forms from its **elements** in their standard states. C(s) + O₂(g) → CO₂(g), ΔH = −393 kJ/mol; C(s) + 2S(s) → CS₂(l), ΔH = +117 kJ/mol. The heat of formation of an element is zero.',
         '**Heat of fusion:** heat **absorbed** when 1 mol of solid melts at its melting point. H₂O(s) → H₂O(l), ΔH = +6.01 kJ/mol.',
         '**Heat of vaporisation:** heat **absorbed** when 1 mol of liquid turns into vapour at its boiling point. H₂O(l) → H₂O(g), ΔH = +40.7 kJ/mol.'),
    U5.TB('t02', 'Types of heat of reaction (textbook 5.2)', 175,
          ['Type', 'Per …', 'Sign', 'Example'],
          [['Combustion', '1 mol of fuel burned completely', 'always −', 'CH₄: −890 kJ/mol'],
           ['Solution', '1 mol of solute dissolved', '− or +', 'NaOH: −44; NH₄NO₃: +26 kJ/mol'],
           ['Neutralisation', '1 mol of water formed', '−', 'strong acid + strong base: −57.1 kJ/mol'],
           ['Formation', '1 mol of compound from elements', '− or +', 'CO₂: −393; CS₂: +117 kJ/mol'],
           ['Fusion', '1 mol of solid melted', '+', 'ice: +6.01 kJ/mol'],
           ['Vaporisation', '1 mol of liquid vaporised', '+', 'water: +40.7 kJ/mol']]),
    U5.WK('w04', 'Worked example: heat of neutralisation', 175,
          '50 mL of 1.0 M HCl is mixed with 50 mL of 1.0 M NaOH. How much heat is released? (ΔH neutralisation = −57.1 kJ/mol)',
          [r'Moles of H⁺ = \(1.0 \times 0.050 = 0.050\text{ mol}\); moles of OH⁻ = 0.050 mol', 'Water formed = 0.050 mol',
           r'Heat released = \(0.050 \times 57.1 = 2.86\text{ kJ}\)'],
          '≈ 2.9 kJ released'),
    U5.WK('w05', 'Worked example: which type is it?', 176,
          'Name the type of heat change: (a) H₂(g) + ½O₂(g) → H₂O(l), ΔH = −286 kJ; (b) KOH(aq) + HNO₃(aq) → KNO₃(aq) + H₂O(l), ΔH = −57.1 kJ; (c) H₂O(l) → H₂O(g), ΔH = +40.7 kJ.',
          ['(a) 1 mol of a compound (water) from its elements → **heat of formation** of water. (It is also the heat of combustion of hydrogen — 1 mol of H₂ burns.)',
           '(b) Acid + base → 1 mol water → **heat of neutralisation**.', '(c) Liquid → vapour, 1 mol → **heat of vaporisation**.'],
          '(a) formation (= combustion of H₂); (b) neutralisation; (c) vaporisation'),
    U5.MN('m01', 'Memory trick: changes of state', 176,
          '**Melting, boiling, evaporating, subliming take heat IN (+). Freezing, condensing take heat OUT (−).** Think of an ice cube melting in your hand: your hand feels cold because the ice takes heat in.'),
    U5.CK('k04', 175, 'The heat of combustion of a substance is always …', ['positive', 'negative', 'zero', 'either sign'], 'B',
          'Burning releases heat, so ΔH of combustion is always negative.'),
    U5.CK('k05', 175, 'The heat of neutralisation of any strong acid by any strong base is about −57.1 kJ/mol because …',
          ['all salts are the same', 'the reaction is always H⁺ + OH⁻ → H₂O', 'water boils', 'the acids are concentrated'], 'B',
          'Strong acids and bases are fully ionised; the other ions are spectators, so the only reaction is H⁺ + OH⁻ → H₂O.'),
    U5.RM('r01', 'Tips', 175,
          'Check the “1 mol of …” in each definition: combustion = 1 mol of fuel; formation = 1 mol of compound; neutralisation = 1 mol of water.',
          'Heats of fusion and vaporisation are **positive**; the reverse changes (freezing, condensing) have the same numbers with a **negative** sign.',
          'Always give the sign and the unit (kJ/mol) with a ΔH value.'),
]

U5.M('q1', L5, 158, 'Which process is endothermic?', ['Burning charcoal', 'Neutralisation of HCl by NaOH', 'Thermal decomposition of CaCO₃', 'Slaking quicklime'], 'C',
     ['Step 1: burning, neutralising and slaking all give out heat.', 'Step 2: CaCO₃ must be heated strongly to decompose → absorbs heat → endothermic (ΔH = +178 kJ).'],
     'Needs continuous heating → endothermic.', [('Is photosynthesis exo- or endothermic?', 'Endothermic (absorbs light energy).'), ('Is respiration exo- or endothermic?', 'Exothermic.')])
U5.S('q2', L5, 162, 'On an energy diagram the reactants are at 120 kJ, the peak at 200 kJ and the products at 160 kJ. Find Ea, ΔH and say whether the reaction is exo- or endothermic.',
     'Ea = 80 kJ; ΔH = +40 kJ; endothermic',
     ['Step 1: Ea = 200 − 120 = 80 kJ.', 'Step 2: ΔH = 160 − 120 = +40 kJ.', 'Step 3: positive ΔH → endothermic.'],
     'ΔH = products − reactants.', [('What is Ea of the reverse reaction?', '200 − 160 = 40 kJ.'), ('A catalyst lowers the peak to 170 kJ. What is ΔH now?', 'Still +40 kJ.')])
U5.M('q3', L5, 176, 'C(s) + O₂(g) → CO₂(g), ΔH = −393 kJ/mol is the heat of …', ['fusion', 'neutralisation', 'formation of CO₂', 'solution'], 'C',
     ['Step 1: one mole of a compound (CO₂) is formed from its elements (C and O₂).', 'Step 2: that is the definition of heat of formation (it is also the heat of combustion of carbon).'],
     'Elements on the left, 1 mol compound on the right → formation.', [('What is the heat of formation of O₂(g)?', 'Zero — it is an element.'), ('Is the heat of formation of CS₂ positive or negative?', 'Positive, +117 kJ/mol.')])
U5.S('q4', L5, 170, 'How much heat is released when 4.0 g of methane burns? (CH₄ = 16 g/mol, ΔH combustion = −890 kJ/mol)', '222.5 kJ',
     ['Step 1: n = 4.0 ÷ 16 = 0.25 mol.', 'Step 2: heat = 0.25 × 890 = 222.5 kJ released.'],
     'Moles × |ΔH|.', [('How much heat is needed to melt 36 g of ice? (ΔH fus = 6.01 kJ/mol)', '2 mol × 6.01 = 12.0 kJ.'), ('How much heat is needed to vaporise 9 g of water? (40.7 kJ/mol)', '0.5 × 40.7 = 20.4 kJ.')],
     accept=['222.5', '222 kJ', '223 kJ', '2.2 × 10² kJ'])
U5.TF('q5', L5, 162, 'A catalyst makes an exothermic reaction release more heat.', False,
      ['Step 1: a catalyst lowers Ea only.', 'Step 2: the reactant and product levels do not change, so ΔH is unchanged.'],
      'Catalyst: faster, not more energy.', [('What does a catalyst change on an energy diagram?', 'The height of the hump (Ea).'), ('Does a catalyst change the products?', 'No.')])

BLOCKS = [
    ('chem10-u2-l2-2', 'chem10-u2-c04', POLAR),
    ('chem10-u2-l2-3', 'chem10-u2-c08', LONDON),
    ('chem10-u3-l3-2', 'chem10-u3-c07', CONC),
    ('chem10-u3-l3-3', 'chem10-u3-c12', COLLIG),
    ('chem10-u4-l4-1', 'chem10-u4-c02', THEORIES),
    ('chem10-u5-l5-1', 'chem10-u5-c05', EXO),
    ('chem10-u5-l5-2', 'chem10-u5-c08', HEATS),
]
UNITS = {'chem10-u2': (U2, DIAG2), 'chem10-u3': (U3, DIAG3), 'chem10-u4': (U4, DIAG4), 'chem10-u5': (U5, DIAG5)}
GLOSSARY = {
    'chem10-u2': [('Polar molecule', 'A molecule with an overall δ+ end and δ− end because its bond dipoles do not cancel.', 46),
                  ('London (dispersion) forces', 'Weak attractions between instantaneous and induced dipoles; present between all molecules.', 53)],
    'chem10-u3': [('Molality', 'Moles of solute per kilogram of solvent (mol/kg).', 84), ('Normality', 'Equivalents of solute per litre of solution; N = M × replaceable H⁺ or OH⁻.', 86),
                  ('Boiling point elevation', 'The rise in boiling point of a solvent when a non-volatile solute is dissolved; ΔTb = Kb·m.', 103),
                  ('Osmotic pressure', 'The pressure needed on a solution to stop osmosis of pure solvent into it.', 106)],
    'chem10-u4': [('Conjugate acid–base pair', 'An acid and the base formed when it loses one H⁺ (e.g. NH₄⁺/NH₃).', 116), ('Lewis acid', 'An electron-pair acceptor (e.g. BF₃, H⁺).', 115),
                  ('Amphiprotic', 'Able to act as both a proton donor and a proton acceptor (H₂O, HCO₃⁻).', 116)],
    'chem10-u5': [('Heat of formation', 'ΔH when 1 mol of a compound forms from its elements in their standard states.', 176), ('Heat of neutralisation', 'Heat released when an acid and a base form 1 mol of water.', 175)],
}
