r"""Grade 11 additions: Unit 1 law of mass action + Le Chatelier (pressure, concentration), Unit 3 carbon allotropes + carbonic
acid, Unit 4 activity series, Unit 5 ideal gas equation derivation, PM = dRT and van der Waals."""
from common import Unit

# ============================================================== Unit 1 Rate and equilibrium
U1 = Unit('chem11-u1')
L1 = '1.2 Equilibrium: mass action and Le Chatelier'
DIAG1 = {'cm_press': 'press', 'cm_conc': 'conc'}

MASS = [
    U1.T('c01', 'The law of mass action, step by step', 19,
         '**Law of mass action** (Guldberg and Waage, 1864): at constant temperature, the rate of a reaction is proportional to the product of the molar concentrations of the reactants, each raised to the power of its coefficient in the balanced equation.',
         r'**Step 1 — Write both rates** for \(a\text{A} + b\text{B} \rightleftharpoons c\text{C} + d\text{D}\):',
         r'$$\text{rate}_f = k_f[\text{A}]^a[\text{B}]^b \qquad \text{rate}_b = k_b[\text{C}]^c[\text{D}]^d$$',
         r'**Step 2 — At equilibrium the two rates are equal:** \(k_f[\text{A}]^a[\text{B}]^b = k_b[\text{C}]^c[\text{D}]^d\).',
         r'**Step 3 — Collect the constants on one side:**',
         r'$$K_c = \frac{k_f}{k_b} = \frac{[\text{C}]^c[\text{D}]^d}{[\text{A}]^a[\text{B}]^b}$$',
         '**Rules for writing Kc:** products on top, reactants below; each concentration (in mol/L) raised to its coefficient; concentrations are the **equilibrium** values. For gases you may use partial pressures instead → **Kp**. Pure solids and pure liquids are left out (their “concentration” is constant).',
         '**Kc changes only with temperature** — not with concentration, pressure or a catalyst.',
         '**Size of K:** K ≫ 1 → mostly products at equilibrium; K ≪ 1 → mostly reactants; K ≈ 1 → appreciable amounts of both.'),
    U1.T('c02', 'Reaction quotient Q: which way will it go?', 20,
         'Q is calculated exactly like K but with the concentrations **at any moment** (not necessarily at equilibrium). Compare Q with K:',
         '**Q < K** → too little product → net reaction goes **forward (to the right)**.',
         '**Q = K** → at equilibrium → no net change.',
         '**Q > K** → too much product → net reaction goes **backward (to the left)**.'),
    U1.WK('w01', 'Worked example: writing Kc expressions', 19,
          'Write Kc for (a) H₂(g) + I₂(g) ⇌ 2HI(g); (b) 2SO₂(g) + O₂(g) ⇌ 2SO₃(g); (c) N₂O₄(g) ⇌ 2NO₂(g); (d) CaCO₃(s) ⇌ CaO(s) + CO₂(g).',
          [r'(a) \(K_c = \dfrac{[\text{HI}]^2}{[\text{H}_2][\text{I}_2]}\)',
           r'(b) \(K_c = \dfrac{[\text{SO}_3]^2}{[\text{SO}_2]^2[\text{O}_2]}\)',
           r'(c) \(K_c = \dfrac{[\text{NO}_2]^2}{[\text{N}_2\text{O}_4]}\)',
           r'(d) Solids are left out: \(K_c = [\text{CO}_2]\)'],
          'Products over reactants, powers = coefficients, no solids or pure liquids.'),
    U1.WK('w02', 'Worked example: calculating Kc (textbook p.19)', 19,
          'For N₂(g) + 3H₂(g) ⇌ 2NH₃(g) at equilibrium: [N₂] = 3.0 × 10⁻² M, [H₂] = 3.7 × 10⁻² M, [NH₃] = 1.6 × 10⁻² M. Calculate Kc.',
          [r'\(K_c = \dfrac{[\text{NH}_3]^2}{[\text{N}_2][\text{H}_2]^3}\)',
           r'Top: \((1.6\times10^{-2})^2 = 2.56\times10^{-4}\)',
           r'Bottom: \((3.0\times10^{-2})(3.7\times10^{-2})^3 = (3.0\times10^{-2})(5.07\times10^{-5}) = 1.52\times10^{-6}\)',
           r'\(K_c = \dfrac{2.56\times10^{-4}}{1.52\times10^{-6}} = 1.68\times10^{2}\)'],
          'Kc = 1.68 × 10²'),
    U1.WK('w03', 'Worked example: finding an equilibrium concentration', 20,
          'Same reaction, same temperature (Kc = 1.68 × 10²). At equilibrium [N₂] = 6.0 × 10⁻² M and [H₂] = 5.6 × 10⁻² M. Find [NH₃].',
          [r'Let \([\text{NH}_3] = x\): \(1.68\times10^{2} = \dfrac{x^2}{(6.0\times10^{-2})(5.6\times10^{-2})^3}\)',
           r'Bottom: \((6.0\times10^{-2})(1.76\times10^{-4}) = 1.05\times10^{-5}\)',
           r'\(x^2 = 1.68\times10^{2} \times 1.05\times10^{-5} = 1.77\times10^{-3}\)',
           r'\(x = \sqrt{1.77\times10^{-3}} = 4.21\times10^{-2}\text{ M}\)'],
          '[NH₃] = 4.21 × 10⁻² M'),
    U1.WK('w04', 'Worked example: Q vs K (textbook p.21)', 21,
          'For N₂ + 3H₂ ⇌ 2NH₃, Kc = 1.7 × 10². A mixture has [N₂] = 2.0 × 10⁻² M, [H₂] = 3.5 × 10⁻² M, [NH₃] = 2.0 × 10⁻² M. Is it at equilibrium? If not, which way does it shift?',
          [r'\(Q_c = \dfrac{(2.0\times10^{-2})^2}{(2.0\times10^{-2})(3.5\times10^{-2})^3} = \dfrac{4.00\times10^{-4}}{8.58\times10^{-7}}\)',
           r'\(Q_c = 4.66\times10^{2}\)', 'Qc (466) > Kc (170): too much product.', 'Net reaction goes to the **left**: some NH₃ decomposes until Q = K.'],
          'Not at equilibrium; shifts left.'),
    U1.CK('k01', 19, 'For 2NO(g) + O₂(g) ⇌ 2NO₂(g), Kc = …',
          ['[NO₂]/([NO][O₂])', '[NO₂]²/([NO]²[O₂])', '[NO]²[O₂]/[NO₂]²', '2[NO₂]/(2[NO][O₂])'], 'B',
          'Products over reactants, each raised to its coefficient: [NO₂]² over [NO]²[O₂].'),
    U1.CK('k02', 20, 'If Q > K for a reaction mixture, the reaction will …',
          ['shift right', 'shift left', 'stay the same', 'stop'], 'B',
          'Q > K means there is more product than at equilibrium, so the backward reaction wins until Q falls to K.'),
]

CHAT = [
    U1.T('c03', 'Le Chatelier’s principle, step by step', 22,
         '**Le Chatelier’s principle:** if a stress is applied to a system at equilibrium, the system shifts so as to **reduce (oppose) the stress** and reaches a new equilibrium position.',
         '**Step 1 — Name the stress:** more or less of a substance (concentration), higher or lower pressure (volume), higher or lower temperature.',
         '**Step 2 — Ask how the system can undo it:** use up what was added; replace what was removed; reduce a pressure increase by making fewer gas molecules.',
         '**Step 3 — State the direction:** “shifts to the right (forward)” or “to the left (backward)”.',
         '**Step 4 — State the result:** what happens to the amount of each substance, the colour, the yield.',
         '**Concentration:** add a reactant or remove a product → shifts **right**; add a product or remove a reactant → shifts **left**. Kc does **not** change.',
         '**Pressure (gases only):** count the **moles of gas** on each side. Increase pressure (decrease volume) → shift to the side with **fewer** gas moles; decrease pressure → side with **more** gas moles. Equal gas moles on both sides → **no shift**. Kc does not change.',
         '**Also remember:** raising the temperature shifts an equilibrium in the **endothermic** direction (this *does* change K); a catalyst does **not** shift the equilibrium — it only helps reach it faster.'),
    U1.SS('s01', 'Model: squeezing N₂O₄ ⇌ 2NO₂', 23, 'cm_press',
          [('a', 'Equilibrium', 'Colourless N₂O₄ and brown NO₂ in a gas syringe at equilibrium: 1 mol gas on the left, 2 mol gas on the right.'),
           ('b', 'Squeeze', 'Push the plunger in: half the volume, double the pressure. The gas looks darker at first (more crowded).'),
           ('c', 'New equilibrium', 'The system reduces the pressure by forming the side with **fewer gas molecules**: 2NO₂ → N₂O₄. Fewer particles, the colour fades a little — shifted **left**.')],
          'Slide to apply the stress and watch the response.'),
    U1.ST('s02', 'Model: adding N₂ to the ammonia equilibrium', 22, 'cm_conc',
          [('**N₂ is added**: its concentration jumps, then falls as some of it reacts — but it stays higher than before.', 'n2'),
           ('**H₂ is used up** with the extra N₂, so its concentration falls.', 'h2'),
           ('**More NH₃ forms**: the equilibrium has shifted to the **right**. Kc is the same at the new equilibrium.', 'nh3')]),
    U1.TB('t01', 'Effect of concentration (textbook p.23)', 23,
          ['Change', 'Shift', 'Example: N₂ + 3H₂ ⇌ 2NH₃'],
          [['Add reactant', 'right', 'add N₂ or H₂ → more NH₃'], ['Remove reactant', 'left', 'remove H₂ → NH₃ decomposes'],
           ['Add product', 'left', 'add NH₃ → more N₂ and H₂'], ['Remove product', 'right', 'liquefy and remove NH₃ → more NH₃ forms']]),
    U1.TB('t02', 'Effect of pressure: count the gas moles', 23,
          ['Reaction', 'Gas moles left → right', 'Increase pressure shifts', 'Decrease pressure shifts'],
          [['N₂ + 3H₂ ⇌ 2NH₃', '4 → 2', 'right', 'left'], ['2SO₂ + O₂ ⇌ 2SO₃', '3 → 2', 'right', 'left'],
           ['N₂O₄ ⇌ 2NO₂', '1 → 2', 'left', 'right'], ['H₂ + I₂ ⇌ 2HI', '2 → 2', 'no shift', 'no shift'],
           ['CaCO₃(s) ⇌ CaO(s) + CO₂(g)', '0 → 1', 'left', 'right']],
          'Only gases count — ignore solids and liquids when counting moles.'),
    U1.WK('w05', 'Worked example: why pressure shifts the ammonia equilibrium (using Q)', 23,
          'Show with Q why halving the volume of an equilibrium mixture of N₂ + 3H₂ ⇌ 2NH₃ shifts it to the right.',
          [r'At equilibrium \(Q = K = \dfrac{[\text{NH}_3]^2}{[\text{N}_2][\text{H}_2]^3}\).',
           'Halving the volume **doubles** every concentration at that instant.',
           r'New \(Q = \dfrac{(2[\text{NH}_3])^2}{(2[\text{N}_2])(2[\text{H}_2])^3} = \dfrac{4}{16}K = \dfrac{K}{4}\)',
           'Q < K → the reaction goes forward (right) until Q rises back to K — more NH₃, fewer gas molecules, lower pressure.'],
          'Q drops to K/4, so the equilibrium shifts right.'),
    U1.WK('w06', 'Worked example: predicting shifts', 23,
          'Predict the shift: (a) adding H₂ to H₂(g) + I₂(g) ⇌ 2HI(g); (b) increasing pressure on the same system; (c) removing O₂ from 2SO₂ + O₂ ⇌ 2SO₃; (d) decreasing pressure on PCl₅(g) ⇌ PCl₃(g) + Cl₂(g).',
          ['(a) A reactant is added → the system uses it up → shifts **right**; more HI, less I₂ (the purple colour fades).',
           '(b) 2 gas moles on each side → **no shift** (pressure has no effect).',
           '(c) A reactant is removed → the system replaces it → shifts **left**; SO₃ decomposes.',
           '(d) Lower pressure → side with **more** gas moles (1 → 2) → shifts **right**; more PCl₃ and Cl₂.'],
          '(a) right; (b) no shift; (c) left; (d) right.'),
    U1.WK('w07', 'Worked example: colour changes', 22,
          'Yellow chromate turns orange dichromate in acid: 2CrO₄²⁻(aq) + 2H⁺(aq) ⇌ Cr₂O₇²⁻(aq) + H₂O(l). What colour do you see when (a) acid is added, (b) NaOH is added?',
          ['(a) More H⁺ (a reactant) → shift **right** → more orange Cr₂O₇²⁻ → the solution turns **orange**.',
           '(b) OH⁻ removes H⁺ (H⁺ + OH⁻ → H₂O) → a reactant is removed → shift **left** → more yellow CrO₄²⁻ → **yellow**.'],
          '(a) orange; (b) yellow.'),
    U1.MN('m01', 'Memory trick', 22, '**“The system is stubborn — it always does the opposite.”** Add something → it uses it up. Take something away → it makes more. Squeeze it → it makes fewer gas molecules.'),
    U1.CK('k03', 23, 'Increasing the pressure on 2SO₂(g) + O₂(g) ⇌ 2SO₃(g) will …',
          ['shift it left', 'shift it right', 'not affect it', 'change Kc'], 'B',
          '3 gas moles on the left, 2 on the right: higher pressure favours fewer moles → right.'),
    U1.CK('k04', 23, 'Pressure has no effect on the position of which equilibrium?',
          ['N₂ + 3H₂ ⇌ 2NH₃', 'N₂O₄ ⇌ 2NO₂', 'H₂ + Cl₂ ⇌ 2HCl', '2SO₂ + O₂ ⇌ 2SO₃'], 'C',
          'H₂ + Cl₂ ⇌ 2HCl has 2 gas moles on each side, so changing pressure cannot reduce the number of molecules.'),
    U1.CK('k05', 22, 'Ammonia is removed from N₂ + 3H₂ ⇌ 2NH₃ as it forms. The effect is …',
          ['less NH₃ forms', 'the equilibrium shifts right and the yield increases', 'Kc increases', 'nothing happens'], 'B',
          'Removing a product makes the system replace it → shift right → higher yield. Kc stays the same at constant temperature.'),
    U1.RM('r01', 'Tips and common mistakes', 23,
          'Concentration and pressure changes move the **position**, not the **value** of K. Only temperature changes K.',
          'Count only **gas** moles for pressure questions.',
          'A catalyst never shifts an equilibrium.',
          'Use the full phrase in answers: “the equilibrium shifts to the right to oppose the increase in …”.'),
]

U1.M('q1', L1, 19, 'For H₂(g) + I₂(g) ⇌ 2HI(g) at equilibrium, [H₂] = [I₂] = 0.10 M and [HI] = 0.70 M. Kc = …', ['7.0', '49', '70', '0.020'], 'B',
     ['Step 1: Kc = [HI]² / ([H₂][I₂]).', 'Step 2: = 0.49 / 0.010 = 49.'],
     'Square [HI] because its coefficient is 2.', [('What is Kc for the reverse reaction 2HI ⇌ H₂ + I₂?', '1/49 ≈ 0.020.'), ('If Kc is large, are reactants or products favoured?', 'Products.')])
U1.S('q2', L1, 20, 'For a reaction Kc = 4.0. A mixture has Qc = 10. In which direction will the reaction proceed? Explain.', 'To the left (backward), because Qc > Kc: there is too much product.',
     ['Step 1: compare Q with K: 10 > 4.0.', 'Step 2: Q > K means the ratio products/reactants is too large.', 'Step 3: the backward reaction is faster until Q falls to 4.0.'],
     'Q < K → right; Q > K → left.', [('Qc = 1.0 and Kc = 4.0: which way?', 'To the right.'), ('What is true when Qc = Kc?', 'The system is at equilibrium.')])
U1.M('q3', L1, 23, 'Decreasing the volume of N₂O₄(g) ⇌ 2NO₂(g) at constant temperature will …',
     ['increase the amount of NO₂', 'increase the amount of N₂O₄', 'have no effect', 'increase Kc'], 'B',
     ['Step 1: smaller volume = higher pressure.', 'Step 2: the system shifts to fewer gas moles (1 mol N₂O₄ vs 2 mol NO₂).', 'Step 3: so more N₂O₄ forms; Kc unchanged.'],
     'Higher pressure → fewer gas moles.', [('What about H₂ + I₂ ⇌ 2HI?', 'No effect — equal gas moles.'), ('Which conditions favour NH₃ in the Haber process?', 'High pressure (and removing NH₃).')])
U1.M('q4', L1, 22, 'In Fe³⁺(aq) + SCN⁻(aq) ⇌ FeSCN²⁺(aq) (blood red), adding more SCN⁻ makes the solution …',
     ['paler', 'a deeper red', 'colourless', 'unchanged'], 'B',
     ['Step 1: SCN⁻ is a reactant.', 'Step 2: adding a reactant shifts the equilibrium right.', 'Step 3: more FeSCN²⁺ → deeper red.'],
     'Add reactant → right.', [('What happens if Fe³⁺ is removed?', 'Shifts left; the red fades.'), ('Does Kc change?', 'No.')])
U1.TF('q5', L1, 22, 'Adding a catalyst to an equilibrium mixture increases the yield of products.', False,
      ['Step 1: a catalyst speeds up the forward and backward reactions equally.', 'Step 2: equilibrium is reached sooner but at the same position.', 'Step 3: so the yield does not change.'],
      'Catalyst: faster, not further.', [('What changes K?', 'Only temperature.'), ('Does increasing [reactant] change Kc?', 'No — it changes the position only.')])
U1.S('q6', L1, 23, 'State the effect of increasing pressure on each: (a) CO(g) + 2H₂(g) ⇌ CH₃OH(g); (b) C(s) + H₂O(g) ⇌ CO(g) + H₂(g).', '(a) shifts right (3 → 1 gas moles); (b) shifts left (1 → 2 gas moles).',
     ['Step 1: count gas moles: (a) 3 left, 1 right; (b) 1 left (carbon is solid), 2 right.', 'Step 2: higher pressure favours the side with fewer gas moles.', 'Step 3: (a) right; (b) left.'],
     'Ignore solids when counting.', [('Effect of lower pressure on (a)?', 'Shifts left.'), ('Effect of adding H₂ to (b)?', 'Shifts left.')])

# ============================================================== Unit 3 Non-metals: carbon
U3 = Unit('chem11-u3')
L3 = '3.2 Carbon: allotropes and carbonic acid'
DIAG3 = {'cm_diamond': 'diamond', 'cm_graphite': 'graphite', 'cm_c60': 'c60'}

ALLO = [
    U3.T('c01', 'The allotropes of carbon, step by step', 72,
         '**Allotropes** are different forms of the same element in the same physical state, with different structures and so different physical properties, but the same chemical properties (all three burn to CO₂). Carbon has three main crystalline allotropes: **diamond, graphite and fullerene**; charcoal, soot and coke are amorphous forms.',
         '**Diamond:** every carbon atom forms **4 strong covalent bonds** to 4 other carbons arranged **tetrahedrally** (109.5°). The bonding continues in all directions → a **giant 3-D covalent network**. All 4 outer electrons are used in bonds.',
         '**Graphite:** every carbon forms **3 covalent bonds** in a flat sheet of **hexagons** (120°). The 4th electron of each atom is **delocalised** (free to move along the sheet). The sheets (layers) are held together only by **weak forces**, so they slide over each other.',
         '**Buckminsterfullerene, C₆₀:** discovered in 1985. 60 carbon atoms form a hollow ball of **12 pentagons and 20 hexagons**, like a football (“buckyball”). Each C bonds to 3 others. It is a **molecule**, not a giant structure — so it is much softer and dissolves in some organic solvents (e.g. benzene, giving a purple solution).'),
    U3.DG('d01', 'Diamond: giant 3-D network', 72, 'cm_diamond', 'Every atom is joined to four others. There are no weak links and no free electrons.'),
    U3.DG('d02', 'Graphite: layers of hexagons', 72, 'cm_graphite', 'Strong bonds inside each layer, weak forces between the layers.'),
    U3.DG('d03', 'Buckminsterfullerene, C₆₀', 73, 'cm_c60', 'A closed cage of 60 atoms: 12 pentagons (one is shaded) surrounded by hexagons.'),
    U3.TB('t01', 'Diamond, graphite and C₆₀ compared', 72,
          ['Property', 'Diamond', 'Graphite', 'C₆₀ (fullerene)'],
          [['Structure', 'giant 3-D covalent network', 'giant layers (2-D sheets)', 'separate C₆₀ molecules'],
           ['Bonds per C atom', '4 (tetrahedral)', '3 (flat, 120°) + 1 delocalised electron', '3'],
           ['Appearance', 'colourless, transparent, sparkles', 'grey-black, shiny, opaque', 'black solid (purple in solution)'],
           ['Hardness', 'hardest natural substance', 'soft, slippery, marks paper', 'soft'],
           ['Electrical conductivity', 'non-conductor', 'good conductor (along the layers)', 'poor (semiconductor)'],
           ['Melting point', 'very high (≈3550 °C)', 'very high (≈3650 °C, sublimes)', 'much lower (sublimes at about 530 °C)'],
           ['Density (g/cm³)', '3.51', '2.26', '1.65'],
           ['Uses', 'jewellery, cutting and drilling tools, glass cutters', 'pencil “lead”, electrodes, lubricant, brushes in motors', 'research: nanotubes, drug delivery, lubricants']]),
    U3.T('c02', 'Structure → property: the reasoning chain', 72,
         '**Hardness:** diamond has strong bonds in every direction → nothing can slide → very hard. Graphite’s layers are joined only by weak forces → layers slide → soft and slippery.',
         '**Conductivity:** graphite has a delocalised electron on every atom that can move along the layers → conducts. Diamond’s electrons are all locked in bonds → insulator.',
         '**Melting point:** to melt diamond or graphite you must break strong **covalent** bonds → both very high. C₆₀ molecules are held by weak forces between molecules → much lower.',
         'Use this chain in every “explain” question: **structure → bonding → property**.'),
    U3.WK('w01', 'Worked example: why does graphite conduct but diamond does not?', 72,
          'Explain why graphite conducts electricity but diamond does not, although both are pure carbon.',
          ['Electricity needs charged particles that can move.', 'Diamond: each C uses all 4 outer electrons in 4 covalent bonds → no free electrons → non-conductor.',
           'Graphite: each C uses only 3 electrons in bonds; the 4th is delocalised along the layer.', 'These delocalised electrons move when a voltage is applied → graphite conducts (along the layers).'],
          'Graphite has delocalised electrons; diamond has none.'),
    U3.WK('w02', 'Worked example: high melting point but soft?', 72,
          'Graphite has a higher melting point than diamond but is very soft. How can both be true?',
          ['Melting graphite means breaking the strong covalent bonds **within** the layers → very high melting point.',
           'Softness depends on the **weak forces between** the layers, which let the layers slide (pencil marks, lubricant).',
           'So different forces control the two properties.'],
          'Strong bonds inside layers (high m.p.); weak forces between layers (soft).'),
    U3.MN('m01', 'Memory trick', 72, '**Diamond = 4 = Fixed** (all electrons in bonds: hard, no current). **Graphite = 3 + 1 free** (layers slide, electrons flow). **C₆₀ = football** (12 pentagons + 20 hexagons).'),
    U3.CK('k01', 72, 'Each carbon atom in diamond is covalently bonded to …', ['2 atoms', '3 atoms', '4 atoms', '6 atoms'], 'C',
          'Diamond: 4 bonds per carbon in a tetrahedral 3-D network.'),
    U3.CK('k02', 72, 'Graphite is used as a lubricant because …',
          ['it is very hard', 'its layers slide over each other easily', 'it conducts electricity', 'it is a molecule'], 'B',
          'Only weak forces hold the layers together, so they slide.'),
    U3.CK('k03', 73, 'Which statement about buckminsterfullerene is correct?',
          ['It is a giant covalent network', 'It contains 60 carbon atoms in 12 pentagons and 20 hexagons', 'It is harder than diamond', 'It has 4 bonds per carbon'], 'B',
          'C₆₀ is a discrete molecule shaped like a football: 12 pentagons + 20 hexagons, 3 bonds per C.'),
]

CARBONIC = [
    U3.T('c03', 'Carbonic acid, step by step', 81,
         '**Formation:** carbon dioxide dissolves slightly in water and some of it reacts: CO₂(g) + H₂O(l) ⇌ H₂CO₃(aq). Carbonic acid exists **only in solution**; it is **weak** and **unstable** — warming or opening a soft-drink bottle drives the CO₂ out.',
         '**Weak acid:** only a small fraction ionises, so it turns blue litmus red **slowly** and only faintly.',
         '**Dibasic (diprotic):** it has two replaceable H and ionises in two steps:',
         r'$$\text{H}_2\text{CO}_3 \rightleftharpoons \text{H}^+ + \text{HCO}_3^- \qquad \text{HCO}_3^- \rightleftharpoons \text{H}^+ + \text{CO}_3^{2-}$$',
         '**Two series of salts:** **hydrogen carbonates** (acid salts, HCO₃⁻), e.g. NaHCO₃, and **carbonates** (normal salts, CO₃²⁻), e.g. Na₂CO₃, CaCO₃.',
         '**Solubility and heat:** Na and K carbonates dissolve in water and are **not** decomposed by heat. Carbonates of Ca, Mg, Zn, Cu … are insoluble and decompose on heating: CaCO₃(s) → CaO(s) + CO₂(g). Hydrogen carbonates decompose easily: 2NaHCO₃(s) → Na₂CO₃(s) + H₂O(g) + CO₂(g) (why baking soda makes dough rise).',
         '**Everyday links:** soda water and soft drinks; normal rain is slightly acidic (pH ≈ 5.6) because of dissolved CO₂; rain with CO₂ slowly dissolves limestone: CaCO₃ + H₂O + CO₂ → Ca(HCO₃)₂ (caves, temporary hardness of water).'),
    U3.TB('t02', 'Salts of carbonic acid', 81,
          ['Salt', 'Formula', 'Type', 'Soluble in water?', 'On heating'],
          [['Sodium carbonate (washing soda)', 'Na₂CO₃', 'normal', 'yes', 'no change'],
           ['Sodium hydrogen carbonate (baking soda)', 'NaHCO₃', 'acid salt', 'yes (moderately)', '→ Na₂CO₃ + H₂O + CO₂'],
           ['Calcium carbonate (limestone, marble)', 'CaCO₃', 'normal', 'no', '→ CaO + CO₂'],
           ['Calcium hydrogen carbonate', 'Ca(HCO₃)₂', 'acid salt', 'yes (only in solution)', '→ CaCO₃ + H₂O + CO₂'],
           ['Copper(II) carbonate', 'CuCO₃', 'normal', 'no', '→ CuO (black) + CO₂']]),
    U3.WK('w03', 'Worked example: CO₂ into sodium hydroxide', 81,
          'Carbon dioxide is bubbled into sodium hydroxide solution, first a little, then in excess. Write the equations.',
          ['Little CO₂ (NaOH in excess) → the normal salt: 2NaOH + CO₂ → Na₂CO₃ + H₂O',
           'Excess CO₂ → the acid salt: Na₂CO₃ + H₂O + CO₂ → 2NaHCO₃', 'Overall with excess CO₂: NaOH + CO₂ → NaHCO₃'],
          'Na₂CO₃ first, then NaHCO₃ with excess CO₂ — two salts because H₂CO₃ is dibasic.'),
    U3.WK('w04', 'Worked example: the limewater test', 80,
          'Explain why limewater turns milky with CO₂ and then clears again if CO₂ is bubbled for a long time.',
          ['Limewater is calcium hydroxide solution.', 'CO₂ + Ca(OH)₂ → CaCO₃(s) + H₂O: insoluble white CaCO₃ makes it **milky**.',
           'Excess CO₂: CaCO₃ + H₂O + CO₂ → Ca(HCO₃)₂, which is **soluble** → the solution clears.'],
          'Milky = CaCO₃; clears = soluble Ca(HCO₃)₂.'),
    U3.CK('k04', 81, 'Carbonic acid is described as dibasic because it …',
          ['is a strong acid', 'has two replaceable hydrogen atoms and forms two series of salts', 'contains two oxygen atoms', 'reacts with two bases only'], 'B',
          'H₂CO₃ can lose one H (→ HCO₃⁻, acid salts) or both (→ CO₃²⁻, normal salts).'),
    U3.CK('k05', 81, 'Which carbonate is NOT decomposed by heating in a Bunsen flame?', ['CaCO₃', 'CuCO₃', 'Na₂CO₃', 'ZnCO₃'], 'C',
          'Carbonates of sodium and potassium are stable to heat; carbonates of less reactive metals decompose to the oxide and CO₂.'),
    U3.RM('r01', 'Tips', 81,
          'Write carbonic acid formation with ⇌: CO₂ + H₂O ⇌ H₂CO₃ (it is reversible and unstable).',
          'Acid salt = still has replaceable H (NaHCO₃); normal salt = all H replaced (Na₂CO₃).',
          'Higher in the activity series → more stable carbonate.'),
]

U3.M('q1', L3, 72, 'Diamond does not conduct electricity because …',
     ['it has no free (delocalised) electrons', 'its atoms are ions', 'it has weak bonds', 'it is a liquid'], 'A',
     ['Step 1: conduction needs mobile charged particles.', 'Step 2: all 4 outer electrons of each C are used in covalent bonds.', 'Step 3: none are free to move.'],
     'Graphite has 1 free electron per atom; diamond has none.', [('Why does graphite conduct?', 'Delocalised electrons move along its layers.'), ('Which allotrope is used in electrodes?', 'Graphite.')])
U3.M('q2', L3, 73, 'Buckminsterfullerene differs from diamond and graphite in that it is …',
     ['made of different atoms', 'a simple molecular substance', 'an ionic solid', 'a metal'], 'B',
     ['Step 1: diamond and graphite are giant structures.', 'Step 2: C₆₀ is a discrete molecule of 60 atoms.', 'Step 3: so it has a lower melting point and dissolves in some organic solvents.'],
     'Giant structure → very high m.p.; molecule → lower m.p.', [('How many pentagons are in C₆₀?', '12 (and 20 hexagons).'), ('When was C₆₀ discovered?', '1985.')])
U3.S('q3', L3, 72, 'Explain why graphite is soft but diamond is very hard.', 'Graphite’s layers are held by weak forces and slide; diamond has strong covalent bonds in all three directions so nothing can slide.',
     ['Step 1: graphite — strong bonds within layers, weak forces between layers.', 'Step 2: layers slide → soft.', 'Step 3: diamond — every atom bonded to 4 others in a 3-D network → very hard.'],
     'Structure → bonding → property.', [('Why is diamond used in drill tips?', 'It is the hardest natural substance.'), ('Why do both have high melting points?', 'Melting breaks strong covalent bonds.')])
U3.S('q4', L3, 81, 'Write equations to show that carbonic acid forms two kinds of sodium salts.', '2NaOH + H₂CO₃ → Na₂CO₃ + 2H₂O (normal salt); NaOH + H₂CO₃ → NaHCO₃ + H₂O (acid salt).',
     ['Step 1: H₂CO₃ has two replaceable H.', 'Step 2: replacing both gives the carbonate Na₂CO₃.', 'Step 3: replacing one gives the hydrogen carbonate NaHCO₃.'],
     'Dibasic acid → normal salt + acid salt.', [('Name an acid salt of sulfuric acid.', 'NaHSO₄.'), ('What forms when NaHCO₃ is heated?', 'Na₂CO₃, H₂O and CO₂.')])
U3.TF('q5', L3, 81, 'Carbonic acid is a strong, stable acid.', False,
      ['Step 1: only a little H₂CO₃ ionises → weak.', 'Step 2: it decomposes back to CO₂ and water easily → unstable.', 'Step 3: it exists only in solution.'],
      'Think of a soft drink going flat.', [('What colour does carbonic acid turn blue litmus?', 'Red, slowly and faintly.'), ('Why is rain naturally slightly acidic?', 'It contains dissolved CO₂ (carbonic acid).')])

# ============================================================== Unit 4 Metals
U4 = Unit('chem11-u4')
L4 = '4.1 Activity series of metals'
DIAG4 = {'cm_activity': 'activity'}

ACT = [
    U4.T('c01', 'The activity series, step by step', 120,
         'The **activity (reactivity) series** lists metals from the **most reactive** (top) to the **least reactive** (bottom). Hydrogen (and often carbon) is included as a reference.',
         '**Why the order?** Metals react by **losing electrons** to form positive ions. The easier a metal loses electrons, the higher it is in the series.',
         '**How it is found:** compare how vigorously metals react with **oxygen, water and dilute acids** (textbook Activity on p.120), and which metal **displaces** which from solutions of their salts.',
         '**The textbook series (Table 4.1):** K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Hg > Ag > Au. (Sn sits between Fe and Pb; Pt below Au.)'),
    U4.ST('s01', 'Model: what the position tells you', 121, 'cm_activity',
          [('**Water:** K, Na, Ca react with cold water (→ hydroxide + H₂); Mg (hot water/steam), Al, Zn, Fe react with steam (→ oxide + H₂); metals below Fe do not react.', 'water'),
           ('**Dilute acids:** metals **above hydrogen** displace H₂ from dilute HCl or H₂SO₄; metals **below hydrogen** (Cu, Hg, Ag, Au, Pt) do not.', 'acid'),
           ('**Extraction:** the higher the metal, the harder it is to extract: electrolysis for K → Al, reduction with carbon for Zn → Cu, and Ag, Au, Pt are found native.', 'extract')]),
    U4.TB('t01', 'Reactions of metals at a glance (textbook pp. 121–123)', 121,
          ['Metal', 'With oxygen', 'With water', 'With dilute acid', 'Extraction'],
          [['K, Na', 'burn very vigorously; tarnish in air', 'violent with cold water (H₂ may ignite)', 'explosive — never try', 'electrolysis of molten chloride'],
           ['Ca', 'burns brightly', 'steady with cold water', 'vigorous', 'electrolysis'],
           ['Mg', 'burns with a white flame', 'hot water; quickly with steam', 'fast, H₂', 'electrolysis'],
           ['Al, Zn, Fe', 'burn when strongly heated (powder)', 'with steam → oxide + H₂', 'moderate, H₂', 'Al: electrolysis of Al₂O₃; Zn, Fe: reduction with C or CO'],
           ['Sn, Pb', 'form oxide when heated, do not burn', 'no reaction', 'slow, H₂', 'reduction with carbon'],
           ['Cu, Hg', 'form oxide when heated (CuO black)', 'no reaction', 'no reaction', 'heating ores / reduction'],
           ['Ag, Au, Pt', 'no reaction even when hot', 'no reaction', 'no reaction', 'found native (uncombined)']]),
    U4.T('c02', 'Uses of the activity series', 123,
         '**1. Predict reactions with water and acids** (table above) — e.g. why we never put sodium in acid, why copper vessels do not react with vinegar.',
         '**2. Predict displacement reactions:** a metal displaces any metal **below** it from a solution of its salt. Zn(s) + CuSO₄(aq) → ZnSO₄(aq) + Cu(s) (blue colour fades, red-brown copper forms). Cu + ZnSO₄ → **no reaction**. Cu(s) + 2AgNO₃(aq) → Cu(NO₃)₂(aq) + 2Ag(s).',
         '**3. Choose the extraction method:** metals above carbon (K → Al) need **electrolysis**; metals below carbon (Zn → Cu) can be **reduced with carbon or CO**; the least reactive (Ag, Au, Pt) occur **native** — that is why gold was the first metal people used.',
         '**4. Protect iron from rusting:** a more reactive metal corrodes **instead of** iron — zinc coating (**galvanising**) on roofing sheets, magnesium or zinc blocks bolted to ship hulls and buried pipes (**sacrificial protection**).',
         '**5. Predict stability of compounds:** compounds of metals high in the series are hard to decompose (Na₂CO₃ is stable to heat; CuCO₃ decomposes easily).',
         '**6. Choose containers:** do not store copper(II) sulfate solution in an iron or zinc container — the container would be eaten away (Fe + CuSO₄ → FeSO₄ + Cu).'),
    U4.MN('m01', 'Memory trick: the textbook order', 120,
          '**“Please Send Charlie’s Monkeys And Zebras In Lead Hutches, Cages, Mostly Securely Guarded.”**',
          [('P', 'Potassium', 'K'), ('S', 'Sodium', 'Na'), ('C', 'Calcium', 'Ca'), ('M', 'Magnesium', 'Mg'), ('A', 'Aluminium', 'Al'), ('Z', 'Zinc', 'Zn'), ('I', 'Iron', 'Fe'),
           ('L', 'Lead', 'Pb'), ('H', 'Hydrogen', 'H (reference)'), ('C', 'Copper', 'Cu'), ('M', 'Mercury', 'Hg'), ('S', 'Silver', 'Ag'), ('G', 'Gold', 'Au')]),
    U4.WK('w01', 'Worked example: will it displace?', 123,
          'Predict whether a reaction occurs and write the equation: (a) Fe + CuSO₄(aq); (b) Cu + FeSO₄(aq); (c) Mg + ZnCl₂(aq); (d) Ag + HCl(aq).',
          ['(a) Fe is above Cu → **yes**: Fe(s) + CuSO₄(aq) → FeSO₄(aq) + Cu(s) (iron nail turns copper-coloured, blue fades).',
           '(b) Cu is below Fe → **no reaction**.', '(c) Mg is above Zn → **yes**: Mg(s) + ZnCl₂(aq) → MgCl₂(aq) + Zn(s).',
           '(d) Ag is below H → **no reaction** (no H₂).'],
          '(a) yes; (b) no; (c) yes; (d) no.'),
    U4.WK('w02', 'Worked example: placing an unknown metal', 123,
          'Metal X reacts with dilute HCl to give H₂ but does not react with cold water. X displaces copper from CuSO₄ solution but does not displace zinc from ZnSO₄. Where is X in the series? Suggest what X could be.',
          ['Reacts with dilute acid → X is **above H**.', 'No reaction with cold water → X is **below Ca** (and Mg reacts with hot water).',
           'Displaces Cu → X is **above Cu**; does not displace Zn → X is **below Zn**.', 'So X lies between Zn and H: **Fe, Sn or Pb** (iron is the usual answer).'],
          'Between Zn and H — for example iron.'),
    U4.WK('w03', 'Worked example: choosing an extraction method', 124,
          'Suggest how each metal is obtained from its ore and why: aluminium, iron, gold.',
          ['Aluminium is above carbon → carbon cannot remove oxygen from Al₂O₃ → **electrolysis** of molten Al₂O₃ (dissolved in cryolite).',
           'Iron is below carbon → **reduction with carbon monoxide** in a blast furnace: Fe₂O₃ + 3CO → 2Fe + 3CO₂.',
           'Gold is very unreactive → found **native**; it only needs to be separated from rock (e.g. at Bisha in Eritrea).'],
          'Al: electrolysis; Fe: reduction by CO/C; Au: native.'),
    U4.CK('k01', 123, 'Which reaction will NOT take place?',
          ['Zn + CuSO₄', 'Mg + FeSO₄', 'Cu + ZnSO₄', 'Fe + CuSO₄'], 'C',
          'Copper is below zinc, so it cannot displace zinc from its salt.'),
    U4.CK('k02', 122, 'Which metal does NOT give hydrogen with dilute hydrochloric acid?', ['Zn', 'Mg', 'Fe', 'Cu'], 'D',
          'Copper is below hydrogen in the activity series.'),
    U4.CK('k03', 124, 'Galvanised iron is coated with zinc. Even when scratched, the iron does not rust because …',
          ['zinc is less reactive than iron', 'zinc is more reactive and corrodes instead of iron', 'zinc is a non-metal', 'zinc stops water from boiling'], 'B',
          'Zinc is higher in the series, so it loses electrons (corrodes) first — sacrificial protection.'),
    U4.RM('r01', 'Tips and common mistakes', 123,
          'Displacement: the **free** metal must be **above** the metal in the salt.',
          'Above H → gives H₂ with dilute acids; below H → no H₂. (Never use nitric acid for this test — it gives nitrogen oxides instead.)',
          'Above carbon → electrolysis; below carbon → carbon reduction.'),
]

U4.M('q1', L4, 123, 'Which pair reacts?', ['Cu + MgSO₄', 'Ag + CuSO₄', 'Zn + Pb(NO₃)₂', 'Pb + ZnSO₄'], 'C',
     ['Step 1: the free metal must be above the metal in the salt.', 'Step 2: Zn is above Pb → Zn displaces Pb.', 'Step 3: in the others the free metal is lower.'],
     'Higher displaces lower.', [('Write the equation for Zn + Pb(NO₃)₂.', 'Zn + Pb(NO₃)₂ → Zn(NO₃)₂ + Pb.'), ('Does Fe displace Ag from AgNO₃?', 'Yes.')])
U4.M('q2', L4, 124, 'Aluminium is extracted by electrolysis rather than by reduction with carbon because …',
     ['aluminium is above carbon in the activity series', 'aluminium is below carbon', 'carbon is too expensive', 'Al₂O₃ is a gas'], 'A',
     ['Step 1: carbon removes oxygen only from oxides of metals less reactive than carbon.', 'Step 2: Al is more reactive than C.', 'Step 3: so electrolysis is needed.'],
     'Above carbon → electrolysis.', [('How is iron extracted?', 'Reduction of iron oxide with CO in a blast furnace.'), ('Why is gold found native?', 'It is very unreactive.')])
U4.S('q3', L4, 123, 'Metals P, Q and R: P displaces Q from its salt solution; R displaces P from its salt solution. Arrange them from most to least reactive.', 'R > P > Q',
     ['Step 1: P displaces Q → P above Q.', 'Step 2: R displaces P → R above P.', 'Step 3: R > P > Q.'],
     'Draw a little ladder as you read each clue.', [('Q does not react with dilute acid; P does. Which is above H?', 'P.'), ('Could Q be copper?', 'Yes — it is below P and below H.')], accept=['R, P, Q', 'R>P>Q'])
U4.S('q4', L4, 124, 'Explain why blocks of magnesium are attached to the steel hulls of ships.', 'Mg is more reactive than iron, so it corrodes (loses electrons) instead of the iron — sacrificial protection.',
     ['Step 1: Mg is higher in the activity series than Fe.', 'Step 2: the more reactive metal is oxidised first.', 'Step 3: the hull stays protected until the Mg block is used up and replaced.'],
     'More reactive metal sacrifices itself.', [('Why is iron roofing sheet coated with zinc?', 'Galvanising — zinc protects iron, even when scratched.'), ('Would copper protect iron in this way?', 'No — copper is less reactive and makes iron rust faster.')])
U4.TF('q5', L4, 122, 'All metals above hydrogen in the activity series react with cold water.', False,
      ['Step 1: only K, Na and Ca react readily with cold water.', 'Step 2: Mg needs hot water or steam; Al, Zn, Fe need steam; Sn and Pb do not react with water.', 'Step 3: but all of them do give H₂ with dilute acids.'],
      'Water test and acid test have different cut-offs.', [('Which metals react with steam but not cold water?', 'Mg, Al, Zn, Fe.'), ('Write the reaction of iron with steam.', '3Fe + 4H₂O(g) → Fe₃O₄ + 4H₂.')])

# ============================================================== Unit 5 Behaviour of gases
U5 = Unit('chem11-u5')
L5 = '5.2–5.3 Ideal and real gases'
DIAG5 = {'cm_ideal': 'ideal', 'cm_real': 'real'}

IDEAL = [
    U5.T('c01', 'Deriving the ideal gas equation, step by step', 177,
         'Four variables describe a gas: pressure **P**, volume **V**, temperature **T** (kelvin) and amount **n** (mol). Each gas law links V to one of the others while the rest are kept fixed:',
         r'**Step 1 — Boyle (n, T fixed):** \(V \propto \dfrac{1}{P}\)',
         r'**Step 2 — Charles (n, P fixed):** \(V \propto T\)',
         r'**Step 3 — Avogadro (P, T fixed):** \(V \propto n\)',
         r'**Step 4 — Combine:** if V is proportional to each separately, it is proportional to all together: \(V \propto \dfrac{nT}{P}\).',
         r'**Step 5 — Put in a constant R** (the molar gas constant): \(V = R\,\dfrac{nT}{P}\), so',
         r'$$PV = nRT$$',
         r'**Step 6 — Find R** from one known gas: 1 mol at STP (273 K, 1 atm) occupies 22.4 L, so \(R = \dfrac{PV}{nT} = \dfrac{1 \times 22.4}{1 \times 273} = 0.0821\ \text{L}\cdot\text{atm/(mol}\cdot\text{K)}\). In SI units (P in Pa, V in m³): R = 8.314 J/(mol·K).',
         '**Check:** fix n and T → PV = constant (Boyle); fix n and P → V/T = constant (Charles); fix n → PV/T = constant (combined gas law).'),
    U5.ST('s01', 'Model: building PV = nRT', 177, 'cm_ideal',
          [('**Boyle:** V ∝ 1/P when n and T are fixed.', 'b'), ('**Charles:** V ∝ T when n and P are fixed.', 'c'), ('**Avogadro:** V ∝ n when P and T are fixed.', 'a'),
           ('Put the three together: **V ∝ nT/P**.', 'comb'), ('Replace “∝” by “= R ×”: **PV = nRT**.', 'pv'), ('Substitute n = m/M and d = m/V: **PM = dRT**.', 'd')]),
    U5.T('c02', 'PM = dRT: density and molar mass of a gas', 179,
         r'**Step 1:** moles = mass ÷ molar mass: \(n = \dfrac{m}{M}\).',
         r'**Step 2:** substitute into PV = nRT: \(PV = \dfrac{m}{M}RT\).',
         r'**Step 3:** multiply both sides by M and divide by V: \(PM = \dfrac{m}{V}RT\).',
         r'**Step 4:** m/V is the density d:',
         r'$$PM = dRT \qquad d = \frac{PM}{RT} \qquad M = \frac{dRT}{P}$$',
         '**What it tells you:** at the same P and T, a gas with a bigger molar mass is denser (CO₂, M = 44, sinks below air, M ≈ 29; H₂ and He rise). Heating a gas lowers its density (hot-air balloons). Measuring the density of an unknown gas gives its molar mass.'),
    U5.WK('w01', 'Worked example: volume from PV = nRT', 178,
          'What volume do 2.0 mol of oxygen occupy at 27 °C and 2.0 atm?',
          ['T = 27 + 273 = 300 K', r'\(V = \dfrac{nRT}{P} = \dfrac{2.0 \times 0.0821 \times 300}{2.0}\)', 'V = 24.6 L'],
          '24.6 L'),
    U5.WK('w02', 'Worked example: pressure in SI units', 178,
          '0.50 mol of nitrogen is held in a 10.0 L container at 300 K. Find the pressure in pascals.',
          ['Use R = 8.314 J/(mol·K), so V must be in m³: 10.0 L = 0.0100 m³.', r'\(P = \dfrac{nRT}{V} = \dfrac{0.50 \times 8.314 \times 300}{0.0100}\)',
           r'\(P = 1.25\times10^{5}\text{ Pa}\) (about 1.23 atm)'],
          '1.25 × 10⁵ Pa'),
    U5.WK('w03', 'Worked example: density of CO₂ at STP', 179,
          'Calculate the density of carbon dioxide (M = 44 g/mol) at STP.',
          [r'\(d = \dfrac{PM}{RT} = \dfrac{1 \times 44}{0.0821 \times 273}\)', 'd = 1.96 g/L', 'Check: 44 g ÷ 22.4 L = 1.96 g/L ✓'],
          '1.96 g/L'),
    U5.WK('w04', 'Worked example: molar mass from density', 179,
          'An unknown gas has a density of 1.25 g/L at STP. Find its molar mass and suggest what it could be.',
          [r'\(M = \dfrac{dRT}{P} = \dfrac{1.25 \times 0.0821 \times 273}{1}\)', 'M = 28.0 g/mol', 'Gases with M = 28: N₂ or CO (or C₂H₄).'],
          '28 g/mol — e.g. N₂ or CO'),
    U5.CK('k01', 177, 'Which law is combined with Boyle’s and Charles’s laws to give PV = nRT?', ['Dalton’s law', 'Avogadro’s law', 'Graham’s law', 'Gay-Lussac’s law of volumes'], 'B',
          'Avogadro’s law (V ∝ n) brings in the amount of gas.'),
    U5.CK('k02', 179, 'At the same temperature and pressure, which gas has the greatest density?', ['H₂', 'He', 'N₂', 'CO₂'], 'D',
          'd = PM/RT: density is proportional to molar mass; CO₂ (44) is largest.'),
]

REAL = [
    U5.T('c03', 'Real gases and the van der Waals equation, step by step', 186,
         '**Ideal gas assumptions (kinetic theory):** (1) the molecules themselves take up **no volume**; (2) there are **no attractions** between molecules. Real gases obey PV = nRT well only at **low pressure and high temperature**.',
         '**Step 1 — Why real gases deviate.** At **high pressure** the molecules are crowded, so their own volume is no longer negligible. At **low temperature** they move slowly, so attractions matter.',
         '**Step 2 — Volume correction.** Each mole of molecules occupies a volume b, so the empty space molecules can move in is the **free volume** V − nb.',
         r'**Step 3 — Pressure correction.** A molecule about to hit the wall is pulled back by its neighbours, so it hits more gently: the measured P is **less** than the ideal pressure. The loss depends on how crowded the gas is, \((n/V)^2\), so we add \(\dfrac{an^2}{V^2}\).',
         r'**Step 4 — Put both into PV = nRT** (textbook 5.3.3, Van der Waals’ equation):',
         r'$$\left(P + \frac{an^2}{V^2}\right)(V - nb) = nRT$$',
         '**Meaning of the constants:** **a** measures the strength of attractions (large for polar or big molecules that are easy to liquefy, e.g. NH₃, H₂O); **b** measures the size of the molecules. The smaller a and b, the more ideal the gas (He and H₂ are closest to ideal).'),
    U5.SS('s02', 'Model: from ideal to real', 188, 'cm_real',
          [('i', 'Ideal', 'Ideal model: molecules are points with no attractions — PV = nRT.'),
           ('v', 'Volume', 'Real molecules take up space: the free volume is V − nb. This matters most at high pressure.'),
           ('p', 'Pressure', 'Neighbours pull a molecule back as it reaches the wall, so the wall feels less pressure: add an²/V². This matters most at low temperature.')]),
    U5.TB('t01', 'Van der Waals constants of some gases', 188,
          ['Gas', 'a (L²·atm/mol²)', 'b (L/mol)', 'Comment'],
          [['He', '0.034', '0.0237', 'nearly ideal: tiny attractions'], ['H₂', '0.244', '0.0266', 'nearly ideal'],
           ['N₂', '1.39', '0.0391', 'fairly ideal at room conditions'], ['CO₂', '3.59', '0.0427', 'easily liquefied'],
           ['NH₃', '4.17', '0.0371', 'polar: strong attractions'], ['H₂O', '5.46', '0.0305', 'hydrogen bonding: largest a']]),
    U5.WK('w05', 'Worked example: ideal vs van der Waals pressure', 188,
          'Find the pressure of 1.00 mol of CO₂ in a 1.00 L container at 300 K (a) as an ideal gas, (b) with the van der Waals equation (a = 3.59 L²·atm/mol², b = 0.0427 L/mol).',
          [r'(a) \(P = \dfrac{nRT}{V} = \dfrac{1.00 \times 0.0821 \times 300}{1.00} = 24.6\text{ atm}\)',
           r'(b) Rearrange: \(P = \dfrac{nRT}{V - nb} - \dfrac{an^2}{V^2}\)',
           r'\(\dfrac{24.63}{1.00 - 0.0427} = \dfrac{24.63}{0.9573} = 25.7\text{ atm}\)',
           r'\(\dfrac{an^2}{V^2} = \dfrac{3.59 \times 1^2}{1.00^2} = 3.59\text{ atm}\)', 'P = 25.7 − 3.59 = 22.1 atm',
           'The real pressure is about 10 % lower: the attraction effect is bigger than the volume effect here.'],
          'Ideal 24.6 atm; van der Waals 22.1 atm'),
    U5.WK('w06', 'Worked example: when is a gas most ideal?', 186,
          'Under which conditions does a real gas behave most like an ideal gas? Explain using the two van der Waals corrections.',
          ['**Low pressure:** molecules are far apart, so nb is tiny compared with V and an²/V² is tiny compared with P.',
           '**High temperature:** molecules move fast, so brief attractions hardly slow them — the pressure correction is unimportant.',
           'So: **low pressure and high temperature**, and gases with small a and b (He, H₂).'],
          'Low pressure, high temperature.'),
    U5.CK('k03', 188, 'In the van der Waals equation, the term nb corrects for …',
          ['attractions between molecules', 'the volume occupied by the molecules', 'the temperature', 'the speed of molecules'], 'B',
          'V − nb is the free volume: the space not taken by the molecules themselves.'),
    U5.CK('k04', 188, 'Which gas has the largest van der Waals constant a?', ['He', 'H₂', 'N₂', 'H₂O'], 'D',
          'a measures attraction; water molecules hydrogen-bond strongly.'),
    U5.RM('r01', 'Tips and common mistakes', 177,
          'Always convert °C to **kelvin**.',
          'Match R to the units: 0.0821 with L and atm; 8.314 with m³ and Pa (1 L = 10⁻³ m³).',
          'In van der Waals: **add** to P (attractions lower the measured pressure), **subtract** from V (molecules take up space).'),
]

U5.M('q1', L5, 177, 'Which combination of laws gives V ∝ nT/P?', ['Boyle, Charles and Avogadro', 'Boyle and Dalton only', 'Charles and Graham', 'Avogadro and Dalton'], 'A',
     ['Step 1: Boyle V ∝ 1/P.', 'Step 2: Charles V ∝ T.', 'Step 3: Avogadro V ∝ n.', 'Step 4: together V ∝ nT/P → PV = nRT.'],
     'One law for each variable.', [('Which law gives V ∝ n?', 'Avogadro’s law.'), ('What is R in L·atm/(mol·K)?', '0.0821.')])
U5.S('q2', L5, 178, 'How many moles of gas are in a 5.0 L flask at 2.0 atm and 27 °C?', '0.41 mol',
     ['Step 1: T = 300 K.', 'Step 2: n = PV/RT = (2.0 × 5.0)/(0.0821 × 300).', 'Step 3: n = 10/24.63 = 0.41 mol.'],
     'Rearrange PV = nRT for the unknown first.', [('What mass of O₂ is that?', '0.41 × 32 = 13 g.'), ('What volume does 0.41 mol occupy at STP?', '9.2 L.')], accept=['0.41', '0.406 mol', '0.406'])
U5.S('q3', L5, 179, 'A gas has density 2.86 g/L at STP. Find its molar mass.', '64 g/mol (e.g. SO₂)',
     ['Step 1: M = dRT/P.', 'Step 2: = 2.86 × 0.0821 × 273 / 1.', 'Step 3: = 64.1 g/mol — SO₂.'],
     'PM = dRT.', [('What is the density of O₂ at STP?', '32/22.4 = 1.43 g/L.'), ('Is SO₂ denser than air?', 'Yes (64 > 29).')], accept=['64', '64.1 g/mol', '64 g mol⁻¹'])
U5.M('q4', L5, 186, 'Real gases deviate most from ideal behaviour at …',
     ['high temperature and low pressure', 'low temperature and high pressure', 'room conditions', 'high temperature only'], 'B',
     ['Step 1: high pressure → molecules crowded → their volume matters.', 'Step 2: low temperature → slow molecules → attractions matter.', 'Step 3: both effects are largest at low T and high P.'],
     'Ideal at “high T, low P”; real at “low T, high P”.', [('Which is more ideal, He or NH₃?', 'He (smaller a and b).'), ('Why do gases liquefy at low T and high P?', 'Attractions win when molecules are slow and close.')])
U5.TF('q5', L5, 188, 'In the van der Waals equation, the term an²/V² is added to P because attractions make the measured pressure lower than the ideal pressure.', True,
      ['Step 1: neighbours pull a molecule back as it reaches the wall.', 'Step 2: it hits the wall more gently → lower measured P.', 'Step 3: adding an²/V² restores the ideal pressure.'],
      'Add to P, subtract from V.', [('What does b represent?', 'The volume occupied per mole of molecules.'), ('What is the free volume?', 'V − nb.')])

BLOCKS = [
    ('chem11-u1-l1-2', 'chem11-u1-c11', MASS),
    ('chem11-u1-l1-2', 'chem11-u1-c12', CHAT),
    ('chem11-u3-l3-2', 'chem11-u3-c04', ALLO),
    ('chem11-u3-l3-2', 'chem11-u3-c06', CARBONIC),
    ('chem11-u4-l4-1', 'chem11-u4-c02', ACT),
    ('chem11-u5-l5-2', 'chem11-u5-c09', IDEAL),
    ('chem11-u5-l5-3', 'chem11-u5-c07', REAL),
]
UNITS = {'chem11-u1': (U1, DIAG1), 'chem11-u3': (U3, DIAG3), 'chem11-u4': (U4, DIAG4), 'chem11-u5': (U5, DIAG5)}
GLOSSARY = {
    'chem11-u1': [('Law of mass action', 'The rate of a reaction is proportional to the product of the reactant concentrations, each raised to its coefficient; it leads to the equilibrium constant Kc.', 19)],
    'chem11-u3': [('Buckminsterfullerene', 'C₆₀, a football-shaped allotrope of carbon made of 12 pentagons and 20 hexagons (discovered 1985).', 73),
                  ('Carbonic acid', 'H₂CO₃, the weak, unstable, dibasic acid formed when CO₂ dissolves in water.', 81)],
    'chem11-u4': [('Displacement reaction', 'A reaction in which a more reactive metal pushes a less reactive metal out of a solution of its salt.', 123),
                  ('Sacrificial protection', 'Protecting iron by joining it to a more reactive metal (Zn, Mg) that corrodes instead.', 124)],
    'chem11-u5': [('Ideal gas equation', 'PV = nRT, obtained by combining Boyle’s, Charles’s and Avogadro’s laws.', 177),
                  ('Van der Waals equation', '(P + an²/V²)(V − nb) = nRT; corrects the ideal gas equation for molecular volume (b) and attractions (a).', 188)],
}
