"""Grade 9 Unit 1, 1.4.3 Separation of mixtures (textbook pp. 27-34): one tutor block with a model for every method."""
from common import Unit

U = Unit('chem9-u1')
T, RM, MN, TB, DG, ST, SS, CK, WK = U.T, U.RM, U.MN, U.TB, U.DG, U.ST, U.SS, U.CK, U.WK
LBL = '1.4.3 Separating mixtures'

DIAGRAMS = {'cm_sed': 'sed', 'cm_filt': 'filt', 'cm_mag': 'mag', 'cm_evap': 'evap', 'cm_funnel': 'funnel', 'cm_dist': 'dist', 'cm_frac': 'frac'}

CARDS = [
    T('c01', '1.4.3 Separating mixtures: the big idea', 27,
      'A **mixture** is two or more substances mixed **physically**. Each part keeps its own properties, so we can separate the parts by **physical** methods (no chemical reaction is needed).',
      '**Step 1 — Name the parts.** Write down what is in the mixture, e.g. *sand + salt + water*.',
      '**Step 2 — Find a property that is different.** Compare the parts: particle size, whether they dissolve, density, magnetism, boiling point.',
      '**Step 3 — Pick the method that uses that difference** (table below). For three or more parts you usually need two or three methods, one after the other.',
      '**Step 4 — Check the product is pure.** A pure substance has a sharp, fixed melting point and boiling point (pure water boils at 100 °C at sea level).'),
    TB('t01', 'Which difference → which method', 27,
       ['Method', 'What it separates', 'Property used', 'Example'],
       [['Sedimentation + decantation', 'heavy insoluble solid from a liquid', 'density (solid sinks)', 'muddy river water, washing rice'],
        ['Filtration', 'insoluble solid from a liquid', 'particle size (solid stays on the paper)', 'sand from water, tea leaves from tea'],
        ['Evaporation', 'dissolved solid from its solution (solid wanted)', 'the liquid is volatile, the solid is not', 'salt from sea water at Massawa'],
        ['Magnetic separation', 'magnetic solid from non-magnetic solid', 'magnetism (Fe, Ni, Co)', 'iron filings from sulfur or sand'],
        ['Separating funnel', 'two immiscible liquids', 'density (liquids form layers)', 'oil from water, kerosene from water'],
        ['Simple distillation', 'liquid from a dissolved solid (liquid wanted)', 'big difference in boiling point', 'pure water from salt water or ink'],
        ['Fractional distillation', 'miscible liquids with close boiling points', 'small difference in boiling point', 'ethanol from water, crude oil fractions']],
       'Read the table row by row: the **property used** column is the one that exams ask about.'),
    MN('m01', 'Memory trick: the five differences', 27,
       'Ask **“Some Students Do Most Brilliantly?”** — the five properties to compare.',
       [('S', 'Size', 'insoluble lumps → filtration / sedimentation'), ('S', 'Solubility', 'dissolved solid → evaporation (or distil to keep the liquid)'),
        ('D', 'Density', 'layers → separating funnel, decanting'), ('M', 'Magnetism', 'iron, nickel, cobalt → magnet'),
        ('B', 'Boiling point', 'liquids → simple or fractional distillation')]),

    # sedimentation and decantation
    SS('s01', 'Model: sedimentation and decantation', 28, 'cm_sed',
       [('s0', 'Stir', 'Muddy water: soil particles are spread all through the water.'),
        ('s1', 'Settle', 'Leave it still. Gravity pulls the heavier particles down — they **settle**.'),
        ('s2', 'Sediment', 'The solid layer at the bottom is the **sediment**; the clearer water above is the **supernatant**.'),
        ('s3', 'Decant', 'Tilt the beaker gently and pour off the clear liquid without disturbing the sediment — **decantation**.')],
       'Move the slider to watch the mixture settle, then decant.'),
    T('c02', 'Sedimentation and decantation, step by step', 28,
      '**Sedimentation:** an insoluble solid that is denser than the liquid sinks to the bottom when the mixture is left to stand.',
      '**Decantation:** pouring off the clear liquid on top, leaving the sediment behind.',
      '1. Pour the mixture into a beaker and leave it **undisturbed** (minutes for sand, hours for fine clay).',
      '2. When a clear layer forms, hold a glass rod against the lip of the beaker and pour the liquid **slowly** down the rod.',
      '3. Stop before the sediment starts to move.',
      '**Limitations:** very fine particles stay suspended, and a little liquid always stays with the sediment. Decanted river water is clearer but **not safe to drink** — it still contains dissolved substances and germs, so it must be filtered and boiled or chlorinated.',
      '**Everyday uses:** washing rice or lentils (dirt settles, water is poured off), letting tella or coffee grounds settle before pouring, the first settling tanks at a water-treatment plant.'),
    CK('k01', 28, 'After muddy water has been left to stand, the solid layer at the bottom is called the …',
       ['filtrate', 'sediment', 'distillate', 'residue of evaporation'], 'B',
       'Solid that settles at the bottom = **sediment**; the clear liquid poured off is decanted. Filtrate and distillate are liquids from filtration and distillation.'),

    # filtration
    ST('s02', 'Model: filtration', 29, 'cm_filt',
       [('Pour the mixture slowly down a glass rod into the funnel.', 'm'),
        ('The folded **filter paper** has tiny holes: water and dissolved substances pass through, larger solid particles do not.', 'p'),
        ('The solid left on the paper is the **residue**.', 'r'),
        ('The clear liquid collected below is the **filtrate**.', 'f')],
       'Tap through the steps; each one highlights a part of the apparatus.'),
    T('c03', 'Filtration, step by step', 29,
      '**Filtration** separates an **insoluble** solid from a liquid using a barrier with tiny holes (filter paper, cloth, sand bed).',
      '1. Fold a circle of filter paper in half, then in half again; open it into a cone (three layers on one side, one on the other).',
      '2. Put it in a funnel and **wet it** with a little water so it sticks to the glass.',
      '3. Pour the mixture down a glass rod. Keep the level **below the top edge of the paper**, otherwise the mixture runs down the side unfiltered.',
      '4. Collect the **filtrate** in a beaker or flask; the **residue** stays on the paper. Wash the residue with a little clean water if you want it pure.',
      '**Remember:** a dissolved solid (salt, sugar) **passes through** the paper. Filtration cannot separate salt from water — that needs evaporation or distillation.',
      '**Everyday uses:** making tea or coffee (strainer), cloth filters for drinking water, sand-and-gravel filters at water-treatment works, air filters in cars.'),
    CK('k02', 29, 'Salt water is poured through filter paper. What comes through?',
       ['Pure water only', 'Salt only', 'Salt water — the salt is dissolved', 'Nothing'], 'C',
       'Dissolved particles are far smaller than the holes in filter paper, so the **filtrate is still salt water**. Use evaporation to get the salt or distillation to get the water.'),

    # evaporation
    SS('s03', 'Model: evaporation', 30, 'cm_evap',
       [('s0', 'Start', 'A salt solution in an evaporating dish, heated gently (or left in the sun).'),
        ('s1', 'Heating', 'Water molecules escape as vapour; the solution becomes more concentrated.'),
        ('s2', 'Dry', 'All the water has gone; salt crystals are left in the dish.')]),
    T('c04', 'Evaporation, step by step', 30,
      '**Evaporation** recovers a **dissolved solid** from its solution by turning the liquid into vapour. The solid is kept; the liquid is lost to the air.',
      '1. Filter the solution first if it contains any insoluble dirt.',
      '2. Pour the clear solution into an evaporating dish and heat it gently over a water bath or a small flame (or use the sun).',
      '3. Stir and lower the heat near the end so the crystals do not spit out.',
      '4. Stop when crystals form; let the last liquid evaporate by itself.',
      '**Crystallisation (better for some salts):** heat only until the solution is **saturated**, then let it cool — larger, purer crystals form. Use this for salts such as copper(II) sulfate that would decompose if heated to dryness.',
      '**In Eritrea:** salt is produced at the salt pans of **Massawa and Assab** — sea water is let into shallow ponds and the sun evaporates the water.'),

    # magnetic separation
    SS('s04', 'Model: magnetic separation', 31, 'cm_mag',
       [('s0', 'Mixture', 'Iron filings (grey) mixed with sulfur powder (yellow).'),
        ('s1', 'Magnet', 'Bring a magnet close; only the iron particles are attracted.'),
        ('s2', 'Separated', 'The iron sticks to the magnet; the sulfur is left behind.')]),
    T('c05', 'Magnetic separation, step by step', 31,
      'A magnet attracts only **magnetic** materials: **iron, nickel, cobalt** and most steels.',
      '1. Spread the dry mixture thinly on paper.',
      '2. Wrap the magnet in paper or a plastic bag (the filings are easy to remove later) and pass it over the mixture several times.',
      '3. Lift the magnet, take off the wrapping over another sheet — the iron drops off.',
      '**Mixture or compound test:** iron + sulfur **mixed** → the magnet pulls out the iron. Iron + sulfur **heated** → **iron(II) sulfide, FeS**, a new compound — the magnet no longer pulls out iron. This is a classic exam contrast.',
      '**Uses:** removing iron scraps from grain at flour mills, sorting scrap metal, separating iron ore from sand.'),
    CK('k03', 31, 'A magnet will separate iron from which of these?',
       ['A mixture of iron filings and sand', 'Iron(II) sulfide, FeS', 'Rust (iron oxide) powder', 'A solution of iron(II) sulfate'], 'A',
       'Only **free iron** in a **mixture** is pulled out. In FeS, rust and iron sulfate the iron is chemically combined — a compound has its own (non-magnetic) properties.'),

    # separating funnel
    SS('s05', 'Model: separating funnel', 33, 'cm_funnel',
       [('s0', 'Shake', 'Oil and water are shaken together in the funnel.'),
        ('s1', 'Layers', 'Left to stand, the liquids form **two layers**: the less dense oil floats on the denser water.'),
        ('s2', 'Drain', 'Remove the stopper, open the tap: the lower (water) layer runs out into the beaker.'),
        ('s3', 'Done', 'Close the tap just as the boundary reaches it. The oil stays in the funnel; pour it out from the top.')]),
    T('c06', 'Separating funnel, step by step', 33,
      'Liquids that do **not mix** (form layers) are **immiscible**; a separating funnel separates them using their **different densities**.',
      '1. Pour the mixture in with the tap **closed**. Let it stand until two clear layers form.',
      '2. **Remove the stopper** (otherwise air cannot get in and the liquid will not flow).',
      '3. Open the tap and run off the **lower, denser** liquid.',
      '4. Close the tap exactly when the boundary reaches it. Run off a few drops of the mixed boundary into a separate beaker if you want each liquid very pure.',
      '5. Pour the upper liquid out through the **top** so it does not pick up drops of the lower liquid left in the tap.',
      '**Examples:** oil and water, kerosene and water, petrol and water. **Not possible:** ethanol and water — they are **miscible** (one layer), so use fractional distillation.'),

    # simple distillation
    ST('s06', 'Model: simple distillation', 32, 'cm_dist',
       [('**Heat** the solution in the flask (add a few anti-bumping chips). The liquid boils; the solid stays.', 'h'),
        ('The **thermometer** bulb sits at the side arm: it reads the boiling point of the vapour leaving (100 °C for water).', 't'),
        ('In the **condenser** cold water flows in at the bottom and out at the top; the vapour cools and condenses.', 'c'),
        ('The pure liquid collected is the **distillate**.', 'd'),
        ('The dissolved solid is left in the flask as the **residue**.', 'r')]),
    T('c07', 'Simple distillation, step by step', 32,
      '**Distillation = evaporation + condensation.** It separates a liquid from a dissolved solid (or from a liquid with a **very different** boiling point) and — unlike evaporation — **keeps the liquid**.',
      '1. Half-fill the flask with the solution; add anti-bumping chips for smooth boiling.',
      '2. Put the thermometer bulb **level with the side arm** — it must measure the vapour that goes into the condenser, not the liquid.',
      '3. Connect the condenser so cold water enters at the **bottom** and leaves at the **top** (the jacket stays full and the cooling is best).',
      '4. Heat until the liquid boils steadily. The temperature stays at the boiling point of the pure liquid while it distils.',
      '5. Collect the **distillate**; never boil the flask dry.',
      '**Uses:** distilled water for batteries and laboratories, drinking water from sea water (desalination), removing the solvent from a solution.'),
    CK('k04', 32, 'Why does cold water enter the condenser at the bottom?',
       ['So the water flows faster', 'So the jacket stays completely full of cold water and cools best', 'So the distillate is heated', 'It makes no difference'], 'B',
       'Entering at the bottom pushes out all the air, so the whole jacket is full of cold water and the vapour meets the coldest water last — the most efficient cooling.'),

    # fractional distillation (extension)
    SS('s07', 'Model: fractional distillation', 33, 'cm_frac',
       [('k1', 'Ethanol first', 'At about 78 °C the vapour reaching the top of the column is mostly **ethanol**: it condenses and is collected first.'),
        ('k2', 'Then water', 'When the ethanol has gone, the thermometer rises to 100 °C and **water** distils over. Change the receiver.')]),
    T('c08', 'Fractional distillation, step by step (extension)', 33,
      '**Fractional distillation** separates **miscible liquids** whose boiling points are **close** (less than about 25 °C apart). The textbook mentions it only briefly; it is explained here because exams use it for ethanol–water and crude oil.',
      '1. Fit a **fractionating column** (packed with glass beads) between the flask and the condenser.',
      '2. As the mixture boils, the vapour condenses and re-boils many times on the beads. Each time, the vapour becomes **richer in the liquid with the lower boiling point**.',
      '3. The top of the column is the coolest part, so only the most volatile liquid gets through. Ethanol (b.p. 78 °C) distils first while the thermometer reads about 78 °C.',
      '4. When the temperature starts to rise, change the receiver; water (b.p. 100 °C) distils next.',
      '**Uses:** refining **crude oil** into fractions (petrol, kerosene, diesel …), separating **liquid air** into nitrogen and oxygen, concentrating alcohol (the same idea as distilling local *areki*).'),
    TB('t02', 'Simple vs fractional distillation', 33,
       ['', 'Simple distillation', 'Fractional distillation'],
       [['Separates', 'liquid from dissolved solid, or liquids with very different b.p.', 'miscible liquids with close b.p.'],
        ['Extra apparatus', 'none', 'fractionating column'],
        ['Thermometer', 'constant at the liquid’s b.p.', 'stays at the lower b.p., then rises to the next'],
        ['Example', 'water from salt water', 'ethanol from water; crude oil']]),

    WK('w01', 'Worked example: sand, salt and iron filings', 31,
       'A mixture contains sand, common salt and iron filings. Describe how to obtain each one pure and dry.',
       ['Look for differences: iron is **magnetic**; salt **dissolves** in water; sand is **insoluble**.',
        '**Magnet first** (while the mixture is dry): pass a wrapped magnet over it — iron filings removed.',
        'Add water to the sand + salt and stir: the salt dissolves.',
        '**Filter**: sand is the residue; wash it with a little water and dry it.',
        '**Evaporate** the filtrate (salt solution): salt crystals are left.'],
       'Magnet → dissolve in water → filter (sand) → evaporate the filtrate (salt). Iron, sand and salt are all recovered.'),
    WK('w02', 'Worked example: drinking water and salt from muddy sea water', 32,
       'You have muddy sea water. How do you get (a) pure water and (b) salt from it?',
       ['The mud is insoluble; the salt is dissolved; water is the liquid we want to keep.',
        'Let the mud **settle** and **decant**, then **filter** to remove the last fine particles.',
        '(a) **Distil** the clear salt water: the distillate is pure water (thermometer steady at 100 °C).',
        '(b) The salt is the residue in the flask — or evaporate a second sample to dryness.'],
       'Sedimentation/decantation → filtration → simple distillation (water = distillate, salt = residue).'),
    WK('w03', 'Worked example: choosing between funnel and distillation', 33,
       'Which method separates (a) kerosene from water, (b) ethanol (b.p. 78 °C) from water, (c) water from ink?',
       ['(a) Kerosene and water do not mix — two layers → **separating funnel** (water, the denser liquid, runs out first).',
        '(b) Ethanol and water mix completely and their boiling points are only 22 °C apart → **fractional distillation**; ethanol distils first.',
        '(c) Ink is a dissolved dye in water; we want the water → **simple distillation**. (Chromatography would be used to separate the dyes.)'],
       '(a) separating funnel; (b) fractional distillation; (c) simple distillation.'),
    RM('r01', 'Tips and common mistakes', 33,
       '**Residue** = solid left on the filter paper (or in the distillation flask); **filtrate** = liquid through the filter; **distillate** = liquid collected after condensing.',
       'Evaporation keeps the **solid**; distillation keeps the **liquid** (and the solid too).',
       'Thermometer at the **side arm**; condenser water **in at the bottom**; funnel stopper **out** before opening the tap.',
       'A magnet separates iron from a **mixture**, never from a **compound** such as FeS.'),
    CK('k05', 33, 'Petrol and water are poured into a separating funnel. Petrol is less dense than water. Which statement is correct?',
       ['Petrol forms the bottom layer', 'Water runs out of the tap first', 'They form one layer', 'Distillation is needed'], 'B',
       'The **denser** liquid (water) is at the bottom, next to the tap, so it runs out first; petrol floats on top.'),
    CK('k06', 33, 'Which method is used to separate the components of crude oil?',
       ['Filtration', 'Separating funnel', 'Fractional distillation', 'Magnetic separation'], 'C',
       'Crude oil is a mixture of many **miscible** liquids with different but close boiling points → **fractional distillation**.'),
]

M, S, F, TF = U.M, U.S, U.F, U.TF
M('q1', LBL, 29, 'Which method separates chalk powder from water?',
  ['Evaporation', 'Filtration', 'Magnetic separation', 'Separating funnel'], 'B',
  ['Step 1: chalk is **insoluble** in water — a suspension.', 'Step 2: an insoluble solid is held back by filter paper.', 'Step 3: chalk = residue, water = filtrate.'],
  'Insoluble solid + liquid → filtration (or sedimentation and decantation).',
  [('Which method separates sand from water?', 'Filtration (or decantation).'), ('What is the solid left on the filter paper called?', 'The residue.')])
M('q2', LBL, 30, 'Salt is obtained from sea water at Massawa by …',
  ['filtration', 'evaporation', 'decantation', 'fractional distillation'], 'B',
  ['Step 1: salt is **dissolved** in sea water, so filtering or decanting cannot remove it.', 'Step 2: the sun heats shallow ponds; water evaporates.', 'Step 3: the non-volatile salt is left behind.'],
  'Dissolved solid wanted → evaporation; liquid wanted → distillation.',
  [('How would you get pure water from sea water?', 'Simple distillation.'), ('How can you get large crystals of copper(II) sulfate from its solution?', 'Crystallisation: heat to saturation, then cool slowly.')])
M('q3', LBL, 33, 'Two liquids form two separate layers when mixed. They are best separated with a …',
  ['fractionating column', 'separating funnel', 'filter paper', 'magnet'], 'B',
  ['Step 1: two layers means the liquids are **immiscible**.', 'Step 2: they differ in density, so the denser one can be run off through the tap.'],
  'Layers → separating funnel. One layer → distillation.',
  [('Can ethanol and water be separated with a separating funnel?', 'No — they are miscible; use fractional distillation.'), ('In an oil/water mixture, which liquid leaves the tap first?', 'Water (the denser, lower layer).')])
M('q4', LBL, 32, 'In simple distillation the thermometer bulb should be placed …',
  ['in the boiling liquid', 'at the side arm leading to the condenser', 'in the receiving flask', 'in the condenser water'], 'B',
  ['Step 1: we want the temperature of the vapour that is actually distilling.', 'Step 2: that vapour passes the side arm into the condenser.', 'Step 3: a steady reading there shows a pure liquid is coming over.'],
  'Thermometer at the side arm; water in at the bottom of the condenser.',
  [('Why are anti-bumping chips added?', 'For smooth, even boiling.'), ('What is the liquid collected in distillation called?', 'The distillate.')])
TF('q5', LBL, 31, 'A magnet can separate iron from iron(II) sulfide formed by heating iron with sulfur.', False,
   ['Step 1: heating iron with sulfur makes a **compound**, FeS.', 'Step 2: a compound has new properties; FeS is not attracted by a magnet.', 'Step 3: only a **mixture** of iron and sulfur can be separated with a magnet.'],
   'Mixture → separable by physical methods; compound → needs a chemical reaction.',
   [('Is a mixture of iron filings and sulfur separable by a magnet?', 'Yes.'), ('Name the three magnetic metals.', 'Iron, nickel and cobalt.')])
F('q6', LBL, 33, 'Ethanol and water are separated by ____ distillation because their boiling points are close and they are miscible.', 'fractional',
  ['fractional', 'simple', 'destructive'],
  ['Step 1: miscible → one layer → no separating funnel.', 'Step 2: boiling points 78 °C and 100 °C are close → a column is needed.', 'Step 3: so **fractional** distillation.'],
  'Close boiling points → fractional; very different → simple.',
  [('Which apparatus is added for fractional distillation?', 'A fractionating column.'), ('Which liquid distils first from ethanol–water?', 'Ethanol (lower b.p.).')])
S('q7', LBL, 31, 'A mixture contains sand, salt and iron filings. Give the methods, in order, to separate all three.',
  'Magnet (iron) → add water and stir → filter (sand is the residue) → evaporate the filtrate (salt).',
  ['Step 1: remove iron with a magnet while dry.', 'Step 2: dissolve the salt in water.', 'Step 3: filter — sand stays on the paper; wash and dry it.', 'Step 4: evaporate the filtrate to get the salt.'],
  'Do the magnet step first, while the mixture is dry.',
  [('How would you separate sand, sugar and sawdust?', 'Float off the sawdust in water (or sieve), dissolve the sugar, filter the sand, evaporate the sugar solution.'),
   ('How would you separate chalk, salt and water?', 'Filter (chalk), then evaporate the filtrate (salt) or distil it (water).')])
S('q8', LBL, 28, 'State one limitation of decantation and how it is overcome.',
  'Fine particles stay suspended and some liquid stays with the sediment; follow decantation with filtration.',
  ['Step 1: light, fine particles settle very slowly or not at all.', 'Step 2: the decanted liquid can still be cloudy, and a little liquid is left on the sediment.', 'Step 3: filtering the decanted liquid removes the remaining fine particles.'],
  'Decant first to save time, then filter.',
  [('Why is decanted river water not yet safe to drink?', 'It still contains dissolved substances and germs — filter and boil or chlorinate it.'), ('Give one everyday example of decantation.', 'Pouring water off washed rice or lentils.')])
M('q9', LBL, 32, 'Which pair is correct for distilling salt water?',
  ['distillate = salt, residue = water', 'distillate = pure water, residue = salt', 'filtrate = salt, residue = water', 'distillate = salt water'], 'B',
  ['Step 1: water boils and its vapour condenses in the condenser → distillate.', 'Step 2: salt does not boil at 100 °C, so it is left in the flask → residue.'],
  'Distillate = what came over; residue = what stayed behind.',
  [('In filtration, what is the liquid that passes through called?', 'The filtrate.'), ('Why is distillation better than evaporation for getting water from salt water?', 'Evaporation loses the water to the air; distillation condenses and keeps it.')])

GLOSSARY = [
    ('Sediment', 'The insoluble solid that settles at the bottom of a liquid.', 28),
    ('Decantation', 'Pouring off the clear liquid above a sediment.', 28),
    ('Filtrate', 'The liquid that passes through a filter.', 29),
    ('Residue', 'The solid left on the filter paper (or left behind after evaporation or distillation).', 29),
    ('Distillate', 'The pure liquid collected after its vapour has condensed.', 32),
    ('Immiscible liquids', 'Liquids that do not mix and form separate layers, e.g. oil and water.', 33),
    ('Miscible liquids', 'Liquids that mix completely to form one layer, e.g. ethanol and water.', 33),
    ('Fractional distillation', 'Distillation through a fractionating column to separate miscible liquids with close boiling points.', 33),
]

BLOCKS = [('chem9-u1-l1-4', 'chem9-u1-tb17', CARDS)]
GAMES = [{'id': 'chem9-u1-cm-g1', 'type': 'match', 'title': 'Match the mixture to its separation method', 'lesson': 'chem9-u1-l1-4', 'pairs': [
    {'a': 'Muddy water (quick first step)', 'b': 'Sedimentation and decantation'}, {'a': 'Sand and water', 'b': 'Filtration'},
    {'a': 'Salt from salt water', 'b': 'Evaporation'}, {'a': 'Iron filings and sulfur', 'b': 'Magnetic separation'},
    {'a': 'Oil and water', 'b': 'Separating funnel'}, {'a': 'Pure water from ink', 'b': 'Simple distillation'},
    {'a': 'Ethanol and water', 'b': 'Fractional distillation'}], 'src': 'notes'}]
